'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {AuthorityPayload,AuthorityReviewRow} from '@/lib/action-authority';
type Review=AuthorityReviewRow&{status:string;nextStep:string};
type Property={id:string;address:string};
type Marketing={dealId:string;purchaseEnvelopeId:string;termsHash:string;stateCode:string;maxCents:number|null};
const labels={contact_permission:'Contact permission',offer_ceiling:'Maximum offer',marketing_release:'Buyer marketing'};
const field='min-h-11 w-full min-w-0 rounded-xl border border-black/15 bg-white px-3 py-2 text-base';
const button='min-h-11 rounded-full border border-black/20 px-4 py-2 text-sm disabled:opacity-50';
async function json(response:Response){const body=await response.json();if(!response.ok)throw Error(body.error||'Could not save review. Please refresh.');return body;}
/** Evidence intake only. Approval is a separate, authenticated human operation. */
export function AuthorityReviewPanel(){
 const [rows,setRows]=useState<Review[]>([]),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[properties,setProperties]=useState<Property[]>([]),[propertyPage,setPropertyPage]=useState(0),[moreProperties,setMoreProperties]=useState(false),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[screeningId,setScreeningId]=useState(''),[kind,setKind]=useState<AuthorityPayload['kind']>('contact_permission'),[contactChannel,setContactChannel]=useState<'voice'|'sms'>('voice'),[marketing,setMarketing]=useState<Marketing|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const [contactParty,setContactParty]=useState<'seller'|'buyer'>('seller'),[buyerOptions,setBuyerOptions]=useState<{id:string;name:string}[]>([]);
 const idempotency=useRef<{content:string;key:string}|null>(null),formRef=useRef<HTMLFormElement>(null),generation=useRef(0);
 async function loadReviews(next=0){const data=await json(await fetch(`/api/authority-reviews?page=${next}`,{cache:'no-store'}));setRows(data.requests);setHasMore(data.hasMore);setLoaded(true);}
 useEffect(()=>{let active=true;fetch(`/api/authority-reviews?page=${page}`,{cache:'no-store'}).then(json).then(data=>{if(active){setRows(data.requests);setHasMore(data.hasMore);setLoaded(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[page]);
 useEffect(()=>{let active=true;fetch(`/api/authority-reviews/options?page=${propertyPage}&query=${encodeURIComponent(search)}`,{cache:'no-store'}).then(json).then(data=>{if(active){setProperties(data.properties);setMoreProperties(data.hasMore);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[propertyPage,search]);
 useEffect(()=>{setMarketing(null);setBuyerOptions([]);if(!screeningId)return;let active=true;fetch(`/api/authority-reviews/options?screeningId=${screeningId}`,{cache:'no-store'}).then(json).then(data=>{if(active){setMarketing(data.marketing);setBuyerOptions(data.buyers??[]);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[screeningId]);
 useEffect(()=>()=>{generation.current++;},[]);
 async function submit(event:FormEvent<HTMLFormElement>){
 event.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');const current=generation.current;
 try{
 const values=new FormData(event.currentTarget),get=(key:string)=>String(values.get(key)??'').trim();
 const cents=(value:string)=>{if(!/^\d+(?:\.\d{1,2})?$/.test(value))throw Error('Use dollars with up to two decimal places.');return Math.round(Number(value)*100);};
 const base={screeningId,kind,purpose:get('purpose'),sourceName:get('sourceName'),evidenceReference:get('evidenceReference'),evidenceObservedAt:new Date(get('evidenceObservedAt')).toISOString(),expiresAt:new Date(get('expiresAt')).toISOString(),stateCode:get('stateCode').toUpperCase()};
 let payload:AuthorityPayload;
 if(kind==='contact_permission')payload={...base,kind,channel:contactChannel,party:contactParty,buyerId:contactParty==='buyer'?get('buyerId'):null,phone:get('phone'),timezone:get('timezone'),localStartHour:Number(get('startHour')),localEndHour:Number(get('endHour'))};
 else if(kind==='offer_ceiling')payload={...base,kind,channel:'offer',maxCents:cents(get('amount'))};
 else{if(!marketing||marketing.maxCents===null)throw Error('A verified signed purchase agreement with an exact fee is needed first.');payload={...base,kind,channel:'buyer_marketing',...marketing,maxCents:marketing.maxCents,market:get('market'),propertyType:get('propertyType') as 'house'|'land',repairsCents:cents(get('repairs')),marketingScope:'assignment_interest'};}
 const content=JSON.stringify(payload);if(idempotency.current?.content!==content)idempotency.current={content,key:crypto.randomUUID()};
 const data=await json(await fetch('/api/authority-reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotencyKey:idempotency.current.key,payload})}));
 if(current!==generation.current)return;setMessage(data.message);setPage(0);await loadReviews(0);
 }catch(e){if(current===generation.current)setError(e instanceof Error?e.message:'Review could not be saved.');}finally{if(current===generation.current)setBusy(false);}
 }
 async function withdraw(row:Review){if(busy)return;setBusy(true);setError('');try{const data=await json(await fetch('/api/authority-reviews',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:row.id})}));setMessage(data.message);await loadReviews(page);}catch(e){setError(e instanceof Error?e.message:'Could not withdraw review.');}finally{setBusy(false);}}
 return <section className="min-w-0 space-y-5" aria-label="Permission review requests">
 <p className="text-sm text-black/65">Send evidence for a human review. This form does not check a do-not-call registry, grant contact consent, approve an offer or release marketing. Work stays subject to its existing checks.</p>
 {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{message&&<p role="status" className="text-sm">{message}</p>}
 <div className="space-y-3">{!loaded&&!error&&<p className="text-sm">Loading reviews…</p>}{loaded&&!rows.length&&<p className="text-sm">No review requests yet. Select a property below and add your evidence.</p>}{rows.map(row=><article key={row.id} className="rounded-xl border border-black/10 p-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{labels[row.kind]}{row.kind==='contact_permission'?` (${row.payload.channel.toUpperCase()})`:''}</strong><span>{row.status.replaceAll('_',' ')}</span></div><p className="mt-2">{row.nextStep}</p>{row.decision_note&&<p className="mt-2 text-black/60">Reviewer note: {row.decision_note}</p>}<p className="mt-2 text-xs text-black/50">Expires {new Date(row.expires_at).toLocaleString()}</p>{!['revoked','denied','expired'].includes(row.status)&&<button type="button" disabled={busy} className={`${button} mt-3`} onClick={()=>withdraw(row)}>Withdraw this request</button>}</article>)}<div className="flex gap-2">{page>0&&<button className={button} disabled={busy} onClick={()=>setPage(page-1)}>Previous reviews</button>}{hasMore&&<button className={button} disabled={busy} onClick={()=>setPage(page+1)}>More reviews</button>}</div></div>
 <details className="rounded-xl border border-black/10 p-4"><summary className="min-h-11 cursor-pointer text-sm font-medium">Submit evidence for review</summary>
 <div className="mt-3 space-y-3"><label className="block text-sm">Find a property<input className={`${field} mt-1`} value={query} onChange={e=>setQuery(e.target.value)} maxLength={100} placeholder="Street address"/></label><button type="button" className={button} disabled={busy} onClick={()=>{setPropertyPage(0);setSearch(query);setScreeningId('');}}>Search properties</button><div className="flex gap-2">{propertyPage>0&&<button className={button} onClick={()=>{setPropertyPage(propertyPage-1);setScreeningId('');}}>Previous properties</button>}{moreProperties&&<button className={button} onClick={()=>{setPropertyPage(propertyPage+1);setScreeningId('');}}>More properties</button>}</div></div>
 <form ref={formRef} onSubmit={submit} className="mt-4 grid gap-4"><fieldset disabled={busy} className="grid min-w-0 gap-4">
 <label className="grid gap-1 text-sm">Property<select className={field} required value={screeningId} onChange={e=>setScreeningId(e.target.value)}><option value="">Select a completed property review</option>{properties.map(p=><option key={p.id} value={p.id}>{p.address}</option>)}</select></label>
 <label className="grid gap-1 text-sm">Review type<select className={field} value={kind} onChange={e=>setKind(e.target.value as AuthorityPayload['kind'])}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label className="grid gap-1 text-sm">What are you asking to approve?<textarea className={field} name="purpose" required minLength={12} maxLength={500} placeholder="Describe the exact purpose and limits"/></label>
 <label className="grid gap-1 text-sm">Property state (two letters)<input className={field} name="stateCode" required pattern="[A-Za-z]{2}" maxLength={2} placeholder="TX"/></label>
 <label className="grid gap-1 text-sm">Evidence source name<input className={field} name="sourceName" required minLength={3} maxLength={100} placeholder="Who or which record provides this evidence?"/></label>
 <label className="grid gap-1 text-sm">Evidence reference or explanation<textarea className={field} name="evidenceReference" required minLength={12} maxLength={1000} placeholder="Identify the dated record and where a reviewer can verify it. Do not paste passwords or payment details."/></label>
 <label className="grid gap-1 text-sm">When was this evidence recorded?<input className={field} type="datetime-local" name="evidenceObservedAt" required/></label>
 <label className="grid gap-1 text-sm">Requested expiry (within 90 days)<input className={field} type="datetime-local" name="expiresAt" required/></label>
 {kind==='contact_permission'&&<><label className="grid gap-1 text-sm">Contact type<select className={field} value={contactParty} onChange={e=>setContactParty(e.target.value as 'seller'|'buyer')}><option value="seller">Property seller</option><option value="buyer">Cash buyer</option></select></label>{contactParty==='buyer'&&<label className="grid gap-1 text-sm">Buyer record<select className={field} name="buyerId" required defaultValue=""><option value="" disabled>Select a discovered buyer</option>{buyerOptions.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}<label className="grid gap-1 text-sm">Contact channel<select className={field} value={contactChannel} onChange={e=>setContactChannel(e.target.value as 'voice'|'sms')}><option value="voice">Outbound voice</option><option value="sms">SMS invitation to an incoming call</option></select></label>{contactChannel==='sms'&&<p className="text-sm text-black/65">Provide the recipient’s prior contact and SMS permission for your actual sending business. Approval creates a paused SMS thread only. Campaign release and Run are separate, and no outbound voice permission is granted.</p>}<p className="text-sm text-black/65">Public or purchased phone details are not consent. A trusted reviewer must verify channel-specific consent, legal scope and an actual current external do-not-call receipt.</p><label className="grid gap-1 text-sm">Contact phone, including +1<input className={field} type="tel" name="phone" required pattern="\+1[2-9][0-9]{9}" placeholder="+12145550123"/></label><label className="grid gap-1 text-sm">Contact time zone<input className={field} name="timezone" required placeholder="America/Chicago"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Earliest hour (local)<input className={field} name="startHour" type="number" defaultValue={9} min={9} max={19} required/></label><label className="grid gap-1 text-sm">Latest hour (local, exclusive)<input className={field} name="endHour" type="number" defaultValue={20} min={10} max={20} required/></label></div></>}
 {kind==='offer_ceiling'&&<><label className="grid gap-1 text-sm">Maximum offer you authorize (USD)<input className={field} name="amount" inputMode="decimal" required pattern="[0-9]+(\.[0-9]{1,2})?" placeholder="125000.00"/></label><p className="text-sm text-black/65">This is your requested exact ceiling. It must also pass reviewed underwriting; approval does not send an offer or sign an agreement.</p></>}
 {kind==='marketing_release'&&<>{marketing?.maxCents!=null?<p className="text-sm">Current purchase agreement found. Exact asking price including assignment fee: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(marketing.maxCents/100)}. A reviewer must verify its signatures, actual signed PDF and marketing rights.</p>:<p className="text-sm">Marketing review needs a completed real purchase agreement and exact assignment fee. Complete that step first.</p>}<label className="grid gap-1 text-sm">Marketing area<input className={field} name="market" required minLength={2} maxLength={100} placeholder="Dallas"/></label><label className="grid gap-1 text-sm">Property type<select className={field} name="propertyType"><option value="house">House</option><option value="land">Land</option></select></label><label className="grid gap-1 text-sm">Reviewed repair estimate (USD)<input className={field} name="repairs" inputMode="decimal" required pattern="[0-9]+(\.[0-9]{1,2})?"/></label><p className="text-sm text-black/65">Requested scope: marketing the contractual assignment interest. Buyer contact permissions and showing access are separate.</p></>}
 <button className={`${button} bg-black text-white`} disabled={busy||!screeningId||(kind==='marketing_release'&&marketing?.maxCents==null)}>{busy?'Saving…':'Submit for human review'}</button>
 </fieldset></form></details></section>;
}
