import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {authoritySubmitSchema,authorityDecisionSchema,validateAuthorityTimes,authorityReviewPresentation,authorityError} from '../lib/action-authority.ts';
const now=Date.parse('2026-09-30T12:00:00Z'),uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const payload={kind:'contact_permission',screeningId:uuid(1),purpose:'Discuss this specific property',sourceName:'Seller evidence record',evidenceReference:'Signed voice-specific consent record',evidenceObservedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+86400000).toISOString(),stateCode:'TX',channel:'voice',party:'seller',buyerId:null,phone:'+12145550123',timezone:'America/Chicago',localStartHour:9,localEndHour:20};
assert(authoritySubmitSchema.parse({idempotencyKey:uuid(2),payload}));validateAuthorityTimes(payload,now);
for(const change of [{dncClear:true},{channel:'email'},{party:'admin'},{phone:'+1999'},{localStartHour:8},{stateCode:'TXX'},{screeningId:'injected&account_id=other'},{approved:true}])assert.throws(()=>authoritySubmitSchema.parse({idempotencyKey:uuid(2),payload:{...payload,...change}}));
for(const change of [{expiresAt:new Date(now-1).toISOString()},{expiresAt:new Date(now+91*86400000).toISOString()},{evidenceObservedAt:new Date(now+1).toISOString()},{timezone:'wrong-zone'},{localStartHour:19,localEndHour:10},{party:'buyer',buyerId:null}])assert.throws(()=>validateAuthorityTimes({...payload,...change},now));
const {party,buyerId,phone,timezone,localStartHour,localEndHour,...common}=payload;
for(const maxCents of [-1,0,1.5,1e20,NaN,Infinity])assert.throws(()=>authoritySubmitSchema.parse({idempotencyKey:uuid(2),payload:{...common,kind:'offer_ceiling',channel:'offer',maxCents}}));
assert.throws(()=>authorityDecisionSchema.parse({requestId:uuid(2),decision:'approved',note:'Explicit operator note',reviewerId:uuid(9)}));
assert.throws(()=>authorityDecisionSchema.parse({requestId:uuid(2),decision:'approved',note:'Explicit operator note',verification:{marketReviewId:uuid(3),reviewReference:'A genuine review source',reviewedAt:new Date(now).toISOString(),validUntil:new Date(now+1).toISOString(),signedDocumentHash:'a'.repeat(64)}}));
for(const [state,expected] of [['submitted','pending'],['needs_information','needs_information'],['declined','denied'],['revoked','revoked'],['approved','approved']])assert.equal(authorityReviewPresentation({kind:'contact_permission',state,expires_at:new Date(now+1).toISOString(),decision_note:null},now).status,expected);
assert.equal(authorityReviewPresentation({kind:'offer_ceiling',state:'approved',expires_at:new Date(now-1).toISOString(),decision_note:null},now).status,'expired');
assert.equal(authorityError(Error('OPERATOR_REQUIRED')).status,403);
const sql=readFileSync(new URL('../config/reviewed-action-authority.sql',import.meta.url),'utf8');
assert(!/security definer/i.test(sql));
assert(!/insert into public\.icash_(trusted_operators|dnc_verification_sources|dnc_verification_receipts|authority_market_reviews)/i.test(sql),'No seeded access or fake checks');
assert(sql.includes('grant select on public.icash_trusted_operators'));
console.log('Authority input: strict tenant/scoped forms, customer grant/spoof rejection, dates, channels, money, honest statuses and zero seeded access passed.');

const sms={...payload,channel:'sms'};assert(authoritySubmitSchema.parse({idempotencyKey:uuid(2),payload:sms}));validateAuthorityTimes(sms,now);validateAuthorityTimes({...sms,party:'buyer',buyerId:uuid(5)},now);assert.throws(()=>validateAuthorityTimes({...sms,party:'buyer',buyerId:null},now));
assert.throws(()=>authoritySubmitSchema.parse({idempotencyKey:uuid(2),payload:{...sms,sendingPrincipal:'Spoofed business'}}));
const smsUi=readFileSync(new URL('../components/dashboard/authority-review-panel.tsx',import.meta.url),'utf8');assert(smsUi.includes('SMS invitation to an incoming call'));assert(smsUi.includes('channel:contactChannel'));assert(smsUi.includes('Approval creates a paused SMS thread only'));
