import assert from 'node:assert/strict';
import {authorityReviewStatus} from '../lib/authority-review-status.ts';
const now=Date.parse('2026-09-30T12:00:00Z'),future='2026-10-01T12:00:00Z',past='2026-09-29T12:00:00Z';
const base={identity:false,availableCents:0,paused:false,permissions:[],offer:null,purchaseSigned:false,marketing:null,now};
const item=(value,key)=>authorityReviewStatus(value).find(x=>x.key===key);
assert.equal(item(base,'contact_permission').status,'review_required');assert.match(item(base,'contact_permission').detail,/Purchased contact details alone/);
assert.equal(item(base,'identity').action,'account_details');assert.equal(item(base,'budget').action,'funding');assert.equal(item(base,'marketing_authority').status,'not_applicable');
const permission={permission_until:future,dnc_checked_at:past,dnc_clear:true,revoked_at:null,suppressed:false};
assert.equal(item({...base,permissions:[permission]},'contact_permission').status,'recorded');
for(const change of [{dnc_clear:false},{dnc_checked_at:future},{dnc_checked_at:'2026-08-01T00:00:00Z'},{permission_until:past},{permission_until:'invalid'},{revoked_at:past},{suppressed:true}])assert.equal(item({...base,permissions:[{...permission,...change}]},'contact_permission').status,'review_required');
assert.match(item({...base,permissions:[{...permission,suppressed:true}]},'contact_permission').detail,/Do not contact/);
assert.equal(item({...base,offer:{max_offer_cents:100000,expires_at:future}},'offer_authority').status,'recorded');
for(const amount of [0,-1,NaN,Infinity,1.5,Number.MAX_SAFE_INTEGER+1])assert.equal(item({...base,offer:{max_offer_cents:amount,expires_at:future}},'offer_authority').status,'review_required');
for(const expires_at of [past,'invalid'])assert.equal(item({...base,offer:{max_offer_cents:1,expires_at}},'offer_authority').status,'review_required');
const marketing={expires_at:future,purchaseMatches:true,priceMatches:true};
assert.equal(item({...base,purchaseSigned:true,marketing},'marketing_authority').status,'recorded');
for(const change of [{purchaseMatches:false},{priceMatches:false},{expires_at:past}])assert.equal(item({...base,purchaseSigned:true,marketing:{...marketing,...change}},'marketing_authority').status,'review_required');
assert.equal(item({...base,availableCents:1000,paused:true},'budget').status,'blocked');
assert(!authorityReviewStatus({...base,permissions:[permission],offer:{max_offer_cents:100000,expires_at:future},purchaseSigned:true,marketing}).some(x=>x.status==='ready'),'Recorded evidence is not unconditional dispatch readiness');
console.log('Authority diagnostics: missing/expired/revoked/suppressed permissions, fresh DNC, bounded offer, exact signed-marketing gates passed.');

assert.equal(item({...base,smsPermissionCurrent:true},'sms_contact_permission').status,'recorded');
assert.equal(item({...base,smsPermissionCurrent:true},'contact_permission').status,'review_required','SMS does not assert voice permission');
assert.equal(item({...base,permissions:[permission]},'sms_contact_permission').status,'review_required','Voice does not assert SMS permission');
assert.equal(item({...base,smsPermissionCurrent:false},'sms_contact_permission').status,'review_required');
