begin;
create function pg_temp.icash_test_abort_approval() returns trigger language plpgsql as $$
begin if new.event='approved' then raise exception 'Injected final audit failure';end if;return new;end $$;
do $$
declare u uuid:=gen_random_uuid();other_user uuid:=gen_random_uuid();op uuid:=gen_random_uuid();a uuid:=gen_random_uuid();other_a uuid:=gen_random_uuid();s uuid:=gen_random_uuid();other_s uuid:=gen_random_uuid();key uuid:=gen_random_uuid();market uuid;src uuid;receipt uuid;
 r public.icash_authority_review_requests;r2 public.icash_authority_review_requests;p jsonb;v jsonb;err boolean;before_count integer;deal uuid:=gen_random_uuid();template uuid:=gen_random_uuid();envelope uuid:=gen_random_uuid();terms jsonb;recipients jsonb;provider uuid:=gen_random_uuid();provider_evidence jsonb;expected_offer jsonb;job uuid:=gen_random_uuid();
begin
 insert into auth.users values(u),(other_user),(op);
 insert into public.icash_accounts(id,owner_user_id,assistant_name) values(a,u,'Fixture'),(other_a,other_user,'Other fixture');
 insert into public.icash_screening_jobs(id,account_id,event_key,snapshot,state,result) values(s,a,'authority-fixture',jsonb_build_object('propertyId','prop_1','fetchedAt',now(),'propertyType','house'),'complete','{"financialCheck":{"status":"eligible"},"preliminarySellerCeilingCents":15000000}'),(other_s,other_a,'authority-other','{}','complete','{}');
 p:=jsonb_build_object('kind','contact_permission','screeningId',s,'channel','voice','party','seller','buyerId',null,'phone','+12145550123','timezone','America/Chicago','localStartHour',9,'localEndHour',20,'stateCode','TX','purpose','Discuss this specific property purchase','sourceName','Isolated test evidence','evidenceReference','Fixture only; never permission to call','evidenceObservedAt',now()-interval '1 hour','expiresAt',now()+interval '10 days');
 r:=public.icash_submit_authority_review(a,u,key,p);
 if r.state<>'submitted' or exists(select 1 from public.icash_contact_permissions) then raise exception 'Submission granted permission';end if;
 r2:=public.icash_submit_authority_review(a,u,key,p);if r.id<>r2.id then raise exception 'Duplicate request';end if;
 if (select count(*) from public.icash_authority_review_audit where request_id=r.id)<>1 then raise exception 'Duplicate audit';end if;
 err:=false;begin perform public.icash_submit_authority_review(a,u,key,p||'{"purpose":"A different purpose"}');exception when others then err:=true;end;if not err then raise exception 'Idempotency conflict accepted';end if;
 err:=false;begin perform public.icash_submit_authority_review(a,other_user,gen_random_uuid(),p);exception when others then err:=true;end;if not err then raise exception 'Foreign owner accepted';end if;
 err:=false;begin perform public.icash_submit_authority_review(a,u,gen_random_uuid(),p||jsonb_build_object('screeningId',other_s));exception when others then err:=true;end;if not err then raise exception 'Foreign property accepted';end if;
 err:=false;begin update public.icash_authority_review_requests set payload=payload||'{"dnc_clear":true}' where id=r.id;exception when others then err:=true;end;if not err then raise exception 'Immutable submission changed';end if;
 err:=false;begin perform public.icash_decide_authority_review(u,r.id,'approved','Customer cannot approve', '{}');exception when others then err:=true;end;if not err then raise exception 'Customer self approval';end if;
 insert into public.icash_trusted_operators(user_id,scopes,provisioned_by,expires_at) values(op,array['authority_review'],'Isolated rollback fixture only',now()+interval '1 day');
 update public.icash_trusted_operators set scopes=array['support'] where user_id=op;
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'declined','Support cannot make authority decisions','{}');exception when others then err:=true;end;if not err then raise exception 'Support operator escalated authority';end if;
 update public.icash_trusted_operators set scopes=array['authority_review'] where user_id=op;
 insert into public.icash_authority_market_reviews(account_id,screening_id,state_code,kind,channel,source_reference,reviewed_by,reviewed_at,expires_at) values(a,s,'TX','contact_permission','voice','Isolated legal review source','Fixture reviewer',now(),now()+interval '2 days') returning id into market;
 v:=jsonb_build_object('marketReviewId',market,'reviewReference','Reviewed only in rollback test','reviewedAt',now(),'validUntil',now()+interval '1 day','consentReference','Actual channel consent fixture','consentObservedAt',now());
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Review approved fixture only',v||'{"dnc_clear":true}');exception when others then err:=true;end;if not err then raise exception 'Checkbox became external DNC';end if;
 insert into public.icash_dnc_verification_sources(name,source_reference,enabled,expires_at) values('Isolated DNC fixture','No real provider enabled',true,now()+interval '1 day') returning id into src;
 insert into public.icash_dnc_verification_receipts(source_id,phone,contact_key,provider_reference,receipt_hash,checked_at,expires_at,clear) values(src,p->>'phone',encode(sha256(convert_to(p->>'phone','UTF8')),'hex'),'Isolated provider reference',repeat('b',64),now()-interval '1 hour',now()+interval '12 hours',true) returning id into receipt;
 v:=v||jsonb_build_object('dncReceiptId',receipt);
 insert into public.icash_text_suppressions values(p->>'phone');
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Review approved fixture only',v);exception when others then err:=true;end;if not err then raise exception 'Opt-out bypass';end if;
 delete from public.icash_text_suppressions;
 update public.icash_dnc_verification_receipts set checked_at=now()+interval '1 hour' where id=receipt;
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Review approved fixture only',v);exception when others then err:=true;end;if not err then raise exception 'Future DNC accepted';end if;
 update public.icash_dnc_verification_receipts set checked_at=now()-interval '31 days' where id=receipt;
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Review approved fixture only',v);exception when others then err:=true;end;if not err then raise exception 'Stale DNC accepted';end if;
 update public.icash_dnc_verification_receipts set checked_at=now()-interval '1 hour' where id=receipt;
 r:=public.icash_decide_authority_review(op,r.id,'approved','Review approved fixture only',v);
 if r.state<>'approved' or (select count(*) from public.icash_contact_permissions where review_request_id=r.id)<>1 or r.expires_at>now()+interval '12 hours' then raise exception 'Scoped permission missing';end if;
 perform public.icash_decide_authority_review(op,r.id,'approved','Repeated response retry',v);
 if (select count(*) from public.icash_authority_review_audit where request_id=r.id and event='approved')<>1 then raise exception 'Approval not idempotent';end if;
 update public.icash_dnc_verification_sources set enabled=false where id=src;
 if (select state from public.icash_authority_review_requests where id=r.id)<>'revoked' or exists(select 1 from public.icash_contact_permissions where review_request_id=r.id and revoked_at is null) then raise exception 'Source revocation ignored';end if;
 -- Offer authority: the exact owner-requested limit, never above reviewed underwriting.
 p:=jsonb_build_object('kind','offer_ceiling','screeningId',s,'channel','offer','stateCode','TX','purpose','Authorize this maximum property offer','sourceName','Owner limit fixture','evidenceReference','Explicit owner maximum fixture','evidenceObservedAt',now(),'expiresAt',now()+interval '1 day','maxCents',10000000);
 r:=public.icash_submit_authority_review(a,u,gen_random_uuid(),p);
 insert into public.icash_authority_market_reviews(account_id,screening_id,state_code,kind,channel,source_reference,reviewed_by,reviewed_at,expires_at) values(a,s,'TX','offer_ceiling','offer','Isolated legal offer source','Fixture reviewer',now(),now()+interval '2 days') returning id into market;
 v:=jsonb_build_object('marketReviewId',market,'reviewReference','Reviewed offer rollback fixture','reviewedAt',now(),'validUntil',now()+interval '1 day','underwritingReference','Actual underwriting evidence fixture','underwritingMaxCents',9999999);
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Offer review fixture approval',v);exception when others then err:=true;end;if not err then raise exception 'Excessive offer accepted';end if;
 r:=public.icash_decide_authority_review(op,r.id,'approved','Offer review fixture approval',v||'{"underwritingMaxCents":10000000}');
 if (select max_offer_cents from public.icash_offer_authorities where review_request_id=r.id)<>10000000 then raise exception 'Exact ceiling changed';end if;
 select to_jsonb(x) into expected_offer from public.icash_offer_authorities x where review_request_id=r.id;
 insert into public.icash_voice_jobs(id,account_id,permission_id) select job,a,id from public.icash_contact_permissions limit 1;
 if not public.icash_claim_reviewed_voice_job(job,expected_offer) then raise exception 'Matching offer claim rejected';end if;
 if public.icash_claim_reviewed_voice_job(job,expected_offer||'{"max_offer_cents":10000001}') then raise exception 'Changed offer snapshot accepted';end if;
 r2:=public.icash_submit_authority_review(a,u,gen_random_uuid(),p);
 create trigger icash_test_atomic_failure before insert on public.icash_authority_review_audit for each row execute function pg_temp.icash_test_abort_approval();
 err:=false;begin perform public.icash_decide_authority_review(op,r2.id,'approved','Approval must rollback completely',v||'{"underwritingMaxCents":10000000}');exception when others then err:=true;end;
 drop trigger icash_test_atomic_failure on public.icash_authority_review_audit;
 if not err or (select state from public.icash_authority_review_requests where id=r2.id)<>'submitted' or (select state from public.icash_authority_review_requests where id=r.id)<>'approved' or (select review_request_id from public.icash_offer_authorities where account_id=a and screening_id=s)<>r.id then raise exception 'Partial failed approval escaped';end if;

 err:=false;begin perform public.icash_withdraw_authority_review(other_a,other_user,r.id);exception when others then err:=true;end;if not err then raise exception 'Cross tenant revoke';end if;
 perform public.icash_withdraw_authority_review(a,u,r.id);
 if exists(select 1 from public.icash_offer_authorities where review_request_id=r.id and expires_at>now()) then raise exception 'Owner withdrawal failed';end if;
 if public.icash_claim_reviewed_voice_job(job,expected_offer) then raise exception 'Withdrawn cached offer reached final claim';end if;
 -- Marketing validates current real signatures, immutable terms and server-fetched PDF hash.
 terms:='{"priceCents":10000000,"assignmentFeeCents":1000000,"state":"TX"}';recipients:='[{"id":"seller","email":"seller@example.test"},{"id":"customer","email":"customer@example.test"}]';
 insert into public.icash_deal_files(id,account_id,screening_id,terms,stage,seller_signed_at) values(deal,a,s,terms,'under_contract',now());
 insert into public.icash_signing_templates(id,state_code,kind,signer_count,provider_template_id,placeholder_names,field_map,reviewed_until,review_reference) values(template,'TX','purchase',1,gen_random_uuid(),'["seller","customer"]','{}',now()+interval '1 day','fixture source');
 provider_evidence:=jsonb_build_object('id',provider,'test_mode',false,'status','completed','apply_signing_order',true,'metadata',jsonb_build_object('icash_envelope',envelope,'terms_hash',repeat('a',64)),'recipients','[{"id":"seller","email":"seller@example.test","status":"signed","signing_order":1},{"id":"customer","email":"customer@example.test","status":"signed","signing_order":2}]'::jsonb);
 insert into public.icash_signing_envelopes(id,account_id,deal_id,kind,template_id,terms,terms_hash,recipients,test_mode,consent_version,requested_by,provider_id,state,provider_evidence) values(envelope,a,deal,'purchase',template,terms,repeat('a',64),recipients,false,'fixture',u,provider,'completed',provider_evidence);
 p:=jsonb_build_object('kind','marketing_release','screeningId',s,'channel','buyer_marketing','stateCode','TX','purpose','Market the assignment interest only','sourceName','Signed contract fixture','evidenceReference','Signed assignment rights fixture','evidenceObservedAt',now(),'expiresAt',now()+interval '1 day','maxCents',11000000,'dealId',deal,'purchaseEnvelopeId',envelope,'termsHash',repeat('a',64),'market','Fixture Dallas','propertyType','house','repairsCents',0,'marketingScope','assignment_interest');
 r:=public.icash_submit_authority_review(a,u,gen_random_uuid(),p);
 insert into public.icash_authority_market_reviews(account_id,screening_id,state_code,kind,channel,source_reference,reviewed_by,reviewed_at,expires_at) values(a,s,'TX','marketing_release','buyer_marketing','Isolated marketing legal source','Fixture reviewer',now(),now()+interval '2 days') returning id into market;
 v:=jsonb_build_object('marketReviewId',market,'reviewReference','Marketing review fixture source','reviewedAt',now(),'validUntil',now()+interval '1 day','marketingRightsReference','Verified assignability fixture');
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Marketing review fixture only',v);exception when others then err:=true;end;if not err then raise exception 'Missing actual signed PDF accepted';end if;
 v:=v||jsonb_build_object('signedDocumentHash',repeat('c',64),'signedDocumentCheckedAt',now());
 update public.icash_signing_envelopes set test_mode=true where id=envelope;
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Marketing review fixture only',v);exception when others then err:=true;end;if not err then raise exception 'Test contract accepted';end if;
 update public.icash_signing_envelopes set test_mode=false,provider_evidence=jsonb_set(public.icash_signing_envelopes.provider_evidence,'{recipients,0,status}','"pending"') where id=envelope;
 err:=false;begin perform public.icash_decide_authority_review(op,r.id,'approved','Marketing review fixture only',v);exception when others then err:=true;end;if not err then raise exception 'Missing signature accepted';end if;
 update public.icash_signing_envelopes set provider_evidence=jsonb_set(public.icash_signing_envelopes.provider_evidence,'{recipients,0,status}','"signed"') where id=envelope;
 r:=public.icash_decide_authority_review(op,r.id,'approved','Marketing review fixture only',v);
 if (select signed_document_hash from public.icash_disposition_authorities where review_request_id=r.id)<>repeat('c',64) then raise exception 'Signed PDF binding lost';end if;
 update public.icash_signing_envelopes set terms_hash=repeat('d',64) where id=envelope;
 if exists(select 1 from public.icash_disposition_authorities where review_request_id=r.id and expires_at>now()) then raise exception 'Changed contract still marketable';end if;
 if has_table_privilege('authenticated','public.icash_authority_review_requests','SELECT') or has_table_privilege('service_role','public.icash_trusted_operators','INSERT') or has_table_privilege('service_role','public.icash_dnc_verification_receipts','INSERT') or has_function_privilege('anon','public.icash_decide_authority_review(uuid,uuid,text,text,jsonb)','EXECUTE') then raise exception 'Authority surface exposed';end if;
 set local role service_role;
 perform public.icash_submit_authority_review(a,u,gen_random_uuid(),p);
 reset role;
end $$;
select 'PASS: immutable tenant intake, spoofed operator/owner denials, real external DNC gates, suppression/stale evidence, exact offer, signed contract/PDF binding, revocation and role isolation' as result;
rollback;
