import assert from 'node:assert/strict';
import {automaticCallOffer,calculateAutomaticCallOffer} from '../lib/automatic-call-offer.ts';
import {callOfferEvidence,callPayoffEvidence,spokenMoneyAmounts} from '../lib/call-offer-evidence.ts';
import {automaticOfferGuardrails,automaticOfferGuardrailMatches} from '../lib/automatic-offer-policy.ts';
import {automaticOfferToolConfig,sellerAgreementToolMatches} from '../lib/seller-agreement-tool.ts';
import {receptionLiveConversationMatches} from '../lib/recorded-reception.ts';
const now=Date.now(),address='45 Oak Road',conversationId='conv_fixture',token='a'.repeat(64);
const snapshot={propertyId:'prop_123',propertyType:'house',fetchedAt:new Date(now).toISOString(),sellerCostReserveCents:0,raw:{data:{dm_property_id:'prop_123',full_address:address,estimated_value:200000,estimated_repair_cost:40000,total_estimated_loan_balance:20000,estimated_equity_percentage:90}}};
const context={party:'seller',accountId:'account',dealId:'deal',address,snapshot,offerState:null,offerVersion:0};
assert.equal(calculateAutomaticCallOffer(context,{},now).priceCents,10200000);
assert.equal(calculateAutomaticCallOffer(context,{repairEstimateCents:6000000},now).priceCents,8800000);
assert.equal(calculateAutomaticCallOffer(context,{repairEstimateCents:1000000},now).priceCents,10200000,'smaller caller estimate cannot replace provider evidence');
assert.equal(calculateAutomaticCallOffer(context,{acceptedPriceCents:9000000},now).priceCents,9000000);
assert.equal(calculateAutomaticCallOffer(context,{acceptedPriceCents:11000000},now).quoteAllowed,false);
for(const ctx of [{...context,address:'Other property'},{...context,snapshot:{...snapshot,fetchedAt:new Date(now-86400001).toISOString()}},{...context,snapshot:{...snapshot,propertyType:'land'}},{...context,snapshot:{...snapshot,raw:{data:{...snapshot.raw.data,estimated_value:null}}}},{party:'unknown'}])assert.equal(calculateAutomaticCallOffer(ctx,{},now).quoteAllowed,false);
const heldContext={...context,snapshot:{...snapshot,raw:{data:{...snapshot.raw.data,estimated_equity_percentage:20,total_estimated_loan_balance:180000}}}};
const conditional=calculateAutomaticCallOffer(heldContext,{},now);
assert.equal(conditional.priceCents,10200000);assert.equal(conditional.quoteAllowed,true);assert.equal(conditional.contractAllowed,false);assert.equal(conditional.conditional,true);assert.equal(conditional.payoffVerified,false);
assert.match(conditional.spokenOffer,/\$102,000 cash, as is, subject to confirming/);
for(const state of [{conditionPending:true},{factsPending:true},{agreementRevisionRequired:true}])assert.equal(calculateAutomaticCallOffer(context,state,now).quoteAllowed,false);
assert.equal(calculateAutomaticCallOffer({party:'buyer',buyer:{askingPriceCents:11200000,address}}, {},now).priceCents,11200000,'buyer total returned without a second assignment fee');
assert.equal(calculateAutomaticCallOffer({party:'buyer'}, {},now).quoteAllowed,false);
assert.equal(calculateAutomaticCallOffer({...context,pendingAgreement:{priceCents:9000000}}, {},now).priceCents,9000000);
for(const [text,cents] of [['eighty-five thousand dollars',8500000],['thirty five thousand',3500000],['one hundred two thousand dollars',10200000],['$85,000',8500000],['35k',3500000],['forty dollars',4000]])assert.deepEqual(spokenMoneyAmounts(text),[cents],text);
const evidence=(agent,user,input)=>callOfferEvidence({transcript:[{role:'agent',message:agent},{role:'user',message:user}]},input);
assert(evidence('We can offer $102,000. Does that work?','Yes',{action:'accept_offer',priceCents:10200000}));
for(const answer of ['No','Yes, but I need $110,000','Yes if you can close tomorrow'])assert(!evidence('We can offer $102,000.',answer,{action:'accept_offer',priceCents:10200000}));
assert(!evidence('We can offer $85,000.','Yes',{action:'accept_offer',priceCents:3500000}));
const statement='Total repairs are sixty thousand dollars.';
assert(evidence('What is the total repair budget?',statement,{action:'update_repairs',sellerStatement:statement,repairEstimateCents:6000000}));
assert(!evidence('What is the total repair budget?',statement,{action:'update_repairs',sellerStatement:statement,repairEstimateCents:7000000}));
assert(!evidence('What is the budget?','Not $60,000',{action:'update_repairs',sellerStatement:'$60,000',repairEstimateCents:6000000}));
let current=structuredClone(context),verified=true,conflict=false,saves=0;
const d={now:()=>now,bind:async()=>{},verifyInput:async()=>verified,db:async(path,method,body)=>{
 if(path==='rpc/icash_call_offer_context')return structuredClone(current);
 assert.equal(path,'rpc/icash_save_call_offer');if(conflict)return false;
 assert.equal(body.p_expected_version,current.offerVersion);assert.deepEqual(body.p_expected_snapshot,current.snapshot);
 current.offerState=structuredClone(body.p_state);current.offerVersion++;saves++;return true;
}};
const call=input=>automaticCallOffer(token,{conversationId,...input},d);
const quoted=await call({action:'get_offer'});assert.equal(quoted.priceCents,10200000);
assert.equal((await call({action:'accept_offer',priceCents:3500000,quoteRevision:quoted.quoteRevision})).quoteAllowed,false);
verified=false;assert.equal((await call({action:'accept_offer',priceCents:quoted.priceCents,quoteRevision:quoted.quoteRevision})).quoteAllowed,false);
verified=true;assert.equal((await call({action:'accept_offer',priceCents:quoted.priceCents,quoteRevision:quoted.quoteRevision})).status,'verbally_accepted');
assert.equal((await call({action:'get_offer'})).priceCents,quoted.priceCents,'return call uses saved accepted amount');
assert.equal((await call({action:'update_repairs',sellerStatement:'The roof needs replacement.'})).quoteAllowed,false);
assert.equal((await call({action:'get_offer'})).quoteAllowed,false,'a held change persists');
const revised=await call({action:'update_repairs',sellerStatement:statement,repairEstimateCents:6000000});assert.equal(revised.priceCents,8800000);
assert.notEqual(revised.quoteRevision,quoted.quoteRevision);
assert.equal((await call({action:'accept_offer',priceCents:quoted.priceCents,quoteRevision:quoted.quoteRevision})).quoteAllowed,false);
conflict=true;assert.equal((await call({action:'get_offer'})).quoteAllowed,false);conflict=false;
current.pendingAgreement={priceCents:8800000};await call({action:'report_change',sellerStatement:'There is another owner.'});
assert.equal((await call({action:'get_offer'})).quoteAllowed,false,'issued agreement cannot bypass a persisted changed-facts hold');
assert(saves>=6);
current=structuredClone(heldContext);
const heldQuote=await call({action:'get_offer'});
assert.equal((await call({action:'accept_offer',priceCents:heldQuote.priceCents,quoteRevision:heldQuote.quoteRevision})).status,'conditional_accepted');
assert.equal(current.offerState.acceptanceConditional,true);assert.equal(current.offerState.contractBlocked,true);
assert.equal((await call({action:'get_offer'})).status,'conditional_accepted');
current.snapshot=structuredClone(snapshot);
assert.equal((await call({action:'get_offer'})).status,'calculated_proposal','fresh eligible research requires renewed acceptance of a formerly conditional offer');
const payoff=await call({action:'report_change',sellerStatement:'My mortgage balance is twenty thousand dollars.'});
assert.equal(payoff.quoteAllowed,true);assert.equal(payoff.contractAllowed,false);assert.match(payoff.nextQuestion,/Does that price work/);
assert.equal(current.offerState.payoffStatement,'My mortgage balance is twenty thousand dollars.');
assert.equal(current.snapshot.raw.data.total_estimated_loan_balance,20000,'statement never overwrites provider research');
assert.equal((await call({action:'get_offer'})).nextQuestion,payoff.nextQuestion,'return call does not repeat a saved payoff question');
await call({action:'report_change',sellerStatement:'There is another owner.'});
assert.equal((await call({action:'report_change',sellerStatement:'My mortgage is twenty thousand dollars.'})).quoteAllowed,false,'a mortgage answer cannot clear an ownership hold');
current=structuredClone(heldContext);verified=false;
assert.equal((await call({action:'report_change',sellerStatement:'My mortgage is paid off.'})).quoteAllowed,false,'unverified transcript stays held');verified=true;
const payoffEvidence=(agent,user)=>callPayoffEvidence({transcript:[{role:'agent',message:agent},{role:'user',message:user}]},{action:'report_change',sellerStatement:user});
assert(payoffEvidence('What is the current mortgage payoff balance?','About twenty thousand dollars.'));
assert(!payoffEvidence('What is the repair budget?','About twenty thousand dollars.'));
assert(!payoffEvidence('What is the payoff balance?','The other owner owes twenty thousand dollars.'));
assert(sellerAgreementToolMatches({id:'tool_offer',tool_config:automaticOfferToolConfig}));
const guardrails=automaticOfferGuardrails();assert(automaticOfferGuardrailMatches(guardrails));
guardrails.custom.config.configs[0].execution_mode='non_blocking';assert(!automaticOfferGuardrailMatches(guardrails));
const row={id:'session',conversation_id:null,agent_id:'agent_fixture',branch_id:'agtbrch_fixture',version_id:'agtvrsn_fixture',call_sid:'CAfixture',from_phone:'+12125550199',to_phone:'+12125550200'};
const provider={conversation_id:'conv_fixture',agent_id:row.agent_id,branch_id:row.branch_id,version_id:row.version_id,user_id:'icash-recorded-reception:'+row.id,metadata:{phone_call:{call_sid:row.call_sid,direction:'inbound',external_number:row.from_phone,agent_number:row.to_phone}}};
assert(receptionLiveConversationMatches(row,provider),'provider may omit initiation metadata during an active call');
for(const patch of [{user_id:'other'},{version_id:'agtvrsn_other'},{conversation_initiation_client_data:{user_id:'other'}},{metadata:{phone_call:{...provider.metadata.phone_call,external_number:'+12125550999'}}}])assert(!receptionLiveConversationMatches(row,{...provider,...patch}));
console.log('PASS automatic offers: exact formula, saved acceptance, changed repairs, financial holds, buyer totals, transcript evidence, concurrent updates and live identity. No external contacts.');
