import assert from 'node:assert/strict';
import {saveBotBuild} from '../lib/bot-build.ts';
import {defaultBotProfile} from '../lib/bot-setup.ts';
const profile={...defaultBotProfile,displayName:'Scout'};
const setup={id:'setup',profile,stage:0,revision:1};
const saved={...setup,stage:4,revision:2};
const signal=new AbortController().signal;
const calls=[];
const request=async(url,options)=>{calls.push([url,options]);return Response.json({setup:saved});};
assert.deepEqual(await saveBotBuild(profile,setup,{retry:false,signal,request}),saved);
assert.equal(calls.length,1);
assert.equal(JSON.parse(calls[0][1].body).revision,1);
assert.equal(calls[0][1].signal,signal);
calls.length=0;
await saveBotBuild(profile,setup,{retry:true,signal,request});
assert.equal(calls.length,2);
assert.equal(calls[0][1].cache,'no-store');
assert.equal(JSON.parse(calls[1][1].body).revision,2);
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:false,signal,request:async()=>Response.json({error:'Please retry.'},{status:503})}),/Please retry/);
let attempts=0;
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:true,signal,request:async()=>{attempts++;return Response.json({error:'Unavailable'},{status:503});}}),/Could not restore/);
assert.equal(attempts,1,'Failed reconciliation must not submit a stale revision');
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:false,signal,request:async()=>Response.json({})}),/Could not save/);
console.log('Bot creation: successful save, retry revision recovery, failed recovery and invalid responses passed');
