import assert from 'node:assert/strict';
import {saveBotBuild} from '../lib/bot-build.ts';
import {defaultBotProfile} from '../lib/bot-setup.ts';
const profile={...defaultBotProfile,displayName:'Scout'};
const setup={id:'setup',profile,stage:0,revision:1};
const saved={...setup,stage:4,revision:2};
const signal=new AbortController().signal;
const calls=[];
const request=async(url,options)=>{calls.push([url,options]);return Response.json({setup:saved});};
assert.deepEqual(await saveBotBuild(profile,setup,{retry:false,signal,request}),saved);
assert.equal(calls.length,1);
assert.equal(JSON.parse(calls[0][1].body).revision,1);
assert.equal(calls[0][1].signal,signal);
calls.length=0;
await saveBotBuild(profile,setup,{retry:true,signal,request});
assert.equal(calls.length,2);
assert.equal(calls[0][1].cache,'no-store');
assert.equal(JSON.parse(calls[1][1].body).revision,2);
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:false,signal,request:async()=>Response.json({error:'Please retry.'},{status:503})}),/Please retry/);
let attempts=0;
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:true,signal,request:async()=>{attempts++;return Response.json({error:'Unavailable'},{status:503});}}),/Could not restore/);
assert.equal(attempts,1,'Failed reconciliation must not submit a stale revision');
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:false,signal,request:async()=>Response.json({})}),/Could not save/);
console.log('Bot creation: successful save, retry revision recovery, failed recovery and invalid responses passed');

const changed={...setup,revision:5,profile:{...profile,market:'Austin, TX',marketMode:'city'}};
const retried=[];
await saveBotBuild({...profile,market:'Nationwide'},setup,{retry:true,nameOnly:true,signal,request:async(url,options)=>{retried.push(options);return Response.json({setup:options.method==='POST'?{...changed,revision:6}:changed});}});
const retryBody=JSON.parse(retried[1].body);assert.equal(retryBody.revision,5);assert.equal(retryBody.profile.market,'Austin, TX');assert.equal(retryBody.profile.marketMode,'city');assert.equal(retryBody.profile.displayName,'Scout');
let changedSessionCalls=0;await assert.rejects(()=>saveBotBuild(profile,setup,{retry:true,nameOnly:true,signal,request:async()=>{changedSessionCalls++;return Response.json({setup:{...changed,id:'other-setup'}});}}),/session changed/);assert.equal(changedSessionCalls,1,'different setup session must not receive a save');
console.log('Name-only retry preserves fresh server market and rejects a changed setup session.');
