import assert from 'node:assert/strict';
import {saveBotBuild,waitForBotCreationTransition} from '../lib/bot-build.ts';
import {defaultBotProfile} from '../lib/bot-setup.ts';
const profile={...defaultBotProfile,displayName:'Scout'};
const setup={id:'setup',profile,stage:0,revision:1};
const saved={...setup,stage:4,revision:2};
const signal=new AbortController().signal;
const calls=[];
const request=async(url,options)=>{calls.push([url,options]);return Response.json({setup:saved});};
assert.deepEqual(await saveBotBuild(profile,setup,{retry:false,signal,request}),saved);
assert.equal(calls.length,1);
assert.equal(JSON.parse(calls[0][1].body).revision,1);
assert.equal(calls[0][1].signal,signal);
calls.length=0;
await saveBotBuild(profile,setup,{retry:true,signal,request});
assert.equal(calls.length,2);
assert.equal(calls[0][1].cache,'no-store');
assert.equal(JSON.parse(calls[1][1].body).revision,2);
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:false,signal,request:async()=>Response.json({error:'Please retry.'},{status:503})}),/Please retry/);
let attempts=0;
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:true,signal,request:async()=>{attempts++;return Response.json({error:'Unavailable'},{status:503});}}),/Could not restore/);
assert.equal(attempts,1,'Failed reconciliation must not submit a stale revision');
await assert.rejects(()=>saveBotBuild(profile,setup,{retry:false,signal,request:async()=>Response.json({})}),/Could not save/);
console.log('Bot creation: successful save, retry revision recovery, failed recovery and invalid responses passed');

const changed={...setup,revision:5,profile:{...profile,market:'Austin, TX',marketMode:'city'}};
const retried=[];
await saveBotBuild({...profile,market:'Nationwide'},setup,{retry:true,nameOnly:true,signal,request:async(url,options)=>{retried.push(options);return Response.json({setup:options.method==='POST'?{...changed,revision:6}:changed});}});
const retryBody=JSON.parse(retried[1].body);assert.equal(retryBody.revision,5);assert.equal(retryBody.profile.market,'Austin, TX');assert.equal(retryBody.profile.marketMode,'city');assert.equal(retryBody.profile.displayName,'Scout');
let changedSessionCalls=0;await assert.rejects(()=>saveBotBuild(profile,setup,{retry:true,nameOnly:true,signal,request:async()=>{changedSessionCalls++;return Response.json({setup:{...changed,id:'other-setup'}});}}),/session changed/);assert.equal(changedSessionCalls,1,'different setup session must not receive a save');
console.log('Name-only retry preserves fresh server market and rejects a changed setup session.');

const changedChoices=[];
await saveBotBuild({...profile,market:'San Antonio, TX',marketMode:'city',voice:'chris'},setup,{retry:true,editedFields:['displayName','market','marketMode','voice'],signal,request:async(url,options)=>{changedChoices.push(options);return Response.json({setup:changed});}});
assert.equal(JSON.parse(changedChoices[1].body).profile.market,'San Antonio, TX');assert.equal(JSON.parse(changedChoices[1].body).profile.voice,'chris');
const {mock}=await import('node:test');mock.timers.enable({apis:['setTimeout','Date'],now:1000});
let transitionDone=false;const transition=waitForBotCreationTransition(1000,new AbortController().signal,false).then(()=>{transitionDone=true;});
mock.timers.tick(4999);await Promise.resolve();assert.equal(transitionDone,false);mock.timers.tick(1);await transition;assert.equal(transitionDone,true);
const interrupted=new AbortController();const pending=waitForBotCreationTransition(Date.now(),interrupted.signal,false);interrupted.abort();await assert.rejects(pending,/Creation interrupted/);
await waitForBotCreationTransition(Date.now(),new AbortController().signal,true);
await waitForBotCreationTransition(Date.now()-6000,new AbortController().signal,false);
mock.timers.reset();console.log('Creation transition: five-second minimum, reduced motion, slow-save completion, cancellation and edited choices passed.');
