import assert from 'node:assert/strict';
import {defaultBotProfile,normalizeBotProfile,botInitials,setupEvents} from '../lib/bot-setup.ts';
assert.equal(botInitials('Oak Street Properties'),'OS');
assert.equal(botInitials('Jordan'),'J');
assert.equal(normalizeBotProfile({...defaultBotProfile,displayName:' Jordan '}).displayName,'Jordan');
for(const p of [{...defaultBotProfile},{...defaultBotProfile,displayName:'<script>'},{...defaultBotProfile,displayName:'Jordan',theme:'url(evil)'},{...defaultBotProfile,displayName:'Jordan',voice:'arbitrary-voice-id'}])assert.throws(()=>normalizeBotProfile(p));
assert(!setupEvents.includes('purchase'));
assert(!setupEvents.includes('setup_completed'));
console.log('Setup validation: names, preset themes/voices and server-only completion/payment events passed');
const {nextSetupStage,resumeSetupStage}=await import('../lib/bot-setup.ts');
assert.equal(nextSetupStage(0,'quick'),4);
assert.equal(nextSetupStage(0,'guided'),4);
assert.equal(nextSetupStage(1,'quick'),4);
assert.equal(nextSetupStage(3,'quick'),4);
for(const stage of [1,2,3,4])assert.equal(resumeSetupStage({stage,profile:{displayName:'Jordan'}}),4);
assert.equal(resumeSetupStage({stage:0,profile:{}}),0);
assert.equal(resumeSetupStage({stage:2,profile:{displayName:''}}),0);
assert.equal(defaultBotProfile.aiLogo,null);
assert.equal(defaultBotProfile.contracts,true);
assert.equal(defaultBotProfile.buyers,true);
assert.equal(defaultBotProfile.marketMode,'nationwide');
console.log('Preset setup: all cohorts skip optional steps; legacy sessions resume safely.');
