import assert from 'node:assert/strict';
import {planBuyerOutreach} from '../lib/buyer-engine.ts';
import {dealProgress,contactDispatchAllowed} from '../lib/deal-operations.ts';
const now=10000000000;
const deal={market:'dallas',propertyType:'house',askingPriceCents:13500000,repairsCents:2500000,sellerContractSigned:true,marketingAuthorized:true};
const a={id:'a',entityId:'entity-a',markets:['dallas'],propertyTypes:['house'],maxPriceCents:15000000,maxRepairCents:3000000,criteriaConfirmedAt:now,permitted:true,proofOfFundsVerifiedAt:now,authorityVerified:true,completedDeals:8,failedDeals:1,estimatedContactChargeCents:100};
const b={...a,id:'b',entityId:'entity-b',completedDeals:1,failedDeals:6};
assert.deepEqual(planBuyerOutreach(deal,[b,a,{...a,id:'duplicate'}],now,250,100).outreach,['a']);
assert.deepEqual(planBuyerOutreach({...deal,sellerContractSigned:false},[a],now,250,0).outreach,[]);
assert.deepEqual(planBuyerOutreach(deal,[{...a,permitted:false}],now,250,0).outreach,[]);
assert.equal(planBuyerOutreach(deal,[{...a,proofOfFundsVerifiedAt:null}],now,250,0).matches[0].ready,false);
assert.equal(planBuyerOutreach(deal,[{...a,criteriaConfirmedAt:now-31*86400000}],now,250,0).matches.length,0);
assert.equal(planBuyerOutreach(deal,[{...a,maxPriceCents:1}],now,250,0).matches.length,0);
const snap={sellerSigned:true,marketingAuthorized:true,buyerSigned:true,depositConfirmedByEscrow:false,titleOpened:true,closingScheduled:true,closedByTitle:false,proceedsConfirmed:false,failed:false,buyerWithdrew:false,titleIssue:false,deadlineAt:null};
assert.equal(dealProgress(snap,now).stage,'finding_buyer');
assert.match(dealProgress(snap,now).next,/deposit/);
assert.equal(dealProgress({...snap,depositConfirmedByEscrow:true},now).stage,'closing');
assert.match(dealProgress({...snap,closedByTitle:true},now).next,/Await confirmation/);
assert.equal(dealProgress({...snap,failed:true},now).pinned,false);
assert.ok(dealProgress({...snap,buyerWithdrew:true},now).attention);
const dispatch={permitted:true,suppressed:false,botPaused:false,humanOwnsConversation:false,exclusiveContactLease:true,duplicateOperation:false};
assert.equal(contactDispatchAllowed(dispatch),true);
for(const overrides of [{humanOwnsConversation:true},{exclusiveContactLease:false},{suppressed:true},{duplicateOperation:true},{botPaused:true}]) assert.equal(contactDispatchAllowed({...dispatch,...overrides}),false);
console.log('buyer planning and deal lifecycle checks passed');
