import assert from 'node:assert/strict';
import {buyerCallInstructions} from '../lib/buyer-call-policy.ts';
import {buyerPhoneFlowInstructions} from '../lib/buyer-phone-flow.ts';
const context={dealId:'deal',address:'45 Oak Road',askingPriceCents:16000000,repairsCents:2500000,packageId:'package',purchasePriceCents:15000000,assignmentFeeCents:1000000,packageUrl:'https://www.geticashx.com/d/fixture',buyerPaysClosingCosts:true};
const prompt=buyerCallInstructions(context,'Fixture Investor','Robin');
const steps=['1. BUYER AND TIMING','2. THE ACTUAL DEAL','3. QUESTIONS AND EVIDENCE','4. PACKAGE','5. SHOWING','6. PRICE, DEPOSIT AND TITLE','7. CLOSING AND NEXT STEP'];
for(let i=1;i<steps.length;i++)assert(prompt.indexOf(steps[i-1])<prompt.indexOf(steps[i]));
assert(prompt.includes('actual principal'));assert(prompt.includes('whether now is a good time'));
assert(prompt.includes('transferring the right to buy'));assert(prompt.includes('Do not imply the principal owns the property'));
assert(prompt.includes('approved total price and disclosed breakdown'));assert(prompt.includes('do not add the assignment fee twice'));
assert(prompt.includes('Offer photos only when actual permitted photos are available'));
assert(prompt.includes('repair figures as estimates'));assert(prompt.includes('Never disclose private seller hardship'));
assert(prompt.includes('showing is confirmed only after required buyer, seller/occupant and scheduling confirmation'));
assert(prompt.includes('do not invent a cost allocation'));
assert(prompt.includes('Do not present a non-refundable deposit as an automatic default'));
assert(prompt.includes('amount, due date, escrow recipient and exceptions'));
assert(prompt.includes('removes it from the market unless the executed agreement and current authorized state'));
assert(prompt.includes('actual agreed closing date or a clearly labeled proposed date'));
assert(prompt.includes('including a claim of twelve properties'));
assert(prompt.includes('Keep existing tool permissions unchanged'));
assert(prompt.includes('Do not add an introduction, recording question or transcript announcement'));
assert(prompt.includes('say accepted or delivered only after its matching result'));
const minimal={dealId:'d',address:'Fixture address',askingPriceCents:10000000,repairsCents:0,packageId:'p'};
assert(buyerCallInstructions(minimal,'Principal','Robin').includes('No package link is supplied'));
assert(!buyerPhoneFlowInstructions(false).includes('context supplies an authorized package link'));
// Unexpected seller/private fields cannot enter the model context through a widened RPC response.
const privatePrompt=buyerCallInstructions({...context,sellerHardship:'PRIVATE_HARDSHIP_MARKER',sellerPhone:'PRIVATE_PHONE_MARKER',maxOfferCents:99999999,photos:['UNVERIFIED_PHOTO_MARKER'],depositCents:123456,inventoryCount:12},'Principal','Robin');
for(const marker of ['PRIVATE_HARDSHIP_MARKER','PRIVATE_PHONE_MARKER','99999999','UNVERIFIED_PHOTO_MARKER','123456','inventoryCount'])assert(!privatePrompt.includes(marker),marker);
assert(privatePrompt.includes('"askingPriceCents":16000000'));assert(privatePrompt.includes('"assignmentFeeCents":1000000'));
for(const altered of [{askingPriceCents:0},{repairsCents:-1},{assignmentFeeCents:-1},{purchasePriceCents:-1},{assignmentFeeCents:1000001}])assert.throws(()=>buyerCallInstructions({...context,...altered},'Principal','Robin'));
assert.throws(()=>buyerCallInstructions({...minimal,assignmentFeeCents:1},'Principal','Robin'),/breakdown mismatch/);
console.log('Buyer phone flow: actual bound assignment, concise questions, factual assets/terms, real showing/deposit/escrow gates, private-field projection and retained notices passed. No provider calls.');
