import assert from 'node:assert/strict';
import {evaluateLaunch} from '../lib/launch-readiness-policy.ts';
import {reviewedContractCoverage,contractCapability} from '../lib/contract-coverage.ts';
const now=Date.parse('2026-09-30T12:00:00Z');
const template=(kind,patch={})=>({template_scope:'state',state_code:'TX',kind,signer_count:1,enabled:true,test_mode:false,provider:'docuseal',reviewed_until:'2026-10-01T12:00:00Z',rate:{operation:'contract_signing',enabled:true,expires_at:'2026-10-01T12:00:00Z'},...patch});
const coverage=reviewedContractCoverage([template('purchase'),template('assignment'),template('purchase',{signer_count:2})],now);
assert(contractCapability(coverage,'TX',1).supported);for(const [state,count] of [['AL',1],['TN',1],['TX',2],[null,1]])assert(!contractCapability(coverage,state,count).supported);
const standard=reviewedContractCoverage([template('purchase',{template_scope:'standard'}),template('assignment',{template_scope:'standard'})],now);
for(const state of ['TX','TN','AL','NY','CA','AK','HI'])assert(contractCapability(standard,state,1).supported);
for(const [state,count] of [[null,1],['',1],['not a state',1],['TX',2],['TN',0],['NY',9]])assert(!contractCapability(standard,state,count).supported);
assert.deepEqual(standard.standardSignerCounts,[1]);assert.deepEqual(standard.states,[]);assert.equal(standard.scope,'configured_templates');
assert(!/counsel|qualified reviewer|state-specific review/i.test(contractCapability(standard,'TN',1).reason));
const mixed=reviewedContractCoverage([template('purchase',{template_scope:'standard'}),template('assignment',{state_code:'TN'})],now);
assert(contractCapability(mixed,'TN',1).supported);assert(!contractCapability(mixed,'AL',1).supported);
for(const patch of [{test_mode:true},{enabled:false},{reviewed_until:'2026-01-01'},{reviewed_until:'invalid'},{rate:null},{provider:'other'},{template_scope:'unknown'},{rate:{operation:'seller_call',enabled:true,expires_at:'2026-10-01'}},{rate:{operation:'contract_signing',enabled:true,expires_at:'invalid'}}])assert(!contractCapability(reviewedContractCoverage([template('purchase',{template_scope:'standard'}),template('assignment',{template_scope:'standard',...patch})],now),'TN',1).supported);
const held=evaluateLaunch({cashReserve:true,discovery:true,voice:true,contactPermission:true,productionContracts:false,unresolvedDispatches:false},{data:true,voice:true,email:true,billing:true});assert.equal(held.ready,false);assert.equal(held.acquisitionReady,false);assert(held.blockers.includes('productionContracts'));
console.log('Contract availability: generic standard pair works across states, scoped forms remain scoped; exact signer counts, template/rate expiry, provider and mode checks stay enforced.');
