import assert from 'node:assert/strict';
import {conversationStreet,conversationAddressFields} from '../lib/conversation-address.ts';
import {sellerFirstMessage,ownershipAlreadyConfirmed} from '../lib/seller-call-context.ts';
import {buyerFirstMessage} from '../lib/buyer-call-policy.ts';
import {receptionContextVariables} from '../lib/reception-property-context.ts';
import {automaticOfferReceptionPolicy,automaticOfferReceptionPolicyHash} from '../lib/seller-agreement-reception.ts';
const address='650 GLADIOLA LOOP, KYLE, TX 78640';
assert.deepEqual(conversationAddressFields(address),{address:'650 GLADIOLA LOOP',city:'KYLE',state:'Texas'});
assert.deepEqual(conversationAddressFields('123 Main St, Apt 4B, Albany, NY 12207, USA'),{address:'123 Main St Apt 4B',city:'Albany',state:'New York'});
assert.equal(conversationStreet('123 Main St Unit 4B, Albany, NY 12207'),'123 Main St Unit 4B');
assert.equal(conversationStreet('45 Oak Road'),'45 Oak Road');
const history={threadId:'bound',messages:[{id:'q',direction:'outgoing',body:'Hi Josh, are you the owner of 650 GLADIOLA LOOP?',at:'2026-10-09T03:25:00Z'},{id:'a',direction:'incoming',body:'Yes',at:'2026-10-09T03:26:00Z'}]};
assert(ownershipAlreadyConfirmed(history,address));
assert(!ownershipAlreadyConfirmed(history,'651 GLADIOLA LOOP, KYLE, TX 78640'));
assert(!ownershipAlreadyConfirmed(history,'650 GLADIOLA LOOP Unit 2, KYLE, TX 78640'));
const c={address,principal:'Fixture buyer',assistantName:'Jamie',history,callbackRequestedNow:true};
assert.equal(sellerFirstMessage(c),"Let's go over the cash offer for 650 GLADIOLA LOOP.");
assert.equal(sellerFirstMessage({...c,history:null}),'Is this the owner of 650 GLADIOLA LOOP?');
assert(!buyerFirstMessage({address,firstName:'Jane'}).includes('TX'));
const config={context_policy:automaticOfferReceptionPolicy,context_policy_hash:automaticOfferReceptionPolicyHash,context_approval_reference:'Owner requested street-only speech',agreement_tool_id:'tool_fixture'};
const vars=receptionContextVariables(config,{status:'matched',address,returningName:'Josh',smsContext:history});
assert.equal(vars.icash_property_greeting,"Hi Josh. Let's continue with the cash offer for 650 GLADIOLA LOOP.");
const safe=JSON.parse(vars.icash_property_context);assert.equal(safe.address,'650 GLADIOLA LOOP');assert.equal(safe.state,'Texas');assert.equal(safe.ownershipAlreadyConfirmed,true);
assert.equal(c.address,address,'Canonical record stays complete');
console.log('PASS street-only seller, buyer and return-call greetings; full state names; units and ownership continuity.');
