import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {createHash,createHmac} from 'node:crypto';
import {object,sid,uuid,verifiedTwilioForm} from '../lib/required-call-recording.ts';
import {twilioUsdChargeMicros} from '../lib/twilio-usd-cost.ts';
import {boundedBytes} from '../lib/required-call-recording-provider.ts';
let calls=0;
const db=async()=>{throw Error('Unexpected database action');};
globalThis.__phone={createHash,createHmac,db,object,sid,uuid,verifiedTwilioForm,twilioUsdChargeMicros,boundedBytes};
const source=ts.transpileModule(readFileSync(new URL('../lib/customer-phone.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
const m=await import('data:text/javascript;base64,'+Buffer.from('const {createHash,createHmac,db,object,sid,uuid,verifiedTwilioForm,twilioUsdChargeMicros,boundedBytes}=globalThis.__phone;\n'+source).toString('base64'));
const from='+12025550101',to='+12025550102',quote={destination_number:to,origination_number:from,iso_country:'US',price_unit:'usd',outbound_call_prices:[{current_price:'0.014'}]};
assert.equal(m.customerPhoneQuote(quote,to,from),14000);
for(const q of [{...quote,iso_country:'BS'},{...quote,destination_number:from},{...quote,price_unit:'eur'},{...quote,outbound_call_prices:[{current_price:null}]},{...quote,outbound_call_prices:[{current_price:'0.11'}]}])assert.throws(()=>m.customerPhoneQuote(q,to,from));
const row={id:'12345678-1234-4234-8234-123456789abc',business_phone:from,callback_phone:to,recipient_phone:'+12025550103'};
const answer=m.customerPhoneTwiml(row,'answer','a'.repeat(64)),connect=m.customerPhoneTwiml(row,'connect','a'.repeat(64));
assert(!answer.includes('<Dial'));assert(answer.includes('numDigits="1"'));assert(connect.includes('callerId="'+from+'"'));assert(connect.includes('timeLimit="570"'));assert(connect.includes('record="do-not-record"'));assert(connect.includes(row.recipient_phone));assert(!connect.includes(row.callback_phone));
const env={TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_AUTH_TOKEN:'synthetic-secret-at-least-20'};
const p=m.customerPhoneProvider(env,async(url,options)=>{calls++;const form=new URLSearchParams(options.body);assert.equal(form.get('From'),from);assert.equal(form.get('To'),to);assert.equal(form.get('TimeLimit'),'600');assert.equal(form.get('Record'),'false');assert.equal(options.redirect,'error');return Response.json({sid:'CA'+'b'.repeat(32)});});
await p.dial(row,'a'.repeat(64));assert.equal(calls,1);
await assert.rejects(()=>m.startCustomerPhoneCall({phone:to,callbackPhone:to}),/PHONE_DIFFERENT_NUMBER_REQUIRED/);
console.log('PASS personal calling: bound US quotes, price limits, owner-first DTMF gate, business caller ID, bounded unrecorded legs, same-number prevention and no implicit provider retry.');
