import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {createHash,createHmac} from 'node:crypto';
import {object,sid,uuid,verifiedTwilioForm} from '../lib/required-call-recording.ts';
import {twilioUsdChargeMicros} from '../lib/twilio-usd-cost.ts';
import {boundedBytes,createRecordingProviders} from '../lib/required-call-recording-provider.ts';
let calls=0;
const db=async()=>{throw Error('Unexpected database action');};
globalThis.__phone={createHash,createHmac,db,object,sid,uuid,verifiedTwilioForm,twilioUsdChargeMicros,boundedBytes,createRecordingProviders};
const source=ts.transpileModule(readFileSync(new URL('../lib/customer-phone.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
const m=await import('data:text/javascript;base64,'+Buffer.from('const {createHash,createHmac,db,object,sid,uuid,verifiedTwilioForm,twilioUsdChargeMicros,boundedBytes,createRecordingProviders}=globalThis.__phone;\n'+source).toString('base64'));
const from='+12025550101',to='+12025550102',quote={destination_number:to,origination_number:from,iso_country:'US',price_unit:'usd',outbound_call_prices:[{current_price:'0.014'}]};
assert.equal(m.customerPhoneQuote(quote,to,from),14000);
for(const q of [{...quote,iso_country:'BS'},{...quote,destination_number:from},{...quote,price_unit:'eur'},{...quote,outbound_call_prices:[{current_price:null}]},{...quote,outbound_call_prices:[{current_price:'0.11'}]}])assert.throws(()=>m.customerPhoneQuote(q,to,from));
const row={id:'12345678-1234-4234-8234-123456789abc',business_phone:from,callback_phone:to,recipient_phone:'+12025550103',recording_required:true,provider_account_sid:'AC'+'a'.repeat(32),parent_sid:'CA'+'b'.repeat(32),created_at:new Date().toISOString(),max_seconds:600};
const answer=m.customerPhoneTwiml(row,'answer','a'.repeat(64)),connect=m.customerPhoneTwiml(row,'connect','a'.repeat(64));
assert(!answer.includes('<Dial'));assert(answer.includes('numDigits="1"'));assert(connect.includes('callerId="'+from+'"'));assert(connect.includes('timeLimit="570"'));assert(connect.includes('record="do-not-record"'));assert(connect.includes(row.recipient_phone));assert(!connect.includes(row.callback_phone));
const env={TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_AUTH_TOKEN:'synthetic-secret-at-least-20'};
const p=m.customerPhoneProvider(env,async(url,options)=>{calls++;const form=new URLSearchParams(options.body);assert.equal(form.get('From'),from);assert.equal(form.get('To'),to);assert.equal(form.get('TimeLimit'),'600');assert.equal(form.get('Record'),'true');assert.equal(form.get('RecordingChannels'),'dual');assert.equal(form.get('RecordingTrack'),'both');assert.equal(form.get('Trim'),'do-not-trim');assert.equal(form.get('RecordingStatusCallback'),m.customerPhoneBase+'/recording?id='+row.id+'&nonce='+'a'.repeat(64));assert.equal(options.redirect,'error');return Response.json({sid:'CA'+'b'.repeat(32)});});
await p.dial(row,'a'.repeat(64));assert.equal(calls,1);assert.throws(()=>p.dial({...row,recording_required:false},'a'.repeat(64)),/PHONE_RECORDING_SETUP_REQUIRED/);assert.equal(calls,1);
await assert.rejects(()=>m.startCustomerPhoneCall({phone:to,callbackPhone:to}),/PHONE_DIFFERENT_NUMBER_REQUIRED/);
console.log('PASS personal calling: bound US quotes, price limits, owner-first DTMF gate, business caller ID, one dual-channel parent recording, bounded legs, same-number prevention and no implicit provider retry.');

const audio={sid:'RE'+'c'.repeat(32),call_sid:row.parent_sid,account_sid:row.provider_account_sid,channels:2,source:'OutboundAPI',status:'completed',start_time:row.created_at,duration:'61',price:null,price_unit:'USD'};
const receipt=m.customerPhoneRecordingReceipt(row,audio);
assert.equal(receipt.costMicros,6000);assert.equal(receipt.recordingPriceEstimated,true);assert.equal(receipt.durationSeconds,61);
assert.equal(m.customerPhoneRecordingReceipt(row,{...audio,price:'-0.005'}).costMicros,6000);
for(const patch of [{call_sid:'CA'+'d'.repeat(32)},{account_sid:'AC'+'d'.repeat(32)},{channels:1},{source:'DialVerb'},{duration:'1000'},{start_time:'2000-01-01'},{status:'processing'}])assert.equal(m.customerPhoneRecordingReceipt(row,{...audio,...patch}),null);
const available={...row,recording_sid:audio.sid,recording_state:'available',recording_expires_at:receipt.expiresAt};assert(m.customerPhoneAudioAvailable(available));assert(!m.customerPhoneAudioAvailable({...available,recording_deleted_at:row.created_at}));assert(!m.customerPhoneAudioAvailable(available,Date.parse(receipt.expiresAt)+1));
console.log('PASS manual audio: exact parent/account/source/channels, bounded duration, explicit estimated costs, private availability and expiry.');
