import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
async function load(path,deps,key){globalThis[key]=deps;const code=ts.transpileModule(readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');const value=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.'+key+';\n'+code).toString('base64'));delete globalThis[key];return value;}
const {dailyCheckoutMatches}=await load('lib/daily-checkout-guard.ts',{},'__checkoutGuard');
let calls=[],failRead=false,early=false;
const originalPlan={id:'plan',mode:'live',account_id:'account',guest_hash:'hash',state:'pending',stripe_session_id:'cs_live_existing',stripe_subscription_id:null,consent_version:'daily-version',consent_text:'daily terms'};
const originalQuote={plan_id:'plan',pack_code:'budget_25',budget_cents:2500,credit_cents:2500,fee_cents:0,budget_price:'price_old',consent_text:'daily terms'};
const originalSession={id:'cs_live_existing',mode:'subscription',status:'open',currency:'usd',livemode:true,metadata:{icash_daily_plan:'plan'},amount_total:2500,url:'https://checkout.stripe.com/c/pay/existing',line_items:{has_more:false,data:[{quantity:1,currency:'usd',amount_total:2500,price:{id:'price_old',recurring:{interval:'day',interval_count:1}}}]}};
let plan,quote,session;
function reset(){calls=[];failRead=false;early=false;plan=structuredClone(originalPlan);quote=structuredClone(originalQuote);session=structuredClone(originalSession);}
const deps={dailyCheckoutMatches,acceptedEarlyAccessTerms:()=>true,earlyAccessTermsVersion:'early-version',earlyAccessDailyDisclosure:'early terms',setupEvent:async name=>calls.push({event:name}),customerFundingReady:async()=>true,NextResponse:{json:(body,o={})=>({body,status:o.status??200})},cookies:async()=>({get:()=>({value:'a'.repeat(64)}),set(){throw Error('Unexpected cookie creation');}}),randomBytes(){throw Error('Unexpected randomness');},currentUser:async()=>({id:'owner',email:'fixture@example.invalid'}),guestHash:()=> 'hash',allowedOrigin:()=>true,earlyAccessFundingEnabled:()=>early,fundingMode:()=> 'live',fundingStripe:()=>({checkout:{sessions:{retrieve:async(id,opts)=>{calls.push({retrieve:id,opts});if(failRead)throw Error('provider unavailable');return session;},create:async()=>{throw Error('Duplicate checkout creation forbidden');},expire:async()=>{throw Error('Automatic cancellation forbidden');}}},subscriptions:{retrieve:async id=>{calls.push({subscription:id});return {id,latest_invoice:'in_current'};}}}),limitRequest:async()=>{},validGuest:()=>true,dailyConsent:'daily terms',dailyConsentVersion:'daily-version',dailyQuote:async()=>{throw Error('Duplicate quote forbidden');},dailyReady:()=>true,stopDaily:async()=>{throw Error('Automatic cancellation forbidden');},syncDailySubscription:async()=>calls.push({sync:true}),settleDailyInvoice:async id=>calls.push({settle:id}),reconcileDailyCheckout:async p=>p,processingFeeCents:()=>0,db:async(path,method,body)=>{calls.push({path,method,body});if(path==='rpc/icash_daily_claim')return;if(path.startsWith('icash_accounts'))return [{id:'account'}];if(path.startsWith('icash_daily_plans'))return [plan];if(path.startsWith('icash_daily_quotes'))return quote?[quote]:[];if(path.startsWith('icash_credit_packs')){const amount=path.includes('budget_ten')?1000:path.includes('budget_50')?5000:2500;return [{price_cents:amount,credit_cents:amount}];}throw Error('Unexpected database mutation: '+path);}};
const {POST}=await load('app/api/billing/daily/route.ts',deps,'__checkoutRetry');
const request=(packCode='budget_25',totalCents=2500)=>new Request('https://example.invalid/api/billing/daily',{method:'POST',headers:{origin:'https://example.invalid'},body:JSON.stringify({action:'start',accepted:true,version:'daily-version',packCode,totalCents})});
reset();let result=await POST(request('budget_ten',1000));assert.equal(result.status,409);assert.match(result.body.error,/Stop the pending plan/);assert.equal(result.body.url,undefined);
reset();result=await POST(request('budget_50',5000));assert.equal(result.status,409,'Increased budget must not reuse old checkout');
reset();for(let n=0;n<2;n++){result=await POST(request());assert.equal(result.status,200);assert.equal(result.body.url,originalSession.url);}assert(calls.filter(c=>c.retrieve).every(c=>c.opts.expand.includes('line_items')));assert.equal(calls.filter(c=>c.event==='checkout_opened').length,2);
for(const mutate of [()=>{session.currency='eur';},()=>{session.livemode=false;},()=>{session.metadata.icash_daily_plan='other';},()=>{session.amount_total=2600;},()=>{session.line_items.data[0].quantity=2;},()=>{session.line_items.has_more=true;},()=>{session.line_items.data[0].price.recurring.interval='month';},()=>{session.line_items.data[0].price.id='price_unrecognized';quote=null;},()=>{quote.pack_code='different_pack';},()=>{quote.credit_cents=2000;},()=>{quote.consent_text='old terms';},()=>{plan.consent_version='old-version';},()=>{plan.consent_text='old terms';},()=>{early=true;},()=>{session.line_items=undefined;}]){reset();mutate();result=await POST(request());assert.equal(result.status,409);assert.equal(result.body.url,undefined);}
reset();session={...session,status:'complete',subscription:'sub_existing'};result=await POST(request());assert.equal(result.status,409);assert(calls.some(c=>c.settle==='in_current'));assert(!calls.some(c=>c.event));
reset();session.status='expired';result=await POST(request());assert.equal(result.status,409);assert.equal(result.body.url,undefined);
reset();failRead=true;result=await POST(request());assert.equal(result.status,503);assert.equal(result.body.url,undefined);
assert(!calls.some(c=>c.method==='POST'&&c.path!=='rpc/icash_daily_claim'));
console.log('Pending checkout retries: decreased/increased budgets and changed pack/currency/amount/terms rejected; identical retries reuse; completed/stale/provider-failure cases do not create or cancel payment attempts. Fixtures only.');
