import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
async function load(path,deps,key){globalThis[key]=deps;const code=ts.transpileModule(readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');const value=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.'+key+';\n'+code).toString('base64'));delete globalThis[key];return value;}
const {dailyCheckoutMatches}=await load('lib/daily-checkout-guard.ts',{},'__checkoutGuard');
let calls=[],failRead=false,early=false;
const originalPlan={id:'plan',mode:'live',account_id:'account',guest_hash:'hash',state:'pending',stripe_session_id:'cs_live_existing',stripe_subscription_id:null,consent_version:'daily-version',consent_text:'daily terms'};
const originalQuote={plan_id:'plan',pack_code:'budget_25',budget_cents:2500,credit_cents:2500,fee_cents:0,budget_price:'price_old',consent_text:'daily terms'};
const originalSession={id:'cs_live_existing',mode:'subscription',status:'open',currency:'usd',livemode:true,metadata:{icash_daily_plan:'plan'},amount_total:2500,url:'https://checkout.stripe.com/c/pay/existing',line_items:{has_more:false,data:[{quantity:1,currency:'usd',amount_total:2500,price:{id:'price_old',recurring:{interval:'day',interval_count:1}}}]}};
let plan,quote,session;
function reset(){calls=[];failRead=false;early=false;plan=structuredClone(originalPlan);quote=structuredClone(originalQuote);session=structuredClone(originalSession);}
const deps={dailyCheckoutMatches,acceptedEarlyAccessTerms:()=>true,earlyAccessTermsVersion:'early-version',earlyAccessDailyDisclosure:'early terms',setupEvent:async name=>calls.push({event:name}),customerFundingReady:async()=>true,NextResponse:{json:(body,o={})=>({body,status:o.status??200})},cookies:async()=>({get:()=>({value:'a'.repeat(64)}),set(){throw Error('Unexpected cookie creation');}}),randomBytes(){throw Error('Unexpected randomness');},currentUser:async()=>({id:'owner',email:'fixture@example.invalid'}),guestHash:()=> 'hash',allowedOrigin:()=>true,earlyAccessFundingEnabled:()=>early,fundingMode:()=> 'live',fundingStripe:()=>({checkout:{sessions:{retrieve:async(id,opts)=>{calls.push({retrieve:id,opts});if(failRead)throw Error('provider unavailable');return session;},create:async()=>{throw Error('Duplicate checkout creation forbidden');},expire:async()=>{throw Error('Automatic cancellation forbidden');}}},subscriptions:{retrieve:async id=>{calls.push({subscription:id});return {id,latest_invoice:'in_current'};}}}),limitRequest:async()=>{},validGuest:()=>true,dailyConsent:'daily terms',dailyConsentVersion:'daily-version',dailyQuote:async()=>{throw Error('Duplicate quote forbidden');},dailyReady:()=>true,stopDaily:async()=>{throw Error('Automatic cancellation forbidden');},syncDailySubscription:async()=>calls.push({sync:true}),settleDailyInvoice:async id=>calls.push({settle:id}),reconcileDailyCheckout:async p=>p,processingFeeCents:()=>0,db:async(path,method,body)=>{calls.push({path,method,body});if(path==='rpc/icash_daily_claim')return;if(path.startsWith('icash_accounts'))return [{id:'account'}];if(path.startsWith('icash_daily_plans'))return [plan];if(path.startsWith('icash_daily_quotes'))return quote?[quote]:[];if(path.startsWith('icash_credit_packs')){const amount=path.includes('budget_ten')?1000:path.includes('budget_50')?5000:2500;return [{price_cents:amount,credit_cents:amount}];}throw Error('Unexpected database mutation: '+path);}};
const {POST}=await load('app/api/billing/daily/route.ts',deps,'__checkoutRetry');
const request=(packCode='budget_25',totalCents=2500)=>new Request('https://example.invalid/api/billing/daily',{method:'POST',headers:{origin:'https://example.invalid'},body:JSON.stringify({action:'start',accepted:true,version:'daily-version',packCode,totalCents})});
reset();let result=await POST(request());assert.equal(result.status,200);assert.equal(result.body.url,originalSession.url);assert(calls.some(c=>c.retrieve));
for(const pack of ['budget_ten','budget_50']){reset();result=await POST(request(pack,pack==='budget_ten'?1000:5000));assert.equal(result.status,409);assert.equal(result.body.url,undefined);}
reset();quote.consent_text='old terms';result=await POST(request());assert.equal(result.status,409);
reset();session.livemode=false;result=await POST(request());assert.equal(result.status,409);
reset();failRead=true;result=await POST(request());assert.equal(result.status,503);
reset();session.status='complete';session.subscription='sub_current';result=await POST(request());assert.equal(result.status,409);assert(calls.some(c=>c.settle==='in_current'));
console.log('PASS daily checkout: matching retries reuse the verified session; changed amount, terms or mode are blocked; ambiguous reads do not create another checkout; completed sessions reconcile.');
