import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
let plan,history,receipts,calls,failInvoice,failPage,failCheckpoint,changeOwner,unpaidLatest,advanceClock,clock,legacyLatest,reviewLatest;
const original={id:'plan',mode:'live',guest_hash:'hash',account_id:'account',stripe_subscription_id:'sub_owned',stripe_session_id:null,state:'active',invoice_reconcile_cursor:null};
const currentPeriod=1790812800;
function reset(){plan={...original};history=Array.from({length:25},(_,n)=>({id:'in_'+String(n).padStart(3,'0'),n}));receipts=new Set();calls=[];failInvoice=null;failPage=null;failCheckpoint=false;changeOwner=false;unpaidLatest=false;advanceClock=null;clock=1000;legacyLatest=false;reviewLatest=false;}
const sub=()=>({id:'sub_owned',metadata:{icash_daily_plan:'plan'},livemode:true,status:'active',latest_invoice:'in_000'});
const number=id=>Number(id.split('_')[1]);
const amount=id=>number(id)===0?1000:2500;
const price=id=>'price_'+String(number(id));
const invoice=id=>({id,parent:{subscription_details:{subscription:'sub_owned'}},livemode:true,status:unpaidLatest&&id==='in_000'?'open':'paid',amount_remaining:unpaidLatest&&id==='in_000'?1000:0,currency:'usd',subtotal:amount(id),total:amount(id),amount_paid:amount(id),total_taxes:[],total_discount_amounts:[],status_transitions:{paid_at:currentPeriod+number(id)*86400},customer_email:'fixture@example.invalid',customer_phone:null});
const stripe={subscriptions:{retrieve:async id=>{calls.push({subscription:id});return sub();}},invoices:{retrieve:async id=>{calls.push({retrieve:id});if(id===failInvoice)throw Error('provider failure');return invoice(id);},listLineItems:async id=>({has_more:false,data:[{quantity:1,amount:amount(id),period:{start:currentPeriod-number(id)*86400,end:currentPeriod-(number(id)-1)*86400},pricing:{price_details:{price:price(id)}}}]}),list:async options=>{calls.push({list:options});assert.equal(options.subscription,'sub_owned');assert.equal(options.status,'paid');assert.equal(options.limit,10);if(options.starting_after===failPage)throw Error('page provider failure');const start=options.starting_after?history.findIndex(i=>i.id===options.starting_after)+1:0;const eligible=unpaidLatest?history.filter(i=>i.id!=='in_000'):history;return {data:eligible.slice(start,start+10),has_more:start+10<eligible.length};}},invoicePayments:{list:async({invoice:id})=>({has_more:false,data:[{payment:{payment_intent:'pi_'+String(number(id))}}]})},paymentIntents:{retrieve:async id=>({id,status:'succeeded',amount_received:Number(id.split('_')[1])===0?1000:2500,currency:'usd',livemode:true})}};
const db=async(path,method,body)=>{calls.push({path,method,body});if(path==='rpc/icash_daily_claim'){assert.equal(body.p_account,'account');return;}if(path.startsWith('icash_daily_plans')){if(!method)return [{...plan,...(changeOwner?{account_id:'other'}:{})}];if(Object.hasOwn(body,'invoice_reconcile_cursor')){if(failCheckpoint)return [];const expected=plan.invoice_reconcile_cursor?'eq.'+plan.invoice_reconcile_cursor:'is.null';assert(path.endsWith('invoice_reconcile_cursor='+expected),'Checkpoint must compare prior cursor');assert(path.includes('account_id=eq.account'));}Object.assign(plan,body);return [{...plan}];}if(path.startsWith('icash_funding_orders')){for(const binding of ['daily_plan_id=eq.plan','stripe_invoice_id=eq.in_000','mode=eq.live','account_id=eq.account','guest_hash=eq.hash','state=eq.paid','credited_at=not.is.null','billing_period_start=not.is.null','paid_at=not.is.null'])assert(path.includes(binding));return receipts.has('in_000')&&!legacyLatest?[{id:'recorded-current',stripe_payment_id:'pi_0'}]:[];}if(path.startsWith('icash_billing_reviews')){assert(path.includes('payment_id=eq.pi_0')&&path.includes('resolved_at=is.null'));return reviewLatest?[{event_id:'evt_review'}]:[];}if(path.startsWith('icash_daily_quotes')){const n=Number(path.match(/price_(\d+)/)[1]);return [{id:'quote'+n,plan_id:'plan',budget_cents:n===0?1000:2500,credit_cents:n===0?1000:2500,fee_cents:0,budget_price:'price_'+n}];}if(path==='rpc/icash_settle_daily_invoice_v2'){receipts.add(body.p_invoice);if(body.p_invoice==='in_000')legacyLatest=false;if(body.p_invoice===advanceClock)clock=10000;return;}throw Error('Unexpected DB path: '+path);};
globalThis.__invoiceRecovery={db,fundingStripe:()=>stripe,earlyAccessFundingEnabled:()=>false,fundingEnabled:()=>true,fundingMode:()=> 'live',processingFeeCents:()=>0,dailyConsent:'fixture'};
let code=ts.transpileModule(readFileSync(new URL('../lib/daily-billing.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'').replace(/^export \{.*\} from .*;$/gm,'');
code='const {'+Object.keys(globalThis.__invoiceRecovery).join(',')+'}=globalThis.__invoiceRecovery;\n'+code;
const {reconcileDailyInvoices,settleDailyInvoice}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));delete globalThis.__invoiceRecovery;
reset();let result=await reconcileDailyInvoices({...plan});assert.equal(result.historyPending,true);assert.equal(plan.invoice_reconcile_cursor,'in_019');assert.equal(receipts.size,20);assert.equal(calls.filter(c=>c.list).length,2);assert.equal(calls.find(c=>c.body?.p_invoice).body.p_invoice,'in_000','Latest cycle settles before history');
result=await reconcileDailyInvoices({...plan});assert.equal(result.historyPending,false);assert.equal(plan.invoice_reconcile_cursor,null);assert.equal(receipts.size,25);assert.equal(calls.filter(c=>c.list).at(-1).list.starting_after,'in_019');
const old=calls.find(c=>c.body?.p_invoice==='in_024').body;assert.equal(old.p_cycle_start,new Date((currentPeriod-24*86400)*1000).toISOString());assert.equal(old.p_paid_at,new Date((currentPeriod+24*86400)*1000).toISOString(),'Actual delayed paid time stays separate from billing-period order');
await reconcileDailyInvoices({...plan});assert.equal(receipts.size,25,'Another scan only replays existing invoice identities');
reset();failInvoice='in_011';await assert.rejects(()=>reconcileDailyInvoices({...plan}),/provider failure/);assert.equal(plan.invoice_reconcile_cursor,'in_010','Failed invoice retains last successful invoice');assert(receipts.has('in_010'));assert(!receipts.has('in_011'));failInvoice=null;await reconcileDailyInvoices({...plan});assert.equal(receipts.size,25);assert.equal(plan.invoice_reconcile_cursor,null);
reset();failPage='in_009';await assert.rejects(()=>reconcileDailyInvoices({...plan}),/page provider/);assert.equal(plan.invoice_reconcile_cursor,'in_009');failPage=null;await reconcileDailyInvoices({...plan});assert.equal(receipts.size,25);
reset();failCheckpoint=true;await assert.rejects(()=>reconcileDailyInvoices({...plan}),/checkpoint changed/);assert.equal(plan.invoice_reconcile_cursor,null);failCheckpoint=false;await reconcileDailyInvoices({...plan});await reconcileDailyInvoices({...plan});assert.equal(receipts.size,25);
reset();const expected={...plan};changeOwner=true;await assert.rejects(()=>settleDailyInvoice('in_000',expected),/owner mismatch/);assert.equal(receipts.size,0);
reset();await assert.rejects(()=>settleDailyInvoice('in_000',{...plan,stripe_subscription_id:'sub_other'}),/owner mismatch/);assert.equal(receipts.size,0);
reset();await assert.rejects(()=>reconcileDailyInvoices({...plan,mode:'test'}),/Subscription owner mismatch/);assert.equal(receipts.size,0);
reset();unpaidLatest=true;await reconcileDailyInvoices({...plan});assert(!receipts.has('in_000'),'Unpaid current invoice never grants');assert(receipts.has('in_001'),'Unpaid current invoice does not block older paid recovery');
reset();plan.state='stopped';history=[history[5]];result=await reconcileDailyInvoices({...plan});assert.equal(result.historyPending,false);assert(receipts.has('in_005'),'Stopped plan with null cursor recovers missed paid invoice');assert.equal(plan.state,'stopped');assert(!calls.some(c=>c.body?.stripe_subscription_id),'Stopped history never synchronizes/cancels billing');
reset();plan.state='stopped';failInvoice='in_011';await assert.rejects(()=>reconcileDailyInvoices({...plan}),/provider failure/);assert.equal(plan.invoice_reconcile_cursor,'in_010');assert.equal(plan.state,'stopped');failInvoice=null;await reconcileDailyInvoices({...plan});assert.equal(plan.invoice_reconcile_cursor,null);assert.equal(plan.state,'stopped');assert.equal(receipts.size,25);
reset();const actualNow=Date.now;Date.now=()=>clock;advanceClock='in_010';try{await assert.rejects(()=>reconcileDailyInvoices({...plan},5000),/deadline/);assert.equal(plan.invoice_reconcile_cursor,'in_010');assert(receipts.has('in_010'));assert(!receipts.has('in_011'));}finally{Date.now=actualNow;}advanceClock=null;await reconcileDailyInvoices({...plan});assert.equal(receipts.size,25);
reset();receipts.add('in_000');legacyLatest=true;await reconcileDailyInvoices({...plan});assert(calls.some(c=>c.retrieve==='in_000'),'Legacy/unknown chronology still requires full verification');
reset();receipts.add('in_000');reviewLatest=true;await reconcileDailyInvoices({...plan});assert(calls.some(c=>c.retrieve==='in_000'),'An unresolved payment review cannot use the known-receipt fast-path');
reset();const savedTime=Date.now;Date.now=()=>clock;try{for(const n of [3,7,11,15,19,23]){clock=1000;advanceClock='in_'+String(n).padStart(3,'0');await assert.rejects(()=>reconcileDailyInvoices({...plan},5000),/deadline/);assert.equal(plan.invoice_reconcile_cursor,advanceClock,'Repeated mid-first-page cutoffs must make durable progress');}clock=1000;advanceClock=null;await reconcileDailyInvoices({...plan},5000);assert.equal(plan.invoice_reconcile_cursor,null);assert.equal(receipts.size,25);assert.equal(calls.filter(c=>c.retrieve==='in_000').length,3,'Already verified latest receipt does not consume every later history run');}finally{Date.now=savedTime;}
reset();receipts.add('in_000');advanceClock='in_000';const beforeSlowLatest=Date.now;Date.now=()=>clock;try{clock=1000;await assert.rejects(()=>reconcileDailyInvoices({...plan},5000),/deadline/);assert.equal(plan.invoice_reconcile_cursor,'in_000');for(let n=0;n<2;n++){clock=1000;await reconcileDailyInvoices({...plan},5000);}assert.equal(receipts.size,25);assert.equal(plan.invoice_reconcile_cursor,null);assert.equal(calls.filter(c=>c.body?.p_invoice==='in_000').length,1,'Known latest must not repeatedly consume the entire history deadline');}finally{Date.now=beforeSlowLatest;}
console.log('Historical invoice recovery: bounded durable pages/reset, latest first, failed-invoice/provider/DB retry, duplicate identities, actual period/payment timestamps, cross-account/subscription/mode guards, unpaid-current handling, stopped-plan recovery and deadline preservation passed. Fixtures only.');
// Exercise scheduling fairness and stopped-plan inclusion through the actual cron route.
let routeCalls=[],lastAttemptState=null,slow=false,routeClock=1000;
const activePlan={...original,id:'active'},stoppedPlan={...original,id:'stopped',state:'stopped',invoice_reconcile_cursor:null};
const routeDeps={NextResponse:{json:(body,o={})=>({body,status:o.status??200})},timingSafeEqual:(a,b)=>a.equals(b),fundingMode:()=> 'live',fundingStripe:()=>{throw Error('No direct provider call for settled plans');},stopDaily:async()=>{throw Error('Historical recovery must not cancel stopped plans');},reconcileDailyCheckout:async p=>p,reconcileDailyInvoices:async(p,deadline)=>{routeCalls.push({recovered:p.id,deadline});if(slow)routeClock+=50000;return {historyPending:false};},db:async(path,method,body)=>{routeCalls.push({path,method,body});if(path==='rpc/icash_settle_pending_estimates')return;if(body?.reconciled_at){lastAttemptState=path.includes('id=eq.stopped')?'stopped':'active';return [];}if(path.includes('select=state'))return lastAttemptState?[{state:lastAttemptState}]:[];if(path.includes('state=neq.stopped')){assert(path.includes('limit=80'));return [activePlan];}if(path.includes('state=eq.stopped')){assert(path.includes('limit=20'));assert(!path.includes('invoice_reconcile_cursor'),'Stopped plans with no cursor must be included');return [stoppedPlan];}throw Error('Unexpected route query');}};
globalThis.__recoveryRoute=routeDeps;const routeSource=ts.transpileModule(readFileSync(new URL('../app/api/billing/reconcile/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
const {GET}=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(routeDeps).join(',')+'}=globalThis.__recoveryRoute;\n'+routeSource).toString('base64'));delete globalThis.__recoveryRoute;
const previousSecret=process.env.CRON_SECRET;process.env.CRON_SECRET='fixture';
const cronRequest=()=>new Request('https://example.invalid/api/billing/reconcile',{headers:{authorization:'Bearer fixture'}});
try{let response=await GET(cronRequest());assert.equal(response.status,200);assert.equal(response.body.checked,2);assert.deepEqual(routeCalls.filter(c=>c.recovered).map(c=>c.recovered),['active','stopped']);
 routeCalls=[];lastAttemptState=null;slow=true;const savedNow=Date.now;Date.now=()=>routeClock;try{for(let n=0;n<3;n++){response=await GET(cronRequest());assert.equal(response.body.checked,1);assert.equal(response.body.deferred,1);}}finally{Date.now=savedNow;}
 assert.deepEqual(routeCalls.filter(c=>c.recovered).map(c=>c.recovered),['active','stopped','active'],'Repeated cutoffs alternate the leading group instead of starving stopped history');
}finally{if(previousSecret===undefined)delete process.env.CRON_SECRET;else process.env.CRON_SECRET=previousSecret;}
console.log('Reconciliation route: null-cursor stopped plans included, bounded active/stopped allocations, interleaved attempts and repeated-cutoff group fairness passed.');
