import assert from 'node:assert/strict';
import {dealCardSummary,recordedDealProgress} from '../lib/deal-card-summary.ts';
const deal={id:'own',stage:'draft',terms:{priceCents:10000000}};
const signature={deal_id:'own',kind:'purchase',state:'completed',test_mode:false};
assert.equal(dealCardSummary(undefined,[]),null);
for(const e of [{...signature,test_mode:true},{...signature,deal_id:'other'},{...signature,state:'awaiting_counterparty'}]){
 const view=dealCardSummary(deal,[e]);assert.equal(view.priceCents,null);assert.equal(view.steps[0].done,false);
}
assert.equal(dealCardSummary(deal,[{...signature,kind:'assignment'}]).steps[1].done,false);
const signed=dealCardSummary(deal,[signature]);assert.equal(signed.priceCents,10000000);assert.equal(signed.steps[0].done,true);assert.equal(signed.steps[3].done,false);
assert.equal(dealCardSummary({...deal,stage:'closing'},[signature]).steps[3].done,false);
assert.equal(dealCardSummary({...deal,stage:'canceled'},[signature]).steps[3].done,false);
assert.equal(dealCardSummary({...deal,stage:'closed'},[signature]).steps[3].done,true);
console.log('Deal cards exclude test/other-deal signatures and do not imply closing or unsigned prices.');
assert.equal(signed.status,'Under contract');assert.equal(signed.steps[1].current,true);assert.match(signed.nextAction,/buyer package/);
const assignment={...signature,kind:'assignment'};
const assigned=dealCardSummary(deal,[signature,assignment]);assert.equal(assigned.status,'Awaiting buyer deposit');assert.equal(assigned.steps[1].current,true);assert.equal(assigned.steps[1].done,false);
assert.equal(dealCardSummary({...deal,stage:'closing'},[signature]).status,'Closing in progress');
assert.equal(dealCardSummary({...deal,stage:'closed'},[signature]).steps.some(s=>s.current),false);
assert.equal(dealCardSummary({...deal,stage:'cancelled'},[signature]).status,'Deal stopped');
assert.equal(dealCardSummary(deal,[{...signature,test_mode:true}]).contractSigned,false);
const confirmed={depositConfirmed:true,closingScheduledDate:null,paymentSent:false};
const reserved=dealCardSummary({...deal,progress:confirmed},[signature,assignment]);
assert.equal(reserved.status,'Buyer deposit confirmed');assert.equal(reserved.steps[1].done,true);assert.equal(reserved.steps[2].current,true);
assert.equal(dealCardSummary({...deal,progress:confirmed},[signature]).status,'Under contract','A receipt alone never invents a signed buyer agreement');
assert.equal(dealCardSummary({...deal,progress:confirmed},[signature,{...assignment,test_mode:true}]).steps[1].done,false);
assert.equal(dealCardSummary({...deal,stage:'title_open',progress:confirmed},[signature,assignment]).status,'Title opened');
const scheduled=dealCardSummary({...deal,stage:'closing',progress:{...confirmed,closingScheduledDate:'2026-10-23'}},[signature,assignment]);
assert.equal(scheduled.status,'Closing scheduled');assert.match(scheduled.nextAction,/Oct 23, 2026/);
assert.equal(scheduled.steps[3].done,false,'A scheduled closing is not a completed closing');
const sent=dealCardSummary({...deal,stage:'closed',progress:{...confirmed,paymentSent:true}},[signature,assignment]);
assert.equal(sent.status,'Title reports payment sent');assert.match(sent.nextAction,/Confirm the payment reached/);
assert.equal(dealCardSummary({...deal,stage:'canceled',progress:{...confirmed,paymentSent:true}},[signature,assignment]).status,'Deal stopped');
assert.equal(dealCardSummary({...deal,stage:'closing',progress:{...confirmed,paymentSent:true}},[signature,assignment]).status,'Closing in progress','Payment claim cannot skip a recorded closing');
const row={account_id:'account',deal_id:'own'};
assert.deepEqual(recordedDealProgress({id:'own',deposit:[row],scheduled:[{...row,effective_date:'2026-10-23'}],payment:[row]},'account'),{depositConfirmed:true,closingScheduledDate:'2026-10-23',paymentSent:true});
assert.deepEqual(recordedDealProgress({id:'own',deposit:[{...row,account_id:'other'}],scheduled:[{...row,deal_id:'other',effective_date:'2026-10-23'}],payment:[{...row,deal_id:'other'}]},'account'),{depositConfirmed:false,closingScheduledDate:null,paymentSent:false});
assert.equal(recordedDealProgress({id:'own',scheduled:[{...row,effective_date:'2026-02-30'}]},'account').closingScheduledDate,null);
console.log('Deal lifecycle scenarios passed: signatures, pending/confirmed deposit, title, scheduled/completed closing, payment confirmation, cancellation and tenant isolation.');
