import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {summarizeDealLearningEvidence,readDealLearningReport} from '../lib/deal-learning-report.ts';
const account='00000000-0000-4000-8000-000000000001',now=Date.parse('2026-10-07T18:00:00Z'),at='2026-10-06T12:00:00Z';
const deal={account_id:account,id:'d1',screening_id:'s1',practice:null};
const call={account_id:account,id:'c1',screening_id:'s1',party:'seller',strategy_key:'cash_interest',conversation_id:'provider-1',operation_key:'op1',state:'complete',created_at:at,completed_at:at};
const spend={account_id:account,operation_key:'op1',state:'settled',actual_micros:1234,cost_basis:'estimated',settlement_evidence:'bound receipt evidence',dispatched_at:at,settled_at:at};
const recipients=[{id:'1',email:'seller@example.test'},{id:'2',email:'buyer@example.test'}];
const envelope={account_id:account,id:'e1',deal_id:'d1',kind:'purchase',state:'completed',test_mode:false,provider_id:'101',terms_hash:'hash',recipients,updated_at:at,provider_evidence:{id:'101',test_mode:false,metadata:{icash_envelope:'e1',terms_hash:'hash'},apply_signing_order:true,status:'Completed',recipients:recipients.map((r,i)=>({...r,status:'signed',signing_order:i+1}))}};
const records={calls:[call],deals:[deal],spend:[spend],envelopes:[envelope]};
const summary=(patch={})=>summarizeDealLearningEvidence(account,{...records,...patch},now);
let r=summary();assert.equal(r.signedPurchaseDeals,1);assert.equal(r.closedDeals,null);assert.equal(r.automaticPromotion,false);assert.equal(r.strategyObservations[0].estimatedCostMicros,1234);assert.equal(r.strategyObservations[0].verifiedCostMicros,0);
assert(!JSON.stringify(r).includes('seller@example.test'));assert(!JSON.stringify(r).includes('provider-1'));assert(!JSON.stringify(r).includes('op1'));
assert.equal(summary({calls:[call,call],envelopes:[envelope,envelope]}).strategyObservations[0].recordedOperations,1);
assert.throws(()=>summary({calls:[call,{...call,state:'waiting'}]}),/Conflicting/);
assert.throws(()=>summary({spend:[{...spend,account_id:'foreign'}]}),/Mixed tenant/);
assert.equal(summary({deals:[{...deal,practice:'true'}]}).signedPurchaseDeals,0);
assert.equal(summary({deals:[]}).strategyObservations.length,0);
assert.equal(summary({spend:[]}).excludedOrUnboundCalls,1);
assert.equal(summary({spend:[{...spend,dispatched_at:null}]}).strategyObservations.length,0);
assert.equal(summary({calls:[{...call,created_at:'2027-01-01'}]}).strategyObservations.length,0);
assert.equal(summary({spend:[{...spend,cost_basis:'verified'}]}).strategyObservations[0].verifiedCostMicros,1234);
for(const patch of [{actual_micros:null},{actual_micros:-1},{settlement_evidence:null},{settled_at:null},{cost_basis:'unknown'}])assert.equal(summary({spend:[{...spend,...patch}]}).strategyObservations[0].unresolvedCostOperations,1);
for(const patch of [{test_mode:true},{provider_id:'wrong'},{provider_evidence:null},{recipients:[]},{state:'customer_signature_needed'},{updated_at:'2027-01-01'},{provider_evidence:{...envelope.provider_evidence,recipients:envelope.provider_evidence.recipients.map(x=>({...x,status:'pending'}))}}])assert.equal(summary({envelopes:[{...envelope,...patch}]}).signedPurchaseDeals,0);
assert.equal(summary({envelopes:[{...envelope,deal_id:'foreign'}]}).signedPurchaseDeals,0);
const tables={icash_live_conversations:records.calls,icash_deal_files:records.deals,icash_operation_spend:records.spend,icash_signing_envelopes:records.envelopes};
let paths=[];
r=await readDealLearningReport(async(path,method)=>{assert.equal(method,undefined);assert(path.includes(`account_id=eq.${account}`));assert(!path.includes('select=*'));paths.push(path);return tables[path.split('?')[0]];},account,now);
assert.equal(r.signedPurchaseDeals,1);assert.equal(paths.length,4);assert.equal(r.complete,true);
await assert.rejects(()=>readDealLearningReport(async()=>[],"evil&account_id=neq.x",now));
await assert.rejects(()=>readDealLearningReport(async()=>[{account_id:'foreign'}],account,now),/Invalid evidence response/);
// A full bounded page is never silently presented as a complete total.
let page=0;r=await readDealLearningReport(async(path)=>{if(!path.startsWith('icash_deal_files?'))return [];page++;return Array.from({length:200},(_,i)=>({...deal,id:`${page}-${i}`}));},account,now);
assert.equal(page,5);assert.equal(r.complete,false);assert(r.limitations.some(x=>x.includes('partial')));
// Route owns authentication; no account IDs are taken from URL or request body.
let auth=true,reads=0;
const mocks={workAccount:async()=>{if(!auth)throw Error('no');return {accountId:account};},db:()=>{},readDealLearningReport:async(_db,id)=>{reads++;assert.equal(id,account);return {mode:'observation_only'};}};
globalThis.__learningMocks=mocks;
let source=ts.transpileModule(readFileSync(new URL('../app/api/work/learning/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
source='const {'+Object.keys(mocks).join(',')+'}=globalThis.__learningMocks;\n'+source;
const {GET}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
let response=await GET();assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'private, no-store');assert.equal(reads,1);
auth=false;response=await GET();assert.equal(response.status,503);assert.equal(reads,1);delete globalThis.__learningMocks;
console.log('Deal learning report: tenant isolation, evidence binding, no false closures, cost basis, deduplication, bounded reads and authenticated read-only route passed.');
