import assert from 'node:assert/strict';
import {liveConversationResult,dealNextStep,openerForAssignment} from '../lib/deal-conversation.ts';
import {contractReadiness,proposedClosingDate} from '../lib/contract-readiness.ts';
const now=Date.parse('2026-09-29T00:00:00Z');
const c={conversation_id:'conv_live',agent_id:'agent_live',status:'done',transcript:[{role:'user',message:'I want to talk to a person.'}],analysis:{transcript_summary:'Asked for a human.',data_collection_results:{}}};
const expected={conversationId:'conv_live',agentId:'agent_live',party:'buyer'};
assert.equal(liveConversationResult(c,expected,now).humanRequested,true);
assert.equal(liveConversationResult(c,expected,now).underContract,false);
assert.equal(liveConversationResult({...c,transcript:[{role:'user',message:'Stop calling me.'}]},expected,now).optedOut,true);
assert.throws(()=>liveConversationResult(c,{...expected,agentId:'agent_wrong'},now));
assert.equal(liveConversationResult({...c,analysis:{...c.analysis,data_collection_results:{interested:{value:true},interest_quote:{value:'Yes I will sell'}}}},expected,now).interested,false);
assert.equal(openerForAssignment(4999),'cash_interest');assert.equal(openerForAssignment(5000),'flexible_timing');
assert.throws(()=>openerForAssignment(-1));
const d={humanRequested:false,optedOut:false,interested:true,qualified:true,agreedPriceCents:10000,signedEvidence:false,authority:{expiresAt:now+10000,maxOfferCents:10000,ownershipVerified:true,allOwnersOnBoard:true,termsReviewed:true,deliveryEnabled:false},now};
assert.equal(dealNextStep(d),'prepare_contract_draft');
assert.equal(dealNextStep({...d,agreedPriceCents:10001}),'review_counteroffer');
assert.equal(dealNextStep({...d,humanRequested:true,signedEvidence:true}),'human_handoff');
assert.equal(dealNextStep({...d,optedOut:true,humanRequested:true}),'stop_contact');
const s={agreedPriceCents:10000,approvedCeilingCents:10000,allDecisionMakersPresent:true,allOwnersConfirmed:true,legalDescription:'LOT 1 BLOCK 2',legalDescriptionReviewed:true,sellerSignaturesVerified:false,customerSignatureVerified:false,autoSignAuthorization:null,documentHash:'a'.repeat(64),now};
assert.equal(contractReadiness(s),'seller_signs_first');
assert.equal(contractReadiness({...s,allDecisionMakersPresent:false}),'wait_for_decision_makers');
assert.equal(contractReadiness({...s,sellerSignaturesVerified:true}),'request_customer_signature');
assert.equal(contractReadiness({...s,sellerSignaturesVerified:true,customerSignatureVerified:true}),'fully_signed');
assert.equal(contractReadiness({...s,sellerSignaturesVerified:true,autoSignAuthorization:{active:true,expiresAt:now+1000,maxPriceCents:10000,documentHash:'b'.repeat(64)}}),'request_customer_signature');
assert.equal(proposedClosingDate('2026-09-28'),'2026-10-28');assert.throws(()=>proposedClosingDate('2026-02-30'));
console.log('Deal conversation, handoff, offer authority and seller-first signature checks passed.');
