import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {earlyAccessFundingEnabled,fundingEnabled,fundingMode,allowedOrigin} from '../lib/funding-policy.ts';
import {acceptedFundingTerms,fundingTermsVersion,fundingTermsText,acceptedEarlyAccessTerms,earlyAccessTermsVersion,earlyAccessDisclosure,earlyAccessDailyDisclosure} from '../lib/funding-consent.ts';
import {dailyConsent,dailyConsentVersion} from '../lib/daily-consent.ts';
import {evaluateLaunch} from '../lib/launch-readiness-policy.ts';
// All providers are in-memory fixtures. Never make live API requests or purchases.
const env={VERCEL_ENV:'production',STRIPE_SECRET_KEY:'sk_live_fixture',SUPABASE_URL:'https://example.invalid',SUPABASE_SECRET_KEY:'fixture',STRIPE_WEBHOOK_SECRET:'fixture',ICASH_AUTH_EMAIL_READY:'true',ICASH_LIVE_PAYMENTS_ENABLED:'true',ICASH_EARLY_ACCESS_FUNDING_ENABLED:'true',ICASH_LIVE_WORK_READY:'false',ICASH_DAILY_BILLING_READY:'true',CRON_SECRET:'fixture',DEALMACHINE_API_KEY:'fixture',ELEVENLABS_API_KEY:'fixture'};
assert.equal(earlyAccessFundingEnabled(env),true);assert.equal(fundingEnabled(env),false);
for(const key of ['SUPABASE_URL','SUPABASE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','ICASH_AUTH_EMAIL_READY','ICASH_LIVE_PAYMENTS_ENABLED','ICASH_EARLY_ACCESS_FUNDING_ENABLED'])assert.equal(earlyAccessFundingEnabled({...env,[key]:''}),false,key);
assert.equal(earlyAccessFundingEnabled({...env,VERCEL_ENV:'preview'}),false);
assert.equal(earlyAccessFundingEnabled({...env,STRIPE_SECRET_KEY:'sk_test_fixture'}),false);
Object.assign(process.env,env);
let seq=0;
async function load(file,deps){const key='__fundingFixture'+seq++;globalThis[key]=deps;let code=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;code=code.replace(/^import .* from .*;$/gm,'').replace(/^export \{.*\} from .*;$/gm,'');assert(!/^import /m.test(code));try{return await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.'+key+';\n'+code).toString('base64'));}finally{delete globalThis[key];}}
const readiness=await load('lib/launch-readiness.ts',{earlyAccessFundingEnabled,fundingEnabled,fundingMode,evaluateLaunch,readContractCoverage:async()=>({states:[]}),db:async path=>path.startsWith('rpc/')?{cashReserve:true,discovery:true,voice:false,contactPermission:false,productionContracts:false,unresolvedDispatches:false}:[]});
assert.equal(await readiness.customerFundingReady(),true);assert.equal(await readiness.liveFundingReady(),false);let launch=await readiness.launchReadiness();assert.equal(launch.ready,false);assert.equal(launch.acquisitionReady,false);assert(launch.blockers.includes('voice'));assert(launch.blockers.includes('productionContracts'));
const billing=await load('lib/daily-billing.ts',{earlyAccessFundingEnabled,fundingEnabled,fundingMode,dailyConsent,db:async()=>[],fundingStripe:()=>{throw Error('Unexpected provider call');},processingFeeCents:()=>0});
assert.equal(billing.dailyReady(),true);process.env.ICASH_AUTH_EMAIL_READY='false';assert.equal(billing.dailyReady(),false);assert.equal(await readiness.customerFundingReady(),false);process.env.ICASH_AUTH_EMAIL_READY='true';
let plans=[],pack={code:'budget_ten',price_cents:1000,credit_cents:1000},records=[],checkouts=[],quotes=[],stops=[],session={status:'open',url:'https://checkout.stripe.com/fixture',metadata:{}};
const stripe={checkout:{sessions:{create:async(body,options)=>{checkouts.push({body,options});return {id:'cs_live_fixture',livemode:true,url:'https://checkout.stripe.com/fixture'};},retrieve:async()=>session}},subscriptions:{retrieve:async()=>({id:'sub_fixture',status:'active',items:{data:[{id:'si_fixture'}]}}),update:async(id,body,options)=>{records.push({update:id,body,options});}}};
const db=async(path,method,body)=>{records.push({path,method,body});if(path.startsWith('icash_accounts'))return [{id:'account'}];if(path.startsWith('icash_credit_packs')){assert(path.includes('enabled=eq.true'));return pack?[pack]:[];}if(path.startsWith('icash_daily_plans')){if(method==='POST')return [{id:'plan',...body,state:'pending'}];if(method==='PATCH')return [{id:'plan',state:'pending',...body}];return plans;}return [];};
const mocks={acceptedEarlyAccessTerms,earlyAccessTermsVersion,earlyAccessDailyDisclosure,setupEvent:async()=>{},customerFundingReady:readiness.customerFundingReady,NextResponse:{json:(body,options={})=>({body,status:options.status??200})},cookies:async()=>({get:()=>({value:'a'.repeat(64)}),set:()=>{}}),randomBytes:()=>{throw Error('Unneeded randomness');},currentUser:async()=>({id:'user',email:'customer@example.invalid'}),db,guestHash:()=> 'a'.repeat(64),allowedOrigin,earlyAccessFundingEnabled,fundingMode,fundingStripe:()=>stripe,limitRequest:async()=>{},validGuest:()=>true,dailyConsent,dailyConsentVersion,dailyReady:billing.dailyReady,dailyQuote:async(p,code,consent)=>{quotes.push({p,code,consent});return {id:'quote',budget_price:'price_fixture'};},stopDaily:async p=>{stops.push(p.id);},syncDailySubscription:async()=>{},settleDailyInvoice:async()=>{},reconcileDailyCheckout:async p=>p,processingFeeCents:()=>0};
const daily=await load('app/api/billing/daily/route.ts',mocks);
const input={action:'start',accepted:true,version:dailyConsentVersion,packCode:'budget_ten',days:1,totalCents:1000,earlyAccessAccepted:true,earlyAccessVersion:earlyAccessTermsVersion};
const req=body=>new Request('https://example.invalid/api/billing/daily',{method:'POST',headers:{origin:'https://example.invalid'},body:JSON.stringify(body)});
for(const bad of [{earlyAccessAccepted:false},{earlyAccessVersion:'old'},{earlyAccessAccepted:'true'}]){assert.equal((await daily.POST(req({...input,...bad}))).status,400);assert.equal(checkouts.length,0);assert.equal(quotes.length,0);}
assert.equal((await daily.GET()).body.ready,true);
assert.equal((await daily.POST(req({...input,totalCents:999}))).status,400);assert.equal(checkouts.length,0);
pack={...pack,price_cents:300};assert.equal((await daily.POST(req({...input,totalCents:300}))).status,400);pack={...pack,price_cents:1000};
let response=await daily.POST(req(input));assert.equal(response.status,200);assert.equal(checkouts.length,1);const checkout=checkouts[0];assert.equal(checkout.body.mode,'subscription');assert.equal(checkout.options.idempotencyKey,'daily-checkout:plan');assert.equal(checkout.body.line_items[0].price,'price_fixture');assert.equal(checkout.body.automatic_tax.enabled,false);assert.equal(checkout.body.metadata.icash_early_access_terms_version,earlyAccessTermsVersion);assert(checkout.body.custom_text.submit.message.includes('even while live work is unavailable'));assert(quotes[0].consent.includes(earlyAccessDailyDisclosure));assert(records.some(r=>r.path==='icash_daily_plans'&&r.body?.consent_text?.includes(earlyAccessDailyDisclosure)&&r.body.consent_version.includes(earlyAccessTermsVersion)));
// A checkout without the current disclosed limitations cannot be reused.
plans=[{id:'old-plan',state:'pending',stripe_session_id:'cs_live_old'}];assert.equal((await daily.POST(req(input))).status,409);assert.equal(checkouts.length,1);
session={...session,metadata:{icash_early_access_terms_version:earlyAccessTermsVersion}};assert.equal((await daily.POST(req(input))).status,200);assert.equal(checkouts.length,1,'retry reuses the existing checkout');
// Updates persist the acknowledgment with the quote and leave proration/renewal intact.
plans=[{id:'active-plan',state:'active',stripe_subscription_id:'sub_fixture'}];assert.equal((await daily.POST(req({...input,action:'change'}))).status,200);assert(quotes.at(-1).consent.includes(earlyAccessDailyDisclosure));assert(records.some(r=>r.update==='sub_fixture'&&r.body.proration_behavior==='none'&&r.body.payment_behavior==='error_if_incomplete'));
process.env.ICASH_EARLY_ACCESS_FUNDING_ENABLED='false';assert.equal((await daily.POST(req(input))).status,503);assert.equal((await daily.POST(req({action:'stop'}))).body.stopped,true);assert.deepEqual(stops,['active-plan']);
// Work/contact/signing code does not consume the funding-only override.
for(const file of ['lib/live-dispatch-service.ts','lib/discovery-service.ts','lib/signing-service.ts','lib/action-authority.ts','app/api/work/control/route.ts']){const code=readFileSync(new URL('../'+file,import.meta.url),'utf8');assert(!code.includes('earlyAccessFundingEnabled'));assert(!code.includes('customerFundingReady'));}
const settle=readFileSync(new URL('../lib/funding.ts',import.meta.url),'utf8');assert(!settle.includes('fundingEnabled'));assert(!settle.includes('earlyAccessFundingEnabled'));
console.log('Early access: funding-only gates, unavailable work, daily consent, quotes, renewal, private minimum, retries, cancellation and settlement independence passed.');
// The existing one-time endpoint keeps the private $3 allowlist and public $10 minimum.
process.env.ICASH_EARLY_ACCESS_FUNDING_ENABLED='true';
let privateAllowed=false,oneTimeCreates=[],oneTimeConsent=[],oldOrders=[];
const oneTime=await load('app/api/funding/checkout/route.ts',{privatePaymentCheckAllowed:async()=>privateAllowed,customerFundingReady:readiness.customerFundingReady,NextResponse:mocks.NextResponse,cookies:mocks.cookies,randomBytes:mocks.randomBytes,currentUser:mocks.currentUser,guestHash:mocks.guestHash,allowedOrigin,earlyAccessFundingEnabled,fundingMode,validGuest:()=>true,limitRequest:async()=>{},settleFunding:async()=>{},acceptedFundingTerms,fundingTermsVersion,fundingTermsText,acceptedEarlyAccessTerms,earlyAccessTermsVersion,earlyAccessDisclosure,maximumFundingDays:()=>7,processingFeeCents:()=>0,fundingStripe:()=>({checkout:{sessions:{create:async(body,options)=>{oneTimeCreates.push({body,options});return {id:'cs_live_once',livemode:true,url:'https://checkout.stripe.com/fixture'};}}}}),db:async(path,method,body)=>{if(path.startsWith('icash_accounts'))return [{id:'account'}];if(path.startsWith('icash_credit_packs'))return [{code:path.includes('private_check_three')?'private_check_three':'budget_ten',price_cents:path.includes('private_check_three')?300:1000,credit_cents:path.includes('private_check_three')?300:1000}];if(path==='rpc/icash_record_funding_consent'){oneTimeConsent.push(body);return [];}if(path.startsWith('icash_funding_orders')){if(method==='POST')return [{id:'order',...body}];if(!method)return oldOrders;return [];}throw Error('Unexpected fixture query '+path);}});
const once={accepted:true,version:fundingTermsVersion,packCode:'budget_ten',days:1,totalCents:1000,earlyAccessAccepted:true,earlyAccessVersion:earlyAccessTermsVersion};
assert.equal((await oneTime.POST(req({...once,earlyAccessAccepted:false}))).status,400);assert.equal(oneTimeCreates.length,0);
assert.equal((await oneTime.POST(req({...once,totalCents:999}))).status,400);assert.equal(oneTimeCreates.length,0);
assert.equal((await oneTime.POST(req({...once,packCode:'private_check_three',totalCents:300}))).status,503);assert.equal(oneTimeCreates.length,0);
assert.equal((await oneTime.POST(req(once))).status,200);assert.equal(oneTimeCreates[0].body.mode,'payment');assert(oneTimeConsent[0].p_terms.includes(earlyAccessDisclosure));assert.equal(oneTimeCreates[0].body.metadata.icash_early_access_terms_version,earlyAccessTermsVersion);
privateAllowed=true;process.env.ICASH_EARLY_ACCESS_FUNDING_ENABLED='false';
assert.equal((await oneTime.POST(req({...once,packCode:'private_check_three',totalCents:300,earlyAccessAccepted:false}))).status,200);assert.equal(oneTimeCreates.at(-1).body.metadata.icash_private_payment_check,'true');
assert.equal((await oneTime.POST(req({...once,packCode:'private_check_three',days:2,totalCents:600}))).status,400);
assert.equal((await oneTime.POST(req(once))).status,503,'private access cannot open public funding when flags are off');
console.log('One-time funding: separate persisted acknowledgment, unchanged prices and allowlisted $3 private check passed.');
