import assert from 'node:assert/strict';
import {screenEquity as screen,sellerCallFinancialGate as gate} from '../lib/equity-screen.ts';
assert.equal(screen({},10000).status,'debt_unknown');
assert.equal(screen({estimated_value:200000,estimated_equity_amount:50000},10000000).status,'payoff_may_exceed_budget');
assert.equal(screen({estimated_value:200000,estimated_equity_amount:-10000},10000000).estimatedLoanBalanceCents,21000000);
assert.equal(screen({estimated_value:200000,estimated_equity_amount:200000},10000000).titleStatus,'unverified');
assert.equal(screen({has_active_lien:false},null).titleStatus,'unverified');
assert.equal(screen({has_active_lien:'false'},null).activeLien,null);
assert.equal(screen({has_hoa_lien:true},null).status,'title_review_needed');
assert.equal(screen({is_tax_delinquent:true},null).status,'title_review_needed');
assert.equal(screen({is_free_and_clear:true,total_estimated_loan_balance:1000},null).status,'conflicting_data');
assert.equal(screen({estimated_value:10,estimated_equity_amount:20},null).status,'conflicting_data');
const x=screen({total_estimated_loan_balance:50000,total_open_lien_amount:50000},10000000);
assert.equal(x.fundsAfterEstimatedMortgageBeforeFeesCents,5000000);
assert.equal(x.lienAndMortgageTotalsCombined,false);
assert.equal(x.dealApproved,false);
assert.equal(screen({total_estimated_loan_balance:'0'},10000).estimatedLoanBalanceCents,null);
console.log('Equity, unknown debt, lien indicators and overlapping balances passed');

assert.equal(gate(screen({},null),{sellerOfferCents:10000000,sellerCostReserveCents:0,checkedAt:1}).status,'hold');
assert.equal(gate(screen({total_estimated_loan_balance:150000},null),{sellerOfferCents:10000000,sellerCostReserveCents:0,checkedAt:1}).status,'hold');
assert.equal(gate(screen({total_estimated_loan_balance:50000},null),{sellerOfferCents:10000000,sellerCostReserveCents:null,checkedAt:1}).status,'hold');
assert.equal(gate(screen({total_estimated_loan_balance:50000},null),{sellerOfferCents:10000000,sellerCostReserveCents:500000,checkedAt:1}).status,'eligible');
import {allocateCredits} from '../lib/outbound-brain.ts';
const base={balanceCents:100000,fundedAmountCents:100000,userDailyLimitCents:10000,spentTodayCents:0,now:100000000,actions:[]};
const action={id:'call',stage:'qualification',customerChargeCents:100,estimatedProviderCostCents:10,evidenceAt:1,dueAt:1,permitted:true,operation:'seller_call'};
assert.equal(allocateCredits({...base,actions:[action]}).selected.length,0);
assert.equal(allocateCredits({...base,actions:[{...action,financialCheck:{status:'hold',checkedAt:base.now,reason:'debt'}}]}).selected.length,0);
assert.equal(allocateCredits({...base,actions:[{...action,financialCheck:{status:'eligible',checkedAt:1,reason:'stale'}}]}).selected.length,0);
assert.equal(allocateCredits({...base,actions:[{...action,financialCheck:{status:'eligible',checkedAt:base.now,reason:'checked'}}]}).selected.length,1);
console.log('Pre-call financial gate and credit allocation block failed, absent and stale screening');
