import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {sampleInputs,sampleOffer,restoreSampleInputs} from '../lib/free-sample.ts';
assert.deepEqual(sampleOffer(sampleInputs),{buyerBudgetCents:13650000,sellerCapCents:12150000,hasRoom:true});
assert.equal(sampleOffer({...sampleInputs,repairs:'35000'}).sellerCapCents,11450000);
assert.equal(sampleOffer({...sampleInputs,fee:'30000'}).sellerCapCents,10650000);
assert.equal(sampleOffer({value:'100.01',repairs:'0.01',fee:'0'}).sellerCapCents,7000);
for(const bad of ['', ' ', '-1', 'NaN', 'Infinity', '1e9', '1.123', '100000001'])for(const key of ['value','repairs','fee'])assert.equal(sampleOffer({...sampleInputs,[key]:bad}),null);
assert.equal(sampleOffer({...sampleInputs,value:'0'}),null);
assert.equal(sampleOffer({...sampleInputs,repairs:'200000'}).hasRoom,false);
const component=readFileSync(new URL('../components/free-sample-workspace.tsx',import.meta.url),'utf8');
assert.doesNotMatch(component,/fetch\(|\/api\//,'the free sample does not call providers or app APIs');
for(const text of ['FREE EXAMPLE','fictional','Written example only','No call is made','not promised income','Run this for real','daily billing'])assert(component.toLowerCase().includes(text.toLowerCase()),text);
assert.match(component,/localStorage\.setItem/,'sample calculation is retained locally');
assert.match(component,/Reset example numbers/);
const setup=readFileSync(new URL('../components/bot-setup.tsx',import.meta.url),'utf8');
assert.match(setup,/navigate\('funding'\);setBuildPhase\(null\)/,'saved setup opens funding directly');
assert.doesNotMatch(setup,/FreeSampleWorkspace/,'fictional sample is not part of bot creation');
assert.match(setup,/Edit bot name/);
assert.match(setup,/paymentReturn\|\|hash/,'payment return keeps priority');
const page=readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');
assert.doesNotMatch(page,/Try a free deal example|FreeSampleWorkspace/,'sample removed from customer workspace');
console.log('PASS free sample arithmetic, invalid input, honest fictional conversation, no API use, retained calculator and funding/back entry points');

assert.deepEqual(restoreSampleInputs({value:'310000',repairs:'',fee:'20000'}),{value:'310000',repairs:'',fee:'20000'},'incomplete input remains saved');
for(const draft of [null,{},[],{value:1,repairs:'0',fee:'0'},{value:'1'.repeat(25),repairs:'0',fee:'0'}])assert.equal(restoreSampleInputs(draft),null);
assert.match(component,/maximumFractionDigits:2/,'do not round a cent-valued offer cap up to whole dollars');
const checkout=readFileSync(new URL('../components/funding-checkout.tsx',import.meta.url),'utf8');
assert.match(checkout,/return\(\)=>\{alive.current=false;/,'closing funding invalidates pending responses');
assert.match(checkout,/const d=await r.json\(\);if\(!alive.current\)return;/,'late checkout response cannot navigate after closing');
