import assert from 'node:assert/strict';
import {fundingMode,fundingEnabled,fundingSessionMatches,allowedOrigin,normalizeEmail} from '../lib/funding-policy.ts';
const test={VERCEL_ENV:'preview',STRIPE_SECRET_KEY:'sk_test_example',SUPABASE_URL:'https://example.supabase.co',SUPABASE_SECRET_KEY:'server-key',STRIPE_WEBHOOK_SECRET:'whsec_example',ICASH_AUTH_EMAIL_READY:'true'};
assert.equal(fundingMode(test),'test');assert.equal(fundingEnabled(test),true);
assert.equal(fundingEnabled({...test,ICASH_AUTH_EMAIL_READY:'false'}),false);
assert.equal(fundingMode({...test,VERCEL_ENV:'production'}),null);
const live={...test,VERCEL_ENV:'production',STRIPE_SECRET_KEY:'sk_live_example'};
assert.equal(fundingMode(live),'live');assert.equal(fundingEnabled(live),false);
assert.equal(fundingEnabled({...live,ICASH_LIVE_PAYMENTS_ENABLED:'true'}),false);
assert.equal(fundingEnabled({...live,ICASH_LIVE_PAYMENTS_ENABLED:'true',ICASH_LIVE_WORK_READY:'true'}),true);
assert.equal(fundingMode({...live,VERCEL_ENV:'preview'}),null);
const order={id:'order',mode:'test',price_cents:2000,stripe_session_id:'cs_test_ok'};
const session={id:'cs_test_ok',livemode:false,mode:'payment',status:'complete',payment_status:'paid',currency:'usd',amount_total:2000,metadata:{icash_funding_order:'order'},payment_intent:'pi_ok',customer_details:{email:'buyer@example.com'}};
assert.equal(fundingSessionMatches(session,order),true);
for(const change of [{livemode:true},{id:'cs_test_wrong'},{amount_total:100},{currency:'eur'},{payment_status:'unpaid'},{status:'open'},{metadata:{}},{customer_details:{}},{payment_intent:null}])assert.equal(fundingSessionMatches({...session,...change},order),false);
assert.equal(normalizeEmail(' Person@Example.com '),'person@example.com');assert.equal(normalizeEmail('evil\n@example.com'),null);
const env={VERCEL_URL:'unique.vercel.app',VERCEL_BRANCH_URL:'branch.vercel.app',ICASH_APP_ORIGIN:'https://icash.example.com'};
for(const origin of ['https://unique.vercel.app','https://branch.vercel.app','https://icash.example.com'])assert.equal(allowedOrigin(new Request('https://unique.vercel.app',{headers:{origin}}),env),true);
for(const origin of ['https://evil.com','null','http://unique.vercel.app','https://unique.vercel.app.evil.com'])assert.equal(allowedOrigin(new Request('https://unique.vercel.app',{headers:{origin}}),env),false);
assert.equal(allowedOrigin(new Request('https://unique.vercel.app'),env),false);
console.log('Funding: mode isolation, paid-session checks, rollout gates, email normalization and origin checks passed.');
const taxedOrder={...order,price_cents:2200,credit_cents:2000,processing_fee_cents:200,tax_required:true};
const taxedSession={...session,amount_subtotal:2200,amount_total:2382,automatic_tax:{enabled:true,status:'complete'},total_details:{amount_tax:182,amount_discount:0,amount_shipping:0}};
assert.equal(fundingSessionMatches(taxedSession,taxedOrder),true);
for(const change of [{amount_total:2200},{amount_subtotal:2000},{automatic_tax:{enabled:true,status:'failed'}},{total_details:{amount_tax:182,amount_discount:100,amount_shipping:0}},{total_details:{amount_tax:-1}},{automatic_tax:{enabled:false,status:'complete'}}])assert.equal(fundingSessionMatches({...taxedSession,...change},taxedOrder),false);
assert.equal(fundingSessionMatches({...taxedSession,amount_total:2200,total_details:{amount_tax:0,amount_discount:0,amount_shipping:0}},taxedOrder),true);
console.log('Fee/tax subtotal reconciliation and incomplete-tax rejection passed.');
