import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {earlyAccessDailyDisclosure,earlyAccessTermsVersion} from '../lib/funding-consent.ts';
import {dailyConsent,dailyConsentVersion} from '../lib/daily-consent.ts';
const source=readFileSync(new URL('../components/funding-checkout.tsx',import.meta.url),'utf8');
assert.ok(!source.includes('Live-work checks unfinished'));
assert.match(source,/Outreach isn’t active yet; funding won’t start it\. Charges continue while unavailable; unused credits remain\./);
assert.match(source,/every 24 hours until you stop bot &amp; daily billing/);
assert.match(source,/No deal or start date is guaranteed/);
assert.match(source,/\[accepted,setAccepted\]=useState\(false\)/);
assert.ok(!source.includes('setEarlyAccessAccepted'),'one daily consent action only');
assert.match(source,/I authorize \$\{\(subtotal\/100\)\.toFixed\(2\)\}\/day and agree to the full terms below/);
assert.match(source,/including continued charges while outreach is unavailable/);
assert.match(source,/accepted:consentAccepted\|\|repeatChange,version:dailyConsentVersion,earlyAccessAccepted:earlyAccess&&consentAccepted/);
assert.match(source,/disabled=\{busy\|\|!selected\|\|!daily\?\.ready\|\|\(!consentAccepted&&!repeatChange\)\}/);
assert.match(source,/accepted&&acceptedScope===consentScope/,'stale consent invalidated synchronously');
assert.match(source,/useEffect\(\(\)=>\{setAccepted\(false\);\},\[consentScope\]\)/);
assert.match(source,/<details className="boost-terms"><summary>Full billing and availability terms<\/summary><p>\{dailyConsent\}<\/p>\{earlyAccess&&<p>\{earlyAccessDailyDisclosure\}<\/p>\}/,'exact audited text remains accessible without repeated expanded blocks');
assert.match(earlyAccessDailyDisclosure,/Daily charges renew every 24 hours even while live work is unavailable/);
assert.match(dailyConsent,/Unused credits remain on my account/);
assert.equal(earlyAccessTermsVersion,'2026-09-30.1');assert.equal(dailyConsentVersion,'daily-2026-09-29.3');
console.log('Single daily checkbox: concise material terms, exact accessible audited text, unchanged versions and synchronous stale-consent guard passed.');
