import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {reconcileReception} from '../lib/general-reception-reconcile.ts';
import {receptionTarget as target} from '../lib/general-reception.ts';
const now=Date.now(),nonce='a'.repeat(64),callSid='CA'+'b'.repeat(32),accountSid='AC'+'c'.repeat(32),from='+12145550199';
const env={TWILIO_ACCOUNT_SID:accountSid,TWILIO_AUTH_TOKEN:'t'.repeat(32),ELEVENLABS_API_KEY:'fixture-only'};
function fixture(change){
 const receipt={account_id:target.accountId,agent_id:target.agentId,call_sid:callSid,receipt_nonce:nonce,operation_key:'reception:'+callSid,customer_charge_cap_cents:65,max_duration_seconds:60,branch_id:'agtbrch_reception',reviewed_version_id:'agtvrsn_reception',reserved_at:new Date(now).toISOString(),caller_hash:createHmac('sha256',env.TWILIO_AUTH_TOKEN).update('reception-caller-v1\0'+from).digest('hex')};
 const list={has_more:false,conversations:[{conversation_id:'conv_reception'}]};
 const conversation={conversation_id:'conv_reception',agent_id:receipt.agent_id,branch_id:receipt.branch_id,version_id:receipt.reviewed_version_id,user_id:'icash-reception:'+nonce,status:'done',conversation_initiation_client_data:{user_id:'icash-reception:'+nonce,branch_id:receipt.branch_id,dynamic_variables:{icash_reception_lane:'general-v1',icash_reception_call_sid:callSid,icash_reception_receipt_nonce:nonce}},metadata:{call_duration_secs:30,phone_call:{call_sid:callSid}},transcript:[{role:'agent',message:'Unverified model statement'},{role:'user',message:'My house is on Main Street'}]};
 const carrier={sid:callSid,account_sid:accountSid,to:target.calledNumber,from,direction:'inbound',status:'completed',date_created:new Date(now-5000).toISOString()};
 const s={receipt,list,conversation,carrier,finish:true};change?.(s);const fetches=[],rpcCalls=[];
 const deps={now:()=>now,rpc:async(name,body)=>{rpcCalls.push({name,body});if(name==='icash_latest_general_reception_receipt')return s.receipt;if(name==='icash_finish_general_reception')return s.finish;throw Error('unexpected');},fetcher:async(url,options)=>{fetches.push({url,options});assert.equal(options.method,undefined);assert.equal(options.redirect,'error');if(url.includes('/conversations?')){const q=new URL(url).searchParams;assert.equal(q.get('agent_id'),target.agentId);assert.equal(q.get('user_id'),'icash-reception:'+nonce);return Response.json(s.list);}return Response.json(url.includes('api.twilio.com')?s.carrier:s.conversation);}};
 return {run:()=>reconcileReception(env,deps),fetches,rpcCalls};
}
const good=fixture(),result=await good.run();assert.equal(result.status,'completed');assert.equal(result.settled,false);assert.equal(result.providerMarginVerified,false);assert.equal(result.customerChargeCapCents,65);assert.equal(good.fetches.length,3);assert.deepEqual(good.rpcCalls[1].body.p_caller_statements,['My house is on Main Street']);
for(const sensitive of [nonce,callSid,accountSid,from,env.ELEVENLABS_API_KEY,env.TWILIO_AUTH_TOKEN,'Main Street'])assert(!JSON.stringify(result).includes(sensitive));
assert.equal((await fixture(s=>s.receipt=null).run()).status,'no_call');
for(const change of [s=>s.receipt.account_id='foreign',s=>s.receipt.customer_charge_cap_cents=66,s=>s.receipt.operation_key='different',s=>s.list.has_more=true,s=>s.list.conversations=[],s=>s.list.conversations.push({conversation_id:'conv_other'}),s=>s.conversation.version_id='agtvrsn_other',s=>s.conversation.branch_id='agtbrch_other',s=>s.conversation.user_id='caller-claimed',s=>s.conversation.conversation_initiation_client_data.dynamic_variables.icash_reception_receipt_nonce='b'.repeat(64),s=>s.conversation.metadata.phone_call.call_sid='CA'+'d'.repeat(32),s=>s.carrier.from='+19995550199',s=>s.carrier.to='+19995550199',s=>s.carrier.account_sid='AC'+'d'.repeat(32),s=>s.carrier.status='in-progress',s=>s.carrier.direction='outbound-api',s=>s.carrier.date_created=new Date(now-121000).toISOString(),s=>s.conversation.status='processing',s=>s.conversation.metadata.call_duration_secs=70]){const f=fixture(change);assert.equal((await f.run()).status,'held');assert(!f.rpcCalls.some(x=>x.name==='icash_finish_general_reception'));}
assert.equal((await fixture(s=>s.finish=false).run()).reason,'ledger_binding_conflict');
assert.equal((await reconcileReception({},{})).reason,'provider_configuration_missing');
console.log('Reception readback: authenticated fixed-origin provider GETs, unique lookup, exact nonce/CallSID/branch/version/carrier binding, no secret creation, uncertain holds and hard65c reservation passed');
