import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {reconcileReception,receptionUsdNumberMicros} from '../lib/general-reception-reconcile.ts';
import {receptionTarget as target,receptionProfiles} from '../lib/general-reception.ts';
const now=Date.now(),nonce='a'.repeat(64),callSid='CA'+'b'.repeat(32),accountSid='AC'+'c'.repeat(32),from='+12145550199';
const env={TWILIO_ACCOUNT_SID:accountSid,TWILIO_AUTH_TOKEN:'t'.repeat(32),ELEVENLABS_API_KEY:'fixture-only'};
function fixture(change){
 const receipt={account_id:target.accountId,agent_id:target.agentId,call_sid:callSid,receipt_nonce:nonce,operation_key:'reception:'+callSid,call_profile:'normal',rate_id:receptionProfiles.normal.rateId,customer_charge_cap_cents:430,max_duration_seconds:600,branch_id:'agtbrch_reception',reviewed_version_id:'agtvrsn_reception',reserved_at:new Date(now).toISOString(),caller_hash:createHmac('sha256',env.TWILIO_AUTH_TOKEN).update('reception-caller-v1\0'+from).digest('hex')};
 const list={has_more:false,conversations:[{conversation_id:'conv_reception'}]};
 const conversation={conversation_id:'conv_reception',agent_id:receipt.agent_id,branch_id:receipt.branch_id,version_id:receipt.reviewed_version_id,user_id:'icash-reception:'+nonce,status:'done',conversation_initiation_client_data:{user_id:'icash-reception:'+nonce,branch_id:receipt.branch_id,dynamic_variables:{icash_reception_lane:'general-v1',icash_reception_call_sid:callSid,icash_reception_receipt_nonce:nonce}},metadata:{call_duration_secs:30,phone_call:{call_sid:callSid}},transcript:[{role:'agent',message:'Unverified model statement'},{role:'user',message:'My house is on Main Street'}]};
 const carrier={sid:callSid,account_sid:accountSid,to:target.calledNumber,from,direction:'inbound',status:'completed',date_created:new Date(now-5000).toISOString()};
 const s={receipt,list,conversation,carrier,finish:true};change?.(s);const fetches=[],rpcCalls=[];
 const deps={now:()=>now,rpc:async(name,body)=>{rpcCalls.push({name,body});if(name==='icash_latest_general_reception_receipt')return s.receipt;if(name==='icash_finish_general_reception')return s.finish;throw Error('unexpected');},fetcher:async(url,options)=>{fetches.push({url,options});assert.equal(options.method,undefined);assert.equal(options.redirect,'error');if(url.includes('/conversations?')){const q=new URL(url).searchParams;assert.equal(q.get('agent_id'),target.agentId);assert.equal(q.get('user_id'),'icash-reception:'+nonce);return Response.json(s.list);}return Response.json(url.includes('api.twilio.com')?s.carrier:s.conversation);}};
 return {run:()=>reconcileReception(env,deps),fetches,rpcCalls,deps};
}
const good=fixture(),result=await good.run();assert.equal(result.status,'completed');assert.equal(result.settled,false);assert.equal(result.providerMarginVerified,false);assert.equal(result.customerChargeCapCents,430);assert.equal(good.fetches.length,3);assert.deepEqual(good.rpcCalls[1].body.p_caller_statements,['My house is on Main Street']);
for(const sensitive of [nonce,callSid,accountSid,from,env.ELEVENLABS_API_KEY,env.TWILIO_AUTH_TOKEN,'Main Street'])assert(!JSON.stringify(result).includes(sensitive));
assert.equal((await fixture(s=>s.receipt=null).run()).status,'no_call');
for(const change of [s=>s.receipt.account_id='foreign',s=>s.receipt.customer_charge_cap_cents=66,s=>s.receipt.operation_key='different',s=>s.list.has_more=true,s=>s.list.conversations=[],s=>s.list.conversations.push({conversation_id:'conv_other'}),s=>s.conversation.version_id='agtvrsn_other',s=>s.conversation.branch_id='agtbrch_other',s=>s.conversation.user_id='caller-claimed',s=>s.conversation.conversation_initiation_client_data.dynamic_variables.icash_reception_receipt_nonce='b'.repeat(64),s=>s.conversation.metadata.phone_call.call_sid='CA'+'d'.repeat(32),s=>s.carrier.from='+19995550199',s=>s.carrier.to='+19995550199',s=>s.carrier.account_sid='AC'+'d'.repeat(32),s=>s.carrier.status='in-progress',s=>s.carrier.direction='outbound-api',s=>s.carrier.date_created=new Date(now-121000).toISOString(),s=>s.conversation.status='processing',s=>s.conversation.metadata.call_duration_secs=610]){const f=fixture(change);assert.equal((await f.run()).status,'held');assert(!f.rpcCalls.some(x=>x.name==='icash_finish_general_reception'));}
assert.equal((await fixture(s=>s.finish=false).run()).reason,'ledger_binding_conflict');
assert.equal((await reconcileReception({},fixture().deps)).reason,'provider_configuration_missing');
console.log('Reception readback: authenticated fixed-origin provider GETs, unique lookup, exact nonce/CallSID/branch/version/carrier binding, no secret creation, uncertain holds and exact profile reservation passed');

const quick=fixture(s=>Object.assign(s.receipt,{call_profile:'owner_quick_test',rate_id:receptionProfiles.owner_quick_test.rateId,max_duration_seconds:60,customer_charge_cap_cents:65}));assert.equal((await quick.run()).customerChargeCapCents,65);assert.equal((await fixture(s=>{s.conversation.metadata.call_duration_secs=500;}).run()).status,'completed');

const priced=await fixture(s=>{s.carrier.price='-0.0085';s.carrier.price_unit='USD';s.conversation.metadata.cost_fiat=0.029;}).run();assert.equal(priced.costEvidence.twilioUsdMicros,8500);assert.equal(priced.costEvidence.elevenLabsUsdMicros,29000);assert.equal(priced.costEvidence.providerSubtotalUsdMicros,37500);assert.equal(priced.costEvidence.allInCostVerified,false);assert.equal(priced.settled,false);
for(const price of ['0.0085','-0.0000001','-1e-3',null]){const p=await fixture(s=>{s.carrier.price=price;s.carrier.price_unit='USD';s.conversation.metadata.cost=123;}).run();assert.equal(p.costEvidence.twilioUsdMicros,null);assert.equal(p.costEvidence.elevenLabsUsdMicros,null);}
assert.equal((await fixture(s=>{s.carrier.price='0';s.carrier.price_unit='USD';s.conversation.metadata.cost_fiat=0;}).run()).costEvidence.providerSubtotalUsdMicros,0);
const shapes=await fixture(s=>{s.carrier.price='-0.0085000';s.carrier.price_unit='usd';s.conversation.metadata.cost_fiat='private-not-a-price';s.conversation.metadata.cost=123;s.conversation.cost_fiat={private:'never expose'};}).run();
assert.equal(shapes.costEvidence.costShape.twilioUnit,'usd');assert.equal(shapes.costEvidence.costShape.twilioPriceFractionDigits,7);assert.equal(shapes.costEvidence.costShape.elevenCostFiatType,'string');assert.equal(shapes.costEvidence.costShape.elevenRootCostFiatType,'object');assert.equal(shapes.costEvidence.twilioUsdMicros,null);assert.equal(shapes.costEvidence.elevenLabsUsdMicros,null);assert(!JSON.stringify(shapes).includes('private-not-a-price'));assert(!JSON.stringify(shapes).includes('never expose'));
assert.equal(result.costEvidence.costShape.elevenCostFiatType,'missing');
const empty=await fixture(s=>{s.carrier.price=null;s.carrier.price_unit='secret-unexpected-unit';s.conversation.metadata.cost_fiat=1e-7;}).run();assert.equal(empty.costEvidence.costShape.twilioPriceType,'null');assert.equal(empty.costEvidence.costShape.twilioUnit,'other');assert.equal(empty.costEvidence.costShape.elevenCostFiatNotation,'exponent');assert(!JSON.stringify(empty).includes('secret-unexpected-unit'));assert.equal(empty.costEvidence.elevenLabsUsdMicros,0);

for(const [value,expected] of [[0.029000000000000005,29000],[0.00000049,0],[0.0000005,1],[0.0000015,2],[1e-7,0],[1e-6,1],[1e3,1000000000],[0,0],[Number.MIN_VALUE,0],[Number.MAX_VALUE,null],[-1,null],[NaN,null],[Infinity,null],[null,null],['0.029',null],[{},null],[9007199254.741,null]])assert.equal(receptionUsdNumberMicros(value),expected,String(value));
const precise=await fixture(s=>{s.carrier.price=null;s.carrier.price_unit='USD';s.conversation.metadata.cost_fiat=0.029000000000000005;}).run();assert.equal(precise.costEvidence.elevenLabsUsdMicros,29000);assert.equal(precise.costEvidence.twilioUsdMicros,null);assert.equal(precise.costEvidence.providerSubtotalUsdMicros,null);assert.equal(precise.settled,false);assert.equal(precise.costEvidence.elevenLabsUsdRounding,'decimal_half_up_to_micros');
