import assert from 'node:assert/strict';
import {inboundAuthorized,inboundCallSchema,inboundCapability,inboundInitiation} from '../lib/inbound-voice.ts';
const secret='fixture-secret-'.repeat(4);
const call={caller_id:'+12125550123',called_number:'+17816093521',agent_id:'agent_fixture',call_sid:'CA'+'1'.repeat(32),conversation_id:'conv_fixture'};
assert(inboundAuthorized('Bearer '+secret,secret));
for(const h of [null,'Bearer wrong',secret,'Basic '+secret,'Bearer '+secret+'x'])assert(!inboundAuthorized(h,secret));
assert(!inboundAuthorized('Bearer x','x'));
assert(!inboundAuthorized('Bearer '+secret,undefined));
inboundCallSchema.parse(call);
for(const changed of [{caller_id:'anonymous'},{call_sid:'wrong'},{account_id:'tenant'},{called_number:'+1&select=*'}])assert.throws(()=>inboundCallSchema.parse({...call,...changed}));
const a=inboundCapability(call,secret);
assert.deepEqual(inboundCapability(call,secret),a,'retry must keep the same per-call capability');
for(const changed of [{caller_id:'+12125550124'},{called_number:'+17816093522'},{agent_id:'agent_other'},{conversation_id:'conv_other'},{call_sid:'CA'+'2'.repeat(32)}])assert.notEqual(inboundCapability({...call,...changed},secret).token,a.token);
const result=inboundInitiation(600,a.token);
assert.equal(result.conversation_config_override.conversation.max_duration_seconds,600);
assert.equal(result.dynamic_variables.approved_offer_ceiling,'NOT AUTHORIZED');
assert(!JSON.stringify(result).includes(call.caller_id));
assert.throws(()=>inboundInitiation(901,a.token));
console.log('Inbound authentication, validation, replay binding, call limits and private-data exclusion passed.');
// Exercise the actual HTTP route with provider/database fakes; never uses network.
const {readFileSync}=await import('node:fs');
const {createHash}=await import('node:crypto');
const {default:ts}=await import('typescript');
let databaseCalls=0,providerCalls=0,registered=true,match=true,lastBody;
const db=async(path,method,body)=>{databaseCalls++;if(path.startsWith('icash_inbound_voice_routes'))return registered?[{agent_id:call.agent_id}]:[];lastBody=body;return match?{maxSeconds:600}:null;};
const elevenRequest=async()=>{providerCalls++;return {conversation_config:{conversation:{max_duration_seconds:600}}};};
globalThis.__inboundFixture={NextResponse:{json:Response.json},createHash,db,elevenRequest,inboundAuthorized,inboundCallSchema,inboundCapability,inboundInitiation};
let source=ts.transpileModule(readFileSync(new URL('../app/api/internal/voice/inbound/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
source='const {NextResponse,createHash,db,elevenRequest,inboundAuthorized,inboundCallSchema,inboundCapability,inboundInitiation}=globalThis.__inboundFixture;\n'+source;
const {POST}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
process.env.ELEVENLABS_INBOUND_WEBHOOK_SECRET=secret;
const req=(body=call,auth='Bearer '+secret)=>new Request('https://example.invalid/api/internal/voice/inbound',{method:'POST',headers:{authorization:auth,'content-type':'application/json'},body:JSON.stringify(body)});
assert.equal((await POST(req(call,'Bearer wrong'))).status,401);assert.equal(databaseCalls,0);assert.equal(providerCalls,0);
registered=false;assert.equal((await POST(req())).status,409);assert.equal(providerCalls,0);
registered=true;match=false;assert.equal((await POST(req())).status,409);
match=true;const response=await POST(req());assert.equal(response.status,200);assert.match(response.headers.get('cache-control'),/no-store/);
const payload=await response.json();assert.equal(payload.dynamic_variables.secret__icash_call_token,a.token);assert.equal(lastBody.p_token_hash,a.hash);assert(!JSON.stringify(lastBody).includes(a.token),'raw tool token never stored');
assert.equal((await POST(req({...call,account_id:'another-tenant'}))).status,409);
delete globalThis.__inboundFixture;delete process.env.ELEVENLABS_INBOUND_WEBHOOK_SECRET;
console.log('Actual inbound HTTP handler: unauthorized, unregistered, unmatched and valid cases passed without provider traffic.');
