import assert from 'node:assert/strict';
import {createHash,randomBytes} from 'node:crypto';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {callEligibility,verifiedOfferCeiling} from '../lib/live-dispatch-policy.ts';
import {evaluateLaunch} from '../lib/launch-readiness-policy.ts';
import {productionDealInstructions,acquisitionOpeners} from '../lib/deal-conversation.ts';
const now=Date.parse('2026-09-29T16:00:00Z');
const realNow=Date.now;Date.now=()=>now;
const snapshot={propertyId:'prop_123',propertyType:'house',fetchedAt:new Date(now).toISOString(),sellerCostReserveCents:100000,raw:{data:{dm_property_id:'prop_123',full_address:'Fixture only',estimated_value:200000,estimated_repair_cost:40000,total_estimated_loan_balance:50000}}};
let permission={id:'permission',account_id:'account',screening_id:'screening',party:'seller',phone:'+12125550123',contact_key:createHash('sha256').update('+12125550123').digest('hex'),timezone:'America/Chicago',local_start_hour:9,local_end_hour:20,permission_until:new Date(now+86400000).toISOString(),dnc_checked_at:new Date(now-1000).toISOString(),dnc_clear:true,revoked_at:null};
assert.equal(callEligibility(permission,snapshot,now).ready,true);
assert.equal(callEligibility({...permission,revoked_at:new Date(now).toISOString()},snapshot,now).ready,false);
assert.equal(callEligibility({...permission,dnc_checked_at:new Date(now+1000).toISOString()},snapshot,now).ready,false);
assert.equal(callEligibility({...permission,timezone:'bogus'},snapshot,now).ready,false);
assert.equal(callEligibility({...permission,timezone:'Pacific/Honolulu'},snapshot,now).reason,'outside_contact_hours');
assert.equal(callEligibility(permission,{...snapshot,fetchedAt:new Date(now-86400001).toISOString()},now).reason,'fresh_screening_required');
assert.equal(verifiedOfferCeiling(9000000,{max_offer_cents:8000000,expires_at:new Date(now+1000).toISOString()},now),8000000);
assert.equal(verifiedOfferCeiling(9000000,undefined,now),null);
assert.equal(verifiedOfferCeiling(9000000,{max_offer_cents:8000000,expires_at:new Date(now-1).toISOString()},now),null);
const config={conversation:{max_duration_seconds:600},agent:{prompt:{tool_ids:['callback','handoff']}}};
const c={enabled:true,agent_id:'agent_fixture',phone_number_id:'number',agent_config_hash:createHash('sha256').update(JSON.stringify(config)).digest('hex'),reviewed_until:new Date(now+100000).toISOString(),seller_rate_id:'rate',max_duration_seconds:600,required_tool_ids:['callback','handoff']};
let records=[],postCount=0,allowClaim=true,paused=false,timeout=false,jobState='issued',practice=false,quoteSeconds=600;
const db=async(path,method,body)=>{
 records.push({path,method,body});
 if(method==='PATCH'){if(body.state==='held'&&path.includes(`state=eq.${jobState}`))jobState='held';return [];}
 if(path.startsWith('icash_voice_jobs'))return [{id:'job',account_id:'account',permission_id:'permission',callback_id:null,state:jobState}];
 if(path.startsWith('icash_voice_configs'))return [c];
 if(path.startsWith('icash_contact_permissions'))return [permission];
 if(path.startsWith('icash_screening_jobs'))return [{snapshot}];
 if(path.startsWith('icash_customer_identities'))return [{principal:'Fixture Buyer',voice_id:'voice'}];
 if(path.startsWith('icash_accounts'))return [{assistant_name:'Alex',bot_paused:paused}];
 if(path.startsWith('icash_voice_test_config'))return practice?[{agent_id:c.agent_id}]:[];
 if(path.startsWith('icash_operation_rates'))return [{operation:'seller_call',enabled:true,expires_at:c.reviewed_until,voice_max_duration_seconds:quoteSeconds}];
 if(path.startsWith('icash_offer_authorities'))return [];
 if(path==='rpc/icash_claim_voice_job'){if(allowClaim)jobState='dispatching';return allowClaim;}
 if(path==='icash_live_conversations')return [];
 throw Error('Unexpected request '+path);
};
const elevenRequest=async(path,body)=>{if(!body)return {conversation_config:config};postCount++;if(timeout)throw Error('timeout');return {success:true,conversation_id:'conv_fixture',callSid:'CA'+'1'.repeat(32)};};
globalThis.__voiceTest={createHash,randomBytes,db,elevenRequest,reserveOperation:async()=>records.push({reserve:true}),callEligibility,verifiedOfferCeiling,productionDealInstructions,acquisitionOpeners};
let source=ts.transpileModule(readFileSync(new URL('../lib/live-dispatch-service.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
source='const {createHash,randomBytes,db,elevenRequest,reserveOperation,callEligibility,verifiedOfferCeiling,productionDealInstructions,acquisitionOpeners}=globalThis.__voiceTest;\n'+source;
const {dispatchLiveVoice}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
process.env.ELEVENLABS_API_KEY='fixture-no-network';
const reset=()=>{records=[];postCount=0;allowClaim=true;paused=false;timeout=false;jobState='issued';practice=false;quoteSeconds=600;};
assert.equal((await dispatchLiveVoice('account','job')).status,'call_started');assert.equal(postCount,1);
const saved=records.find(r=>r.path==='icash_live_conversations');assert.match(saved.body.tool_token_hash,/^[a-f0-9]{64}$/);assert(!JSON.stringify(saved).includes('secret__'));
reset();paused=true;await dispatchLiveVoice('account','job');assert.equal(postCount,0);assert(!records.some(r=>r.reserve));
reset();practice=true;assert.equal((await dispatchLiveVoice('account','job')).status,'practice_agent_blocked');assert.equal(postCount,0);
reset();quoteSeconds=60;assert.equal((await dispatchLiveVoice('account','job')).status,'full_call_cost_quote_required');assert.equal(postCount,0);
reset();allowClaim=false;await dispatchLiveVoice('account','job');assert.equal(postCount,0);
reset();timeout=true;assert.equal((await dispatchLiveVoice('account','job')).status,'provider_outcome_unknown_no_retry');assert.equal(jobState,'held');await dispatchLiveVoice('account','job');assert.equal(postCount,1,'uncertain dial must never retry');
const readiness=evaluateLaunch({cashReserve:true,discovery:true,voice:true,contactPermission:true,productionContracts:true,unresolvedDispatches:false},{data:true,voice:true,email:true,billing:true});assert.equal(readiness.acquisitionReady,true);assert.equal(readiness.ready,false);assert(readiness.blockers.includes('allProviderCostSettlement'));
assert(evaluateLaunch({cashReserve:true,discovery:true,voice:true,contactPermission:true,productionContracts:true,unresolvedDispatches:false},{data:true,voice:false,email:true,billing:true}).blockers.includes('voiceProvider'));
delete globalThis.__voiceTest;delete process.env.ELEVENLABS_API_KEY;Date.now=realNow;
console.log('Voice dispatch: permissions, hours, fresh underwriting, reviewed offer ceilings, full-duration costs, Stop, practice-agent isolation, uncertain-call no-retry and honest launch readiness passed. No provider traffic.');
