import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import ts from 'typescript';import * as policy from '../lib/membership-policy.ts';
const require=createRequire(import.meta.url);const code=ts.transpileModule(readFileSync(new URL('../components/membership-settings.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const all=root=>!root||typeof root!=='object'?[]:Array.isArray(root)?root.flatMap(all):[root,...all(root.props?.children)];const text=root=>typeof root==='string'?root:Array.isArray(root)?root.map(text).join(' '):root&&typeof root==='object'?text(root.props?.children):'';
let slots=[],cursor=0,dirty=true,pending=[],tree,calls=[],changed=[];
let data={state:'active',priceCents:5000,paidThrough:new Date(Date.now()+30*86400000).toISOString(),cancelAtPeriodEnd:false,accessible:true};let offer={eligible:true,retryable:false,priceCents:2500,months:6,version:'retention-50-six-months-v1'},partial=false,fail=false;
globalThis.window={location:{assign(url){calls.push({redirect:url});}}};
globalThis.fetch=async(url,options={})=>{calls.push({url,options});if(options.method==='POST'){const {action}=JSON.parse(options.body);if(fail)return Response.json({error:'Could not confirm. You can cancel instead.'},{status:409});if(action==='retain'){offer={...offer,eligible:false};data={...data,retentionEndsAt:new Date(Date.now()+183*86400000).toISOString()};return Response.json({saved:true,message:'Offer applied.'});}if(action==='cancel'){data={...data,state:partial?'cancel_requested':'cancelled',accessible:false};return Response.json({saved:!partial,stopped:true,message:partial?'Cancellation is retrying automatically.':'Cancelled.'},{status:partial?202:200});}}return Response.json({membership:data,retentionOffer:offer});};
const hooks={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],next=>{const value=typeof next==='function'?next(slots[i]):next;if(!Object.is(value,slots[i])){slots[i]=value;dirty=true;}}];},useRef(initial){const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect(fn,deps){const i=cursor++,previous=slots[i];if(!previous||deps.some((v,n)=>!Object.is(v,previous.deps[n]))){slots[i]={deps};pending.push(fn);}}};
const mod={exports:{}};new Function('require','module','exports',code)(n=>n==='react'?hooks:n==='@/lib/membership-policy'?policy:n==='@/components/funding-dialog'?{FundingDialog:'FundingDialog'}:require(n),mod,mod.exports);
function render(){cursor=0;dirty=false;tree=mod.exports.MembershipSettings({onChanged(stopped){changed.push(stopped);}});}
async function flush(){for(let i=0;i<20;i++){if(dirty)render();const tasks=pending;pending=[];tasks.forEach(fn=>fn());await new Promise(r=>setTimeout(r,1));if(!dirty&&!pending.length)return;}throw Error('Did not settle');}
const button=label=>{const n=all(tree).filter(n=>n.type==='button'&&text(n)===label).at(-1);assert(n,'Missing '+label);return n;};const posts=()=>calls.filter(c=>c.options?.method==='POST').map(c=>JSON.parse(c.options.body));
await flush();assert.equal(posts().length,0);button('Cancel subscription').props.onClick();await flush();assert.equal(posts().length,0,'Opening an offer does not cancel or apply it');assert.match(text(tree),/month for 6 months/);assert.match(text(tree),/Then\s+\$50/);assert.match(text(tree),/No charge today/);button('Keep my subscription').props.onClick();button('Keep my subscription').props.onClick();await flush();assert.deepEqual(posts().map(p=>p.action),['retain']);assert.equal(posts()[0].accepted,true);assert.equal(posts()[0].priceCents,2500);assert.deepEqual(changed,[false]);
button('Cancel subscription').props.onClick();await flush();button('Cancel subscription').props.onClick();await flush();assert.deepEqual(posts().map(p=>p.action),['retain','cancel']);assert.deepEqual(changed,[false,true]);assert.match(text(tree),/Renew subscription/);
slots=[];dirty=true;calls=[];changed=[];data={...data,state:'active',accessible:true};offer={...offer,eligible:true};partial=true;await flush();button('Cancel subscription').props.onClick();await flush();button('No thanks, cancel').props.onClick();await flush();assert.deepEqual(posts().map(p=>p.action),['cancel']);assert.deepEqual(changed,[true]);assert.match(text(tree),/finishing automatically/);
slots=[];dirty=true;calls=[];data={...data,state:'active',accessible:true};partial=false;fail=true;await flush();button('Cancel subscription').props.onClick();await flush();button('Keep my subscription').props.onClick();await flush();assert(button('No thanks, cancel'),'Failed offer never hides cancellation');
console.log('PASS Settings: explicit retention choice, visible decline, no automatic mutation, duplicate-click protection, six-month/reversion price, immediate lock callback and failure recovery.');
