import {webinarViewerLocation} from '../lib/webinar-viewer-location.ts';
import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {z} from 'zod';import * as policy from '../lib/membership-policy.ts';import * as embeddedPolicy from '../lib/embedded-checkout-policy.ts';
async function load(file,deps,key){globalThis[key]=deps;const code=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .*;\s*$/gm,'');return import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.'+key+';\n'+code).toString('base64'));}
let user=null,offer={priceCents:5000,revision:1,interval:'month',enabled:true},prior=null,calls=[],origin=true,cancelPending=false;
const id='00000000-0000-4000-8000-000000000011';const guest='a'.repeat(64);const NextResponse={json:(body,o={})=>({body,status:o.status??200,headers:o.headers})};
const stripe={checkout:{sessions:{create:async(body,options)=>{calls.push({create:body,options});return {id:'cs_live_new',url:'https://checkout.stripe.com/fake',livemode:true};},retrieve:async()=>({id:prior.stripe_session_id,metadata:{icash_membership:id},status:'open',livemode:true,url:'https://checkout.stripe.com/existing'})}},billingPortal:{configurations:{create:async()=>({id:'bpc_fake'})},sessions:{create:async()=>({url:'https://billing.stripe.com/fake'})}}};
const deps={webinarViewerLocation,checkoutVipSession:async()=>null,paidVipDestination:async()=>null,...policy,...embeddedPolicy,checkoutCustomerContext:async(_guest,email)=>email?{email}:{},NextResponse,z,randomBytes:()=>{throw Error('Unexpected token regeneration');},cookies:async()=>({get:()=>({value:guest})}),currentUser:async()=>user,guestHash:()=>guest,validGuest:()=>true,allowedOrigin:()=>origin,fundingMode:()=> 'live',fundingStripe:()=>stripe,limitRequest:async()=>{},customerFundingReady:async()=>true,membershipOffer:async()=>offer,publicMembership:m=>m,membershipRetentionOffer:async()=>null,retainMembership:async m=>calls.push({retain:m}),retentionVersion:'retention-50-six-months-v1',accountMembership:async()=>prior,reconcileMembershipCheckout:async m=>m,stopMembership:async m=>{calls.push({stop:m});if(cancelPending)throw Error('MEMBERSHIP_CANCELLATION_PENDING');},db:async(path,method,body)=>{calls.push({path,method,body});if(path.startsWith('icash_accounts'))return user?[{id:'account'}]:[];if(path==='rpc/icash_begin_membership')return {id,price_cents:body.p_price,offer_revision:body.p_revision};if(path.startsWith('icash_memberships'))return prior?[prior]:[];throw Error('Unexpected DB '+path);}};
const route=await load('app/api/billing/membership/route.ts',deps,'__membershipRoute');const req=body=>new Request('https://example.invalid/api/billing/membership',{method:'POST',headers:{origin:'https://example.invalid'},body:JSON.stringify(body)});const purchase={action:'checkout',accepted:true,version:policy.membershipTermsVersion,revision:1,totalCents:5000};
let r=await route.GET(new Request('https://example.invalid/api/billing/membership'));assert.equal(r.status,200);assert.equal(r.body.offer.priceCents,5000);assert.equal(calls.some(c=>c.create),false);
origin=false;r=await route.POST(req(purchase));assert.equal(r.status,403);origin=true;
r=await route.POST(req({...purchase,accepted:false}));assert.equal(r.status,400);r=await route.POST(req({...purchase,accountId:'other'}));assert.equal(r.status,400);
for(const change of [{totalCents:4900},{revision:2}]){r=await route.POST(req({...purchase,...change}));assert.equal(r.status,409);}assert.equal(calls.some(c=>c.create),false);
r=await route.POST(req(purchase));assert.equal(r.status,200);const created=calls.find(c=>c.create);assert.equal(created.create.mode,'subscription');assert.equal(created.create.line_items[0].price_data.unit_amount,5000);assert.equal(created.create.line_items[0].price_data.recurring.interval,'month');assert.equal(created.create.customer_email,undefined,'Guest supplies email only at secure payment');assert.match(created.create.custom_text.submit.message,/\$0 in work credits/);assert.equal(created.options.idempotencyKey,'membership-checkout:'+id);
prior={id,consent_version:policy.membershipTermsVersion,account_id:null,mode:'live',state:'pending',price_cents:5000,offer_revision:1,stripe_session_id:'cs_live_existing'};calls=[];r=await route.POST(req(purchase));assert.equal(r.body.url,'https://checkout.stripe.com/existing');assert.equal(calls.some(c=>c.create),false,'Identical pending purchase reuses payment');
prior.state='active';r=await route.POST(req(purchase));assert.equal(r.status,409);assert.equal(calls.some(c=>c.create),false);r=await route.POST(req({action:'cancel'}));assert.equal(r.status,401);assert.equal(calls.some(c=>c.stop),false);
user={id:'user',email:'fixture@example.invalid'};prior.account_id='account';r=await route.POST(req({action:'cancel'}));assert.equal(r.status,200);assert.equal(calls.filter(c=>c.stop).length,1);
let patches=0;const ownerDeps={...deps,ownerInboundTarget:{ownerUserId:'owner'},db:async(path,method,body)=>{assert(path.startsWith('icash_membership_offer?'));if(!path.includes('revision=eq.'+offer.revision))return [];patches++;offer={...offer,priceCents:body.price_cents,revision:body.revision,enabled:body.enabled};return [{}];}};const owner=await load('app/api/billing/offer/route.ts',ownerDeps,'__offerRoute');
r=await owner.GET();assert.equal(r.status,403);r=await owner.POST(req({priceCents:9700,revision:1,enabled:true}));assert.equal(r.status,400);assert.equal(patches,0);user={id:'owner'};r=await owner.POST(req({priceCents:9700,revision:1,enabled:true}));assert.equal(r.status,200);assert.equal(offer.priceCents,9700);assert.equal(offer.revision,2);r=await owner.POST(req({priceCents:5000,revision:1,enabled:true}));assert.equal(r.status,409);assert.equal(patches,1,'Stale owner edit cannot overwrite another edit');
console.log('PASS membership routes: public price, no early data form, strict amount/version/consent, one pending checkout, auth-scoped cancellation, owner-only offer edits, stale edit conflict. No live providers.');

user={id:'user',email:'fixture@example.invalid'};calls=[];
const retention={action:'retain',accepted:true,version:'retention-50-six-months-v1',priceCents:2500,months:6};
r=await route.POST(req({...retention,accepted:false}));assert.equal(r.status,400);
r=await route.POST(req({...retention,priceCents:100}));assert.equal(r.status,409);
r=await route.POST(req({...retention,accountId:'other'}));assert.equal(r.status,400);assert(!calls.some(c=>c.retain));
r=await route.POST(req(retention));assert.equal(r.status,200);assert.equal(calls.filter(c=>c.retain).length,1);
cancelPending=true;r=await route.POST(req({action:'cancel'}));assert.equal(r.status,202);assert.equal(r.body.saved,false);assert.equal(r.body.stopped,true);assert.match(r.body.message,/retrying automatically/);
console.log('PASS retention routes: explicit acceptance, exact price/version, authenticated account only, and truthful durable-cancellation pending result.');
