import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import * as policy from '../lib/membership-policy.ts';
// Real service code, fake database/Stripe only. No network or charges.
const id='00000000-0000-4000-8000-000000000001';let member,sub,invoice,line,pi,session,calls;
function reset(){calls=[];member={id,mode:'live',state:'pending',price_cents:5000,offer_revision:1,stripe_session_id:'cs_live_one',stripe_subscription_id:null,stripe_customer_id:null,paid_through:null};sub={id:'sub_one',metadata:{icash_membership:id},status:'active',livemode:true,customer:'cus_one',latest_invoice:'in_one',cancel_at_period_end:false,items:{has_more:false,data:[{quantity:1,current_period_end:1794000000,price:{id:'price_one',currency:'usd',unit_amount:5000,recurring:{interval:'month',interval_count:1}}}]}};invoice={id:'in_one',parent:{subscription_details:{subscription:'sub_one'}},livemode:true,status:'paid',currency:'usd',amount_remaining:0,amount_paid:5000,total:5000,subtotal:5000,customer:'cus_one',customer_email:'fixture@example.invalid'};line={quantity:1,amount:5000,pricing:{price_details:{price:'price_one'}},period:{start:1790000000,end:1792592000}};pi={id:'pi_one',status:'succeeded',amount_received:5000,currency:'usd',livemode:true,customer:'cus_one'};session={id:'cs_live_one',currency:'usd',amount_total:5000,mode:'subscription',metadata:{icash_membership:id},livemode:true,status:'complete',payment_status:'paid',subscription:'sub_one',customer:'cus_one'};}
const stripe={invoices:{retrieve:async()=>invoice,listLineItems:async()=>({has_more:false,data:[line]})},subscriptions:{retrieve:async()=>sub,update:async(id,body,opts)=>{calls.push({update:id,body,opts});return {...sub,...body};}},invoicePayments:{list:async()=>({has_more:false,data:[{payment:{payment_intent:'pi_one'}}]})},paymentIntents:{retrieve:async()=>pi},checkout:{sessions:{retrieve:async()=>session,expire:async id=>calls.push({expire:id})}}};
const db=async(path,method,body)=>{calls.push({path,method,body});if(path==='rpc/icash_settle_membership_invoice'){member.paid_through=body.p_period_end;return null;}if(path.startsWith('icash_memberships')){if(method==='PATCH'){if(!path.includes('state=neq.needs_review')||member.state!=='needs_review')Object.assign(member,body);return [member];}return [{...member}];}throw Error('Unexpected database path '+path);};
const mocks={...policy,db,fundingStripe:()=>stripe,fundingMode:()=> 'live'};globalThis.__member=mocks;let code=ts.transpileModule(readFileSync(new URL('../lib/membership.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .*;\s*$/gm,'');const service=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(mocks).join(',')+'}=globalThis.__member;\n'+code).toString('base64'));
reset();assert.equal(await service.settleMembershipInvoice('in_one'),true);assert(calls.some(c=>c.path==='rpc/icash_settle_membership_invoice'));assert(!calls.some(c=>/wallet|post_credit|settle_funding/.test(c.path??'')),'Software never posts work credits');assert.equal(member.state,'active');
for(const mutate of [()=>sub.livemode=false,()=>sub.items.data[0].price.unit_amount=4900,()=>sub.items.data[0].price.recurring.interval='day',()=>sub.items.has_more=true,()=>sub.items.data[0].quantity=2,()=>member.stripe_subscription_id='sub_other',()=>member.stripe_customer_id='cus_other',()=>invoice.total=5001,()=>invoice.amount_paid=4000,()=>invoice.currency='eur',()=>invoice.status='open',()=>invoice.customer='cus_other',()=>line.amount=4000,()=>line.quantity=2,()=>line.pricing.price_details.price='price_other',()=>line.period.end=line.period.start,()=>pi.status='processing',()=>pi.livemode=false,()=>pi.amount_received=4999,()=>pi.customer='cus_other']){reset();mutate();await assert.rejects(service.settleMembershipInvoice('in_one'));assert(!calls.some(c=>c.path==='rpc/icash_settle_membership_invoice'));}
reset();sub.metadata={};assert.equal(await service.settleMembershipInvoice('in_one'),false,'Legacy invoice delegates to legacy handler');
reset();member.state='needs_review';await service.syncMembershipSubscription(sub);assert.equal(member.state,'needs_review','Refund/dispute holds survive late active events');
reset();const originalDb=db;await service.reconcileMembershipCheckout({...member});assert.equal(member.state,'active');
reset();sub.metadata.icash_membership='00000000-0000-4000-8000-000000000002';await assert.rejects(service.reconcileMembershipCheckout({...member}));assert(!calls.some(c=>c.method==='PATCH'));
reset();session.customer='cus_other';await assert.rejects(service.reconcileMembershipCheckout({...member}));
reset();member.stripe_session_id='cs_live_other';await assert.rejects(service.reconcileMembershipSession('cs_live_one'));
reset();member.stripe_subscription_id='sub_one';await service.stopMembership({...member});assert.equal(member.cancel_at_period_end,true);assert(calls.some(c=>c.update==='sub_one'&&c.body.cancel_at_period_end===true&&c.opts.idempotencyKey));
reset();member.stripe_subscription_id='sub_one';sub.metadata.icash_membership='00000000-0000-4000-8000-000000000002';await assert.rejects(service.stopMembership({...member}));assert(!calls.some(c=>c.update));
reset();session.status='open';await service.stopMembership({...member});assert(calls.some(c=>c.expire==='cs_live_one'));assert.equal(member.state,'cancelled');
assert.equal(policy.membershipAccessible({state:'active',paid_through:new Date(Date.now()+60000).toISOString()}),true);assert.equal(policy.membershipAccessible({state:'active',paid_through:null}),false);assert.equal(policy.membershipAccessible({state:'active',paid_through:new Date(Date.now()-1).toISOString()}),false);
console.log('PASS software billing: canonical paid USD amount/price/customer/mode/period, no credit grants, checkout ownership binding, review hold, and cancel-at-period-end. Fake Stripe only.');
