import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import * as policy from '../lib/membership-policy.ts';
// Real service code, fake database/Stripe only. No network or charges.
const id='00000000-0000-4000-8000-000000000001';let member,sub,invoice,line,pi,session,calls;
function reset(){calls=[];member={id,mode:'live',state:'pending',price_cents:5000,offer_revision:1,account_id:'account',stripe_session_id:'cs_live_one',stripe_subscription_id:null,stripe_customer_id:null,paid_through:null};sub={id:'sub_one',metadata:{icash_membership:id},status:'active',livemode:true,customer:'cus_one',latest_invoice:'in_one',cancel_at_period_end:false,items:{has_more:false,data:[{quantity:1,current_period_end:1794000000,price:{id:'price_one',currency:'usd',unit_amount:5000,recurring:{interval:'month',interval_count:1}}}]}};invoice={id:'in_one',parent:{subscription_details:{subscription:'sub_one'}},livemode:true,status:'paid',currency:'usd',amount_remaining:0,amount_paid:5000,total:5000,subtotal:5000,customer:'cus_one',customer_email:'fixture@example.invalid'};line={quantity:1,amount:5000,pricing:{price_details:{price:'price_one'}},period:{start:1790000000,end:1792592000}};pi={id:'pi_one',status:'succeeded',amount_received:5000,currency:'usd',livemode:true,customer:'cus_one'};session={id:'cs_live_one',currency:'usd',amount_total:5000,mode:'subscription',metadata:{icash_membership:id},livemode:true,status:'complete',payment_status:'paid',subscription:'sub_one',customer:'cus_one'};}
const stripe={invoices:{retrieve:async()=>invoice,listLineItems:async()=>({has_more:false,data:[line]})},subscriptions:{retrieve:async()=>sub,cancel:async(id,body)=>{calls.push({cancel:id,body});sub={...sub,status:'canceled'};return sub;},update:async(id,body,opts)=>{calls.push({update:id,body,opts});return {...sub,...body};}},invoicePayments:{list:async()=>({has_more:false,data:[{payment:{payment_intent:'pi_one'}}]})},paymentIntents:{retrieve:async()=>pi},checkout:{sessions:{retrieve:async()=>session,expire:async id=>calls.push({expire:id})}}};
const db=async(path,method,body)=>{calls.push({path,method,body});if(path==='rpc/icash_request_membership_cancellation'){if(member.state!=='cancelled')member.state='cancel_requested';return {...member};}if(path==='rpc/icash_settle_membership_invoice_v2'){member.paid_through=body.p_period_end;return null;}if(path.startsWith('icash_memberships')){if(method==='PATCH'){if(!path.includes('state=neq.needs_review')||member.state!=='needs_review')Object.assign(member,body);return [member];}return [{...member}];}throw Error('Unexpected database path '+path);};
const mocks={...policy,db,fundingStripe:()=>stripe,fundingMode:()=> 'live'};globalThis.__member=mocks;let code=ts.transpileModule(readFileSync(new URL('../lib/membership.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .*;\s*$/gm,'');const service=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(mocks).join(',')+'}=globalThis.__member;\n'+code).toString('base64'));
reset();assert.equal(await service.settleMembershipInvoice('in_one'),true);assert(calls.some(c=>c.path==='rpc/icash_settle_membership_invoice_v2'));assert(!calls.some(c=>/wallet|post_credit|settle_funding/.test(c.path??'')),'Software never posts work credits');assert.equal(member.state,'active');
for(const mutate of [()=>sub.livemode=false,()=>sub.items.data[0].price.unit_amount=4900,()=>sub.items.data[0].price.recurring.interval='day',()=>sub.items.has_more=true,()=>sub.items.data[0].quantity=2,()=>member.stripe_subscription_id='sub_other',()=>member.stripe_customer_id='cus_other',()=>invoice.total=5001,()=>invoice.amount_paid=4000,()=>invoice.currency='eur',()=>invoice.status='open',()=>invoice.customer='cus_other',()=>line.amount=4000,()=>line.quantity=2,()=>line.pricing.price_details.price='price_other',()=>line.period.end=line.period.start,()=>pi.status='processing',()=>pi.livemode=false,()=>pi.amount_received=4999,()=>pi.customer='cus_other']){reset();mutate();await assert.rejects(service.settleMembershipInvoice('in_one'));assert(!calls.some(c=>c.path==='rpc/icash_settle_membership_invoice_v2'));}
reset();sub.metadata={};assert.equal(await service.settleMembershipInvoice('in_one'),false,'Legacy invoice delegates to legacy handler');
reset();member.state='needs_review';await service.syncMembershipSubscription(sub);assert.equal(member.state,'needs_review','Refund/dispute holds survive late active events');
reset();const originalDb=db;await service.reconcileMembershipCheckout({...member});assert.equal(member.state,'active');
reset();sub.metadata.icash_membership='00000000-0000-4000-8000-000000000002';await assert.rejects(service.reconcileMembershipCheckout({...member}));assert(!calls.some(c=>c.method==='PATCH'));
reset();session.customer='cus_other';await assert.rejects(service.reconcileMembershipCheckout({...member}));
reset();member.stripe_session_id='cs_live_other';await assert.rejects(service.reconcileMembershipSession('cs_live_one'));
reset();member.stripe_subscription_id='sub_one';await service.stopMembership({...member});assert.equal(member.state,'cancelled');assert(calls.some(c=>c.cancel==='sub_one'&&c.body.invoice_now===false&&c.body.prorate===false));assert.equal(calls[0].path,'rpc/icash_request_membership_cancellation','lock persists before provider calls');
reset();member.stripe_subscription_id='sub_one';sub.metadata.icash_membership='00000000-0000-4000-8000-000000000002';await assert.rejects(service.stopMembership({...member}));assert(!calls.some(c=>c.update));
reset();session.status='open';await service.stopMembership({...member});assert(calls.some(c=>c.expire==='cs_live_one'));assert.equal(member.state,'cancelled');
assert.equal(policy.membershipAccessible({state:'active',paid_through:new Date(Date.now()+60000).toISOString()}),true);assert.equal(policy.membershipAccessible({state:'active',paid_through:null}),false);assert.equal(policy.membershipAccessible({state:'active',paid_through:new Date(Date.now()-1).toISOString()}),false);
console.log('PASS software billing: canonical paid USD amount/price/customer/mode/period, no credit grants, checkout ownership binding, review hold, and immediate cancellation. Fake Stripe only.');

reset();member.state='cancel_requested';await service.syncMembershipSubscription(sub);assert.equal(member.state,'cancel_requested');
reset();member.state='cancelled';await service.syncMembershipSubscription(sub);assert.equal(member.state,'cancelled');
reset();member.stripe_subscription_id='sub_one';const cancel=stripe.subscriptions.cancel;stripe.subscriptions.cancel=async()=>{throw Error('provider failure');};await assert.rejects(service.stopMembership({...member}),/MEMBERSHIP_CANCELLATION_PENDING/);assert.equal(member.state,'cancel_requested');stripe.subscriptions.cancel=cancel;await service.stopMembership({...member});assert.equal(member.state,'cancelled');console.log('PASS durable cancellation and retry; late active events cannot unlock stopped membership.');

// Retention is a server-authorized discount, not a relaxed invoice amount check.
const coupon={id:'icash-retention-50-six-months-v1',valid:true,percent_off:50,amount_off:null,duration:'repeating',duration_in_months:6};
let discount;
stripe.coupons={retrieve:async()=>coupon};
const update=stripe.subscriptions.update;
stripe.subscriptions.update=async(id,body,options)=>{calls.push({retentionUpdate:id,body,options});sub={...sub,discounts:[discount]};return sub;};
const claimDb=mocks.db;
mocks.db=async(path,method,body)=>{if(path==='rpc/icash_claim_membership_retention'){calls.push({path,body});member.retention_requested_at??=new Date(discount.start*1000).toISOString();return {...member};}return claimDb(path,method,body);};
// The imported service captured its original db binding. Reload with the retention fixture.
globalThis.__member=mocks;const retained=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(mocks).join(',')+'}=globalThis.__member;\n'+code+'\n//retention').toString('base64'));
function retentionReset(){reset();const start=Math.floor(Date.now()/1000);member.state='active';member.stripe_subscription_id='sub_one';member.stripe_customer_id='cus_one';member.paid_through=new Date((start+86400*30)*1000).toISOString();sub.discounts=[];discount={id:'di_retention',customer:'cus_one',subscription:'sub_one',promotion_code:null,source:{type:'coupon',coupon},start,end:start+183*86400};}
retentionReset();await retained.retainMembership({...member});assert.equal(member.retention_discount_id,'di_retention');assert.equal(calls.filter(c=>c.retentionUpdate).length,1);assert.equal(calls.find(c=>c.retentionUpdate).body.proration_behavior,'none');assert.equal(calls.find(c=>c.retentionUpdate).body.cancel_at_period_end,undefined);assert.equal(calls.find(c=>c.retentionUpdate).options.idempotencyKey,'membership-retain:'+id);
await retained.retainMembership({...member});assert.equal(calls.filter(c=>c.retentionUpdate).length,1,'Retry reads the existing discount and does not restart six months');
invoice.discounts=[discount];invoice.total_discount_amounts=[{amount:2500,discount:'di_retention'}];invoice.total=invoice.amount_paid=pi.amount_received=2500;line.period={start:discount.start+86400,end:discount.start+31*86400};calls=[];
await retained.settleMembershipInvoice('in_one');assert.equal(calls.find(c=>c.path==='rpc/icash_settle_membership_invoice_v2').body.p_amount,2500);assert.equal(calls.find(c=>c.path==='rpc/icash_settle_membership_invoice_v2').body.p_discount,'di_retention');
for(const tamper of [()=>invoice.total_discount_amounts[0].amount=2000,()=>invoice.total_discount_amounts[0].discount='di_other',()=>invoice.discounts[0]={...discount,source:{type:'coupon',coupon:{...coupon,percent_off:75}}},()=>line.period={start:discount.end,end:discount.end+30*86400},()=>member.retention_requested_at=null]){const previous={invoice:structuredClone(invoice),line:structuredClone(line),member:structuredClone(member)};tamper();calls=[];await assert.rejects(retained.settleMembershipInvoice('in_one'));assert(!calls.some(c=>c.path==='rpc/icash_settle_membership_invoice_v2'));invoice=previous.invoice;line=previous.line;member=previous.member;}
invoice.discounts=[];invoice.total_discount_amounts=[];invoice.total=invoice.amount_paid=pi.amount_received=5000;line.period={start:discount.end+86400,end:discount.end+31*86400};calls=[];await retained.settleMembershipInvoice('in_one');assert.equal(calls.find(c=>c.path==='rpc/icash_settle_membership_invoice_v2').body.p_amount,5000,'Normal full-price renewals resume after the offer');
member.state='cancel_requested';await assert.rejects(retained.retainMembership({...member}));
stripe.subscriptions.update=update;
console.log('PASS 50% retention: exact authorized coupon, no immediate charge, repeat-safe application, discounted/full renewals, and rejection of unauthorized or expired discounts.');
