import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {validOwnerOverview,overviewMoney,overviewTime,overviewLeadStatus} from '../lib/owner-overview.ts';
const owner='592171a0-2bb9-484e-8c9a-dd5d2b43b5f7';
let user={id:owner},queries=[],bad=false,authFails=false;
const fixture=filters=>({...filters,pageSize:25,timezone:'America/Chicago',startAt:'2026-10-01T05:00:00Z',endAt:'2026-10-10T05:00:00Z',leadCount:0,reviewCount:0,matchedCount:0,leads:[],usage:{completedCount:0,missingChargeCount:0,chargedCents:0,coveredCents:0,knownCostMicros:0,costMicros:0,marginMicros:0,missingCostCount:0,estimatedCount:0,pendingCount:0}});
const mocks={currentUser:async verify=>{assert.equal(verify,true);if(authFails)throw Error('Provider unavailable');return user;},ownerInboundTarget:{ownerUserId:owner},validOwnerOverview,db:async(path,method,body,signal)=>{queries.push({path,method,body,signal});return bad?null:fixture({days:body.p_days,includeOwner:body.p_include_owner,query:body.p_query,page:body.p_page});}};
globalThis.__ownerOverview=mocks;
const code=ts.transpileModule(readFileSync(new URL('../app/api/admin/overview/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
const {GET}=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(mocks).join(',')+'}=globalThis.__ownerOverview;\n'+code).toString('base64'));
const get=query=>GET(new Request('https://example.invalid/api/admin/overview?'+query));
user=null;assert.equal((await get('')).status,401);
user={id:'another-user',user_metadata:{isBillingOwner:true}};assert.equal((await get('actor='+owner)).status,403);assert.equal(queries.length,0);
authFails=true;assert.equal((await get('')).status,503);assert.equal(queries.length,0);authFails=false;user={id:owner};
for(const query of ['days=2','days=30x','includeOwner=1','page=0','page=1.5','page=100001','q='+'x'.repeat(101)])assert.equal((await get(query)).status,400);assert.equal(queries.length,0);
let response=await get('days=7&includeOwner=true&q=%25_&page=2&actor=another-user');assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal(response.headers.get('vary'),'Cookie');
assert.deepEqual(queries[0].body,{p_actor:owner,p_days:7,p_include_owner:true,p_query:'%_',p_page:2});assert(queries[0].signal instanceof AbortSignal);
bad=true;response=await get('');assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'The overview could not load. Try refreshing in a moment.'});
const filters={days:30,includeOwner:false,query:'',page:1},valid=fixture(filters);
assert(validOwnerOverview(valid,filters));
for(const patch of [{leadCount:NaN},{leads:null},{days:7},{includeOwner:true},{startAt:'bad'},{matchedCount:1}])assert.equal(validOwnerOverview({...valid,...patch},filters),false);
for(const patch of [{costMicros:null},{marginMicros:1},{chargedCents:null},{missingCostCount:1},{chargedCents:Infinity}])assert.equal(validOwnerOverview({...valid,usage:{...valid.usage,...patch}},filters),false);
assert.equal(overviewMoney(null),'—');assert.equal(overviewMoney(-10003000),'-$10.00');assert.equal(overviewMoney(250,'cents'),'$2.50');assert.match(overviewTime('2026-11-01T07:30:00Z'),/1:30 AM/);assert.equal(overviewLeadStatus('unmatched'),'Check address');
delete globalThis.__ownerOverview;
console.log('PASS owner API: owner-only/no metadata bypass, private cache, validated totals, safe filters, honest failures, and 12-hour Central time.');
