import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import {prepareOwnerAudioPhonePin as prepare,applyOwnerAudioPhonePin as apply,restoreOwnerAudioPhonePin as restore,inspectOwnerAudioPhonePin as inspect,assertPinReviewCurrent} from '../lib/owner-audio-phone-pin.ts';
import {ownerInboundTarget as target} from '../lib/owner-inbound-acceptance.ts';
// Synthetic receipts and injected fetch only. No live provider requests.
const env={ELEVENLABS_API_KEY:'SYNTHETIC_PROVIDER_KEY',ELEVENLABS_INBOUND_WEBHOOK_SECRET:'SYNTHETIC_INBOUND_SIGNING_SECRET_123456789'};
const mainId='agtbrch_syntheticMain',hidden='PRIVATE_CONFIG_MUST_NOT_LEAVE_SERVER',ref='secret_fixture';
const base=`https://api.us.elevenlabs.io/v1/convai/agents/${target.agentId}`;
const urls={default:base,main:base+'?branch_id='+mainId,private:base+'?branch_id='+target.branchId,branches:base+'/branches?include_archived=true&limit=100',phone:`https://api.us.elevenlabs.io/v1/convai/phone-numbers/${target.phoneNumberId}`};
function state(original=null){
 const privateAgent={agent_id:target.agentId,branch_id:target.branchId,main_branch_id:mainId,version_id:'agtvrsn_private1',name:hidden,metadata:{updated_at:1},conversation_config:{agent:{prompt:{prompt:hidden,tools:[],tool_ids:[],mcp_server_ids:[],knowledge_base:[]}},conversation:{max_duration_seconds:60}},platform_settings:{auth:{enable_auth:true},privacy:{record_voice:false},overrides:{enable_conversation_initiation_client_data_from_webhook:true,conversation_config_override:{agent:{first_message:true,prompt:{prompt:true}}}},workspace_overrides:{conversation_initiation_client_data_webhook:{url:'https://www.geticashx.com/api/internal/voice/inbound',request_headers:{Authorization:{secret_id:ref}}}},queueing_config:{enabled:true,wait_timeout_seconds:30},call_limits:{bursting_enabled:false}},procedures:{}};
 const main=structuredClone(privateAgent);main.branch_id=mainId;main.version_id='agtvrsn_main1';main.conversation_config.conversation.max_duration_seconds=600;
 const branches={results:[{id:mainId,agent_id:target.agentId,name:'Main',is_archived:false,current_live_percentage:100,draft_exists:false,calls_7d:1},{id:target.branchId,agent_id:target.agentId,name:'Private',is_archived:false,current_live_percentage:0,draft_exists:false,calls_7d:2}],meta:{total:2}};
 const phone={phone_number_id:target.phoneNumberId,phone_number:target.ingressNumber,provider:'twilio',assigned_agent:{agent_id:target.agentId,branch_id:original},label:hidden,environment:null};
 for(const a of [main,privateAgent])a.phone_numbers=[structuredClone(phone),{phone_number_id:'phnum_other',label:'unchanged other phone',assigned_agent:{agent_id:target.agentId,branch_id:null}}];
 return {main,privateAgent,branches,phone};
}
function fixture(initial=state(),options={}){
 const s=structuredClone(initial),calls=[],patches=[];
 const fetcher=async(url,req)=>{
  calls.push({url,method:req.method});assert(Object.values(urls).includes(url));assert.equal(req.headers['xi-api-key'],env.ELEVENLABS_API_KEY);assert.equal(req.cache,'no-store');assert.equal(req.redirect,'error');assert.equal(req.credentials,'omit');assert(req.signal instanceof AbortSignal);
  if(req.method==='PATCH'){
   assert.equal(url,urls.phone);const body=JSON.parse(req.body);assert.deepEqual(Object.keys(body),['branch_id']);patches.push(body);
   if(options.beforePatch)await options.beforePatch(s,body);
   if(options.patchChanges!==false){s.phone.assigned_agent.branch_id=body.branch_id;for(const a of [s.main,s.privateAgent])for(const p of a.phone_numbers??[])if(p.phone_number_id===target.phoneNumberId)p.assigned_agent.branch_id=body.branch_id;}
   if(options.afterPatch)options.afterPatch(s,body);
   if(options.patchThrows)throw Error(hidden);
   return new Response(hidden,{status:options.patchStatus??200});
  }
  assert.equal(req.method,'GET');assert.equal(req.body,undefined);
  const override=options.getResponse?.(url,s,calls);if(override)return override;
  return Response.json(url===urls.default?(options.defaultAgent?.(s)??s.main):url===urls.main?s.main:url===urls.private?s.privateAgent:url===urls.branches?s.branches:s.phone);
 };
 return {s,calls,patches,fetcher,prepare:()=>prepare(env,fetcher),apply:token=>apply(env,token,fetcher),restore:token=>restore(env,token,fetcher),inspect:token=>inspect(env,token,fetcher)};
}
function redacted(output){
 const serialized=JSON.stringify(output);for(const value of [hidden,ref,env.ELEVENLABS_API_KEY,env.ELEVENLABS_INBOUND_WEBHOOK_SECRET,target.ownerPhone,target.ingressNumber,target.agentId,target.phoneNumberId])assert(!serialized.includes(value));
 if(output.reviewToken){const token=JSON.parse(Buffer.from(output.reviewToken.split('.')[0],'base64url').toString());assert.deepEqual(Object.keys(token).sort(),['expires','fingerprint','nonce','op','originalBranch','phoneFingerprint','pinnedFingerprint','restoreExpires','v']);for(const value of [hidden,ref,env.ELEVENLABS_API_KEY,env.ELEVENLABS_INBOUND_WEBHOOK_SECRET,target.ownerPhone,target.ingressNumber,target.agentId,target.phoneNumberId])assert(!JSON.stringify(token).includes(value));}
}
for(const original of [null,mainId]){
 const x=fixture(state(original)),review=await x.prepare();assert.equal(review.status,'ready');assert.equal(x.patches.length,0);assert.equal(x.calls.length,5);assert.match(review.fingerprint,/^[a-f0-9]{64}$/);assert.equal(Date.parse(review.restoreExpiresAt)-Date.parse(review.expiresAt),24*60*60*1000-120000);redacted(review);
 assert.equal(assertPinReviewCurrent(env,review.reviewToken).reviewToken,review.reviewToken);
 const pinned=await x.apply(review.reviewToken);assert.equal(pinned.status,'pinned');assert.equal(pinned.reviewToken,review.reviewToken);assert.deepEqual(x.patches,[{branch_id:target.branchId}]);redacted(pinned);
 assert.equal((await x.prepare()).reason,'already_pinned');assert.equal((await x.inspect(review.reviewToken)).status,'pinned');assert.equal((await x.apply(review.reviewToken)).reason,'invalid_review');assert.equal(x.patches.length,1);
 const restored=await x.restore(review.reviewToken);assert.equal(restored.status,'restored');assert.equal(restored.reviewToken,review.reviewToken);assert.deepEqual(x.patches,[{branch_id:target.branchId},{branch_id:original}]);redacted(restored);
 assert.equal((await x.inspect(review.reviewToken)).status,'restored');assert.equal((await x.restore(review.reviewToken)).reason,'invalid_review');assert.equal(x.patches.length,2);
}
for(const [mutate,reason] of [
 [s=>s.phone.assigned_agent.agent_id='foreign','routing_not_safe'],[s=>s.phone.phone_number='foreign','routing_not_safe'],[s=>s.phone.phone_number_id='foreign','routing_not_safe'],[s=>s.phone.provider='foreign','routing_not_safe'],[s=>delete s.phone.assigned_agent.branch_id,'routing_not_safe'],[s=>s.phone.assigned_agent.branch_id='agtbrch_foreign','routing_not_safe'],
 [s=>s.main.phone_numbers[0].assigned_agent.branch_id='agtbrch_other','evidence_missing'],[s=>s.main.phone_numbers.push(structuredClone(s.main.phone_numbers[0])),'evidence_missing'],[s=>s.main.main_branch_id=target.branchId,'evidence_missing'],[s=>delete s.privateAgent.version_id,'evidence_missing'],[s=>s.privateAgent.main_branch_id='agtbrch_foreign','evidence_missing'],[s=>s.branches.results[0].draft_exists=true,'evidence_missing'],[s=>delete s.branches.results[1].draft_exists,'evidence_missing'],[s=>s.branches.results.push(structuredClone(s.branches.results[1])),'evidence_missing'],[s=>s.branches.meta.total=3,'evidence_missing'],[s=>s.branches.results[1].is_archived=true,'routing_not_safe'],[s=>s.branches.results[0].current_live_percentage=99,'routing_not_safe'],[s=>s.branches.results[1].current_live_percentage=1,'routing_not_safe'],
 [s=>s.privateAgent.conversation_config.conversation.max_duration_seconds=600,'unsafe_configuration'],[s=>s.privateAgent.conversation_config.agent.prompt.tool_ids=['unsafe'],'unsafe_configuration'],[s=>s.privateAgent.platform_settings.privacy.record_voice=true,'unsafe_configuration'],[s=>s.privateAgent.platform_settings.queueing_config.wait_timeout_seconds=31,'unsafe_configuration'],[s=>s.privateAgent.platform_settings.call_limits.bursting_enabled=true,'unsafe_configuration'],[s=>s.privateAgent.platform_settings.overrides.enable_conversation_initiation_client_data_from_webhook=false,'unsafe_configuration'],[s=>s.privateAgent.platform_settings.workspace_overrides.conversation_initiation_client_data_webhook.url='https://foreign.invalid','unsafe_configuration'],[s=>s.main.platform_settings.workspace_overrides.conversation_initiation_client_data_webhook.request_headers.Authorization.secret_id='different','unsafe_configuration'],
 ]){const s=state();mutate(s);const x=fixture(s),out=await x.prepare();assert.equal(out.reason,reason);assert.equal(x.patches.length,0);redacted(out);}
for(const mutate of [s=>s.phone.label='changed',s=>s.phone.environment='staging',s=>s.main.name='changed',s=>s.main.version_id='agtvrsn_main2',s=>s.privateAgent.name='changed',s=>s.branches.results[1].name='changed',s=>s.main.phone_numbers[1].label='changed',s=>s.privateAgent.phone_numbers[0].label='changed']){const x=fixture(),review=await x.prepare();mutate(x.s);const out=await x.apply(review.reviewToken);assert.equal(out.reason,'configuration_changed');assert.equal(x.patches.length,0);}
const volatile=fixture(),vr=await volatile.prepare();volatile.s.main.metadata.updated_at=99;volatile.s.branches.results[0].calls_7d=99;assert.equal((await volatile.apply(vr.reviewToken)).status,'pinned');
const unrelated=fixture(),ur=await unrelated.prepare();assert.equal((await unrelated.apply(ur.reviewToken)).status,'pinned');unrelated.s.main.name='external Main edit';unrelated.s.main.version_id='agtvrsn_newMain';unrelated.s.privateAgent.conversation_config.conversation.max_duration_seconds=61;assert.equal((await unrelated.restore(ur.reviewToken)).status,'restored','Unrelated agent edits must not prevent narrow phone restoration');
for(const mutate of [s=>s.phone.assigned_agent.branch_id='agtbrch_foreign',s=>s.phone.assigned_agent.agent_id='foreign',s=>s.phone.label='changed',s=>s.phone.environment='staging',s=>s.phone.phone_number='foreign']){const x=fixture(),r=await x.prepare();await x.apply(r.reviewToken);mutate(x.s);assert.equal((await x.restore(r.reviewToken)).status,'blocked');assert.equal(x.patches.length,1);}
const untouched=fixture(),tr=await untouched.prepare();assert.equal((await untouched.restore(tr.reviewToken)).status,'restored');assert.equal(untouched.patches.length,0);
for(const options of [{patchThrows:true},{patchStatus:500},{patchStatus:403,patchChanges:false},{patchChanges:false},{afterPatch:s=>s.phone.label='unexpected'},{afterPatch:s=>s.main.name='unexpected'},{afterPatch:s=>s.main.phone_numbers[1].label='unexpected'},{afterPatch:s=>s.privateAgent.phone_numbers[0].label='unexpected'},{getResponse:(url,s,calls)=>calls.some(c=>c.method==='PATCH')?new Response(hidden,{status:503}):null}]){
 const x=fixture(state(),options),r=await x.prepare(),out=await x.apply(r.reviewToken);assert.equal(out.status,'outcome_unknown');assert.equal(out.reviewToken,r.reviewToken);assert.equal(x.patches.length,1);assert(x.calls.slice(x.calls.findIndex(c=>c.method==='PATCH')+1).every(c=>c.method==='GET'));assert.equal((await x.apply(r.reviewToken)).status,'blocked');assert.equal(x.patches.length,1);redacted(out);
}
const uncertain=fixture(state(),{patchThrows:true}),rr=await uncertain.prepare();assert.equal((await uncertain.apply(rr.reviewToken)).status,'outcome_unknown');assert.equal((await uncertain.inspect(rr.reviewToken)).status,'pinned');assert.equal((await uncertain.restore(rr.reviewToken)).status,'outcome_unknown');assert.equal((await uncertain.inspect(rr.reviewToken)).status,'restored');assert.equal(uncertain.patches.length,2);
let unblock;const concurrent=fixture(state(),{beforePatch:()=>new Promise(resolve=>unblock=resolve)}),cr=await concurrent.prepare();const first=concurrent.apply(cr.reviewToken);while(!unblock)await new Promise(resolve=>setImmediate(resolve));assert.equal((await concurrent.apply(cr.reviewToken)).status,'blocked');assert.equal((await concurrent.restore(cr.reviewToken)).status,'blocked');unblock();assert.equal((await first).status,'pinned');assert.equal(concurrent.patches.length,1);
const forged=fixture(),fr=await forged.prepare();for(const token of [undefined,'',fr.reviewToken+'extra',fr.reviewToken.slice(0,-3)+'xyz']){const n=forged.calls.length;assert.equal((await forged.apply(token)).reason,'invalid_review');assert.equal((await forged.restore(token)).reason,'invalid_review');assert.equal((await forged.inspect(token)).reason,'invalid_review');assert.equal(forged.calls.length,n);assert.throws(()=>assertPinReviewCurrent(env,token));}
const expire=Date.parse(fr.expiresAt)+1;assert.equal((await apply(env,fr.reviewToken,forged.fetcher,expire)).reason,'review_expired');assert.throws(()=>assertPinReviewCurrent(env,fr.reviewToken,expire));assert.equal((await inspect(env,fr.reviewToken,forged.fetcher,expire)).status,'restored');assert.equal((await restore(env,fr.reviewToken,forged.fetcher,Date.parse(fr.restoreExpiresAt)+1)).reason,'restore_expired');
function signed(change){const token=JSON.parse(Buffer.from(fr.reviewToken.split('.')[0],'base64url').toString());change(token);const encoded=Buffer.from(JSON.stringify(token)).toString('base64url');return encoded+'.'+createHmac('sha256',env.ELEVENLABS_INBOUND_WEBHOOK_SECRET).update('icash-audio-phone-pin-review-v1\0'+encoded).digest('base64url');}
for(const change of [t=>t.originalBranch=target.branchId,t=>t.extra=true,t=>t.restoreExpires++,t=>t.fingerprint='nothex',t=>t.nonce='bad',t=>t.op='foreign'])assert.equal((await forged.apply(signed(change))).reason,'invalid_review');
assert.equal((await forged.apply(signed(t=>t.fingerprint='a'.repeat(64)))).reason,'configuration_changed');assert.equal(forged.patches.length,0);
for(const replacement of [()=>new Response(hidden,{status:401}),()=>new Response(hidden,{status:403}),()=>new Response(hidden,{status:500}),()=>Response.json([]),()=>new Response('invalid',{headers:{'content-type':'application/json'}}),()=>Response.json(state().main,{headers:{'Content-Length':'2000000'}}),()=>new Response('x'.repeat(1024*1024+1),{headers:{'content-type':'application/json'}}),()=>{throw Error(hidden);},()=>{const r=Response.json(state().main);Object.defineProperty(r,'url',{value:'https://foreign.invalid'});return r;}]){const x=fixture(state(),{getResponse:replacement}),out=await x.prepare();assert.equal(out.status,'blocked');assert.equal(x.patches.length,0);redacted(out);}
for(const config of [{},{...env,ELEVENLABS_API_KEY:'bad\nkey'},{...env,ELEVENLABS_INBOUND_WEBHOOK_SECRET:'short'}]){let calls=0;assert.equal((await prepare(config,async()=>{calls++;throw Error();})).reason,'configuration_unavailable');assert.equal(calls,0);}
globalThis.window={};assert.equal((await prepare(env,()=>{throw Error('should not fetch');})).reason,'configuration_unavailable');delete globalThis.window;
const source=readFileSync('lib/owner-audio-phone-pin.ts','utf8');assert(!source.includes('process.env'));assert(!/console\./.test(source));assert(!source.includes('/v1/convai/secrets'));assert(!/method:'(?:PUT|DELETE)'/.test(source));assert.equal((source.match(/method:'PATCH'/g)??[]).length,1);assert(source.includes('JSON.stringify({branch_id:desired})'));
console.log('Phone pin provider control passed: exact null/Main restoration, signed pre-write recovery token, private60 preflight, fixed branch-only PATCH, drift guards, readback, no retries, redaction and bounded errors');
