import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
import {webinarRequest} from '../lib/webinar-client.ts';
import {saveBotBuild,waitForBotCreationTransition} from '../lib/bot-build.ts';import {defaultBotProfile,setupProfileSchema} from '../lib/bot-setup.ts';
// Exercise the real component handlers and server save protocol without providers.
async function harness(file,extra){const cells=[],effects=[],pending=[];let index=0;
 const same=(a,b)=>a&&b&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
 const deps={useState(initial){const n=index++;if(!(n in cells))cells[n]=typeof initial==='function'?initial():initial;return [cells[n],value=>cells[n]=typeof value==='function'?value(cells[n]):value];},useRef(initial){const n=index++;return cells[n]??=( {current:initial});},useEffect(fn,list){const n=index++;if(!same(effects[n]?.list,list))pending.push(()=>{effects[n]?.cleanup?.();effects[n]={list,cleanup:fn()};});},_Fragment:'fragment',_jsx:(type,props)=>({type,props}),_jsxs:(type,props)=>({type,props}),Check:'check',ArrowRight:'arrow',ShieldCheck:'shield',...extra};
 const key='component'+Math.random().toString(36).slice(2);globalThis[key]=deps;const code=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/^import .*;\s*$/gm,'');const module=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.'+key+';\n'+code).toString('base64'));return {render(name,props){index=0;const node=module[name](props);while(pending.length)pending.shift()();return node;},close(){effects.forEach(e=>e?.cleanup?.());}};}
const all=(node)=>!node||typeof node!=='object'?[]:[node,...[node.props?.children].flat(Infinity).flatMap(all)];
const find=(tree,type)=>all(tree).find(n=>n.type===type);const flush=async()=>{for(let n=0;n<12;n++)await Promise.resolve();};
const AccountAccess=()=>null,BotBuilding=()=>null,PostPurchaseSetup=()=>null,StripeEmbeddedCheckout=()=>null;
globalThis.window={location:{search:''}};globalThis.matchMedia=()=>({matches:true});
for(const accessible of [false,true]){
 globalThis.fetch=async()=>Response.json({offer:{revision:1,priceCents:5000},membership:{accessible},ready:false,needsClaim:true,email:'paid@example.invalid',customerName:'Casey'});
 const h=await harness('components/membership-checkout.tsx',{PostPurchaseSetup,StripeEmbeddedCheckout,webinarRequest,webinarBrowserEvent:()=>{},priceLabel:()=>'$50',membershipTermsVersion:'fixture'}),props={onSignedIn:()=>{}};h.render('MembershipCheckout',props);await flush();const tree=h.render('MembershipCheckout',props);assert.equal(!!find(tree,PostPurchaseSetup),accessible,'Only confirmed accessible membership unlocks post-purchase setup');h.close();
}
let saved={id:'saved-setup',revision:1,stage:0,profile:{...defaultBotProfile,voice:'chris',market:'Austin, TX',marketMode:'city'}},requests=[],opens=0,hold;
globalThis.fetch=async(_url,options)=>{const body=JSON.parse(options.body);requests.push(body);if(body.action==='save'){await new Promise(resolve=>hold=resolve);saved={...saved,profile:body.profile,revision:saved.revision+1,stage:4};}return Response.json({setup:saved});};
const h=await harness('components/post-purchase-setup.tsx',{AccountAccess,BotBuilding,saveBotBuild,waitForBotCreationTransition,defaultBotProfile,setupProfileSchema}),props={email:'paid@example.invalid',customerName:'Casey',needsClaim:true,onWorkspace:()=>opens++};
h.render('PostPurchaseSetup',props);await flush();let tree=h.render('PostPurchaseSetup',props);const input=find(tree,'input');assert.equal(input.props.value,'Casey’s bot');input.props.onChange({target:{value:'Scout'}});tree=h.render('PostPurchaseSetup',props);find(tree,'form').props.onSubmit({preventDefault(){}});await flush();tree=h.render('PostPurchaseSetup',props);assert.equal(find(tree,BotBuilding).props.phase,'saving');assert.equal(opens,0);assert.equal(requests.filter(r=>r.action==='save').length,1);assert.equal(requests.at(-1).profile.voice,'chris');assert.equal(requests.at(-1).profile.market,'Austin, TX','Naming preserves their previously selected settings');
hold();await flush();tree=h.render('PostPurchaseSetup',props);assert.equal(saved.profile.displayName,'Scout');assert.equal(saved.stage,4);assert.equal(find(tree,AccountAccess).props.initialEmail,'paid@example.invalid');assert.equal(opens,0,'A paid but unverified guest does not receive an account session');find(tree,AccountAccess).props.onSignedIn();assert.equal(opens,1);h.close();
// A confirmed account already signed in proceeds immediately after durable save.
saved={...saved,stage:0,profile:{...saved.profile,displayName:''}};requests=[];opens=0;
const signed=await harness('components/post-purchase-setup.tsx',{AccountAccess,BotBuilding,saveBotBuild,waitForBotCreationTransition,defaultBotProfile,setupProfileSchema}),signedProps={...props,needsClaim:false};signed.render('PostPurchaseSetup',signedProps);await flush();tree=signed.render('PostPurchaseSetup',signedProps);find(tree,'form').props.onSubmit({preventDefault(){}});await flush();assert.equal(opens,0);hold();await flush();assert.equal(opens,1,'Workspace navigation follows the saved bot, not the animation timer alone');signed.close();
console.log('PASS immediate payoff handlers: verified billing gate, carried name/email, durable bot save, visible creation state, preserved preferences, guest email verification and immediate signed-in workspace handoff.');
