import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {practiceBudgets,readPracticeSelection,savePracticeSelection,practiceScope} from '../lib/practice-funnel.ts';
import {readDemoProgress,saveDemoProgress,DEMO_PROGRESS_KEY} from '../lib/demo-progress.ts';
const catalog={mode:'live',packs:[{code:'budget_ten',price_cents:1000,enabled:true},{code:'disabled',price_cents:2000,enabled:false},{code:'bad',price_cents:NaN,enabled:true},{code:'small',price_cents:300,enabled:true},{code:'more',price_cents:2500,enabled:true},{code:'budget_ten',price_cents:1000,enabled:true}]};
assert.deepEqual(practiceBudgets(catalog),[{code:'budget_ten',priceCents:1000},{code:'more',priceCents:2500}]);
assert.equal(practiceBudgets({...catalog,mode:'test'}).length,3);
assert.throws(()=>practiceBudgets({packs:catalog.packs}));assert.throws(()=>practiceBudgets({mode:'live'}));
const values=new Map();globalThis.localStorage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};
assert.equal(readPracticeSelection('setup-a'),null);
savePracticeSelection('setup-a','budget_ten','demo');assert.equal(readPracticeSelection('setup-a').screen,'demo');assert.equal(readPracticeSelection('setup-b'),null);
savePracticeSelection('setup-a','budget_ten','funding');assert.equal(readPracticeSelection('setup-a').screen,'funding');
const scope=practiceScope('setup-a','budget_ten');saveDemoProgress(scope,3,false);assert.equal(readDemoProgress(scope).count,3);assert.equal(readDemoProgress(practiceScope('setup-a','more')),null);assert.equal(readDemoProgress(practiceScope('setup-b','budget_ten')),null);
values.set('icash-test-v3',JSON.stringify({version:3,count:5,limitConfirmed:true,savedAt:Date.now()}));assert.equal(readDemoProgress('new-setup'),null,'legacy completion must not skip a new demo');
saveDemoProgress(scope,5,false);assert.equal(readDemoProgress(scope),null);saveDemoProgress(scope,5,true);assert.equal(readDemoProgress(scope).count,5);
values.set(`${DEMO_PROGRESS_KEY}:${scope}`,JSON.stringify({version:4,scope,count:4,limitConfirmed:true,savedAt:Date.now()+60000}));assert.equal(readDemoProgress(scope),null);
globalThis.localStorage={getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}};assert.equal(readPracticeSelection('setup-a'),null);assert.equal(readDemoProgress(scope),null);assert.doesNotThrow(()=>savePracticeSelection('setup-a','budget_ten','demo'));assert.doesNotThrow(()=>saveDemoProgress(scope,1,false));
const setup=readFileSync(new URL('../components/bot-setup.tsx',import.meta.url),'utf8');
assert.match(setup,/Create &amp; run demo/);assert.ok(setup.indexOf('id="practice-budget"')<setup.indexOf('Create &amp; run demo'));
assert.match(setup,/disabled=\{busy\|\|loading\|\|!profile.displayName.trim\(\)\|\|!selected\}/);
assert.match(setup,/if\(saveInFlight.current\)return false/);assert.ok(setup.indexOf('await saveBotBuild')<setup.indexOf("setScreen('demo')"));
assert.match(setup,/\.\.\.current.profile,displayName:parsed.data.displayName/,'current saved market is carried without a new field');
assert.match(setup,/FundingCheckout initialCode=\{selected\?\.code/);assert.match(setup,/practiceScope\(setup.id,selected.code\)/);
assert.match(setup,/get\('payment'\)==='funded'/,'payment return is not forced through demo');
assert.match(setup,/funnel-fund-cta/);assert.match(setup,/Fund my bot/);assert.match(setup,/No real charges, outreach, or earnings/);
const demo=readFileSync(new URL('../components/demo-runner.tsx',import.meta.url),'utf8');assert.ok(!demo.includes('fetch('),'simulation never calls live endpoints');assert.ok(!demo.includes('Real payments are not open yet'));assert.ok(!demo.includes('needsYou'),'simulation does not require a second continue action');assert.match(demo,/return\(\)=>clearTimeout\(timer\)/);assert.match(demo,/No real charges, calls, contracts, or earnings/);assert.match(demo,/!paused&&visible&&!complete/);
const checkout=readFileSync(new URL('../components/funding-checkout.tsx',import.meta.url),'utf8');assert.match(checkout,/\[accepted,setAccepted\]=useState\(false\)/,'real billing consent stays unchecked');assert.match(checkout,/Renews every day/);
console.log('Practice funnel: verified budget catalog, name/market/budget handoff, scoped recovery, explicit creation gate, automatic isolated simulation and unchanged billing consent passed.');
