import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
import * as view from '../components/workspace-view.ts';
import * as contracts from '../lib/property-contract-visibility.ts';
import * as guidance from '../lib/workspace-guidance.ts';
import * as analysis from '../lib/property-analysis-view.ts';
import * as milestone from '../lib/work-milestone.ts';
import {makeWorkspaceFixture} from './fixtures/workspace-volume.mjs';
const require=createRequire(import.meta.url);
const source=readFileSync(new URL('../components/live-workspace.tsx',import.meta.url),'utf8');
const compiled=ts.transpileModule(source+'\nexport {PropertyCard};',{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};
new Function('require','module','exports',compiled)(name=>name==='react'?{useState:v=>[v,()=>{}],useEffect(){},useRef:v=>({current:v}),Activity:'Activity'}:name==='react/jsx-runtime'?require(name):name==='./workspace-view'?view:name==='@/lib/work-milestone'?milestone:name==='@/lib/workspace-guidance'?guidance:name==='@/lib/property-analysis-view'?analysis:name==='@/lib/property-contract-visibility'?contracts:{},mod,mod.exports);
const all=node=>!node||typeof node!=='object'?[]:Array.isArray(node)?node.flatMap(all):[node,...all(node.props?.children)];
const text=node=>typeof node==='string'?node:typeof node==='number'?String(node):Array.isArray(node)?node.map(text).join(' '):node&&typeof node==='object'?text(node.props?.children):'';
const work=makeWorkspaceFixture(),property=work.properties[0];
const toggle=[];
const props={property,work,principal:'Synthetic Company',active:false,visited:false,hidden:false,onToggle:open=>toggle.push(open),onRefresh(){}};
let card=mod.exports.PropertyCard(props),nodes=all(card);
const disclosure=nodes.find(n=>n.type==='div'&&n.props.className==='property-disclosure');
const summary=nodes.find(n=>n.type==='button'&&n.props.className==='property-summary');
assert.equal(summary.props['aria-expanded'],false);
assert.equal(card.props['aria-labelledby'],`property-address-${property.id}`);
assert.match(text(summary),/100 Example Street/);assert.match(text(summary),/Demo City, TX 75001/);
assert.match(text(summary),/View details/);assert.match(text(summary),/1\s+saved call/);
assert.equal(nodes.filter(n=>n.props?.className==='property-details').length,0,'unvisited properties do not mount expensive detail work');
assert.equal(all(summary.props.children).filter(n=>n.type==='button').length,0,'the disclosure has no nested interactive buttons');
assert.equal(nodes.filter(n=>n.type==='button'&&n.props.className!=='contact-dialog-close').length,3,'separate property, Calls and Text controls are visible while collapsed');
assert.equal(nodes.find(n=>n.type==='svg').props['aria-hidden'],'true');
summary.props.onClick();assert.deepEqual(toggle,[true]);
for(const button of all(nodes.find(n=>n.props?.className==='property-quick-actions')).filter(n=>n.type==='button'))button.props.onClick();
assert.deepEqual(toggle,[true],'Call and Text open their own panel without expanding property details');
card=mod.exports.PropertyCard({...props,active:true,visited:true});nodes=all(card);
assert.equal(card.props['data-expanded'],true);
assert.match(text(nodes.find(n=>n.props?.className==='property-summary')),/Close/);
assert.equal(nodes.find(n=>n.type==='Activity').props.mode,'visible');
assert(nodes.some(n=>n.props?.className==='property-control'));
assert(!nodes.some(n=>n.props?.className==='property-overview'));
assert(!nodes.some(n=>n.props?.className==='property-milestones'));
assert(nodes.some(n=>n.type==='dialog'),'Call and Text have their own immediate dialog');
assert(nodes.some(n=>n.props?.className==='property-resources'));
assert(nodes.some(n=>n.type==='button'&&text(n)==='Take over'),'manual-control action remains available');
card=mod.exports.PropertyCard({...props,visited:true,hidden:true});nodes=all(card);
assert.equal(card.props.hidden,true);assert.equal(nodes.find(n=>n.type==='Activity').props.mode,'hidden','visited child state remains mounted when collapsed or filtered');
const sparse={...work,conversations:[],controls:[]};
card=mod.exports.PropertyCard({...props,work:sparse,property:{...property,completed_at:'unknown'}});nodes=all(card);
assert.equal(nodes.filter(n=>n.props?.className==='property-recorded-meta').length,0,'missing dates and calls do not invent metadata');
assert.doesNotMatch(source,/photo-placeholder|fake-price|dummy-value/);
console.log('Property-card presentation: address hierarchy, evidence-only metadata, native keyboard disclosure, nested-toggle isolation, grouped details and retained child state passed.');

const cashPreview=saved=>all(mod.exports.PropertyCard({...props,property:{...property,result:saved}})).find(n=>n.props?.className==='property-cash-preview');
const historical={...property.result,calculationVersion:undefined,preliminarySellerCeilingCents:410000,property:{...property.result.property,fetchedAt:'2026-10-01T05:13:42.573Z'}};
const before=JSON.stringify(historical);
let preview=cashPreview(historical);
assert.equal(preview.props['data-earlier-estimate'],true);
assert.match(text(preview),/Earlier saved estimate.*\$4,100.*Needs update · Unapproved.*Recorded Oct 1, 2026/,'the collapsed card prominently shows historical amount and limitations together');
assert.doesNotMatch(text(preview),/Cash offer estimate|Refresh the saved calculation/,'historical research is not described as a current offer or a working refresh action');
assert.equal(all(preview).find(n=>n.type==='strong').props.children,'$4,100','the exact saved amount stays in the large existing amount element');
assert.equal(all(preview).filter(n=>['button','a','input'].includes(n.type)).length,0,'the historical display introduces no action');
assert.equal(JSON.stringify(historical),before,'card rendering does not mutate saved results');
preview=cashPreview(property.result);
assert.equal(preview.props['data-earlier-estimate'],undefined);
assert.match(text(preview),/Cash offer estimate.*\$145,000.*Based on saved analysis/);assert.doesNotMatch(text(preview),/Earlier saved estimate|Needs update/);
for(const fetchedAt of [undefined,null,'bad']){
 preview=cashPreview({...historical,property:{...historical.property,fetchedAt}});
 assert.match(text(preview),/Earlier saved estimate.*\$4,100.*Needs update · Unapproved.*Recorded date unavailable/);
 assert.doesNotMatch(text(preview),/Invalid Date|Sep 30|Oct 1/,'card completion time is not substituted for the snapshot date');
}
assert.match(text(cashPreview({...historical,property:{...historical.property,fetchedAt:'2026-10-01T23:30:00-07:00'}})),/Recorded Oct 2, 2026/);
assert.match(text(cashPreview({...historical,preliminarySellerCeilingCents:0})),/Earlier saved estimate.*\$0.*Needs update · Unapproved/);
for(const amount of [null,undefined,-1,1.5,'410000',NaN,Infinity,Number.MAX_SAFE_INTEGER+1]){
 const unavailable=text(cashPreview({...historical,preliminarySellerCeilingCents:amount}));
 assert.match(unavailable,/Not available/);assert.doesNotMatch(unavailable,/Earlier saved estimate|\$/);
}
assert.match(text(cashPreview({...historical,calculationVersion:'unrecognized_version'})),/Earlier saved estimate.*Needs update/);
console.log('Historical collapsed card: saved amount, explicit historical/update/unapproved/date labels, unchanged current-version display, invalid/missing input handling and no added action passed.');

const cashStyles=readFileSync(new URL('../app/workspace-clarity.css',import.meta.url),'utf8');
assert.match(cashStyles,/\.property-cash-preview\[data-earlier-estimate=true\] :is\(span,strong,small\)\{color:#475467\}/,'historical card labels, amount and date stay high-contrast');
