import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
import * as view from '../components/workspace-view.ts';
import * as contracts from '../lib/property-contract-visibility.ts';
import * as guidance from '../lib/workspace-guidance.ts';
import * as analysis from '../lib/property-analysis-view.ts';
import * as cardSummary from '../lib/deal-card-summary.ts';
import * as milestone from '../lib/work-milestone.ts';
import {makeWorkspaceFixture} from './fixtures/workspace-volume.mjs';
const require=createRequire(import.meta.url);
const source=readFileSync(new URL('../components/live-workspace.tsx',import.meta.url),'utf8');
const compiled=ts.transpileModule(source+'\nexport {PropertyCard};',{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};
new Function('require','module','exports',compiled)(name=>name==='react'?{useState:v=>[v,()=>{}],useEffect(){},useRef:v=>({current:v}),Activity:'Activity'}:name==='react/jsx-runtime'?require(name):name==='./workspace-view'?view:name==='@/lib/deal-card-summary'?cardSummary:name==='@/lib/work-milestone'?milestone:name==='@/lib/workspace-guidance'?guidance:name==='@/lib/property-analysis-view'?analysis:name==='@/lib/property-contract-visibility'?contracts:{},mod,mod.exports);
const all=node=>!node||typeof node!=='object'?[]:Array.isArray(node)?node.flatMap(all):[node,...all(node.props?.children)];
const text=node=>typeof node==='string'?node:typeof node==='number'?String(node):Array.isArray(node)?node.map(text).join(' '):node&&typeof node==='object'?text(node.props?.children):'';
const work=makeWorkspaceFixture(),property=work.properties[0];
const toggle=[];
const props={property,work,principal:'Synthetic Company',active:false,visited:false,hidden:false,onToggle:open=>toggle.push(open),onRefresh(){}};
let card=mod.exports.PropertyCard(props),nodes=all(card);
const disclosure=nodes.find(n=>n.type==='div'&&n.props.className==='property-disclosure');
const summary=nodes.find(n=>n.type==='button'&&n.props.className==='property-summary');
assert.equal(summary.props['aria-expanded'],false);
assert.equal(card.props['aria-labelledby'],`property-address-${property.id}`);
assert.match(text(summary),/100 Example Street/);assert.match(text(summary),/Demo City, TX 75001/);
assert.match(text(summary),/View details/);assert.match(text(summary),/1\s+saved call/);
assert.equal(nodes.filter(n=>n.props?.className==='property-details').length,0,'unvisited properties do not mount expensive detail work');
assert.equal(all(summary.props.children).filter(n=>n.type==='button').length,0,'the disclosure has no nested interactive buttons');
assert.equal(nodes.filter(n=>n.type==='button'&&n.props.className!=='contact-dialog-close').length,4,'property, Call, Text and saved-call history controls are visible while collapsed');
assert(nodes.some(n=>n.type==='button'&&text(n)==='View call summaries'),'saved history remains directly accessible separately from paid contact actions');
assert.equal(nodes.find(n=>n.type==='svg').props['aria-hidden'],'true');
summary.props.onClick();assert.deepEqual(toggle,[true]);
for(const button of all(nodes.find(n=>n.props?.className==='property-quick-actions')).filter(n=>n.type==='button'))button.props.onClick();
assert.deepEqual(toggle,[true],'Call and Text open their own panel without expanding property details');
card=mod.exports.PropertyCard({...props,active:true,visited:true});nodes=all(card);
assert.equal(card.props['data-expanded'],true);
assert.match(text(nodes.find(n=>n.props?.className==='property-summary')),/Close/);
assert.equal(nodes.find(n=>n.type==='Activity').props.mode,'visible');
assert(nodes.some(n=>n.props?.className==='property-control'));
assert(!nodes.some(n=>n.props?.className==='property-overview'));
assert(!nodes.some(n=>n.props?.className==='property-milestones'));
assert(nodes.some(n=>n.type==='dialog'),'Call and Text have their own immediate dialog');
assert(nodes.some(n=>n.props?.className==='property-resources'));
assert(nodes.some(n=>n.type==='button'&&text(n)==='Take over'),'manual-control action remains available');
card=mod.exports.PropertyCard({...props,visited:true,hidden:true});nodes=all(card);
assert.equal(card.props.hidden,true);assert.equal(nodes.find(n=>n.type==='Activity').props.mode,'hidden','visited child state remains mounted when collapsed or filtered');
const sparse={...work,conversations:[],controls:[]};
card=mod.exports.PropertyCard({...props,work:sparse,property:{...property,completed_at:'unknown'}});nodes=all(card);
assert.equal(nodes.filter(n=>n.props?.className==='property-recorded-meta').length,0,'missing dates and calls do not invent metadata');
assert.doesNotMatch(source,/photo-placeholder|fake-price|dummy-value/);
console.log('Property-card presentation: address hierarchy, evidence-only metadata, native keyboard disclosure, nested-toggle isolation, grouped details and retained child state passed.');

const cashPreview=saved=>all(mod.exports.PropertyCard({...props,property:{...property,result:saved}})).find(n=>n.props?.className==='property-cash-preview');
const historical={...property.result,calculationVersion:undefined,preliminarySellerCeilingCents:410000,property:{...property.result.property,fetchedAt:'2026-10-01T05:13:42.573Z'}};
const before=JSON.stringify(historical);
let preview=cashPreview(historical);
assert.equal(preview.props['aria-label'],'Cash offer price');
assert.equal(text(preview),'Cash offer price $4,100','collapsed offer labels the exact saved amount');
assert.equal(JSON.stringify(historical),before,'rendering never modifies saved results');
assert.equal(text(cashPreview(property.result)),'Cash offer price $145,000');
assert.equal(text(cashPreview({...historical,preliminarySellerCeilingCents:0})),'Cash offer price $0');
for(const amount of [null,undefined,-1,1.5,'410000',NaN,Infinity,Number.MAX_SAFE_INTEGER+1]){
 assert.equal(text(cashPreview({...historical,preliminarySellerCeilingCents:amount})),'Cash offer price Not available','invalid amounts stay unavailable');
}
const opened=all(mod.exports.PropertyCard({...props,property:{...property,result:historical},active:true,visited:true}));
assert(opened.some(n=>n.props?.result===historical),'full source and stale-estimate context remain in the opened analysis');
console.log('Compact cash offer: exact saved number, accessible label, invalid-value handling and full analysis retained in details.');

const signedWork={...work,signing:[{deal_id:work.deals[0].id,kind:'purchase',state:'completed',test_mode:false}]};
const signedCard=all(mod.exports.PropertyCard({...props,work:signedWork,active:true,visited:true}));
assert.match(text(signedCard.find(n=>n.props?.className==='property-cash-preview')),/Purchase price/);
assert(signedCard.some(n=>n.props?.className==='contract-deal-estimates'),'signed contract puts original estimates behind disclosure');
