import assert from 'node:assert/strict';
import {dealMachinePhoto} from '../lib/property-photo.ts';
import {loadPropertyPhoto} from '../lib/dealmachine-photo.ts';
import {cachedPropertyPhoto} from '../lib/property-photo-cache.ts';
import {propertyContext} from '../lib/property-context.ts';
import {showPropertyContract} from '../lib/property-contract-visibility.ts';
const url='https://img.dealmachine.com/sv/30.2598,-97.7544.jpg';
assert.deepEqual(dealMachinePhoto({street_view:url}),{url,source:'DealMachine',view:'street_view'});
for(const street_view of ['http://img.dealmachine.com/sv/1,2.jpg','https://img.dealmachine.com.evil.test/sv/1,2.jpg','javascript:alert(1)','https://user:pass@img.dealmachine.com/sv/1,2.jpg','https://img.dealmachine.com:444/sv/1,2.jpg','https://img.dealmachine.com/map/1,2.jpg',null,[],{},''])assert.equal(dealMachinePhoto({street_view}),null);
assert.equal(dealMachinePhoto({street_view:null,satellite:'https://img.dealmachine.com/sat/1,2.jpg'}).view,'satellite');
assert.equal(dealMachinePhoto({roadmap:'https://img.dealmachine.com/map/1,2.jpg'}),null,'Map is not a property photo');
let requests=[];const transport=async(path,options)=>{requests.push({path,options});return {ok:true,json:async()=>({data:{dm_property_id:'prop_123',images:{street_view:url}}})};};
assert.equal((await loadPropertyPhoto('prop_123','dm_sk_live_fixture',transport)).url,url);
assert.equal(requests.length,1);assert.equal(requests[0].path,'https://api.v2.dealmachine.com/v1/properties/prop_123?enrich=false&contact_audience=none');assert.equal(requests[0].options.redirect,'error');
assert.equal(await loadPropertyPhoto('prop_456','dm_sk_live_fixture',transport),null,'Mismatched property never displays a photo');
assert.equal(await loadPropertyPhoto('prop_123','dm_sk_live_fixture',async()=>({ok:false})),null);
assert.equal(await loadPropertyPhoto('prop_123','dm_sk_live_fixture',async()=>{throw Error();}),null);
requests=[];for(const id of ['https://evil.test','prop_1/../../','practice_owner_sms'])assert.equal(await loadPropertyPhoto(id,'dm_sk_live_fixture',transport),null);assert.equal(requests.length,0);
const normalized=propertyContext({data:{dm_property_id:'prop_123',full_address:'Fixture property',images:{street_view:url},estimated_value:100000}},'prop_123','2026-10-02T00:00:00Z');assert.deepEqual(normalized.images,{street_view:url});
let loads=0;const loader=async()=>{loads++;return dealMachinePhoto({street_view:url});};
await Promise.all([cachedPropertyPhoto('a','1',loader,100000),cachedPropertyPhoto('a','1',loader,100000)]);assert.equal(loads,1);
await cachedPropertyPhoto('a','1',loader,100001);assert.equal(loads,1);await cachedPropertyPhoto('b','1',loader,100001);assert.equal(loads,2,'Cache is account scoped');
for(let i=0;i<20;i++)await cachedPropertyPhoto('c',String(i),loader,100000);assert.equal(loads,14,'Bounded per account');
await cachedPropertyPhoto('c','after-window',loader,160001);assert.equal(loads,15,'Quota recovers after one minute');
let misses=0;const missing=async()=>{misses++;return null;};await cachedPropertyPhoto('missing','one',missing,100000);await cachedPropertyPhoto('missing','one',missing,100001);assert.equal(misses,1);await cachedPropertyPhoto('missing','one',missing,160001);assert.equal(misses,2,'Missing-photo cache expires');
const draft={id:'d',stage:'draft',terms:{seller:'',priceCents:15000000,priceSource:'proposed'}};
assert.equal(showPropertyContract(undefined,[]),false);assert.equal(showPropertyContract(draft,[]),false);assert.equal(showPropertyContract({...draft,terms:{...draft.terms,seller:'Example Seller',priceSource:'seller_reported'}},[]),true);
assert.equal(showPropertyContract(draft,[{deal_id:'d'}]),true);assert.equal(showPropertyContract({...draft,stage:'closed'},[]),true);assert.equal(showPropertyContract(draft,[{deal_id:'other'}]),false);
console.log('Property photos and contract visibility: provider-only imagery, free lookup, mismatch/error fallback, bounded account cache and stage-aware contracts passed');
