import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
import * as photos from '../lib/property-photo.ts';
const require=createRequire(import.meta.url),source=readFileSync(new URL('../components/property-thumbnail.tsx',import.meta.url),'utf8');
let state=[],cursor=0,effects=[];
const hooks={useState(initial){const key=cursor++;if(!(key in state))state[key]=initial;return [state[key],value=>{state[key]=value;}];},useEffect(fn){effects.push(fn);}};
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};new Function('require','module','exports',code)(name=>name==='react'?hooks:name==='react/jsx-runtime'?require(name):name==='@/lib/property-photo'?photos:name==='next/image'?{__esModule:true,default:'Image'}:{House:'House'},mod,mod.exports);
const all=node=>!node||typeof node!=='object'?[]:Array.isArray(node)?node.flatMap(all):[node,...all(node.props?.children)];
const render=props=>{cursor=0;effects=[];return mod.exports.PropertyThumbnail(props);};
const props={screeningId:'one',address:'Fictional property',images:{street_view:'https://img.dealmachine.com/sv/1,2.jpg'}};
let nodes=all(render(props)),img=nodes.find(n=>n.type==='Image');assert(img);assert.equal(img.props.referrerPolicy,'no-referrer');assert.equal(img.props.unoptimized,true);assert.equal(img.props.loading,'lazy');assert.match(img.props.alt,/Street view of Fictional property/);
img.props.onError();nodes=all(render(props));assert(!nodes.some(n=>n.type==='Image'));assert(nodes.some(n=>n.props.className==='property-thumbnail-empty'));
nodes=all(render({...props,images:{satellite:'https://img.dealmachine.com/sat/3,4.jpg'}}));assert(nodes.some(n=>n.type==='Image'),'New image is not held by previous failure');
state=[];const originalFetch=globalThis.fetch;let resolve;
globalThis.fetch=()=>new Promise(done=>{resolve=done;});render({...props,images:undefined});const cleanup=effects[0]();cleanup();
resolve({ok:true,json:async()=>({photo:{view:'street_view',url:props.images.street_view}})});await new Promise(done=>setImmediate(done));assert.equal(state[0],null,'Aborted old property response never updates the current thumbnail');globalThis.fetch=originalFetch;
console.log('Property thumbnail: image attributes, missing/broken fallback, changed-image recovery and stale-response abort passed');
