import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {z} from 'zod';
import {dealMachinePhoto} from '../lib/property-photo.ts';
const id='00000000-0000-4000-8000-000000000001',url='https://img.dealmachine.com/sv/1,2.jpg';
let authorized=true,rows=[],paths=[],lookups=[],cache=[];
const dependencies={NextResponse:{json:(body,opts)=>({body,...opts})},z,workAccount:async()=>{if(!authorized)throw Error();return {accountId:'account-a'};},db:async path=>{paths.push(path);return rows;},dealMachinePhoto,loadPropertyPhoto:async propertyId=>{lookups.push(propertyId);return dealMachinePhoto({street_view:url});},cachedPropertyPhoto:async(account,screening,load)=>{cache.push({account,screening});return load();}};
const source=readFileSync(new URL('../app/api/work/property-photo/route.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};new Function('require','module','exports',compiled)(()=>dependencies,mod,mod.exports);
const get=()=>mod.exports.GET(new Request('https://fixture.test/api/work/property-photo?screeningId='+id+'&propertyId=prop_other'));
let r=await get();assert.equal(r.status,404);assert.equal(lookups.length,0);
rows=[{snapshot:{raw:{data:{dm_property_id:'prop_123',images:{street_view:url}}}},result:{property:{propertyId:'prop_123'}}}];
r=await get();assert.equal(r.body.photo.url,url);assert.equal(lookups.length,0);assert(paths.every(path=>path.includes('account_id=eq.account-a')&&path.includes('state=eq.complete')));
rows[0].snapshot.raw.data.dm_property_id='prop_other';r=await get();assert.deepEqual(lookups,['prop_123'],'Only authenticated stored property ID is used');assert.deepEqual(cache,[{account:'account-a',screening:id}]);
rows[0].result.property.images={street_view:url};r=await get();assert.equal(lookups.length,1,'Stored normalized photos skip provider lookup');
authorized=false;paths=[];lookups=[];r=await get();assert.equal(r.status,503);assert.equal(paths.length,0);assert.equal(lookups.length,0);
assert.equal(r.headers['Cache-Control'],'private, no-store');
authorized=true;paths=[];lookups=[];r=await mod.exports.GET(new Request('https://fixture.test/api/work/property-photo?screeningId=invalid'));assert.equal(r.status,503);assert.equal(paths.length,0);assert.equal(lookups.length,0);
console.log('Property photo route: authenticated tenant-bound stored property ID, raw mismatch rejection, stored-first lookup, no raw data and private caching passed');
