import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {reviewReceptionForwarding as review,applyReceptionForwarding as apply} from '../lib/reception-forwarding.ts';
import {receptionTarget as target,receptionUrl} from '../lib/general-reception.ts';
import {ownerInboundTarget} from '../lib/owner-inbound-acceptance.ts';
const source=ownerInboundTarget.sourceNumber,destination=target.calledNumber,url='https://api.contiguity.com/numbers/lease/'+encodeURIComponent(source)+'/call_forwarding',now=Date.parse('2026-10-02T20:12:00Z');
const env={CONTIGUITY_API_KEY:'synthetic_contiguity_key_1234567890',CONTIGUITY_FROM:source,TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_AUTH_TOKEN:'synthetic_twilio_token_1234567890',ELEVENLABS_INBOUND_WEBHOOK_SECRET:'synthetic_existing_signing_secret_1234567890'};
const hidden='PRIVATE_PROVIDER_DATA_MUST_NOT_LEAVE_SERVER';
function fixture(options={}){
 const s={config:{account_id:target.accountId,owner_user_id:target.ownerUserId,called_number:destination,enabled:true,private_value:hidden},state:{schema_version:1,attempt:null},forwarding:{enabled:false,to:null,status:'active',estimated_completion:null},phone:{sid:'PN'+'b'.repeat(32),account_sid:env.TWILIO_ACCOUNT_SID,phone_number:destination,capabilities:{voice:true},voice_url:receptionUrl,voice_method:'POST',voice_fallback_url:'https://www.geticashx.com/api/reception/fallback',voice_fallback_method:'POST',voice_application_sid:'',trunk_sid:null},...options.state};
 const calls=[],rpcCalls=[];let clock=now;
 const receipt=()=>({id:'req_synthetic',timestamp:clock,api_version:'v2026.10.1',object:'response',data:{number:source,call_forwarding:structuredClone(s.forwarding)}});
 const deps={now:()=>clock,rpc:async(name,body)=>{rpcCalls.push({name,body});if(options.rpcThrows)throw Error(hidden);if(name==='icash_get_general_reception_config')return structuredClone(s.config);if(name==='icash_get_reception_forwarding')return structuredClone(s.state);if(name==='icash_claim_reception_forwarding'){assert.deepEqual(body.p_original_setting,{enabled:false,to:null});assert.match(body.p_nonce,/^[a-f0-9]{32}$/);assert.match(body.p_fingerprint,/^[a-f0-9]{64}$/);if(options.denyClaim||s.state.attempt)return false;s.state.attempt={state:'started',started_at:new Date(clock).toISOString(),accepted_at:null,source_number:source,destination_number:destination,provider_status:null};return true;}if(name==='icash_complete_reception_forwarding'){assert(s.state.attempt);assert.deepEqual(Object.keys(body).sort(),['p_fingerprint','p_nonce','p_result']);assert.deepEqual(Object.keys(body.p_result).sort(),['enabled','status','to']);assert.equal(body.p_result.to,destination);assert.equal(body.p_result.enabled,true);if(options.denyComplete)return false;s.state.attempt={...s.state.attempt,state:'accepted',accepted_at:new Date(clock).toISOString(),provider_status:body.p_result.status};return true;}assert.fail('Unexpected RPC '+name);},fetcher:async(targetUrl,init)=>{
  calls.push({url:targetUrl,init});assert.equal(init.cache,'no-store');assert.equal(init.redirect,'error');assert.equal(init.credentials,'omit');assert(init.signal instanceof AbortSignal);
  if(options.fetchThrows)throw Error(hidden);if(options.response){const r=options.response(targetUrl,init,s);if(r)return r;}
  if(targetUrl===url){assert.equal(init.method,'GET');assert.equal(init.body,undefined);assert.equal(init.headers.Authorization,'Bearer '+env.CONTIGUITY_API_KEY);return Response.json(receipt());}
  if(targetUrl===url+'/enable'){assert.equal(init.method,'POST');assert.equal(init.headers.Authorization,'Bearer '+env.CONTIGUITY_API_KEY);assert(s.state.attempt?.state==='started','durable claim before enable');assert.deepEqual(JSON.parse(init.body),{to:destination});if(!options.noMutation)s.forwarding={enabled:true,to:destination,status:options.queued?'queued':'active',estimated_completion:options.queued?clock+60000:null};options.afterWrite?.(s);if(options.writeThrows)throw Error(hidden);return Response.json(receipt());}
  assert.equal(targetUrl,'https://api.twilio.com/2010-04-01/Accounts/'+env.TWILIO_ACCOUNT_SID+'/IncomingPhoneNumbers.json?PhoneNumber=%2B17816093521&PageSize=2');assert.equal(init.method,'GET');assert.equal(init.body,undefined);assert.equal(init.headers.Authorization,'Basic '+Buffer.from(env.TWILIO_ACCOUNT_SID+':'+env.TWILIO_AUTH_TOKEN).toString('base64'));return Response.json({incoming_phone_numbers:[s.phone],next_page_uri:null});
 }};
 options.mutate?.(s);return {s,calls,rpcCalls,deps,clock:v=>clock=v,review:()=>review(env,deps),apply:t=>apply(env,deps,t)};
}
const writes=f=>f.calls.filter(c=>c.init.method==='POST');
const f=fixture(),r=await f.review();assert.equal(r.status,'review');assert(r.reviewToken);assert.equal(r.forwarding.enabled,false);assert.equal(r.forwardingCostVerified,false);assert.equal(r.checks.twilioRouteVerified,true);assert.equal(writes(f).length,0);assert.equal((await f.apply(r.reviewToken)).status,'active');assert.equal(writes(f).length,1);assert.equal(f.s.state.attempt.state,'accepted');assert.equal((await f.apply(r.reviewToken)).status,'blocked');assert.equal(writes(f).length,1);const active=await f.review();assert.equal(active.status,'active');assert.equal(active.reviewToken,undefined);assert.equal(active.forwardingCostVerified,false);
const queued=fixture({queued:true}),qr=await queued.review();assert.equal((await queued.apply(qr.reviewToken)).status,'pending');assert.equal(queued.s.state.attempt.provider_status,'queued');assert.equal((await queued.review()).status,'pending');assert.equal((await queued.review()).reviewToken,undefined);assert.equal(writes(queued).length,1);queued.s.forwarding={enabled:true,to:destination,status:'active',estimated_completion:null};assert.equal((await queued.review()).status,'active');assert.equal(writes(queued).length,1);
for(const mutate of [s=>s.config.account_id='foreign',s=>s.config.owner_user_id='foreign',s=>s.config.called_number='+19995550123',s=>s.config.enabled=false,s=>s.state.schema_version=2]){const x=fixture({mutate});assert.equal((await x.review()).status,'blocked');assert.equal(x.calls.length,0);}
for(const mutate of [s=>s.phone.voice_url='https://other.example',s=>s.phone.voice_fallback_url=null,s=>s.phone.voice_method='GET',s=>s.phone.voice_application_sid='AP'+'c'.repeat(32),s=>s.phone.trunk_sid='TK'+'c'.repeat(32),s=>s.phone.account_sid='AC'+'c'.repeat(32),s=>s.state.attempt={state:'started'},s=>s.state.attempt={state:'accepted'},s=>s.forwarding={enabled:true,to:'+19995550123',status:'active',estimated_completion:null},s=>s.forwarding={enabled:false,to:null,status:'queued',estimated_completion:now+60000}]){const x=fixture({mutate}),readback=await x.review();assert.equal(readback.reviewToken,undefined);assert.equal(writes(x).length,0);assert(!JSON.stringify(readback).includes('+19995550123'));}
for(const mutate of [s=>s.config.enabled=false,s=>s.config.private_value='changed',s=>s.phone.voice_url='https://other.example',s=>s.state.attempt={state:'started'},s=>s.forwarding={enabled:true,to:destination,status:'active',estimated_completion:null}]){const x=fixture(),xr=await x.review();mutate(x.s);assert.equal((await x.apply(xr.reviewToken)).status,'blocked');assert.equal(writes(x).length,0);}
for(const bad of ['',null,'invalid',r.reviewToken+'x']){const x=fixture();assert.equal((await x.apply(bad)).status,'blocked');assert.equal(writes(x).length,0);}const expired=fixture(),er=await expired.review();expired.clock(now+120001);assert.equal((await expired.apply(er.reviewToken)).status,'blocked');assert.equal(writes(expired).length,0);
for(const options of [{denyClaim:true},{rpcThrows:true},{fetchThrows:true}]){const x=fixture(options),xr=await x.review();if(xr.reviewToken)assert.equal((await x.apply(xr.reviewToken)).status,'blocked');assert.equal(writes(x).length,0);}
for(const options of [{writeThrows:true},{denyComplete:true},{noMutation:true},{afterWrite:s=>s.phone.voice_url='https://drift.example'},{afterWrite:s=>s.config.private_value='drift'}]){const x=fixture(options),xr=await x.review();assert.equal((await x.apply(xr.reviewToken)).status,'outcome_unknown');assert.equal(x.s.state.attempt.state,'started');assert.equal(writes(x).length,1);assert.equal((await x.apply(xr.reviewToken)).status,'blocked');assert.equal(writes(x).length,1);assert.equal((await x.review()).reviewToken,undefined);}
for(const status of [400,401,403,402,500]){const x=fixture({response:(u,init)=>u===url+'/enable'?Response.json({object:'error',data:{message:hidden}},{status}):undefined}),xr=await x.review(),out=await x.apply(xr.reviewToken);assert.equal(out.status,'outcome_unknown');assert.equal(writes(x).length,1);assert.equal(x.s.state.attempt.state,'started');assert(!JSON.stringify(out).includes(hidden));if(status===402)assert(out.message.includes('Separate approval'));assert.equal(x.calls.at(-1).url,url+'/enable');}
for(const field of ['fee','price','cost','amount','currency','subscription','payment_required','terms_url','credit_purchase']){const x=fixture({response:u=>u===url?Response.json({object:'response',data:{number:source,call_forwarding:{enabled:false,to:null,status:'active',estimated_completion:null},[field]:hidden}}):undefined}),out=await x.review();assert.equal(out.status,'blocked');assert(out.message.includes('Separate approval'));assert.equal(writes(x).length,0);assert(!JSON.stringify(out).includes(hidden));}
for(const patch of [{CONTIGUITY_FROM:'+19995550123'},{CONTIGUITY_API_KEY:'bad\nkey'},{ELEVENLABS_INBOUND_WEBHOOK_SECRET:''},{TWILIO_ACCOUNT_SID:'foreign'}]){const x=fixture();assert.equal((await review({...env,...patch},x.deps)).status,'blocked');assert.equal(x.calls.length,0);assert.equal(x.rpcCalls.length,0);}
for(const text of [JSON.stringify(r),JSON.stringify(active),JSON.stringify(await queued.review())])for(const value of [hidden,env.CONTIGUITY_API_KEY,env.TWILIO_AUTH_TOKEN,env.ELEVENLABS_INBOUND_WEBHOOK_SECRET])assert(!text.includes(value));
const sourceText=readFileSync('lib/reception-forwarding.ts','utf8');for(const prohibited of ['process.env','console.','/disable','/Calls.json','/Events.json','/numbers/lease/new','method:\'PATCH\''])assert(!sourceText.includes(prohibited));
console.log('Reception forwarding: fixed signed review, existing credentials, verified destination route, durable one-shot claim, exact enable/readback, queued honesty and no automatic replay/payment');

const mixed=fixture({response:(u,init,s)=>{if(u!==url+'/enable')return; s.forwarding={enabled:true,to:destination,status:'queued',estimated_completion:now+60000};return Response.json({object:'response',data:{number:source,call_forwarding:{enabled:true,to:destination,status:'active',estimated_completion:null}}});}}),mr=await mixed.review();assert.equal((await mixed.apply(mr.reviewToken)).status,'pending');assert.equal(mixed.s.state.attempt.provider_status,'active','audit preserves actual POST acknowledgement, not merged GET status');
