import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {readReceptionSetupAnalytics as read} from '../lib/reception-setup-analytics.ts';
import {receptionTarget as target} from '../lib/general-reception.ts';
const key='SYNTHETIC_EXISTING_ELEVENLABS_KEY',hidden='PRIVATE_ROW_VALUE_MUST_NOT_LEAVE_SERVER';
const start=Date.parse('2026-10-02T18:08:20Z'),end=Date.parse('2026-10-02T18:09:00Z'),path=`/v1/convai/agents/${target.agentId}/branches`;
function fixture(options={}){const calls=[],rpcCalls=[],config={account_id:target.accountId,owner_user_id:target.ownerUserId,called_number:target.calledNumber,enabled:false,...options.config},state={schema_version:1,attempts:{prepare_branch:{state:'started',started_at:'2026-10-02T18:08:33.000Z',finished_at:null}},...options.state};
 const deps={rpc:async(name,body)=>{rpcCalls.push(name);assert.equal(body,undefined);if(options.rpcThrows)throw Error(hidden);if(name==='icash_get_general_reception_config')return config;if(name==='icash_get_reception_setup')return state;assert.fail('Unexpected RPC');},fetcher:async(url,request)=>{calls.push({url,request});assert.equal(url,'https://api.us.elevenlabs.io/v1/workspace/analytics/requests');assert.equal(request.method,'POST');assert.equal(request.headers['xi-api-key'],key);assert.deepEqual(JSON.parse(request.body),{start_time:start,end_time:end,limit:20,sort:'asc',search:path});assert.equal(request.cache,'no-store');assert.equal(request.redirect,'error');assert.equal(request.credentials,'omit');assert(request.signal instanceof AbortSignal);if(options.fetchThrows)throw Error(hidden);return options.response?.()??Response.json(options.data??{columns:['unsupported_column'],column_types:['String'],column_units:[null],rows:[[hidden]]});}};return {calls,rpcCalls,deps};}
const f=fixture(),r=await read({ELEVENLABS_API_KEY:key},f.deps);assert.deepEqual(r,{status:'unavailable',schemaColumns:['unsupported_column']});assert.equal(f.calls.length,1);assert.deepEqual(f.rpcCalls.sort(),['icash_get_general_reception_config','icash_get_reception_setup']);assert(!JSON.stringify(r).includes(hidden));assert(!JSON.stringify(r).includes(key));
for(const options of [{config:{enabled:true}},{config:{account_id:'foreign'}},{config:{owner_user_id:'foreign'}},{config:{called_number:'foreign'}},{state:{schema_version:2}},{state:{attempts:{}}},{state:{attempts:{prepare_branch:{state:'verified',started_at:'2026-10-02T18:08:33Z',finished_at:null}}}},{state:{attempts:{prepare_branch:{state:'started',started_at:'2026-10-02T18:09:00Z',finished_at:null}}}},{state:{attempts:{prepare_branch:{state:'started',started_at:'2026-10-02T18:08:19Z',finished_at:null}}}},{state:{attempts:{prepare_branch:{state:'started',started_at:'bad',finished_at:null}}}},{state:{attempts:{prepare_branch:{state:'started',started_at:'2026-10-02T18:08:33Z',finished_at:'2026-10-02T18:08:35Z'}}}},{rpcThrows:true}]){const f=fixture(options);assert.deepEqual(await read({ELEVENLABS_API_KEY:key},f.deps),{status:'unavailable'});assert.equal(f.calls.length,0);}
for(const options of [{fetchThrows:true},{response:()=>new Response(hidden,{status:403})},{response:()=>new Response(hidden,{status:401})},{response:()=>new Response(hidden,{status:500})},{response:()=>new Response(hidden,{headers:{'content-type':'text/html'}})},{response:()=>Response.json({},{headers:{'content-length':'9999999'}})},{data:{columns:['unknown'],rows:[],column_types:[],column_units:[]}},{data:{columns:['secret\nvalue'],rows:[[hidden]],column_types:['String'],column_units:[null]}},{data:{columns:['unknown','unknown'],rows:[[hidden,hidden]],column_types:['String','String'],column_units:[null,null]}}]){const f=fixture(options);assert.deepEqual(await read({ELEVENLABS_API_KEY:key},f.deps),{status:'unavailable'});assert.equal(f.calls.length,1);}
const table=(rows)=>({columns:['timestamp','method','path','status_code','private_payload'],column_types:['DateTime','String','String','Int','String'],column_units:['ms',null,null,null,null],rows});
for(const status of [200,400,422,500]){const f=fixture({data:table([[start+13000,'POST',path,status,hidden]])});assert.deepEqual(await read({ELEVENLABS_API_KEY:key},f.deps),{status:'matched',httpStatus:status,method:'POST',path});}
const duplicate=fixture({data:table([[start+13000,'POST',path,422,hidden],[start+14000,'POST',path,422,hidden]])});assert.deepEqual(await read({ELEVENLABS_API_KEY:key},duplicate.deps),{status:'ambiguous'});
for(const row of [['2026-10-02T18:08:33Z','GET',path,200,hidden],['2026-10-02T18:08:33Z','POST',path+'?unexpected=1',422,hidden],['2026-10-02T18:08:33Z','POST',path.replace(target.agentId,'agent_foreign'),422,hidden],['2026-10-02T18:09:00Z','POST',path,422,hidden],['invalid','POST',path,422,hidden],['2026-10-02T18:08:33Z','POST',path,'422',hidden],[0,'POST',path,422,hidden]]){const f=fixture({data:table([row])});assert.deepEqual(await read({ELEVENLABS_API_KEY:key},f.deps),{status:'unavailable'});}
const truncated=fixture({data:table(Array.from({length:20},()=>[start+13000,'POST',path,422,hidden]))});assert.deepEqual(await read({ELEVENLABS_API_KEY:key},truncated.deps),{status:'ambiguous'});
const wrongType=table([[start+13000,'POST',path,422,hidden]]);wrongType.column_types[3]='String';assert.deepEqual(await read({ELEVENLABS_API_KEY:key},fixture({data:wrongType}).deps),{status:'unavailable',schemaColumns:wrongType.columns});
const numeric=table([[start+13000,'POST',path,422,hidden]]);numeric.column_units[0]='ms';assert.equal((await read({ELEVENLABS_API_KEY:key},fixture({data:numeric}).deps)).status,'matched');
for(const env of [{},{ELEVENLABS_API_KEY:'bad\nvalue'}]){const f=fixture();assert.deepEqual(await read(env,f.deps),{status:'unavailable'});assert.equal(f.calls.length,0);assert.equal(f.rpcCalls.length,0);}
const source=readFileSync('lib/reception-setup-analytics.ts','utf8');assert(!source.includes('process.env'));assert(!source.includes('console.'));assert(!source.includes("method:'PATCH'"));assert(!source.includes("method:'DELETE'"));assert(!source.includes('icash_claim_'));assert(!source.includes('icash_complete_'));
console.log('Fixed reception analytics: single read-only query, exact held attempt/time/owner gates, no retries on403, bounded schema-only output and row/credential redaction');

assert.deepEqual(await read({ELEVENLABS_API_KEY:key},fixture({data:table([[start+1000,'POST',path,422,hidden]])}).deps),{status:'unavailable'});
assert.deepEqual(await read({ELEVENLABS_API_KEY:key},fixture({data:{columns:['Status code','Request.path'],column_types:['Int','String'],column_units:[null,null],rows:[[422,hidden]]}}).deps),{status:'unavailable',schemaColumns:['Status code','Request.path']});
