import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {reviewReceptionSetup as review,applyReceptionSetup as apply,receptionBranchName,receptionBranchBody} from '../lib/reception-setup.ts';
import {receptionTarget as target,receptionUrl,receptionGreeting,receptionPrompt,inspectReceptionAgent} from '../lib/general-reception.ts';
const owner='agtbrch_8901m3sw5tn6fvkae4d334netswh',mainId='agtbrch_main',branchId='agtbrch_reception',origin='https://api.us.elevenlabs.io',base=origin+'/v1/convai/agents/'+target.agentId;
const env={ELEVENLABS_API_KEY:'synthetic_provider_key_123456789',ELEVENLABS_INBOUND_WEBHOOK_SECRET:'synthetic_existing_review_secret_123456789',TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_AUTH_TOKEN:'synthetic_twilio_token_123456789',RECEPTION_ENABLED:'true'};
const now=Date.now();
const normalProfile={call_profile:'normal',rate_id:'e827a7c9-8648-4999-885c-f136fd07100e',max_duration_seconds:600,customer_charge_cap_cents:430};
const quickProfile={call_profile:'owner_quick_test',rate_id:'f93ace00-83fc-4d09-a37c-6d9d9f0a38f0',max_duration_seconds:60,customer_charge_cap_cents:65,owner_quick_test_enabled:true,owner_quick_test_approval_reference:'explicit-fixture-only-approval',owner_caller_hash:'a'.repeat(64)};
function fixture(options={}){
 const s={config:{...normalProfile,account_id:target.accountId,owner_user_id:target.ownerUserId,called_number:target.calledNumber,enabled:false,receipt_mode:'provider_readback'},state:{schema_version:1,attempts:{},original_phone:null,route_started_at:null},main:{agent_id:target.agentId,branch_id:mainId,main_branch_id:mainId,version_id:'agtvrsn_main',procedures:{},conversation_config:{agent:{prompt:{prompt:'private main prompt',llm:'gpt-4o-mini',tool_ids:['private-tool'],built_in_tools:{transfer_to_number:{type:'system'},memory_entry_create:{type:'system'}}}},tts:{voice_id:'syntheticVoice',model_id:'eleven_turbo_v2'}},platform_settings:{auth:{enable_auth:true},privacy:{record_voice:false},call_limits:{agent_concurrency_limit:1,bursting_enabled:false},queueing_config:{enabled:false}}},branch:null,branches:[{id:mainId,name:'Main',agent_id:target.agentId,current_live_percentage:100,draft_exists:false,is_archived:false},{id:owner,name:'Owner audio',agent_id:target.agentId,current_live_percentage:0,draft_exists:false,is_archived:false}],phone:{sid:'PN'+'b'.repeat(32),account_sid:env.TWILIO_ACCOUNT_SID,phone_number:target.calledNumber,capabilities:{voice:true},voice_url:'https://existing.example/inbound',voice_method:'POST',voice_fallback_url:null,voice_fallback_method:'POST',voice_application_sid:'',trunk_sid:null,sms_url:'https://existing.example/sms',friendly_name:'private phone label'}};
 s.owner={...structuredClone(s.main),branch_id:owner,version_id:'agtvrsn_owner'};
 const calls=[],rpcCalls=[];const deps={now:()=>now,rpc:async(name,b)=>{
  rpcCalls.push({name,b});if(options.rpcThrows)throw Error('private database error');
  if(name==='icash_get_reception_setup')return structuredClone(s.state);
  if(name==='icash_get_general_reception_config')return structuredClone(s.config);
  if(name==='icash_claim_reception_setup'){if(options.denyClaim||s.state.attempts[b.p_action])return false;s.state.attempts[b.p_action]={state:'started',started_at:new Date(now).toISOString()};if(b.p_action==='route'){s.state.original_phone=structuredClone(b.p_original_phone);s.state.route_started_at=new Date(now-31000).toISOString();}return true;}
  if(name==='icash_complete_reception_setup'){if(options.denyComplete)return false;s.state.attempts[b.p_action].state='verified';if(b.p_action.endsWith('_branch'))Object.assign(s.config,b.p_result,{agent_id:target.agentId});return true;}
  assert.fail('unexpected RPC '+name);
 },fetcher:async(url,init={})=>{
  calls.push({url,init});assert.equal(init.cache,'no-store');assert.equal(init.redirect,'error');assert.equal(init.credentials,'omit');assert(init.signal instanceof AbortSignal);
  if(options.fetchThrows)throw Error('private provider error');
  if(init.method!=='GET'){
   assert(Object.values(s.state.attempts).some(a=>a.state==='started'),'durable claim precedes provider write');
   if(options.beforeWrite)await options.beforeWrite(s);
   if(url.includes('api.twilio.com')){
    assert(url.endsWith('/IncomingPhoneNumbers/'+s.phone.sid+'.json'));assert.equal(init.method,'POST');assert(s.state.original_phone,'durable original before URL mutation');const p=new URLSearchParams(init.body);assert.deepEqual([...p.keys()],['VoiceUrl','VoiceMethod','VoiceFallbackUrl','VoiceFallbackMethod']);
    if(options.noMutation!==true)Object.assign(s.phone,{voice_url:p.get('VoiceUrl')||null,voice_method:p.get('VoiceMethod'),voice_fallback_url:p.get('VoiceFallbackUrl')||null,voice_fallback_method:p.get('VoiceFallbackMethod')});
   }else{
    assert(url===base+'/branches'||url===base+'?branch_id='+branchId);const b=JSON.parse(init.body);for(const k of ['auth','privacy','call_limits','queueing_config'])assert(!(k in b.platform_settings),'never write shared/unverified platform fields');assert.equal(b.conversation_config.agent.first_message,receptionGreeting);assert.equal(b.conversation_config.agent.prompt.prompt,receptionPrompt);assert.equal(b.conversation_config.agent.prompt.max_tokens,120);assert.equal(b.conversation_config.conversation.max_duration_seconds,s.config.max_duration_seconds);assert.deepEqual(b.conversation_config.agent.prompt.tool_ids,[]);assert.equal(b.conversation_config.agent.prompt.built_in_tools.transfer_to_number,null);assert.equal(b.conversation_config.agent.prompt.built_in_tools.memory_entry_create,null);assert(Object.entries(b.conversation_config.agent.prompt.built_in_tools).every(([k,v])=>k==='end_call'||v===null));assert.deepEqual(b.conversation_config.agent.prompt.built_in_tools.end_call,{type:'system',name:'end_call',description:'',params:{system_tool_type:'end_call'}});assert.deepEqual(b.conversation_config.agent.prompt.native_mcp_server_ids,[]);assert.deepEqual(b.platform_settings.workspace_overrides.webhooks.events,[]);assert.equal(b.platform_settings.workspace_overrides.webhooks.post_call_webhook_id,null);
    s.branch={...structuredClone(s.main),...b,platform_settings:{...structuredClone(s.main.platform_settings),...b.platform_settings},branch_id:branchId,version_id:'agtvrsn_reception'+(init.method==='PATCH'?'2':'1')};
    if(init.method==='POST'){assert.equal(b.parent_version_id,s.main.version_id);assert.equal(b.include_draft,false);assert.equal(b.name,receptionBranchName);s.branches.push({id:branchId,name:receptionBranchName,agent_id:target.agentId,current_live_percentage:0,draft_exists:false,is_archived:false});}
   }
   options.afterWrite?.(s);if(options.writeThrows)throw Error('private uncertain write');
   return Response.json(url.includes('api.twilio.com')?s.phone:{created_branch_id:branchId,created_version_id:s.branch.version_id});
  }
  if(options.getResponse){const override=options.getResponse(url,s);if(override)return override;}
  if(url.includes('api.twilio.com'))return Response.json({incoming_phone_numbers:[s.phone],next_page_uri:null});
  if(url===base)return Response.json(s.main);
  if(url===base+'?branch_id='+owner)return Response.json(s.owner);
  if(url===base+'?branch_id='+branchId)return Response.json(s.branch);
  if(url===base+'/branches?include_archived=true&limit=100')return Response.json({results:s.branches,meta:{total:s.branches.length}});
  if(url===origin+'/v1/workspace/webhooks?include_usages=false')return Response.json({webhooks:[]});
  assert.fail('unexpected provider URL '+url);
 }};
 options.mutate?.(s);return {s,calls,rpcCalls,deps,review:()=>review(env,deps),apply:(action,token)=>apply(env,deps,action,token)};
}
const token=(r,action)=>r.actions.find(x=>x.action===action)?.reviewToken;
const writes=x=>x.calls.filter(c=>c.init.method!=='GET');
const x=fixture(),initial=await x.review();assert.equal(initial.status,'review');assert(token(initial,'prepare_branch'));assert.equal(writes(x).length,0);assert.equal(initial.checks.providerReadbackMode,true);assert.deepEqual(initial.profile,{name:'normal',maxDurationSeconds:600,customerChargeCapCents:430});assert(!initial.blockers.some(b=>b.includes('postcall')));
const originalMain=structuredClone(x.s.main),originalOwner=structuredClone(x.s.owner),originalPhone=structuredClone(x.s.phone);
assert.equal((await x.apply('prepare_branch',token(initial,'prepare_branch'))).status,'verified');assert.equal(writes(x).length,1);assert.deepEqual(x.s.main,originalMain);assert.deepEqual(x.s.owner,originalOwner);assert.deepEqual(x.s.phone,originalPhone);assert.equal(x.s.config.enabled,false);assert(inspectReceptionAgent(x.s.config,x.s.branch,x.s.branches.at(-1)).safe);
assert.equal((await x.apply('prepare_branch',token(initial,'prepare_branch'))).status,'blocked');assert.equal(writes(x).length,1);
let ready=await x.review();assert.equal(ready.checks.dedicatedBranch,true);assert(token(ready,'configure_branch'));assert(!token(ready,'route'));
assert.equal((await x.apply('configure_branch',token(ready,'configure_branch'))).status,'verified');
x.s.config.enabled=true;ready=await x.review();assert(token(ready,'route'));assert(!token(ready,'configure_branch'));
assert.equal((await x.apply('route',token(ready,'route'))).status,'verified');assert.equal(x.s.phone.voice_url,receptionUrl);assert.deepEqual(x.s.state.original_phone,originalPhone);assert.equal(x.s.phone.sms_url,originalPhone.sms_url);
ready=await x.review();assert(token(ready,'restore'));assert(!token(ready,'route'));assert.equal((await x.apply('restore',token(ready,'restore'))).status,'verified');assert.deepEqual(x.s.phone,originalPhone);
for(const broken of ['outage','main_drift','branch_missing']){const f=fixture(),r=await f.review();await f.apply('prepare_branch',token(r,'prepare_branch'));f.s.config.enabled=true;await f.apply('route',token(await f.review(),'route'));const fetcher=f.deps.fetcher;f.deps.fetcher=async(url,init)=>{if(url.startsWith(origin)){if(broken==='outage')throw Error('ElevenLabs outage');if(broken==='main_drift'&&url===base)return Response.json({...f.s.main,branch_id:'agtbrch_wrong'});if(broken==='branch_missing'&&url===base+'?branch_id='+branchId)return new Response(null,{status:404});}return fetcher(url,init);};const restoreReview=await f.review();assert(token(restoreReview,'restore'),'restore must survive '+broken);const count=f.calls.length;assert.equal((await f.apply('restore',token(restoreReview,'restore'))).status,'verified');assert(f.calls.slice(count).every(c=>!c.url.startsWith(origin)),'restore itself is Twilio-only');assert.deepEqual(f.s.phone,f.s.state.original_phone);}
for(const options of [{mutate:s=>s.main.platform_settings.privacy.record_voice=true},{mutate:s=>s.main.platform_settings.auth.enable_auth=false},{mutate:s=>s.main.platform_settings.call_limits.agent_concurrency_limit=2},{mutate:s=>s.main.platform_settings.queueing_config.enabled=true},{denyClaim:true},{rpcThrows:true},{mutate:s=>s.main.procedures={tool:'unsafe'}},{mutate:s=>s.branches[0].current_live_percentage=99},{mutate:s=>s.owner.branch_id='agtbrch_foreign'},{mutate:s=>s.branches.push(s.branches[0])}]){const f=fixture(options),r=await f.review();const t=token(r,'prepare_branch');if(t)assert.equal((await f.apply('prepare_branch',t)).status,'blocked');assert.equal(writes(f).length,0);}
for(const mutate of [s=>s.main.version_id='agtvrsn_changed',s=>s.phone.sms_url='https://changed.example',s=>s.main.conversation_config.agent.prompt.prompt='changed']){const f=fixture(),r=await f.review();mutate(f.s);assert.equal((await f.apply('prepare_branch',token(r,'prepare_branch'))).status,'blocked');assert.equal(writes(f).length,0);}
for(const options of [{writeThrows:true},{denyComplete:true},{afterWrite:s=>s.main.version_id='agtvrsn_changed'},{afterWrite:s=>s.branch.platform_settings.privacy.record_voice=true},{afterWrite:s=>s.branch.branch_id=owner},{afterWrite:s=>s.phone.sms_url='https://changed.example'}]){const f=fixture(options),r=await f.review();assert.equal((await f.apply('prepare_branch',token(r,'prepare_branch'))).status,'outcome_unknown');assert.equal(writes(f).length,1);assert.equal((await f.apply('prepare_branch',token(r,'prepare_branch'))).status,'blocked');assert.equal(writes(f).length,1);assert(!token(await f.review(),'prepare_branch'));}
const forged=fixture(),r=await forged.review(),t=token(r,'prepare_branch');for(const bad of ['',null,t+'x',t.slice(0,-5)+'12345']){assert.equal((await forged.apply('prepare_branch',bad)).status,'blocked');}assert.equal(writes(forged).length,0);
assert.equal((await apply(env,{...forged.deps,now:()=>now+120001},'prepare_branch',t)).status,'blocked');assert.equal(writes(forged).length,0);
assert.equal((await apply(env,forged.deps,'route',t)).status,'blocked');
for(const mutate of [s=>s.phone.voice_application_sid='AP'+'c'.repeat(32),s=>s.phone.trunk_sid='TK'+'c'.repeat(32),s=>s.config.config_hash='0'.repeat(64),s=>s.config.receipt_mode='webhook']){const f=fixture(),r=await f.review();await f.apply('prepare_branch',token(r,'prepare_branch'));f.s.config.enabled=true;mutate(f.s);assert(!token(await f.review(),'route'));}
for(const e of [{},{...env,ELEVENLABS_INBOUND_WEBHOOK_SECRET:'short'},{...env,ELEVENLABS_API_KEY:'bad\nkey'}]){const f=fixture();assert.equal((await review(e,f.deps)).status,'blocked');assert.equal(writes(f).length,0);}
for(const text of [JSON.stringify(initial),JSON.stringify(await x.review())])for(const secret of [env.ELEVENLABS_API_KEY,env.TWILIO_AUTH_TOKEN,env.ELEVENLABS_INBOUND_WEBHOOK_SECRET,'private main prompt','private phone label'])assert(!text.includes(secret));
const body=receptionBranchBody(originalMain,null,normalProfile);assert.equal(body.conversation_config.conversation.max_duration_seconds,600);const shortBody=receptionBranchBody(originalMain,null,quickProfile);assert.equal(shortBody.conversation_config.conversation.max_duration_seconds,60);assert.throws(()=>receptionBranchBody(originalMain,null,{...quickProfile,owner_quick_test_enabled:false}));assert.equal(body.platform_settings.call_limits,undefined);assert.equal(body.platform_settings.auth,undefined);assert.equal(body.platform_settings.privacy,undefined);assert.equal(body.platform_settings.queueing_config,undefined);assert.equal(body.platform_settings.overrides.enable_conversation_initiation_client_data_from_webhook,false);assert.equal(body.platform_settings.overrides.enable_procedure_ids_from_client,false);
// Profiles are selected only by separately approved configuration, never by setup input.
for(const selected of [normalProfile,quickProfile]){const f=fixture({mutate:s=>Object.assign(s.config,selected)}),r=await f.review();assert(token(r,'prepare_branch'));assert.equal(r.profile.maxDurationSeconds,selected.max_duration_seconds);assert.equal(r.profile.customerChargeCapCents,selected.customer_charge_cap_cents);for(const key of ['owner_caller_hash','owner_quick_test_approval_reference']){assert(!JSON.stringify(r).includes(key));if(selected[key])assert(!JSON.stringify(r).includes(selected[key]));}assert.equal((await f.apply('prepare_branch',token(r,'prepare_branch'))).status,'verified');assert.equal(f.s.branch.conversation_config.conversation.max_duration_seconds,selected.max_duration_seconds);assert.equal(f.s.config.max_duration_seconds,selected.max_duration_seconds);const complete=f.rpcCalls.find(x=>x.name==='icash_complete_reception_setup').b.p_result;assert.deepEqual(Object.keys(complete).sort(),['branch_id','call_profile','config_hash','customer_charge_cap_cents','max_duration_seconds','rate_id','reviewed_version_id']);for(const key of ['call_profile','rate_id','max_duration_seconds','customer_charge_cap_cents'])assert.equal(complete[key],selected[key]);}
for(const fields of [{call_profile:undefined},{call_profile:'arbitrary'},{max_duration_seconds:60},{customer_charge_cap_cents:65},{rate_id:quickProfile.rate_id},{...quickProfile,owner_quick_test_enabled:false},{...quickProfile,owner_quick_test_approval_reference:''},{...quickProfile,owner_caller_hash:'invalid'}]){const f=fixture({mutate:s=>Object.assign(s.config,fields)}),r=await f.review();assert.equal(r.status,'blocked');assert(r.blockers.includes('profile_configuration_invalid'));assert.equal(writes(f).length,0);}
const changed=fixture(),cr=await changed.review();Object.assign(changed.s.config,quickProfile);assert.equal((await changed.apply('prepare_branch',token(cr,'prepare_branch'))).status,'blocked');assert.equal(writes(changed).length,0);
const source=readFileSync('lib/reception-setup.ts','utf8');assert(!source.includes('process.env'));assert(!source.includes('/twilio/register-call'));assert(!source.includes('/v1/convai/secrets'));assert(!source.includes('console.'));
console.log('Reception setup: fixed target, owner-review signatures, durable claims/snapshot, disabled preparation, provider readback, preservation/drift checks, exact restore, no calls or credentials');
