import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {readReceptionCarrierDiagnostic as read} from '../lib/reception-carrier-diagnostic.ts';
import {receptionTarget as target} from '../lib/general-reception.ts';
import {ownerInboundTarget} from '../lib/owner-inbound-acceptance.ts';
const env={TWILIO_ACCOUNT_SID:'AC'+'a'.repeat(32),TWILIO_AUTH_TOKEN:'synthetic_existing_twilio_token_12345'},sid='CA'+'b'.repeat(32),now=Date.parse('2026-10-02T19:55:00Z'),base='https://api.twilio.com/2010-04-01/Accounts/'+env.TWILIO_ACCOUNT_SID,hidden='PRIVATE_RESPONSE_DATA_MUST_NOT_LEAVE_SERVER';
const call=(change={})=>({sid,account_sid:env.TWILIO_ACCOUNT_SID,to:target.calledNumber,from:ownerInboundTarget.ownerPhone,status:'completed',date_created:'Fri, 02 Oct 2026 19:51:48 +0000',start_time:'Fri, 02 Oct 2026 19:51:49 +0000',duration:'60',forwarded_from:hidden,uri:hidden,price:hidden,...change});
function fixture(options={}){const requests=[],rpcCalls=[],config={account_id:target.accountId,owner_user_id:target.ownerUserId,called_number:target.calledNumber,...options.config};const deps={now:()=>options.now??now,rpc:async(name,body)=>{rpcCalls.push(name);assert.equal(body,undefined);assert.equal(name,'icash_get_general_reception_config');if(options.rpcThrows)throw Error(hidden);return config;},fetcher:async(url,request)=>{requests.push({url,request});assert.equal(request.method,'GET');assert.equal(request.cache,'no-store');assert.equal(request.redirect,'error');assert.equal(request.credentials,'omit');assert(request.signal instanceof AbortSignal);assert.equal(request.headers.Authorization,'Basic '+Buffer.from(env.TWILIO_ACCOUNT_SID+':'+env.TWILIO_AUTH_TOKEN).toString('base64'));assert.equal(request.body,undefined);if(options.fetchThrows)throw Error(hidden);if(options.response){const response=options.response(url,requests.length);if(response)return response;}if(url===base+'/Calls.json?To=%2B17816093521&PageSize=20')return Response.json({calls:options.calls??[call()],next_page_uri:options.next??null});assert.match(url,new RegExp('^'+base.replaceAll('.','\\.')+'/Calls/CA[0-9a-f]{32}/Notifications\\.json\\?PageSize=20$'));const call_sid=url.match(/\/Calls\/(CA[a-f0-9]{32})\//)[1];return Response.json({notifications:options.notes??[{account_sid:env.TWILIO_ACCOUNT_SID,call_sid,error_code:'11200',message_text:hidden,request_url:hidden,response_body:hidden},{account_sid:env.TWILIO_ACCOUNT_SID,call_sid,error_code:'11200'}],next_page_uri:options.noteNext??null});}};return {deps,requests,rpcCalls};}
const f=fixture(),result=await read(env,f.deps);assert.deepEqual(result,{status:'matched',complete:true,calls:[{sid,status:'completed',createdAt:'2026-10-02T19:51:48.000Z',startTime:'2026-10-02T19:51:49.000Z',durationSeconds:60,ownerCallerMatched:true,errorCodes:[11200]}]});assert.equal(f.requests.length,2);assert.deepEqual(f.rpcCalls,['icash_get_general_reception_config']);
for(const value of [env.TWILIO_AUTH_TOKEN,env.TWILIO_ACCOUNT_SID,ownerInboundTarget.ownerPhone,target.calledNumber,hidden,'https:'])assert(!JSON.stringify(result).includes(value));
for(const status of ['queued','ringing','in-progress','busy','failed','no-answer','canceled'])for(const empty of [null,'']){const f=fixture({calls:[call({status,start_time:empty,duration:empty})],notes:[]}),r=await read(env,f.deps);assert.equal(r.status,'matched');assert.equal(r.calls[0].startTime,null);assert.equal(r.calls[0].durationSeconds,null);}
{const f=fixture({calls:[call({from:'+19995550123'})],notes:[]}),r=await read(env,f.deps);assert.equal(r.calls[0].ownerCallerMatched,false);assert(!JSON.stringify(r).includes('+19995550123'));}
for(const date_created of ['2026-10-02T19:40:44Z','2026-10-02T19:55:01Z']){const f=fixture({calls:[call({date_created})]});assert.deepEqual(await read(env,f.deps),{status:'no_calls',complete:true,calls:[]});assert.equal(f.requests.length,1);}
for(const next of [null,'https://untrusted.example/page']){const f=fixture({calls:[],next});assert.deepEqual(await read(env,f.deps),{status:'no_calls',complete:next===null,calls:[]});assert.equal(f.requests.length,1);}
{const f=fixture({noteNext:'https://untrusted.example/page'}),r=await read(env,f.deps);assert.equal(r.complete,false);assert.equal(f.requests.length,2);}
{const calls=Array.from({length:8},(_,i)=>call({sid:'CA'+i.toString(16).padStart(32,'0')})),f=fixture({calls,notes:[]}),r=await read(env,f.deps);assert.equal(r.status,'matched');assert.equal(r.complete,false);assert.equal(r.calls.length,5);assert.equal(f.requests.length,6);}
for(const config of [{account_id:'foreign'},{owner_user_id:'foreign'},{called_number:'+19995550123'}]){const f=fixture({config});assert.deepEqual(await read(env,f.deps),{status:'unavailable',complete:false,calls:[]});assert.equal(f.requests.length,0);}
for(const badEnv of [{},{...env,TWILIO_ACCOUNT_SID:'AC/../../Calls'},{...env,TWILIO_AUTH_TOKEN:'bad\nvalue'},{...env,TWILIO_AUTH_TOKEN:'short'}]){const f=fixture();assert.equal((await read(badEnv,f.deps)).status,'unavailable');assert.equal(f.rpcCalls.length,0);assert.equal(f.requests.length,0);}
for(const patch of [{sid:'CA/../secret'},{account_sid:'AC'+'c'.repeat(32)},{to:'+19995550123'},{status:hidden},{date_created:'invalid'},{date_created:'2026-10-02 19:51:48'},{start_time:'2026-10-02T19:40:00Z'},{start_time:'2026-10-02T20:00:00Z'},{duration:'-1'},{duration:'12.5'},{duration:86401}]){const f=fixture({calls:[call(patch)]});assert.equal((await read(env,f.deps)).status,'unavailable');assert.equal(f.requests.length,1);}
for(const calls of [[call(),call()],Array.from({length:21},()=>call()),{}]){const f=fixture({calls});assert.equal((await read(env,f.deps)).status,'unavailable');assert.equal(f.requests.length,1);}
for(const notes of [[{account_sid:env.TWILIO_ACCOUNT_SID,call_sid:'CA'+'c'.repeat(32),error_code:'11200'}],[{account_sid:'AC'+'c'.repeat(32),call_sid:sid,error_code:'11200'}],Array.from({length:21},()=>({})),{}]){const f=fixture({notes});assert.equal((await read(env,f.deps)).status,'unavailable');}
for(const code of [hidden,null,'1234','01234','123456','11200<script>',NaN]){const f=fixture({notes:[{account_sid:env.TWILIO_ACCOUNT_SID,call_sid:sid,error_code:code}]}),r=await read(env,f.deps);assert.equal(r.status,'matched');assert.equal(r.complete,false);assert.deepEqual(r.calls[0].errorCodes,[]);assert(!JSON.stringify(r).includes(hidden));}
for(const at of [1,2])for(const status of [401,403,500]){const f=fixture({calls:[call(),call({sid:'CA'+'c'.repeat(32)})],response:(_,n)=>n===at?Response.json({message:hidden},{status}):undefined});assert.deepEqual(await read(env,f.deps),{status:'unavailable',complete:false,calls:[]});assert.equal(f.requests.length,at,'no retry or continuation after failure');}
for(const response of [()=>new Response('invalid',{headers:{'content-type':'application/json'}}),()=>new Response(hidden,{headers:{'content-type':'text/html'}}),()=>Response.json({calls:[],padding:'x'.repeat(262145)}),()=>Response.json([])]){const f=fixture({response});assert.equal((await read(env,f.deps)).status,'unavailable');assert.equal(f.requests.length,1);}
for(const options of [{rpcThrows:true},{fetchThrows:true},{now:Date.parse('2026-10-02T19:40:00Z')}])assert.equal((await read(env,fixture(options).deps)).status,'unavailable');
const source=readFileSync('lib/reception-carrier-diagnostic.ts','utf8');for(const forbidden of ['process.env','console.','method:\'POST\'','method:\'PATCH\'','/Events.json','icash_claim_','icash_complete_'])assert(!source.includes(forbidden));
assert(!f.requests[0].url.includes('From='));assert(!f.requests[0].url.includes('StartTime'));
console.log('Reception carrier diagnostic: fixed owner/DID/window, bounded read-only calls+notifications, unanswered visibility, pagination honesty, redaction and denial stops');
