import assert from 'node:assert/strict';
import {runScreeningJob,recalculateSavedScreening} from '../lib/screening-job.ts';
const fetchedAt='2026-10-01T12:00:00Z',now=Date.parse('2026-10-05T12:00:00Z');
const snapshot={propertyId:'prop_123',propertyType:'house',fetchedAt,assignmentFeeCents:2000000,sellerCostReserveCents:100000,raw:{data:{dm_property_id:'prop_123',full_address:'Fixture',estimated_value:211000,estimated_repair_cost:59185,estimated_repair_cost_high:84550,estimated_repair_cost_low:33820,total_estimated_loan_balance:0}}};
const previous={property:{propertyId:'prop_123'},preliminarySellerCeilingCents:5315000};
const original=JSON.stringify({snapshot,previous});
const revised=recalculateSavedScreening(snapshot,previous,now);
assert.equal(revised.preliminarySellerCeilingCents,9627050);
assert.equal(revised.property.repairs.baselineCents,5918500);
assert.equal(revised.property.fetchedAt,fetchedAt);
assert.equal(revised.financialCheck.status,'hold');
assert.equal(revised.financialCheck.checkedAt,Date.parse(fetchedAt));
assert.equal(revised.offerAuthorized,false);
assert.equal(revised.outreachAuthorized,false);
assert.equal(revised.nextAction,'review');
assert.equal(revised.calculationHistory[0].sellerCeilingCents,5315000);
assert.equal(revised.calculatedAt,new Date(now).toISOString());
assert.equal(JSON.stringify({snapshot,previous}),original);
assert.throws(()=>runScreeningJob(snapshot,now),/INVALID_SNAPSHOT/);
assert.throws(()=>recalculateSavedScreening({...snapshot,propertyId:'prop_456'},previous,now),/INVALID_SNAPSHOT/);
assert.throws(()=>recalculateSavedScreening({...snapshot,fetchedAt:'bad'},previous,now),/INVALID_SNAPSHOT/);
assert.equal(runScreeningJob({...snapshot,propertyType:'land'},Date.parse(fetchedAt)).preliminarySellerCeilingCents,null);
const larger=recalculateSavedScreening({...snapshot,raw:{data:{...snapshot.raw.data,estimated_value:300000}}},previous,now);
assert.equal(larger.property.offerCalculation.assignmentFeeCents,2000000);
console.log('Historical recalculation preserves evidence dates and authorization gates');
