import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const sql=read('config/seller-recipient-variants.sql');
const fixture=read('tests/fixtures/seller-opener-current.sql');

assert.match(sql,/lock table public\.icash_seller_matches in share row exclusive mode nowait/i);
assert.match(sql,/array\['account_id','deal_id','sender','recipient'\]/);
assert.match(sql,/to_regclass\('public\.icash_text_threads_active_number'\) is not null/);
assert.doesNotMatch(sql,/create unique index[^;]+sender,recipient/i,'Must not reinstate global-number uniqueness');
assert.match(sql,/row_number\(\) over\(partition by lead_id order by assigned_at,account_id\)/);
assert.match(sql,/pg_advisory_xact_lock\(hashtextextended\(new\.lead_id::text,219705\)\)/);
assert.match(sql,/coalesce\(max\(recipient_ordinal\),0\)\+1/);
assert.match(sql,/before update or delete on public\.icash_seller_recipient_ordinals/);
assert.match(sql,/ordinal not between 1 and 3/);
assert.match(sql,/m\.screening_id=d\.screening_id/);
assert.match(sql,/t\.account_id=p_account and t\.party='seller' and t\.retired_at is null/);
assert.match(sql,/length\(body\)>160/);
assert.match(sql,/Reply STOP to opt out\./);
assert.equal([...sql.matchAll(/about a possible cash offer\./g)].length,3,'Every variant discloses the same conditional buying purpose');
assert.match(sql,/alter table public\.icash_seller_recipient_ordinals enable row level security/i);
assert.match(sql,/revoke all on public\.icash_seller_recipient_ordinals from public,anon,authenticated,service_role/i);
assert.match(sql,/grant select,insert on public\.icash_seller_recipient_ordinals to service_role/i);
assert.equal([...sql.matchAll(/language plpgsql (?:stable )?security invoker set search_path=''/g)].length,3);
assert.doesNotMatch(sql,/security definer/i);
assert.doesNotMatch(sql,/insert into public\.(?:icash_text_threads|icash_text_messages|icash_contact_permissions)\b/i);
assert.doesNotMatch(sql,/\b(?:perform|select) public\.icash_(?:reserve|fund|provision)/i);
const needle=sql.match(/needle:=\$old\$([\s\S]*?)\$old\$/)?.[1];
assert(needle);assert.equal(fixture.split(needle).length-1,1,'Current live opener has exactly one target body expression');
assert.match(sql,/execute replace\(definition,needle,/);
assert.match(sql,/if message_body is null then return null;end if/);
console.log('Seller recipient variants: narrow copy patch, immutable scoped ordinals, routing prerequisite, existing one-segment holds and restricted invoker permissions checked.');
