import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {sellerPhoneFlowInstructions} from '../lib/seller-phone-flow.ts';
import {sellerCallPrompt,sellerFirstMessage} from '../lib/seller-call-context.ts';
const context={address:'45 Oak Road',principal:'Fixture Homes',assistantName:'Robin',history:null};
const company=sellerPhoneFlowInstructions({hasBoundRequest:true,buyerKind:'company',hasPendingAgreement:true});
const steps=['1. SELLER AND PROPERTY','2. BUYER AND INQUIRY','3. TIME TO TALK','4. SHORT QUALIFICATION','5. SUPPORTED LOWER OFFER','6. NEGOTIATION','7. AGREEMENT AND PROCESS','8. NEXT STEP'];
for(let i=1;i<steps.length;i++)assert(company.indexOf(steps[i-1])<company.indexOf(steps[i]));
assert(company.includes('actual buying company'));
assert(company.includes('briefly referencing their submitted property form'));
assert(company.includes('Before interest, condition or price questions'));
assert(company.includes('exact date, AM/PM time and timezone'));
assert(company.includes('existing required notices'));
assert(company.includes('provider recording/AI disclosures and consent process unchanged'));
assert(company.includes('Move upward only as needed within the current maximum, never beyond it'));
assert(company.includes('Preserve an already agreed lower price'));
assert(company.includes('Never invent repair/holding costs, comparable sales, a fixed discount or competing offers'));
assert(company.includes('one page without a verified page count'));
assert(company.includes('Do not invent a sign-today deadline or higher-price incentive'));
assert(company.includes('as-is or no seller repairs only when those actual terms support it'));
assert(company.includes('An inspection period does not establish a guaranteed cancellation right'));
const investor=sellerPhoneFlowInstructions({hasBoundRequest:false,buyerKind:'individual',hasPendingAgreement:false});
assert(investor.includes('individual investor'));
assert(investor.includes('do not invent a company or LLC'));
assert(investor.includes('No bound submitted-form record is supplied'));
assert(investor.includes('No approved pending purchase agreement is supplied'));
assert(!investor.includes('briefly referencing their submitted property form'));
assert(sellerPhoneFlowInstructions({hasBoundRequest:false,hasPendingAgreement:false}).includes('without guessing whether it is a company'));
const noRequest=sellerCallPrompt(context,15000000,null,true,15000000);
assert(noRequest.includes('No bound submitted-form record is supplied'));
assert(!noRequest.includes('Acknowledge that they requested an offer.'));
assert(noRequest.includes('a price objection alone is not a reason to stop negotiating or hand off'));
assert(!noRequest.includes('explain that amount is outside your authority and request follow-up'));
assert(noRequest.includes('"maxOfferCents":15000000'));
assert(!noRequest.includes('"priceCents":15000000'));
const submitted={...context,buyerKind:'individual',principal:'Fixture Investor',request:{name:'Jane Seller',submittedAt:new Date(Date.now()-1000).toISOString()}};
assert(sellerCallPrompt(submitted,15000000).includes('briefly referencing their submitted property form'));
assert(sellerCallPrompt({...submitted,request:{...submitted.request,submittedAt:new Date(Date.now()+86400000).toISOString()}},15000000).includes('No bound submitted-form record is supplied'));
const terms={priceCents:14000000,earnestCents:50000,inspectionDays:7,closingDate:'2026-11-12',effectiveDate:'2026-10-15',escrowAgent:'Fixture Title',dealNotes:'Inspection/access terms require review.'};
const prepared=sellerCallPrompt(submitted,15000000,terms,true,15000000);
assert(prepared.includes('"priceCents":14000000'));assert(prepared.includes('"inspectionDays":7'));assert(prepared.includes('"escrowAgent":"Fixture Title"'));
assert(prepared.includes('existing matched-envelope and successful-delivery checks'));
assert.throws(()=>sellerCallPrompt(submitted,15000000,{...terms,priceCents:20000000},true,15000000),/CALL_OFFER_AUTHORITY_INVALID/);
assert.throws(()=>sellerCallPrompt(submitted,15000000,null,true,20000000),/CALL_OFFER_AUTHORITY_INVALID/);
assert(sellerCallPrompt(context).includes('If null, do not quote an offer'));
// This task changes the post-notice flow, not the paused first utterance/disclosure topic.
assert.equal(sellerFirstMessage(context),"Hi, I'm Robin, the AI assistant for Fixture Homes. Is this the owner of 45 Oak Road?");
assert.equal(sellerFirstMessage(context,true),'Is this the owner of 45 Oak Road?');
assert.equal(sellerFirstMessage(submitted),"Hi, I'm Robin, the AI assistant for Fixture Investor. Is this Jane, the owner of 45 Oak Road?");
const source=readFileSync(new URL('../lib/seller-call-context.ts',import.meta.url),'utf8');
assert(source.includes('sellerPhoneFlowInstructions({hasBoundRequest:!!c.request,buyerKind:c.buyerKind,hasPendingAgreement:closing!==null})'));
console.log('Seller phone flow: ordered post-notice sequence, actual principal/form evidence, time-to-talk gate, bounded supported negotiation, saved contract terms and unchanged first disclosure passed. Synthetic context only.');
