import assert from 'node:assert/strict';
import {sellerSubmission,sellerConsentVersion,sellerDuplicateKeyInput} from '../lib/seller-leads.ts';
import {qualifySellerProperty,sellerLeadCharge} from '../lib/seller-qualification.ts';
import {processSellerIntake} from '../lib/seller-pipeline.ts';
import {sellerMetaEvent,deliverSellerEvent} from '../lib/seller-conversions.ts';
import {dailyBudgetTier,validDailyBudget} from '../lib/daily-budget.ts';
const now=Date.now(),future=new Date(now+86400000).toISOString();
const input={name:'Sample Seller',address:'Synthetic address, Dallas, TX 75217',phone:'214-555-0123',consented:true,consentVersion:sellerConsentVersion,requestId:'12345678-1234-4234-8234-123456789abc'};
assert.equal(sellerSubmission.parse(input).phone,'+12145550123');assert.equal(sellerSubmission.parse(input).consented,true,'Only explicit affirmative consent is accepted');
for(const bad of [{...input,phone:'invalid'},{...input,consented:false},{...input,consented:undefined},{...input,ownerConfirmed:true},{...input,consentVersion:'old'},{...input,qualified:true},{...input,email:'invalid'},{...input,email:'x@example.com\nBcc: other@example.com'}])assert.equal(sellerSubmission.safeParse(bad).success,false);
assert.equal(sellerSubmission.parse({...input,email:' Seller@Example.com '}).email,'seller@example.com');assert.equal(sellerSubmission.parse(input).email,null);assert.equal(sellerSubmission.parse({...input,email:''}).email,null);
assert.equal(sellerDuplicateKeyInput(' 123 Main St. ','+12145550123'),sellerDuplicateKeyInput('123 MAIN ST','+12145550123'));
const raw={data:[{matched:true,dm_property_id:'prop_123',full_address:'Synthetic only',city:'Dallas',state:'TX',zip:'75217',property_type:1,estimated_value:200000,estimated_repair_cost:40000,total_estimated_loan_balance:50000}],credits:{used:1,people:0},totals:{submitted:1}};
const markets=[{city:'dallas',state:'TX',enabled:true,reviewed_until:future,review_ref:'Synthetic reviewed market'}],options={assignmentFeeCents:1000000,sellerCostReserveCents:100000};
let r=qualifySellerProperty(raw,markets,options,now);assert.equal(r.status,'qualified');assert.equal(r.result.outreachAuthorized,false);assert.equal(r.result.offerAuthorized,false);
assert.equal(qualifySellerProperty(raw,[],options,now).status,'market_review');
assert.equal(qualifySellerProperty({...raw,data:[{...raw.data[0],estimated_repair_cost:null}]},markets,options,now).numbersPassed,false);
assert.throws(()=>qualifySellerProperty({...raw,credits:{used:2,people:0}},markets,options,now));
assert.throws(()=>qualifySellerProperty({...raw,data:[{...raw.data[0],match_warning:'Ambiguous'}]},markets,options,now));
assert.equal(sellerLeadCharge(1000000,100000),330);assert.equal(sellerLeadCharge(1,0),1);assert.throws(()=>sellerLeadCharge(-1,0));
assert(validDailyBudget(1000));assert(!validDailyBudget(999));assert(!validDailyBudget(500));assert(!validDailyBudget(1000.5));assert.equal(dailyBudgetTier(500).name,'Starter');assert.equal(dailyBudgetTier(5000).name,'Growth');
let requests=0,saved=0,claimed=false;
const db=async(path,method,body)=>{if(path.startsWith('icash_seller_markets'))return markets;if(path==='rpc/icash_take_dealmachine_request')return true;if(path==='rpc/icash_claim_seller_lookup'){if(claimed)return null;claimed=true;return {id:'lead',token:'one-use',address:input.address,...options};}if(path==='rpc/icash_finish_seller_lookup'){saved++;assert.equal(body.p_output.status,'qualified');return true;}throw Error(path);};
assert.equal((await processSellerIntake(db,undefined)).status,'provider_not_configured');assert.equal(claimed,false);
const transport=async(url,opts)=>{requests++;assert.equal(url,'https://api.v2.dealmachine.com/v1/enrichment/address');const body=JSON.parse(opts.body);assert.equal(body.data.length,1);assert.equal(body.contact_audience,'none');assert(!('estimate_cost' in body));return Response.json(raw);};
assert.equal((await processSellerIntake(db,'dm_sk_live_fixture',transport)).status,'property_checked');await processSellerIntake(db,'dm_sk_live_fixture',transport);assert.equal(requests,1);assert.equal(saved,1);
claimed=false;assert.equal((await processSellerIntake(db,'dm_sk_live_fixture',async()=>{requests++;throw Error('ambiguous provider timeout');})).status,'lookup_requires_review');await processSellerIntake(db,'dm_sk_live_fixture',transport);assert.equal(requests,2,'an ambiguous paid lookup is not retried');
const event={id:'event-fixture',leadId:'lead-fixture',token:'claim',name:'Lead',occurredAt:new Date(now).toISOString(),phone:'+12145550123'};
const payload=sellerMetaEvent(event,now);assert.equal(payload.event_id,'keypath:event-fixture');assert(!JSON.stringify(payload).includes(event.phone));assert.equal(payload.user_data.ph[0].length,64);assert(!('custom_data' in payload));assert.throws(()=>sellerMetaEvent({...event,occurredAt:new Date(now-8*86400000).toISOString()},now));
let writes=[];const eventDb=async(path,method,body)=>{writes.push({path,body});return path==='rpc/icash_claim_seller_event'?event:true;};
assert.equal((await deliverSellerEvent(eventDb,{})).status,'measurement_setup_required');assert.equal(writes.length,0);
const env={META_SELLER_EVENTS_ENABLED:'true',META_SELLER_DATASET_ID:'123456789',META_SELLER_ACCESS_TOKEN:'fixture',META_GRAPH_VERSION:'v25.0'};
assert.equal((await deliverSellerEvent(eventDb,env,async()=>Response.json({events_received:1}))).status,'delivered');assert.equal(writes.at(-1).body.p_delivered,true);
console.log('PASS seller funnel: explicit affirmative consent, input validation, real financial screening, reviewed markets, exact 3× pricing, one-use paid lookup, ambiguous-outcome hold, private measurement payload and credential gate.');
