import assert from 'node:assert/strict';
import {sellerSubmission,sellerConsentVersion,sellerDuplicateKeyInput} from '../lib/seller-leads.ts';
import {qualifySellerProperty,sellerLeadCharge} from '../lib/seller-qualification.ts';
import {processSellerIntake} from '../lib/seller-pipeline.ts';
import {sellerMetaEvent,deliverSellerEvent} from '../lib/seller-conversions.ts';
import {runScreeningJob} from '../lib/screening-job.ts';
import {dailyBudgetTier,validDailyBudget} from '../lib/daily-budget.ts';
const now=Date.now();
const input={name:'Sample Seller',address:'Synthetic address, Dallas, TX 75217',phone:'214-555-0123',consented:true,consentVersion:sellerConsentVersion,requestId:'12345678-1234-4234-8234-123456789abc'};
assert.equal(sellerSubmission.parse(input).phone,'+12145550123');assert.equal(sellerSubmission.parse(input).consented,true,'Only explicit affirmative consent is accepted');
for(const bad of [{...input,phone:'invalid'},{...input,consented:false},{...input,consented:undefined},{...input,ownerConfirmed:true},{...input,consentVersion:'old'},{...input,qualified:true},{...input,email:'invalid'},{...input,email:'x@example.com\nBcc: other@example.com'}])assert.equal(sellerSubmission.safeParse(bad).success,false);
assert.equal(sellerSubmission.parse({...input,email:' Seller@Example.com '}).email,'seller@example.com');assert.equal(sellerSubmission.parse(input).email,null);assert.equal(sellerSubmission.parse({...input,email:''}).email,null);
assert.equal(sellerDuplicateKeyInput(' 123 Main St. ','+12145550123'),sellerDuplicateKeyInput('123 MAIN ST','+12145550123'));
const raw={data:[{matched:true,dm_property_id:'prop_123',full_address:'Synthetic only',city:'Dallas',state:'TX',zip:'75217',property_type:1,estimated_value:200000,estimated_repair_cost:40000,total_estimated_loan_balance:50000}],credits:{used:1,people:0},totals:{submitted:1}};
const options={assignmentFeeCents:1000000,sellerCostReserveCents:100000};
let r=qualifySellerProperty(raw,options,now);assert.equal(r.status,'qualified');assert.equal(r.result.outreachAuthorized,false);assert.equal(r.result.offerAuthorized,true,'Eligible fresh screening authorizes only the calculated offer ceiling');assert.equal(r.result.cashOfferPriceCents,10200000);assert.equal(r.result.cashOfferPriceCents,r.result.preliminarySellerCeilingCents);assert.equal(r.result.property.offerAuthorized,false,'Raw provider context alone never authorizes an offer');
assert.equal(qualifySellerProperty({...raw,data:[{...raw.data[0],property_type:[1]}]},options,now).status,'qualified','The documented MULTI_SELECT array must qualify the same as its legacy scalar');
for(const type of ['Single Family',['Single Family'],' single family ']){
 const labeled=qualifySellerProperty({...raw,data:[{...raw.data[0],property_type:type}]},options,now);
 assert.equal(labeled.status,'qualified','Address-enrichment display labels must pass the same screening as option IDs');
 assert.deepEqual(labeled.property.raw.data.property_type,type,'Keep the actual provider receipt');
 assert.equal(labeled.result.outreachAuthorized,false);
}
for(const type of [[],[1,2],['1'],[2],null,'Multi Family','Single Family, Condo',['Single Family','Condo'],[1,'Single Family'],{},true])assert.throws(()=>qualifySellerProperty({...raw,data:[{...raw.data[0],property_type:type}]},options,now),/PROPERTY_MATCH_REQUIRES_REVIEW/,'Mixed, missing or unrecognized types remain reviewable');
for(const [city,state] of [['Houston','TX'],['Phoenix','AZ'],['Columbus','OH']])assert.equal(qualifySellerProperty({...raw,data:[{...raw.data[0],city,state}]},options,now).status,'qualified','Submitted addresses do not need a city allowlist');
const missingRepairs=qualifySellerProperty({...raw,data:[{...raw.data[0],estimated_repair_cost:null}]},options,now);assert.equal(missingRepairs.numbersPassed,false);assert.equal(missingRepairs.result.offerAuthorized,false);assert.equal(missingRepairs.result.cashOfferPriceCents,null);assert.equal(missingRepairs.result.outreachAuthorized,false);
assert.throws(()=>qualifySellerProperty({...raw,credits:{used:2,people:0}},options,now));
assert.throws(()=>qualifySellerProperty({...raw,data:[{...raw.data[0],match_warning:'Ambiguous'}]},options,now));
assert.equal(sellerLeadCharge(1000000,100000),330);assert.equal(sellerLeadCharge(1,0),1);assert.throws(()=>sellerLeadCharge(-1,0));
assert(validDailyBudget(1000));assert(!validDailyBudget(999));assert(!validDailyBudget(500));assert(!validDailyBudget(1000.5));assert.equal(dailyBudgetTier(500).name,'Starter');assert.equal(dailyBudgetTier(5000).name,'Growth');
let requests=0,saved=0,claimed=false;
const db=async(path,method,body)=>{if(path==='rpc/icash_take_dealmachine_request')return true;if(path==='rpc/icash_claim_seller_lookup'){if(claimed)return null;claimed=true;return {id:'lead',token:'one-use',address:input.address,...options};}if(path==='rpc/icash_finish_seller_lookup'){saved++;assert.equal(body.p_output.status,'qualified');return true;}throw Error(path);};
assert.equal((await processSellerIntake(db,undefined)).status,'provider_not_configured');assert.equal(claimed,false);
const transport=async(url,opts)=>{requests++;assert.equal(url,'https://api.v2.dealmachine.com/v1/enrichment/address');const body=JSON.parse(opts.body);assert.equal(body.data.length,1);assert.equal(body.contact_audience,'none');assert(!('estimate_cost' in body));return Response.json(raw);};
assert.equal((await processSellerIntake(db,'dm_sk_live_fixture',transport)).status,'property_checked');await processSellerIntake(db,'dm_sk_live_fixture',transport);assert.equal(requests,1);assert.equal(saved,1);
claimed=false;assert.equal((await processSellerIntake(db,'dm_sk_live_fixture',async()=>{requests++;throw Error('ambiguous provider timeout');})).status,'lookup_requires_review');await processSellerIntake(db,'dm_sk_live_fixture',transport);assert.equal(requests,2,'an ambiguous paid lookup is not retried');
claimed=false;let targetClaim=false;
const targeted=async(path,method,body)=>{if(path==='rpc/icash_claim_seller_lookup_for'){assert.deepEqual(body,{p_id:input.requestId});targetClaim=true;return db('rpc/icash_claim_seller_lookup',method,{});}return db(path,method,body);};
assert.equal((await processSellerIntake(targeted,'dm_sk_live_fixture',transport,input.requestId)).status,'property_checked');assert(targetClaim);
await processSellerIntake(targeted,'dm_sk_live_fixture',transport,input.requestId);assert.equal(requests,3,'targeted retries reuse the durable claim');
const event={id:'event-fixture',leadId:'lead-fixture',token:'claim',name:'Lead',occurredAt:new Date(now).toISOString(),phone:'+12145550123'};
const payload=sellerMetaEvent(event,now);assert.equal(payload.event_id,'keypath:event-fixture');assert(!JSON.stringify(payload).includes(event.phone));assert.equal(payload.user_data.ph[0].length,64);assert(!('custom_data' in payload));assert.throws(()=>sellerMetaEvent({...event,occurredAt:new Date(now-8*86400000).toISOString()},now));
let writes=[];const eventDb=async(path,method,body)=>{writes.push({path,body});return path==='rpc/icash_claim_seller_event'?event:true;};
assert.equal((await deliverSellerEvent(eventDb,{})).status,'measurement_setup_required');assert.equal(writes.length,0);
const env={META_SELLER_EVENTS_ENABLED:'true',META_SELLER_DATASET_ID:'123456789',META_SELLER_ACCESS_TOKEN:'fixture',META_GRAPH_VERSION:'v25.0'};
assert.equal((await deliverSellerEvent(eventDb,env,async()=>Response.json({events_received:1}))).status,'delivered');assert.equal(writes.at(-1).body.p_delivered,true);
console.log('PASS seller funnel: explicit affirmative consent, input validation, real financial screening, address-driven research, exact 3× pricing, one-use paid lookup, ambiguous-outcome hold, private measurement payload and credential gate.');

assert.equal(sellerSubmission.parse({...input,contactTimezone:'America/Chicago'}).contactTimezone,'America/Chicago');
assert.equal(sellerSubmission.safeParse({...input,contactTimezone:'invalid/zone'}).success,false);

assert.equal(r.property.sellerCostReserveCents,options.sellerCostReserveCents);
assert.equal(runScreeningJob({propertyId:r.property.id,propertyType:'house',fetchedAt:r.property.fetchedAt,raw:r.property.raw,sellerCostReserveCents:r.property.sellerCostReserveCents},now).financialCheck.status,'eligible','Qualification reserve must survive the delivered snapshot');
