import assert from 'node:assert/strict';
import {discoverPage} from '../lib/discovery-pipeline.ts';
import {runScreeningJob} from '../lib/screening-job.ts';
import {enrichOwners} from '../lib/owner-enrichment.ts';
import {callEligibility} from '../lib/live-dispatch-policy.ts';
import {dealNextStep} from '../lib/deal-conversation.ts';
import {workMilestone} from '../lib/work-milestone.ts';
// Integrated fixture flow. No provider network calls, messages, or voice minutes.
const now=Date.parse('2026-09-29T16:00:00Z');let saved,lookups=0;
const row={dm_property_id:'prop_123',full_address:'Fixture only',estimated_value:200000,estimated_repair_cost:40000,total_estimated_loan_balance:50000};
await discoverPage({zip:'75217',page:1,perPage:1,unitCostMicros:10000,quotedDataCostMicros:10000},{request:async b=>b.estimate_cost?{estimated_credits:{this_page:1,breakdown:{people:0}}}:{data:[row],credits:{used:1,people:0},pagination:{has_next_page:false}},reserveAndClaim:async()=>true,persist:async r=>{saved=r;}});
const snapshot={propertyId:'prop_123',propertyType:'house',fetchedAt:new Date(now).toISOString(),sellerCostReserveCents:100000,raw:{data:saved.rows[0]}};
assert.equal(runScreeningJob(snapshot,now).financialCheck.status,'eligible');
assert.equal((await enrichOwners({snapshot,creditCap:1,unitCostMicros:10000,quotedDataCostMicros:10000},{previewOwners:async()=>({data:{dm_property_id:'prop_123',contacts:[{dm_person_id:'per_123',is_likely_owner:true}]},credits:{used:0,people:0,properties:0,deduplicated:0}}),reserveAndClaim:async()=>true,fetchPeople:async ids=>{lookups++;assert.deepEqual(ids,['per_123']);return {data:[{dm_person_id:'per_123',found:false}],totals:{submitted:1,found:0,not_found:1},credits:{used:0,people:0,properties:0,deduplicated:0}}},recordReceipt:async()=>{},persist:async()=>{}},now)).status,'contacts_saved');
const permission={phone:'+12145550123',timezone:'America/Chicago',local_start_hour:9,local_end_hour:20,permission_until:'2026-09-30T16:00:00Z',dnc_checked_at:new Date(now).toISOString(),dnc_clear:true,revoked_at:null};
assert.equal(callEligibility(permission,snapshot,now).ready,true);
assert.equal(callEligibility({...permission,revoked_at:new Date(now).toISOString()},snapshot,now).ready,false);
const bad={...snapshot,raw:{data:{...row,total_estimated_loan_balance:190000}}};
assert.equal((await enrichOwners({snapshot:bad,creditCap:1,unitCostMicros:10000,quotedDataCostMicros:10000},{previewOwners:async()=>{throw Error('Should not preview');},reserveAndClaim:async()=>{throw Error('Should not spend');},fetchPeople:async()=>{throw Error('Should not fetch');},recordReceipt:async()=>{throw Error('Should not record');},persist:async()=>{}},now)).status,'financial_hold');
assert.equal(lookups,1);
const deal={humanRequested:false,optedOut:false,interested:true,qualified:true,agreedPriceCents:8000000,signedEvidence:false,authority:{expiresAt:now+10000,maxOfferCents:9000000,ownershipVerified:true,allOwnersOnBoard:true,termsReviewed:true,deliveryEnabled:true},now};
assert.equal(dealNextStep(deal),'send_for_signatures');
assert.equal(dealNextStep({...deal,humanRequested:true}),'human_handoff');
assert.equal(dealNextStep({...deal,agreedPriceCents:10000000}),'review_counteroffer');
assert.equal(dealNextStep({...deal,signedEvidence:true}),'match_buyers');
const status={needsHuman:false,needsSignature:false,purchaseSigned:true,assignmentSigned:true,eligible:true};
assert.equal(workMilestone({...status,stage:'closed'}),'✅ Deal closed');
assert.equal(workMilestone({...status,stage:'canceled'}),'Deal canceled');
assert.equal(workMilestone({...status,stage:'title_open'}),'📄 Title opened');
console.log('Seller fixture flow, spending gate, revoked contact, authority, handoff and terminal milestones passed');
