import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
const require=createRequire(import.meta.url);
let cursor=0,status='review_required';
const hooks={useState(initial){const i=cursor++;return [i===1?[{key:'sms_contact_permission',title:'Seller SMS contact review',status,detail:'SMS evidence needed',action:'operator_review'}]:initial,()=>{}];},useEffect(){}};
const source=readFileSync(new URL('../components/live-workspace.tsx',import.meta.url),'utf8')+'\nexport {PropertyReviewStatus};';
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};new Function('require','module','exports',code)(name=>name==='react'?hooks:name==='react/jsx-runtime'?require(name):{},mod,mod.exports);
const all=root=>!root||typeof root!=='object'?[]:Array.isArray(root)?root.flatMap(all):[root,...all(root.props?.children)];
let tree=mod.exports.PropertyReviewStatus({screeningId:'fixture'});
const link=all(tree).find(node=>node.type==='a'&&node.props.href==='#authority-settings');assert(link,'SMS status links directly to existing evidence form');
const details={'account-details':{open:false},'authority-settings':{open:false}};globalThis.document={getElementById:id=>details[id]};link.props.onClick();assert(details['account-details'].open&&details['authority-settings'].open);delete globalThis.document;
status='recorded';cursor=0;tree=mod.exports.PropertyReviewStatus({screeningId:'fixture'});assert(!all(tree).some(node=>node.type==='a'&&node.props.href==='#authority-settings'));
console.log('SMS status navigation: missing review opens the existing account evidence form without any send or activation action.');
