import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {z} from 'zod';
const messageId='00000000-0000-4000-8000-000000000002';
let current=7,signedIn=true,origin=true,calls=[];
const deps={z,NextResponse:{json:(body,o={})=>({body,status:o.status??200})},allowedOrigin:()=>origin,workAccount:async()=>{if(!signedIn)throw Error('SIGN_IN');return {accountId:'owner-account',userId:'owner-user'};},db:async(path,method,body)=>{calls.push({path,method,body});assert.equal(path,'rpc/icash_review_sms_route');assert.equal(method,'POST');assert.equal(body.p_account,'owner-account');assert.equal(body.p_actor,'owner-user');assert.equal(body.p_message,messageId);return body.p_revision===current;}};
globalThis.__routeReview=deps;
let source=ts.transpileModule(readFileSync(new URL('../app/api/work/sms-route-review/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
const {POST}=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.__routeReview;\n'+source).toString('base64'));delete globalThis.__routeReview;
const req=body=>new Request('https://example.invalid/api/work/sms-route-review',{method:'POST',body:JSON.stringify(body)});
assert.equal((await POST(req({messageId,revision:6}))).status,409);
assert.equal((await POST(req({messageId,revision:7}))).status,200);
assert.equal((await POST(req({messageId,revision:7}))).status,200);
calls=[];for(const body of [{messageId},{messageId,revision:7,accountId:'other'},{messageId,revision:0},{messageId,revision:7.5},{messageId:'bad',revision:7}])assert.equal((await POST(req(body))).status,400);assert.equal(calls.length,0);
signedIn=false;assert.equal((await POST(req({messageId,revision:7}))).status,400);assert.equal(calls.length,0);
signedIn=true;origin=false;assert.equal((await POST(req({messageId,revision:7}))).status,403);assert.equal(calls.length,0);
const sql=readFileSync(new URL('../config/sms-property-routing.sql',import.meta.url),'utf8');
assert.equal(sql,readFileSync(new URL('../supabase/migrations/20261007221403_sms_property_routing.sql',import.meta.url),'utf8'));
assert.ok(!/icash_reserve_before_inventory|icash_claim_before_activation|icash_reserve_before_activation|funded.*provision/i.test(sql));
const ui=readFileSync(new URL('../components/sms-route-review.tsx',import.meta.url),'utf8');assert.match(ui,/pending.current/);assert.match(ui,/role="alert"/);assert.match(ui,/revision:item.revision/);
console.log('SMS routing-review API: authenticated account/actor, origin, strict payload, stale CAS 409, idempotent retry; migration parity and UI duplicate-click guard passed.');
// Render the actual review card and check the hostile text/attachment boundaries.
const React=await import('react');const {renderToStaticMarkup}=await import('react-dom/server');
globalThis.__smsReviewReact={...React};
let component=ts.transpileModule(ui,{compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
const {SmsRouteReviewCard}=await import('data:text/javascript;base64,'+Buffer.from('const React=globalThis.__smsReviewReact;const {useRef,useState}=React;\n'+component).toString('base64'));delete globalThis.__smsReviewReact;
const html=renderToStaticMarkup(React.createElement(SmsRouteReviewCard,{item:{message_id:messageId,revision:7,recipient:'+12145550123',body:'<script>unsafe</script>',created_at:'2026-10-07',needs_review:true,candidates:[{threadId:messageId,screeningId:messageId,address:'2149 Arden Rd'}],attachments:[{url:'https://api.contiguity.com/attachments/fixture'},{url:'javascript:alert(1)'},{url:'https://untrusted.invalid/private'}]},onOpen:()=>{},onHandled:()=>{}}));
assert.ok(html.includes('&lt;script&gt;unsafe&lt;/script&gt;'));assert.ok(!html.includes('<script>'));
assert.ok(html.includes('https://api.contiguity.com/attachments/fixture'));assert.ok(!html.includes('href="javascript:'));assert.ok(!html.includes('https://untrusted.invalid'));
assert.ok(html.includes('2149 Arden Rd'));assert.ok(html.includes('Mark reviewed'));
console.log('SMS review actual React render: escaped quotes, permitted attachment links only, property links, and clear hold-release action passed.');
