import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../components/live-workspace.tsx',import.meta.url),'utf8');
const home=readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');
assert(!source.includes('PropertyReviewStatus'));
assert(!source.includes('Why work may be waiting'));
assert(!home.includes('<AuthorityReviewPanel'));
assert(!source.includes('Showing proposals'));
const route=readFileSync(new URL('../app/api/work/review-status/route.ts',import.meta.url),'utf8');
assert(route.includes('icash_sms_thread_review_current'));
assert(route.includes('contractCapability'));
assert(route.includes('icash_contact_suppressions'));
assert(route.includes('icash_offer_authorities'));
console.log('Workspace removes generic review/proposal clutter without disabling SMS, contract, suppression or offer checks');
