import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
const require=createRequire(import.meta.url);
const code=ts.transpileModule(readFileSync(new URL('../components/live-workspace.tsx',import.meta.url),'utf8')+'\nexport {TextAttentionCard,WorkspaceAttention};',{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const mod={exports:{}};let slots=[],cursor=0;const hooks={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return [slots[i],value=>{slots[i]=typeof value==='function'?value(slots[i]):value;}];}};
new Function('require','module','exports',code)(name=>name==='react'?hooks:name==='react/jsx-runtime'?require(name):{},mod,mod.exports);
const text=root=>typeof root==='string'?root:Array.isArray(root)?root.map(text).join(' '):root&&typeof root==='object'?text(root.props?.children):'';
const all=root=>!root||typeof root!=='object'?[]:Array.isArray(root)?root.flatMap(all):[root,...all(root.props?.children)];
const item={id:'reply-fixture',message_id:'message-fixture',kind:'campaign_reply',party:'seller',quote:'Yes, but who is this?',timezone:'America/Chicago'};
let handled=0,calls=[];
const tree=mod.exports.TextAttentionCard({item,onHandled:()=>handled++});
assert.match(text(tree),/Seller reply needs review/);assert.match(text(tree),/Check the conversation for the latest delivery and contact status/);assert.match(text(tree),/does not establish ownership or authorize an offer/);
assert.doesNotMatch(text(tree),/keeps automatic work paused/);assert.match(text(tree),/does not send a message or change work controls/);
assert.equal(all(tree).find(node=>node.type==='blockquote').props.children,item.quote);
globalThis.fetch=async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return Response.json({saved:true});};
await all(tree).find(node=>node.type==='button').props.onClick();assert.equal(handled,1);assert.deepEqual(calls,[{url:'/api/work/text-attention',body:{id:item.id,messageId:item.message_id}}]);
const human=mod.exports.TextAttentionCard({item:{...item,kind:'human'},onHandled:()=>{}});assert.match(text(human),/Automatic work on this property is paused/);
console.log('SMS reply attention: actual card renders truthful review-only copy and acknowledgment invokes only the existing attention endpoint.');

slots=[];let work={textAttention:[{...item,screening_id:'property',message_id:'reply-A'}],signatureActions:[],handoffs:[],callRequests:[],properties:[]};
const renderQueue=()=>{cursor=0;return mod.exports.WorkspaceAttention({work,page:0,onPage:()=>{},onOpen:()=>{},onRefresh:()=>{}});};
let queue=renderQueue();assert.equal(queue.props.open,undefined,'request queue starts compact');assert.match(text(queue),/1 request shown/);
const oldKey=all(queue).find(n=>n.type==='details'&&n.props.className==='attention-item').key;
all(queue).find(n=>n.type===mod.exports.TextAttentionCard).props.onHandled();queue=renderQueue();assert.equal(queue,null,'empty attention panel stays out of the workspace');
work={...work,textAttention:[{...work.textAttention[0],message_id:'reply-B',quote:'A newer reply'}]};queue=renderQueue();assert.match(text(queue),/1 request shown/);assert.notEqual(all(queue).find(n=>n.type==='details'&&n.props.className==='attention-item').key,oldKey,'new reply gets a fresh child key and busy state');
assert.equal(all(queue).find(n=>n.type===mod.exports.TextAttentionCard).props.item.message_id,'reply-B');
console.log('Attention queue: a later reply on the same row reappears after its predecessor was handled.');
