import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import ts from 'typescript';
import * as policy from '../lib/disputes.ts';
import * as finalSale from '../lib/final-sale-policy.ts';
import {disputePdf} from '../lib/dispute-pdf.ts';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
let calls=[],user={id:id(99)},mode='live',recorded=[],data,dispute,charge;
const fixture=()=>{calls=[];recorded=[];mode='live';dispute={id:'dp_fixture',amount:2500,currency:'usd',status:'needs_response',reason:'product_not_received',charge:'ch_fixture',payment_intent:'pi_fixture',livemode:true,created:1791590400,evidence:{customer_email_address:'fixture@example.invalid'},evidence_details:{due_by:1792000000,has_evidence:false,past_due:false}};charge={id:'ch_fixture',amount:2500,amount_refunded:0,currency:'usd',status:'succeeded',created:1791504000,livemode:true,payment_intent:'pi_fixture',billing_details:{name:'Fixture Customer',email:'fixture@example.invalid'},payment_method_details:{card:{brand:'visa',last4:'4242',checks:{cvc_check:'pass',address_postal_code_check:'pass'},three_d_secure:{result:'authenticated'}}}};data={icash_funding_orders:[{id:id(3),account_id:id(1),state:'paid',price_cents:2500,credit_cents:2500,paid_at:'2026-10-09T00:00:00Z',credited_at:'2026-10-09T00:00:01Z'}],icash_membership_invoices:[],icash_plan_changes:[],icash_funding_consents:[{version:'historic',terms_text:'Original terms did not state final sales.',accepted_at:'2026-10-08T23:59:59Z'}],icash_auto_recharge_attempts:[],icash_purchase_acceptances:[],icash_operation_spend:[{operation_key:'research_fixture',charged_cents:150,settled_at:'2026-10-09T00:30:00Z'}],icash_software_access_receipts:[],icash_support_messages:[],icash_support_cancel_requests:[]};};
async function load(file,deps){const code=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .*;\s*$/gm,'');const key='__dispute'+Math.random().toString(36).slice(2);globalThis[key]=deps;return import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.'+key+';\n'+code).toString('base64'));}
const stripe={disputes:{retrieve:async id=>{calls.push(id);return dispute;},list:async params=>{calls.push(params);return {data:[dispute],has_more:true};}},charges:{retrieve:async id=>{calls.push(id);return charge;}}};
const service=await load('lib/dispute-service.ts',{...policy,db:async(path,method,body,signal)=>{calls.push(path);if(method==='POST'){recorded.push(body);return;}const table=path.split('?')[0];assert(table in data,'Unexpected table '+table);return structuredClone(data[table]);},fundingStripe:()=>stripe,fundingMode:()=>mode});
fixture();let packet=await service.prepareDisputeEvidence('dp_fixture');assert(packet.gaps.some(g=>g.includes('No new final-sale')));assert(!JSON.stringify(packet.sections).includes(finalSale.finalSalePolicy));assert(packet.sections.some(s=>s.title==='Original credit purchase terms'));assert(packet.sections.find(s=>s.title==='Completed account usage').lines[0].includes('not attributed to a specific top-up'));assert(calls.filter(x=>typeof x==='string'&&x.includes('account_id=')).every(x=>x.includes('account_id=eq.'+id(1))));
fixture();data.icash_purchase_acceptances=[{kind:'credits',reference_id:id(3),version:'work-credits-2026-10-10.1',terms_text:'I authorize $25. '+finalSale.finalSalePolicy,policy_version:finalSale.finalSaleVersion,policy_text:finalSale.finalSalePolicy,amount_cents:2500,accepted_at:'2026-10-08T23:59:59Z',request_context:{ip:'192.0.2.1',userAgent:'Fixture browser',path:'/api/funding/checkout'}}];data.icash_software_access_receipts=[{recorded_at:'2026-10-09T00:10:00Z',request_context:{ip:'192.0.2.1',userAgent:'Fixture browser'}}];data.icash_support_messages=[{role:'user',created_at:'2026-10-09T01:00:00Z',content:'I accessed the software. Please help me with setup.'}];packet=await service.prepareDisputeEvidence('dp_fixture');assert(!packet.gaps.some(g=>g.includes('No new final-sale')));assert(JSON.stringify(packet).includes('192.0.2.1'));assert(JSON.stringify(packet).includes('background refresh'));assert(JSON.stringify(packet).includes('authenticated'));assert(calls.some(p=>typeof p==='string'&&p.includes('accepted_at=lt.')));assert(packet.sections.find(s=>s.title==='Customer support excerpts').lines[0].includes('Please help'));
// Retain an inspectable PDF fixture without ever touching Stripe or a real account.
if(process.env.DISPUTE_PDF_FIXTURE){const bytes=await disputePdf(packet);assert(bytes.length<4_000_000);writeFileSync(process.env.DISPUTE_PDF_FIXTURE,bytes);}
fixture();data.icash_funding_orders=[];packet=await service.prepareDisputeEvidence('dp_fixture');assert(packet.gaps.some(g=>g.includes('not uniquely linked')));assert(!calls.some(p=>typeof p==='string'&&p.includes('icash_support_messages')));
fixture();data.icash_funding_orders[0].account_id=null;packet=await service.prepareDisputeEvidence('dp_fixture');assert(packet.gaps.some(g=>g.includes('not been claimed')));assert(!calls.some(p=>typeof p==='string'&&p.includes('icash_support_messages')));
fixture();dispute.livemode=false;await assert.rejects(service.prepareDisputeEvidence('dp_fixture'),/mode|binding/);assert.equal(calls.length,1);
fixture();charge.payment_intent='pi_other';await assert.rejects(service.prepareDisputeEvidence('dp_fixture'),/binding/);assert.equal(calls.length,2);
fixture();data.icash_operation_spend=Array.from({length:26},()=>data.icash_operation_spend[0]);data.icash_support_messages=[{role:'user',content:'Long support content '.repeat(200),created_at:'2026-10-09T01:00:00Z'}];packet=await service.prepareDisputeEvidence('dp_fixture');assert(packet.gaps.some(g=>g.includes('first 25')));assert(packet.gaps.some(g=>g.includes('excerpts')));assert(packet.sections.find(s=>s.title==='Customer support excerpts').lines[0].endsWith('[excerpt ends]'));
fixture();await service.recordDisputeEvent({id:'evt_fixture',type:'charge.dispute.created',created:dispute.created,data:{object:dispute}});assert.equal(recorded[0].p_event.disputeId,'dp_fixture');assert.equal(recorded[0].p_event.dueAt,new Date(dispute.evidence_details.due_by*1000).toISOString());for(const type of ['charge.dispute.updated','charge.dispute.closed'])await service.recordDisputeEvent({id:'evt_'+type.split('.').at(-1),type,created:dispute.created,data:{object:dispute}});assert.equal(recorded.length,3);
fixture();const list=await service.listDisputes('dp_previous');assert.equal(list.nextCursor,'dp_fixture');assert.equal(calls[0].starting_after,'dp_previous');dispute.livemode=false;await assert.rejects(service.listDisputes(),/mode/);
fixture();dispute.id='du_fixture';const liveList=await service.listDisputes('du_previous');assert.equal(liveList.nextCursor,'du_fixture');assert.equal(liveList.disputes[0].id,'du_fixture');assert.equal(calls[0].starting_after,'du_previous');packet=await service.prepareDisputeEvidence('du_fixture');assert.equal(packet.dispute.id,'du_fixture');await service.recordDisputeEvent({id:'evt_livefixture',type:'charge.dispute.updated',created:dispute.created,data:{object:dispute}});assert.equal(recorded[0].p_event.disputeId,'du_fixture');
const route=await load('app/api/admin/disputes/route.ts',{...policy,currentUser:async verified=>{assert(verified);return user;},ownerInboundTarget:{ownerUserId:id(99)},listDisputes:async cursor=>{calls.push(cursor);return {disputes:[]};},prepareDisputeEvidence:async id=>{calls.push(id);return {dispute:{id}};},disputePdf:async()=>new Uint8Array([37,80,68,70])});
const get=q=>route.GET(new Request('https://example.invalid/api/admin/disputes'+q));
calls=[];user=null;assert.equal((await get('')).status,401);user={id:id(1),user_metadata:{isBillingOwner:true}};assert.equal((await get('?actor='+id(99))).status,403);assert.equal(calls.length,0);user={id:id(99)};
for(const q of ['?id=wrong','?after=../../secret','?format=pdf','?id=dp_one&after=dp_two','?id=dp_one&format=other'])assert.equal((await get(q)).status,400);assert.equal(calls.length,0);
let res=await get('');assert.equal(res.status,200);assert.equal(res.headers.get('cache-control'),'private, no-store');assert.equal(res.headers.get('vary'),'Cookie');res=await get('?id=dp_fixture&format=pdf');assert.equal(res.headers.get('content-type'),'application/pdf');assert.match(res.headers.get('content-disposition'),/dp_fixture-evidence.pdf/);assert.equal(await res.text(),'%PDF');
res=await get('?id=du_fixture&format=pdf');assert.equal(res.status,200);assert.match(res.headers.get('content-disposition'),/du_fixture-evidence.pdf/);assert.equal((await get('?after=du_previous')).status,200);
const acceptance=await load('lib/purchase-acceptance.ts',{...finalSale,isIP:(await import('node:net')).isIP,db:async(path,method,body)=>{recorded.push(body);}});
const req=new Request('https://www.geticashx.com/api/funding/checkout',{headers:{'x-forwarded-for':'192.0.2.99','x-vercel-forwarded-for':'192.0.2.1','user-agent':'Fixture'}});
assert.equal(acceptance.purchaseContext(req,{}).ip,null);assert.equal(acceptance.purchaseContext(req,{VERCEL:'1'}).ip,'192.0.2.1');assert.equal(acceptance.purchaseContext(new Request(req.url,{headers:{'x-vercel-forwarded-for':'bad,192.0.2.2'}}),{VERCEL:'1'}).ip,null);
console.log('PASS disputes: owner auth before access, live/test isolation, charge binding, historic-only terms, pooled-credit attribution, missing/truncated evidence, signed-event shape, pagination, PDF routing and trusted request context. No provider requests.');
