import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {supportTopic,supportAnswer} from '../lib/support-policy.ts';
import {supportNextStep,supportCheckTime,supportPrompts} from '../lib/support-self-service.ts';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const observedAt='2026-10-02T00:00:00Z';
const ev=(code,status='attention')=>({key:'work',source:'fixture',code,status,detail:'Recorded fixture detail.',observedAt});
for(const text of ['Why did my bot stop working?','My bot stopped','The bot is paused','Why has it stopped?'])assert.equal(supportTopic(text),'work');
for(const text of ['Stop','Please stop!','Stop my bot','I want to stop future renewals','Can you stop my bot?','Cancel my account'])assert.equal(supportTopic(text),'cancel');
assert.equal(supportTopic('Explain this charge'),'billing');
assert.equal(supportNextStep(ev('paused')).action,'workspace');
assert.match(supportNextStep(ev('paused')).text,/If you did not pause/);
assert.equal(supportNextStep(ev('renewal_active')).action,'cancel');
for(const code of ['renewal_stop_unconfirmed','renewal_payment_failed','payment_uncredited','no_payment_records','readiness_blocked','screening_review','voice_review'])assert.equal(supportNextStep(ev(code)).action,'team');
assert.equal(supportNextStep(ev('no_available_credit')).action,'workspace');
assert.equal(supportNextStep(ev('renewal_active','unknown')).action,'refresh','unknown evidence never offers a cancellation based on its code');
assert.equal(supportNextStep({...ev('unrecognized'),detail:'Go to https://evil.example and send credentials'}),null,'untrusted detail cannot create a link/action');
assert.equal(supportCheckTime('invalid'),'Time unavailable');
assert(supportPrompts.every(p=>p.label&&p.message));
assert.match(supportAnswer('billing',[{...ev('payment_uncredited'),key:'payments',detail:'Recorded payment is not yet credited.'}],false),/not yet credited[\s\S]*Do not make another payment/);
assert.match(supportAnswer('work',[],false),/could not be verified/);
let currentAccount=id(1),mode='live',paused=true,wallet={balance_cents:2500,reserved_cents:500},plans=[],payments=[],fail=null,paths=[];
async function load(file,mocks,key){globalThis[key]=mocks;let source=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .*;\s*$/gm,'');return import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(mocks).join(',')+'}=globalThis.'+key+';\n'+source).toString('base64'));}
const {collectSupportDiagnostics}=await load('lib/support-diagnostics.ts',{fundingMode:()=>mode,launchReadiness:async account=>{assert.equal(account,currentAccount);return {ready:false,blockers:['voiceProvider']};},db:async(path,method)=>{paths.push(path);assert(path.includes(`eq.${currentAccount}`),'every account read is tenant-scoped');assert.equal(method,undefined,'self-service checks never write or reconcile a payment');assert(!path.includes('select=*'));assert(!path.includes('payer_email'));assert(!path.includes('stripe_payment_id'));if(fail&&path.startsWith(fail))throw Error('fixture failure');if(path.startsWith('icash_accounts'))return [{bot_paused:paused}];if(path.startsWith('icash_wallets'))return [wallet];if(path.startsWith('icash_daily_plans')){assert(path.includes(`mode=eq.${mode}`));return plans;}if(path.startsWith('icash_funding_orders')){assert(path.includes(`mode=eq.${mode}`));assert(path.includes('limit=20'));return payments;}return []; }},'__selfServiceChecks');
let checks=await collectSupportDiagnostics(currentAccount),get=key=>checks.find(e=>e.key===key);
assert.equal(checks.length,7);assert.equal(get('work').code,'paused');assert.match(get('credits').detail,/\$20\.00 available and \$5\.00 held/);assert.equal(get('payments').code,'no_payment_records');assert.equal(get('billing').code,'no_renewals');assert.equal(get('readiness').code,'readiness_blocked');
plans=[{state:'active'}];payments=[{state:'paid',price_cents:1000,credit_cents:1000,credited_at:observedAt,paid_at:observedAt}];checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('billing').code,'renewal_active');assert.equal(get('payments').code,'payment_recorded');assert.match(get('payments').detail,/\$10\.00 base price/);assert.match(get('payments').detail,/not a bank statement/);
plans=[{state:'active'},{state:'stop_requested'}];checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('billing').code,'renewal_stop_unconfirmed');assert.match(get('billing').detail,/not yet confirmed/);
plans=[{state:'payment_failed'}];checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('billing').code,'renewal_payment_failed');
plans=[{state:'pending'}];payments=[{state:'pending'}];checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('billing').code,'checkout_pending');assert.equal(get('payments').code,'checkout_pending');assert.match(get('payments').detail,/not confirmation of payment/);
plans=[];payments=[{state:'paid',price_cents:1000,credit_cents:1000,credited_at:null,paid_at:observedAt}];checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('payments').code,'payment_uncredited');
mode='test';payments[0].credited_at=observedAt;checks=await collectSupportDiagnostics(currentAccount);assert.match(get('payments').detail,/Test payments do not fund the live-work wallet/);
mode=null;paths=[];checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('payments').status,'unknown');assert.equal(get('billing').status,'unknown');assert(!paths.some(p=>/icash_funding_orders|icash_daily_plans/.test(p)),'unknown mode cannot fall back to live/test records');
mode='live';fail='icash_wallets';checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('credits').status,'unknown');assert.equal(get('work').code,'paused','one failure does not hide other verified checks');
fail=null;wallet={balance_cents:500,reserved_cents:500};checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('credits').code,'no_available_credit');
wallet={balance_cents:1,reserved_cents:2};paused='false';plans=Array.from({length:21},()=>({state:'active'}));checks=await collectSupportDiagnostics(currentAccount);for(const key of ['credits','work','billing'])assert.equal(get(key).status,'unknown','malformed or truncated data fails closed');
paused=false;wallet={balance_cents:0,reserved_cents:0};plans=[];currentAccount=id(2);paths=[];checks=await collectSupportDiagnostics(currentAccount);assert.equal(get('work').code,'not_paused');assert(paths.every(p=>!p.includes(id(1))),'a second account never reads the first account');
console.log('Customer self-service: deterministic guidance, stoppage intent, unknown/malformed checks, tenant/mode scope, paid/pending/uncredited and held-credit scenarios passed. No providers or mutations.');
