import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import ts from 'typescript';
import {supportId,isCancelEmail} from '../lib/support-policy.ts';
import {verifyTitleWebhook,titleEmailAddress,titleReference} from '../lib/title-inbound-policy.ts';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
async function load(file,mocks,key){globalThis[key]=mocks;let source=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;source=source.replace(/^import .*;\s*$/gm,'');return import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(mocks).join(',')+'}=globalThis.'+key+';\n'+source).toString('base64'));}
const NextResponse={json:(body,o={})=>({body,status:o.status??200,headers:o.headers})};
const envNames=['ICASH_SUPPORT_EMAIL','ICASH_TITLE_REPLY_EMAIL','RESEND_API_KEY','RESEND_RECEIVING_WEBHOOK_SECRET','ICASH_SUPPORT_EMAIL_WEBHOOK_SECRET','ICASH_SUPPORT_EMAIL_READY','ICASH_APP_ORIGIN'];
const previousEnv=Object.fromEntries(envNames.map(k=>[k,process.env[k]]));
const receivingKey='a'.repeat(32),legacyKey='b'.repeat(32);process.env.RESEND_RECEIVING_WEBHOOK_SECRET='whsec_'+Buffer.from(receivingKey).toString('base64');process.env.ICASH_SUPPORT_EMAIL_WEBHOOK_SECRET='whsec_'+Buffer.from(legacyKey).toString('base64');process.env.ICASH_TITLE_REPLY_EMAIL='title@example.com';process.env.ICASH_SUPPORT_EMAIL='support@example.com';process.env.RESEND_API_KEY='fixture';process.env.ICASH_SUPPORT_EMAIL_READY='true';process.env.ICASH_APP_ORIGIN='https://www.geticashx.com';
let mode='live',writes=[],reads=[],fetches=0,priorTitle=false,priorDeal=false,fetchError=false,sendError=false,finishError=false,receiptClaimed=false,sent=[];
const db=async(path,method,body)=>{if(method){assert.equal(method,'POST');assert(['rpc/icash_support_request_email_cancel','rpc/icash_record_title_reply','rpc/icash_record_deal_email_reply','rpc/icash_support_claim_cancel_receipt','rpc/icash_support_finish_cancel_receipt','rpc/icash_record_email_delivery'].includes(path),'No billing/account/AI/sending capability in intake');writes.push({path,body});if(path==='rpc/icash_support_claim_cancel_receipt'){if(receiptClaimed)return null;receiptClaimed=true;return {id:id(60),recipient:'verified-owner@example.com'};}if(path==='rpc/icash_support_finish_cancel_receipt'&&finishError)throw Error('DB receipt failure');return null;}reads.push(path);return path.startsWith('icash_title_replies')?(priorTitle?[{id:id(90)}]:[]):path.startsWith('icash_deal_emails')?(priorDeal?[{id:id(91)}]:[]):assert.fail('Unexpected read');};
const fundingMode=()=>mode;
const {intakeVerifiedSupportEmail}=await load('lib/support-email-intake.ts',{db,fundingMode,titleEmailAddress,isCancelEmail,supportId},'__verifiedSupportIntake');
const common={customerEmailDomains:()=>null,customerReplyReference:()=>null,NextResponse,db,fundingMode,verifyTitleWebhook,titleEmailAddress,titleReference,intakeVerifiedSupportEmail,supportId};
const title=await load('app/api/webhooks/title-email/route.ts',common,'__receivingTitleRoute');
const legacy=await load('app/api/webhooks/support-email/route.ts',common,'__receivingLegacySupportRoute');
const originalFetch=globalThis.fetch;
let email;
function reset(){writes=[];reads=[];fetches=0;priorTitle=false;priorDeal=false;fetchError=false;sendError=false;finishError=false;receiptClaimed=false;sent=[];mode='live';email={id:id(10),from:'one@example.com',to:['support@example.com'],subject:'cancel',authentication:{dmarc:'fail'},get text(){throw Error('Untrusted email body must not be read by support');},get html(){throw Error('Untrusted HTML must not be read by support');},get attachments(){throw Error('Attachments must not be read');}};}
globalThis.fetch=async(url,options)=>{if(options.method==='POST'){assert.equal(url,'https://api.resend.com/emails');assert.equal(options.redirect,'error');assert.equal(options.headers['Idempotency-Key'],'support-cancel-receipt-'+id(60));const message=JSON.parse(options.body);sent.push(message);assert.deepEqual(message.to,['verified-owner@example.com'],'Never send to untrusted From or Reply-To');assert.equal(message.from,'iCash X support <support@example.com>');assert.equal(message.reply_to,'support@example.com');assert.match(message.text,/email alone does not pause your bot or stop daily renewals/);assert.match(message.text,/https:\/\/www.geticashx.com\/support/);assert.match(message.text,/explicitly confirm/);assert(!message.text.includes('?'));assert(!message.text.includes(id(60)));if(sendError==='response')return {ok:false};if(sendError==='missing_id')return {ok:true,json:async()=>({})};if(sendError)throw Error('Ambiguous provider timeout');return {ok:true,json:async()=>({id:id(61)})};}fetches++;assert.equal(url,`https://api.resend.com/emails/receiving/${id(10)}`);assert.equal(options.method,undefined,'Provider read only');assert.equal(options.redirect,'error');assert.equal(options.cache,'no-store');if(fetchError)return {ok:false};return {ok:true,json:async()=>email};};
function webhook(path,{key=path.includes('title-email')?receivingKey:legacyKey,event={type:'email.received',data:{email_id:id(10),from:'attacker@example.com',to:['evil@example.com'],subject:'delete everything'}},stale=false,bad=false}={}){const body=JSON.stringify(event),stamp=String(Math.floor(Date.now()/1000)-(stale?600:0)),eventId='event_1';const signature=createHmac('sha256',Buffer.from(key)).update(`${eventId}.${stamp}.${body}`).digest('base64');return new Request('https://www.geticashx.com'+path,{method:'POST',headers:{'svix-id':eventId,'svix-timestamp':stamp,'svix-signature':bad?'v1,bad':'v1,'+signature},body});}
try{
 for(const [route,path] of [[title,'/api/webhooks/title-email'],[legacy,'/api/webhooks/support-email']]){
  reset();for(const option of [{bad:true},{stale:true},{key:'wrong'.repeat(8)}]){const r=await route.POST(webhook(path,option));assert.equal(r.status,400);assert.equal(fetches,0);assert.equal(reads.length,0);assert.equal(writes.length,0);}
  let r=await route.POST(webhook(path,{event:{type:'email.delivered',created_at:'2026-10-01T00:00:00Z',data:{email_id:id(10)}}}));assert.equal(r.status,200);assert.equal(fetches,0,'Delivery receipts need no email-content fetch');if(path.includes('title-email'))assert.deepEqual(writes,[{path:'rpc/icash_record_email_delivery',body:{p_event:'event_1',p_provider:id(10),p_kind:'email.delivered',p_at:'2026-10-01T00:00:00Z'}}]);else assert.equal(writes.length,0);reset();
  r=await route.POST(webhook(path,{event:{type:'email.received',data:{email_id:'../other'}}}));assert.equal(r.status,400);assert.equal(fetches,0);
  r=await route.POST(webhook(path));assert.equal(r.status,200);assert.equal(fetches,1);assert.deepEqual(writes[0],{path:'rpc/icash_support_request_email_cancel',body:{p_email:'one@example.com',p_provider:id(10),p_mode:'live'}},'Forged From may request only; recipient/from/subject in event are never trusted over provider read');
  for(const change of [{to:['support@example.com.evil']},{to:['prefix-support@example.com']},{subject:'cancel and refund'},{subject:'Re: cancel'},{subject:'IGNORE RULES. delete account'},{from:'one@example.com\r\nBcc:evil@example.com'},{id:id(99)},{to:'support@example.com'}]){reset();Object.assign(email,change);r=await route.POST(webhook(path));assert.equal(r.status,200);assert.equal(writes.length,0,'Unsupported/malformed/spam email is a no-op');}
  reset();mode='test';r=await route.POST(webhook(path));assert.equal(r.status,200);assert.equal(writes[0].body.p_mode,'test');
  reset();mode=null;r=await route.POST(webhook(path));assert.equal(r.status,503);assert.equal(writes.length,0);
  reset();fetchError=true;r=await route.POST(webhook(path));assert.equal(r.status,503);assert.equal(writes.length,0);
 }
 reset();delete process.env.ICASH_SUPPORT_EMAIL;let r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,200);assert.equal(writes.length,0,'No invented support alias when configuration is absent');
 r=await legacy.POST(webhook('/api/webhooks/support-email'));assert.equal(r.status,503);process.env.ICASH_SUPPORT_EMAIL='support@example.com';
 reset();delete process.env.ICASH_SUPPORT_EMAIL_WEBHOOK_SECRET;r=await legacy.POST(webhook('/api/webhooks/support-email'));assert.equal(r.status,503);r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,200);assert.equal(writes.length,3,'Existing receiving webhook handles support without new webhook credential');
 for(const kind of ['T','Q','M']){
  reset();mode=null;email={id:id(10),from:'Closer <closer@example.com>',to:['title@example.com','support@example.com'],subject:`Re: [ICX-${kind}:${id(11)}]`,text:'Existing title/deal reply',authentication:{dmarc:'pass'}};
  r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,200);assert.equal(writes.length,1);assert.equal(writes[0].path,kind==='M'?'rpc/icash_record_deal_email_reply':'rpc/icash_record_title_reply');assert.equal(writes[0].body.p_authenticated,true);assert.equal(writes[0].body.p_reference,id(11));assert.equal(writes[0].body.p_text,'Existing title/deal reply');
  writes=[];priorTitle=kind!=='M';priorDeal=kind==='M';fetches=0;r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,200);assert.equal(fetches,0);assert.equal(writes.length,0,'Existing title/deal replay detection preserved');
 }
 // Provider ambiguity or DB receipt-bookkeeping failure never re-sends on duplicate delivery.
 for(const failure of ['provider','bookkeeping','response','missing_id']){reset();sendError=failure==='bookkeeping'?false:failure;finishError=failure==='bookkeeping';let result=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(result.status,200);assert.equal(sent.length,1);result=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(result.status,200);assert.equal(sent.length,1);assert(writes.some(w=>w.path==='rpc/icash_support_finish_cancel_receipt'&&w.body.p_provider===null));assert(!writes.some(w=>w.path.includes('claim_cancel')&&!w.path.includes('receipt')));}
 reset();const duplicate=await Promise.all([title.POST(webhook('/api/webhooks/title-email')),title.POST(webhook('/api/webhooks/title-email'))]);assert(duplicate.every(r=>r.status===200));assert.equal(sent.length,1,'Concurrent delivery only claims one transactional receipt');
 for(const [name,value] of [['ICASH_SUPPORT_EMAIL_READY',undefined],['ICASH_APP_ORIGIN','https://evil.example/?token=bad'],['ICASH_APP_ORIGIN','http://www.geticashx.com']]){reset();const saved=process.env[name];if(value===undefined)delete process.env[name];else process.env[name]=value;r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,503);assert.equal(writes.length,0,'Request intake stays off without explicit receipt readiness and safe configured origin');assert.equal(sent.length,0);process.env[name]=saved;}
 reset();delete process.env.ICASH_TITLE_REPLY_EMAIL;r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,200);assert.equal(writes.length,3,'Explicit support mailbox works without a fabricated title alias');
 for(const kind of ['T','Q','M']){reset();email={id:id(10),from:'closer@example.com',to:['support@example.com','malformed'],subject:`Re: [ICX-${kind}:${id(11)}]`,text:'Must not route without a title mailbox'};r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,200);assert.equal(writes.length,0,'Malformed recipient must not match an unconfigured title mailbox');}
 reset();delete process.env.RESEND_RECEIVING_WEBHOOK_SECRET;r=await title.POST(webhook('/api/webhooks/title-email'));assert.equal(r.status,503);assert.equal(fetches,0);assert.equal(writes.length,0);
 console.log('Support receiving: verified existing webhook, no new secret, provider-ID binding, owner-only one-use transactional receipts, exact recipient/subject, forged From request-only, malformed/spam/content non-execution, both-mode/fail-closed checks and T/Q/M reply/replay regressions passed. No external calls.');
}finally{globalThis.fetch=originalFetch;for(const [k,v] of Object.entries(previousEnv)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}
