import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import ts from 'typescript';
import {z} from 'zod';
import {supportId,supportMessageInput,supportAnswer,redactSupportQuestion,supportStatusInput,hashCancelNonce,createCancelToken,parseCancelToken} from '../lib/support-policy.ts';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,accountId=id(1),userId=id(2),threadId=id(3);
async function load(file,mocks,key){globalThis[key]=mocks;let source=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;source=source.replace(/^import .*;\s*$/gm,'');return import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(mocks).join(',')+'}=globalThis.'+key+';\n'+source).toString('base64'));}
const NextResponse={json:(body,o={})=>({body,status:o.status??200,headers:o.headers})};let authorized=true,origin=true,paths=[],replay=false,rateLimited=false,diagnostics=0;
let activeMode='live',activeAccount=accountId,activeUser=userId;const fundingMode=()=>activeMode;
const workAccount=async()=>{if(!authorized)throw Error('SIGN_IN_REQUIRED');return {accountId:activeAccount,userId:activeUser};};
const request=(path,body)=>new Request('https://www.geticashx.com'+path,{method:'POST',headers:{origin:'https://www.geticashx.com','Content-Type':'application/json'},body:JSON.stringify(body)});
const route=await load('app/api/support/route.ts',{NextResponse,z,workAccount,db:async(path,method,body)=>{paths.push({path,method,body});if(path.startsWith('rpc/')){assert.equal(body.p_account,accountId);assert.equal(body.p_user,userId);if(path.endsWith('begin_message'))return {threadId,replay,rateLimited,response:replay?{content:'saved'}:null};if(path.endsWith('escalate'))return body.p_thread===threadId;return null;}assert(path.includes(`account_id=eq.${accountId}`),'Tenant filter on every read');if(path.startsWith('icash_support_threads'))return [{id:threadId,subject:'Help',status:'open'}];return [];},allowedOrigin:()=>origin,fundingMode,supportId,supportMessageInput,supportAnswer,redactSupportQuestion,collectSupportDiagnostics:async id=>{assert.equal(id,accountId);diagnostics++;return [];},classifySupportQuestion:async()=>({topic:'general',ai:false})},'__supportRoute');
authorized=false;let r=await route.GET(new Request('https://example.com/api/support'));assert.equal(r.status,401);assert.equal(paths.length,0);
authorized=true;r=await route.GET(new Request('https://example.com/api/support?threadId='+id(99)));assert.equal(r.status,404);
paths=[];origin=false;r=await route.POST(request('/api/support',{requestId:id(4),message:'help'}));assert.equal(r.status,403);assert.equal(paths.length,0);origin=true;
r=await route.POST(request('/api/support',{requestId:id(4),message:'help',accountId:id(99)}));assert.equal(r.status,400);assert.equal(paths.length,0);
r=await route.POST(request('/api/support',{requestId:id(4),message:'Why paused?'}));assert.equal(r.status,200);assert.equal(diagnostics,1);assert(paths.some(x=>x.path.endsWith('finish_message')));
paths=[];replay=true;r=await route.POST(request('/api/support',{requestId:id(4),message:'Why paused?'}));assert.equal(r.status,200);assert.equal(diagnostics,1,'Duplicate request never calls model/diagnostics again');assert.equal(paths.length,1);
replay=false;rateLimited=true;r=await route.POST(request('/api/support',{requestId:id(5),message:'help'}));assert.equal(r.status,429);assert.equal(diagnostics,1);rateLimited=false;
r=await route.POST(request('/api/support',{action:'escalate',threadId:id(99)}));assert.equal(r.status,404);
r=await route.POST(request('/api/support',{action:'escalate',threadId}));assert.equal(r.body.escalated,true);
r=await route.GET(new Request('https://example.com/api/support'));assert.equal(r.status,200);assert.deepEqual(r.body.evidence,[]);assert.equal(r.headers['Cache-Control'],'private, no-store');assert.equal(diagnostics,2,'current diagnostics are tenant-bound and returned by authenticated GET');
let stopFailure=false,stops=0,prepared=null;paths=[];delete process.env.ICASH_SUPPORT_CANCEL_SECRET;
const cancel=await load('app/api/support/cancel/route.ts',{NextResponse,randomBytes,z,workAccount,db:async(path,method,body)=>{
 paths.push({path,method,body});
 if(path.endsWith('prepare_cancel')){assert.equal(body.p_account,accountId);assert.equal(body.p_user,userId);assert.equal(body.p_mode,activeMode);assert.match(body.p_nonce,/^[a-f0-9]{64}$/);prepared={account:body.p_account,user:body.p_user,mode:body.p_mode,hash:body.p_nonce,consumed:false};return id(6);}
 if(path.endsWith('claim_cancel')){const valid=prepared&&!prepared.consumed&&body.p_account===prepared.account&&body.p_user===prepared.user&&body.p_mode===prepared.mode&&body.p_request===id(6)&&body.p_nonce===prepared.hash;if(valid)prepared.consumed=true;return !!valid;}
 if(path.startsWith('icash_daily_plans')){assert(path.includes('account_id=eq.'+accountId));assert(path.includes('mode=eq.'+activeMode),'Read and verification must exclude other-mode plans');return path.includes('select=*')?[{id:id(7),account_id:accountId,mode:activeMode}]:[];}
 if(path.startsWith('icash_accounts'))return [{bot_paused:true}];assert(path.includes('account_id=eq.'+accountId));assert(path.includes('mode=eq.'+activeMode));return [];
},allowedOrigin:()=>origin,fundingMode,stopDaily:async p=>{assert.equal(p.account_id,accountId);assert.equal(p.mode,activeMode,'Never cancel another mode with current Stripe credentials');stops++;if(stopFailure)throw Error('provider unavailable');},supportId,hashCancelNonce,createCancelToken,parseCancelToken},'__cancelRoute');
authorized=false;r=await cancel.POST(request('/api/support/cancel',{action:'prepare'}));assert.equal(r.status,401);assert.equal(paths.length,0);authorized=true;
r=await cancel.POST(new Request('https://www.geticashx.com/api/support/cancel',{method:'POST',headers:{origin:'https://alternate.geticashx.com'},body:JSON.stringify({action:'prepare'})}));assert.equal(r.status,403);assert.equal(paths.length,0,'Alias-origin requests cannot prepare even if general origin policy permits them');
activeMode=null;r=await cancel.POST(request('/api/support/cancel',{action:'prepare'}));assert.equal(r.status,503);assert.equal(paths.length,0);activeMode='live';
r=await cancel.POST(request('/api/support/cancel',{action:'prepare'}));assert.equal(r.status,200);assert.equal(r.headers['Cache-Control'],'private, no-store');assert(r.body.token);const token=r.body.token;
assert.notEqual(parseCancelToken(token).nonce,prepared.hash,'Only hash persists');assert.equal(hashCancelNonce(parseCancelToken(token).nonce),prepared.hash);
paths=[];r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:false}));assert.equal(r.status,400);assert.equal(paths.length,0);assert.equal(stops,0);
for(const t of [id(6),token+'.extra','e30.signature']){r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token:t,acknowledged:true}));assert.equal(r.status,400);assert.equal(paths.length,0);}
for(const t of [createCancelToken(id(99),parseCancelToken(token).nonce),createCancelToken(id(6),'f'.repeat(64))]){r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token:t,acknowledged:true}));assert.equal(r.status,409);assert.equal(stops,0);}
activeAccount=id(99);r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:true}));assert.equal(r.status,409);activeAccount=accountId;
activeUser=id(99);r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:true}));assert.equal(r.status,409);activeUser=userId;
activeMode='test';r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:true}));assert.equal(r.status,409);assert.equal(stops,0);activeMode='live';
const race=await Promise.all([cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:true})),cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:true}))]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);assert.equal(stops,1,'Only one claim executes provider calls');assert(race.some(r=>r.body.confirmed===true));
r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:true}));assert.equal(r.status,409);assert.equal(stops,1);
const replacement=await cancel.POST(request('/api/support/cancel',{action:'prepare'}));assert.notEqual(replacement.body.token,token);r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token,acknowledged:true}));assert.equal(r.status,409,'Preparing again invalidates earlier nonce');
stopFailure=true;r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token:replacement.body.token,acknowledged:true}));assert.equal(r.status,202);assert.equal(r.body.confirmed,false);assert.match(r.body.message,/not yet confirmed/);assert(paths.some(p=>p.body?.state==='needs_review'));
stopFailure=false;activeMode='test';r=await cancel.POST(request('/api/support/cancel',{action:'prepare'}));assert.match(r.body.summary,/test daily renewals/);const testToken=r.body.token;activeMode='live';r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token:testToken,acknowledged:true}));assert.equal(r.status,409);activeMode='test';r=await cancel.POST(request('/api/support/cancel',{action:'confirm',token:testToken,acknowledged:true}));assert.equal(r.status,200);assert.match(r.body.message,/test daily renewals/);activeMode='live';
let operator=false;paths=[];const admin=await load('app/api/support/admin/route.ts',{NextResponse,z,requireTrustedOperator:async()=>{if(!operator)throw Error('OPERATOR_REQUIRED');return {userId};},db:async(path,method,body)=>{paths.push({path,method,body});if(path.startsWith('icash_support_threads?id='))return [{id:threadId,account_id:accountId,subject:'Help',status:'open'}];return [];},allowedOrigin:()=>origin,fundingMode,supportId,supportStatusInput,redactSupportQuestion,collectSupportDiagnostics:async a=>{assert.equal(a,accountId);return [];},supportDeploymentHealth:async()=>({status:'unavailable'})},'__adminRoute');
r=await admin.GET(new Request('https://example.com/api/support/admin'));assert.equal(r.status,403);assert.equal(paths.length,0);
r=await admin.POST(request('/api/support/admin',{requestId:id(8),threadId,status:'resolved'}));assert.equal(r.status,403);assert.equal(paths.length,0);
operator=true;r=await admin.GET(new Request('https://example.com/api/support/admin'));assert.equal(r.status,200);assert(paths.some(p=>p.path.includes('receipt_state.in.(claimed,needs_review,suppressed,rate_limited)')),'Operators can see receipt exceptions without implying cancellation');r=await admin.GET(new Request('https://example.com/api/support/admin?threadId='+threadId));assert.equal(r.status,200);assert(paths.some(p=>p.path.includes('account_id=eq.'+accountId)));
r=await admin.POST(request('/api/support/admin',{requestId:id(8),threadId,status:'waiting_on_customer',reply:'Please retry'}));assert.equal(r.status,200);assert(paths.some(p=>p.path==='rpc/icash_support_operator_update'&&p.body.p_operator===userId));
console.log('Support routes: auth/exact-origin/tenant/admin isolation, strict inputs, duplicate/rate gates, per-request nonce, replay/race/replacement protection, both-mode isolation and partial provider failure passed. No external calls.');
