import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
let state='ready',allow=true,sends=0,timeout=false,records=[];
const db=async(path,method,body)=>{records.push({path,method,body});if(method==='PATCH'){state=body.state;return [];}if(path==='rpc/icash_queue_title_qualification')return null;if(path==='rpc/icash_claim_title_qualification'){assert.equal(body.p_recipient,'office@example.invalid');if(allow)state='dispatching';return allow;}if(path.startsWith('icash_title_qualification_jobs'))return state==='ready'?[{id:'job',company_id:'company',market:'Dallas',state_code:'TX'}]:[];if(path.startsWith('icash_title_directory'))return [{name:'Fixture',public_email:'office@example.invalid',contact_checked_until:'2099-01-01'}];if(path.startsWith('icash_customer_identities'))return [{principal:'Fixture Principal'}];return [{id:'rate'}];};
globalThis.__title={db,reserveOperation:async()=>{},completedSigningPdf:async()=>new Uint8Array([1,2,3]).buffer};
const realFetch=globalThis.fetch;globalThis.fetch=async()=>{sends++;if(timeout)throw Error('timeout');return {ok:true,json:async()=>({id:'email_fixture'})};};
process.env.RESEND_API_KEY='fixture';process.env.ICASH_TITLE_FROM_EMAIL='fixture@example.invalid';process.env.ICASH_TITLE_REPLY_EMAIL='inbox@example.invalid';
let source=ts.transpileModule(readFileSync('lib/title-directory-service.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');
const {qualifyTitleCompanies}=await import('data:text/javascript;base64,'+Buffer.from('const {db,reserveOperation,completedSigningPdf}=globalThis.__title;\n'+source).toString('base64'));
assert.equal((await qualifyTitleCompanies('account','deal')).status,'title_inquiry_sent');assert.equal(sends,1);await qualifyTitleCompanies('account','deal');assert.equal(sends,1);
state='ready';allow=false;await qualifyTitleCompanies('account','deal');assert.equal(sends,1);
state='ready';allow=true;timeout=true;assert.equal((await qualifyTitleCompanies('account','deal')).status,'title_inquiry_needs_reconciliation');await qualifyTitleCompanies('account','deal');assert.equal(sends,2);
assert(!records.some(r=>r.body?.stage==='title_open'||r.body?.stage==='closed'));
globalThis.fetch=realFetch;delete globalThis.__title;delete process.env.RESEND_API_KEY;delete process.env.ICASH_TITLE_FROM_EMAIL;
console.log('Title qualification: claim gate, no replay, ambiguous delivery hold, no fabricated closing status passed. No emails sent.');
