import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import * as policy from '../lib/vip-policy.ts';
import * as embeddedPolicy from '../lib/embedded-checkout-policy.ts';
let m,c,s,session,pi,calls;
const id='00000000-0000-4000-8000-000000000001',end=Math.floor(Date.now()/1000)+864000;
function reset(){calls=[];m={id,account_id:'account',mode:'live',state:'active',price_cents:5000,paid_through:new Date(end*1000).toISOString(),stripe_subscription_id:'sub_one',stripe_customer_id:'cus_one',vip_until:null};c=null;s={id:'sub_one',metadata:{icash_membership:id},livemode:true,customer:'cus_one',status:'active',cancel_at_period_end:false,pending_update:null,schedule:null,items:{has_more:false,data:[{id:'si_one',quantity:1,current_period_end:end,price:{id:'price_standard',currency:'usd',unit_amount:5000,product:'prod_one',recurring:{interval:'month',interval_count:1}}}]}};session={id:'cs_live_vip',metadata:{icash_vip_change:id},mode:'payment',livemode:true,customer:'cus_one',currency:'usd',amount_total:5000,amount_subtotal:5000,total_details:{amount_discount:0,amount_tax:0},status:'open',payment_status:'unpaid',payment_intent:'pi_one',url:'https://checkout.stripe.com/fixture'};pi={id:'pi_one',status:'succeeded',amount_received:5000,currency:'usd',livemode:true,customer:'cus_one'};}
const stripe={subscriptions:{retrieve:async()=>s,update:async(id,body,options)=>{calls.push({kind:'update',id,body,options});assert.equal(body.proration_behavior,'none');assert.equal(body.items.length,1);assert.equal(body.items[0].id,'si_one');s.items.data[0].price={...s.items.data[0].price,id:body.items[0].price,unit_amount:c.to_price};return structuredClone(s);}},prices:{create:async(body,options)=>{calls.push({kind:'price',body,options});return {id:'price_'+c.to_price};}},checkout:{sessions:{create:async(body,options)=>{calls.push({kind:'checkout',body,options});session={...session,...(body.ui_mode==='embedded_page'?{ui_mode:'embedded_page',client_secret:'cs_live_secret_fixture',url:null}:{ui_mode:'hosted_page',client_secret:null,url:'https://checkout.stripe.com/fixture'})};return session;},retrieve:async()=>session,expire:async id=>{calls.push({kind:'expire',id});session.status='expired';}}},paymentIntents:{retrieve:async()=>pi}};
const db=async(path,method,body)=>{calls.push({path,method,body});if(path.startsWith('icash_memberships'))return [{...m}];if(path.startsWith('icash_plan_changes')){if(method==='PATCH'){Object.assign(c,body);return [c];}return c&&(!path.includes('state=in.')||['pending','paid'].includes(c.state))?[{...c}]:[];}if(path==='rpc/icash_begin_plan_change'){c??={id,membership_id:m.id,account_id:m.account_id,action:body.p_action,state:'pending',period_end:m.paid_through,from_price:m.price_cents,to_price:body.p_action==='downgrade'?5000:10000,session_id:null,price_id:null,payment_id:null};return {...c};}if(path==='rpc/icash_mark_plan_change_paid'){c.state='paid';c.payment_id=body.p_payment;return;}if(path==='rpc/icash_apply_plan_change'){assert.equal(body.p_subscription,m.stripe_subscription_id);m.price_cents=c.to_price;if(c.action==='upgrade')m.vip_until=c.period_end;c.state='applied';return;}throw Error(path);};
const deps={...policy,...embeddedPolicy,checkoutPublishableKey:()=> 'pk_live_fixture',db,fundingStripe:()=>stripe,fundingMode:()=> 'live'};globalThis.__vip=deps;const code=ts.transpileModule(readFileSync(new URL('../lib/vip-membership.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .*;\s*$/gm,'');const api=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.__vip;\n'+code).toString('base64'));
reset();await api.changeVipPlan(m,'upgrade','https://www.geticashx.com');assert.equal(calls.filter(c=>c.kind==='checkout').length,1);assert.equal(calls.find(c=>c.kind==='checkout').body.line_items[0].price_data.unit_amount,5000);assert.equal(m.price_cents,5000);assert.equal(m.vip_until,null);
await api.changeVipPlan(m,'upgrade','https://www.geticashx.com');assert.equal(calls.filter(c=>c.kind==='checkout').length,1,'Reuse open checkout');
session.status='complete';session.payment_status='paid';await api.reconcileVipCheckout(session.id);assert.equal(m.price_cents,10000);assert.equal(m.vip_until,m.paid_through);assert.equal(s.items.data[0].current_period_end,end);
await api.reconcileVipCheckout(session.id);assert.equal(calls.filter(c=>c.kind==='update').length,1,'Payment replay cannot double apply');
c=null;await api.changeVipPlan(m,'downgrade','https://www.geticashx.com');assert.equal(m.price_cents,5000);assert.equal(policy.vipActive(m),true);assert.equal(calls.filter(c=>c.kind==='checkout').length,1,'No payment for downgrade');
c=null;await api.changeVipPlan(m,'keep_vip','https://www.geticashx.com');assert.equal(m.price_cents,10000);assert.equal(calls.filter(c=>c.kind==='checkout').length,1,'Restore VIP renewal without another upgrade charge');
for(const mutate of [()=>session.customer='cus_other',()=>session.amount_total=4999,()=>session.livemode=false,()=>pi.amount_received=1,()=>pi.customer='cus_other',()=>pi.status='processing']){reset();await api.changeVipPlan(m,'upgrade','https://www.geticashx.com');session.status='complete';session.payment_status='paid';mutate();await assert.rejects(api.reconcileVipCheckout(session.id));assert.equal(m.vip_until,null);assert(!calls.some(c=>c.kind==='update'));}
assert.equal(policy.vipPrice(1000,'lead'),800);assert.equal(policy.vipPrice(1000,'usage'),800);
console.log('PASS VIP checkout: exactly $50 once, verified payment before access, $100 renewal on same date, $50 downgrade, restore without recharge, tampered receipts rejected');

reset();const inline=await api.changeVipPlan(m,'upgrade','https://www.geticashx.com',{webinar:true,embedded:true});assert.equal(inline.clientSecret,'cs_live_secret_fixture');assert.equal(inline.publishableKey,'pk_live_fixture');assert.equal(calls.find(c=>c.kind==='checkout').body.redirect_on_completion,'never');assert.equal(calls.find(c=>c.kind==='checkout').body.success_url,undefined);assert.equal(m.vip_until,null);await api.changeVipPlan(m,'upgrade','https://www.geticashx.com',{webinar:true,embedded:true});assert.equal(calls.filter(c=>c.kind==='checkout').length,1);
reset();await api.changeVipPlan(m,'upgrade','https://www.geticashx.com',{webinar:true});assert.equal(calls.find(c=>c.kind==='checkout').body.success_url,'https://www.geticashx.com/webinar/upgrade?upgrade=paid&vip_session={CHECKOUT_SESSION_ID}');assert.equal(calls.find(c=>c.kind==='checkout').body.cancel_url,'https://www.geticashx.com/webinar/upgrade');
reset();await api.changeVipPlan(m,'upgrade','https://www.geticashx.com');session.customer='cus_other';await assert.rejects(api.changeVipPlan(m,'upgrade','https://www.geticashx.com'),/binding|mismatch/);assert.equal(calls.filter(c=>c.kind==='checkout').length,1);
console.log('PASS inline VIP upgrade and safe hosted return: same-session retry, no access before payment, and customer binding.');
