import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {voicePreflight} from '../scripts/voice-preflight.mjs';
import {costCategories} from '../lib/cost-guard.ts';
const now=Date.parse('2026-09-30T12:00:00Z');
const config={conversation:{max_duration_seconds:600},agent:{prompt:{tool_ids:['callback','handoff']}}};
const account={account_id:'00000000-0000-0000-0000-000000000001',enabled:true,agent_id:'agent_production',phone_number_id:'phone',agent_config_hash:createHash('sha256').update(JSON.stringify(config)).digest('hex'),reviewed_until:new Date(now+60000).toISOString(),max_duration_seconds:600,required_tool_ids:['callback','handoff'],seller_rate_id:'seller',buyer_rate_id:'buyer'};
const rate=operation=>({id:operation.split('_')[0],operation,enabled:true,verified_at:new Date(now-1000).toISOString(),expires_at:new Date(now+60000).toISOString(),voice_max_duration_seconds:600,costs_micros:Object.fromEntries(costCategories.map(k=>[k,100])),evidence_ref:'fixture rates, never live'});
const env={SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_SECRET_KEY:'secret-fixture',ELEVENLABS_API_KEY:'voice-fixture',CONTIGUITY_FROM:'+14243948384'};
let configs=[account],rates=[rate('seller_call'),rate('buyer_call')],practice=[],phone='+14243948384',requests=[];
const fetcher=async(url,options)=>{assert.equal(options.method,'GET');assert.equal(options.redirect,'error');requests.push(url);const data=url.includes('/rest/v1/icash_voice_configs')?configs:url.includes('/rest/v1/icash_operation_rates')?rates:url.includes('/rest/v1/icash_voice_test_config')?practice:url.includes('/phone-numbers/')?{provider:'twilio',phone_number:phone}:{conversation_config:config};return Response.json(data);};
const run=()=>voicePreflight({env,fetcher,now});
let report=await run();assert.equal(report.configurationVerified,true);assert.equal(report.callsPlaced,0);assert(report.notVerified.includes('authorized_end_to_end_call'));
assert(!JSON.stringify(report).includes('secret-fixture'));assert(!JSON.stringify(report).includes('agent_production'));
configs=[];assert((await run()).blockers.includes('production_voice_configuration_missing'));configs=[account];
phone='+12125550123';assert.equal((await run()).configurationVerified,false);phone=env.CONTIGUITY_FROM;
practice=[{agent_id:account.agent_id}];assert.equal((await run()).accounts[0].checks.productionAgent,false);practice=[];
rates=[rate('seller_call')];assert.equal((await run()).accounts[0].checks.buyerRate,false);rates=[rate('seller_call'),rate('buyer_call')];
rates[0].expires_at=new Date(now).toISOString();assert.equal((await run()).accounts[0].checks.sellerRate,false);
const bad=await voicePreflight({env,fetcher:async()=>{throw Error('secret error text');},now});assert(!JSON.stringify(bad).includes('secret error text'));
requests=[];assert((await voicePreflight({env,fetcher,accountId:'bad&select=*'})).blockers.includes('invalid_account_id'));assert.equal(requests.length,0);
assert((await voicePreflight({env:{...env,SUPABASE_URL:'http://fixture.supabase.co'},fetcher})).blockers.includes('database_origin_invalid'));
console.log('Voice preflight: GET-only, sanitized failure, scoped IDs, missing configs, expired rates, practice isolation and caller mismatch passed. No provider traffic.');
