import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
import {membershipAccessible} from '../lib/membership-policy.ts';import {webinarLink} from '../lib/webinar-links.ts';
let calls=[],source={webinar_id:'main',is_preview:false,config:{}},rows=[],settings={},token='guest';
class WebinarError extends Error{constructor(status,message){super(message);this.status=status;}}
const deps={membershipAccessible,webinarLink,WebinarError,cookies:async()=>({get:()=>token?{value:token}:undefined}),validGuest:token=>token==='guest',guestHash:()=> 'owned-hash',webinarSession:async id=>{assert.equal(id,'owned-session');return {s:source};},db:async(path)=>{calls.push(path);if(path.startsWith('icash_webinar_settings'))return [{config:settings}];return rows;}};
globalThis.__vip=deps;const src=ts.transpileModule(readFileSync(new URL('../lib/webinar-vip.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .* from .*;$/gm,'');const api=await import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.__vip;\n'+src).toString('base64'));
rows=[{id:'vip'}];assert.equal(await api.checkoutVipSession('owned-session'),'vip');assert.match(calls.at(-1),/parent_webinar_id=eq.main/);
source.is_preview=true;await assert.rejects(()=>api.checkoutVipSession('owned-session'));source.is_preview=false;source.config.parentWebinarId='main';await assert.rejects(()=>api.checkoutVipSession('owned-session'));source.config={};
calls=[];settings={homepageVipId:'chosen'};await api.checkoutVipSession();assert.match(calls.at(-1),/id=eq.chosen/);settings={};await api.checkoutVipSession();assert.match(calls.at(-1),/status=eq.published.*order=public_code.asc/);
const paid={mode:'live',state:'active',paid_through:new Date(Date.now()+86400000).toISOString(),post_purchase_webinar_id:'vip'};rows=[{public_code:123457,config:{status:'published',videoUrl:'https://example.test/vip.mp4'}}];assert.equal(await api.paidVipDestination(paid),'/live/123457');
for(const patch of [{mode:'test'},{state:'pending'},{state:'needs_review'},{state:'cancelled'},{paid_through:null},{paid_through:'2020-01-01'},{post_purchase_webinar_id:null}]){calls=[];assert.equal(await api.paidVipDestination({...paid,...patch}),null);assert.equal(calls.length,0,'Unpaid/invalid purchases cannot resolve private videos');}
rows[0].config.status='draft';assert.equal(await api.paidVipDestination(paid),null,'Draft VIP safely falls back to setup');
rows=[paid];assert.equal(await api.webinarVipAccess(),true);assert.match(calls.at(-1),/guest_hash=eq.owned-hash&account_id=is.null/);token=null;assert.equal(await api.webinarVipAccess(),false);assert.equal(await api.webinarVipAccess('owned-account'),true);assert.match(calls.at(-1),/account_id=eq.owned-account/);rows=[{...paid,paid_through:'2020-01-01'}];assert.equal(await api.webinarVipAccess('owned-account'),false);
console.log('PASS VIP destination: verified purchase only, owned main session, explicit homepage selection, stable default, draft fallback, live mode and account/guest scoping.');
