import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {creditAmount,recordedProgress,nextWorkFunding} from '../lib/workspace-progress.ts';
const empty={analyzed:0,ownerRecords:0,screeningCandidates:0,contracts:0,closed:0};
assert.equal(recordedProgress(empty).empty,'No completed work is recorded yet.');
assert.deepEqual(recordedProgress(empty).items,[]);
assert.equal(recordedProgress({}).empty,'Completed-work totals are not available yet.');
assert.equal(recordedProgress({...empty,analyzed:undefined}).empty,'Completed-work totals are not available yet.');
assert.deepEqual(recordedProgress({...empty,analyzed:1}).items,['1 property analysis completed']);
assert.deepEqual(recordedProgress({...empty,analyzed:5,screeningCandidates:2}).items,['5 property analyses completed','2 analyses passed the first numbers check']);
assert.match(recordedProgress({...empty,screeningCandidates:1}).note,/do not mean a seller is interested/);
assert.deepEqual(recordedProgress({...empty,ownerRecords:2,contracts:1}).items,['2 owner lookup results recorded','1 seller signature recorded']);
assert.deepEqual(recordedProgress({...empty,contracts:2,closed:1}).items,['1 funded closing recorded']);
for(const bad of [-1,NaN,Infinity,1.1,'5',null])assert.deepEqual(recordedProgress({...empty,analyzed:bad}).items,[]);
for(const bad of [undefined,NaN,Infinity,-1,'20',null])assert.equal(creditAmount(bad),'Unavailable');
assert.equal(creditAmount(0),'$0.00');assert.equal(creditAmount(20),'$0.20');
const a={identity:{principal:'Synthetic'},balanceCents:20,reservedCents:65,paused:true,workReady:false,contactWorkReady:true,contactQuote:{chargeCents:50,maxContacts:2}};
let funding=nextWorkFunding(a);assert.equal(funding.needsFunding,true);assert.match(funding.detail,/\$0.50 planning hold/);assert.match(funding.detail,/\$0.30 more/);assert.doesNotMatch(funding.detail,/\$0.95/,'reserved credits must never be subtracted twice');
assert.equal(nextWorkFunding({...a,balanceCents:50}).needsFunding,false);assert.match(nextWorkFunding({...a,balanceCents:50}).detail,/cover this hold/);
assert.equal(nextWorkFunding({...a,balanceCents:undefined}).needsFunding,false);assert.match(nextWorkFunding({...a,balanceCents:undefined}).detail,/could not be confirmed/);
assert.equal(nextWorkFunding(a,true).needsFunding,false);assert.doesNotMatch(nextWorkFunding(a,true).detail,/\$/);
assert.equal(nextWorkFunding({...a,billingReview:true}).detail,null);
assert.equal(nextWorkFunding({...a,identity:null}).detail,null);
assert.equal(nextWorkFunding({...a,activeWork:true,paused:false}).needsFunding,false);
assert.match(nextWorkFunding({...a,contactWorkReady:false,discoveryWorkReady:true,discoveryQuote:{chargeCents:100,maxProperties:10}}).detail,/property search.*\$1.00/);
for(const chargeCents of [NaN,Infinity,-50,undefined,0])assert.match(nextWorkFunding({...a,contactQuote:{chargeCents,maxContacts:2}}).detail,/not available yet/);
assert.equal(nextWorkFunding({...a,workReady:true}).needsFunding,false,'do not predict which paid task runs when multiple channels are ready');
assert.match(nextWorkFunding({...a,contactWorkReady:false,smsWorkReady:false}).detail,/not confirmed yet.*funding does not clear/,'low-budget and setup holds do not invent a price');
const source=readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');
assert.match(source,/DailyBudgetControl balanceCents=\{account.balanceCents\}/);
assert.match(source,/reservedCents=\{account.reservedCents\}/);
assert.match(source,/Your next step/);
assert.match(source,/aria-label="Close funding"/);
assert.match(source,/addEventListener\('popstate',syncFunding\)/);
assert.match(source,/addEventListener\('hashchange',syncFunding\)/);
assert.match(source,/initialCode=\{fundingCode\|\|undefined\}/,'opening Manage preserves the actual plan');
console.log('PASS honest progress, first milestone, missing/invalid evidence, net credits, current cost holds, shortfall, blocked work, stale estimates and refill navigation');
