import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {z} from 'zod';
import * as policy from '../lib/workspace-assistant-policy.ts';
import {redactSupportQuestion} from '../lib/support-policy.ts';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const context={checkedAt:new Date().toISOString(),report:{days:1,timezone:'America/Chicago',startAt:new Date().toISOString(),endAt:new Date().toISOString(),leads:2,calls:4,texts:6,contracts:0},paused:true,balanceCents:1000,task:'Paused',active:false,needsYou:false,selectedId:id(5),hasMore:false,properties:[{id:id(5),address:'123 Fixture Lane, Demo, TX',offer:'$96,270.50',arv:'$211,000',repairs:'$59,185',fee:'$10,000',currentCalculation:true,stage:'Property researched',next:'Confirm seller terms.',summary:null,practice:false}]};
assert.match(policy.answerWorkspaceQuestion('report',context,null).text,/2 new leads, 4 calls, 6 texts, and 0 signed/);
assert.match(policy.answerWorkspaceQuestion('offer',context,null).text,/96,270.50/);
assert.match(policy.answerWorkspaceQuestion('offer',context,null).text,/\(ARV − repairs\) × 70% − wholesale fee/);
assert.match(policy.answerWorkspaceQuestion('offer',{...context,properties:[{...context.properties[0],currentCalculation:false}]},null).text,/do not contain a verified current calculation/);
assert.equal(policy.answerWorkspaceQuestion('offer',{...context,selectedId:null},id(99)).propertyId,null,'An invented property never resolves');
assert.match(policy.answerWorkspaceQuestion('status',context,null).text,/paused/);
assert.match(policy.answerWorkspaceQuestion('status',{...context,paused:false,balanceCents:0},null).text,/needs credits/);
assert.deepEqual(policy.answerWorkspaceQuestion('next',{...context,needsYou:true},null).actions,[{kind:'attention',label:'Review request'}]);
assert.deepEqual(policy.answerWorkspaceQuestion('resume',{...context,balanceCents:0},null).actions,[{kind:'funding',label:'Add money'}]);
assert(!policy.answerWorkspaceQuestion('pause',{...context,paused:false},null).text.includes('I paused'),'A reply never claims to execute work');
async function load(file,deps,key){globalThis[key]=deps;const s=ts.transpileModule(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/^import .*;\s*$/gm,'');return import('data:text/javascript;base64,'+Buffer.from('const {'+Object.keys(deps).join(',')+'}=globalThis.'+key+';\n'+s).toString('base64'));}
const ai=await load('lib/workspace-assistant-ai.ts',{z,...policy},'__assistantAI');
process.env.OPENAI_API_KEY='fixture-key';process.env.ICASH_SUPPORT_AI_MODEL='fixture-model';
let fetched=0;const fake=async(_url,options)=>{fetched++;const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.tools,undefined);assert(!options.body.includes('$96,270.50'),'Classifier never generates or receives financial amounts');return Response.json({id:'fixture-completion',usage:{prompt_tokens:100,completion_tokens:20},choices:[{finish_reason:'stop',message:{content:JSON.stringify({intent:'offer',propertyId:id(99)})}}]});};
let routed=await ai.routeWorkspaceQuestion('Explain the offer',{...context,selectedId:null},[],fake);assert.equal(routed.propertyId,null);assert.equal(routed.model,'fixture-model');assert.equal(routed.usage.prompt_tokens,100);
routed=await ai.routeWorkspaceQuestion('Pause my bot',context,[],fake);assert.equal(routed.intent,'pause');
routed=await ai.routeWorkspaceQuestion('Explain this offer',context,[],async()=>{throw Error('fixture timeout');});assert.equal(routed.intent,'offer');assert.equal(routed.propertyId,id(5));
delete process.env.OPENAI_API_KEY;delete process.env.ICASH_SUPPORT_AI_MODEL;
let authorized=true,origin=true,subscription=true,fresh=true,priorState='complete',paths=[],contextReads=0,classifications=0,rateLimited=false;
const responseAnswer=policy.answerWorkspaceQuestion('offer',context,null);
const deps={...policy,z,redactSupportQuestion,NextResponse:{json:(body,o={})=>({body,status:o.status??200,headers:o.headers})},allowedOrigin:()=>origin,workAccount:async()=>{if(!authorized)throw Error('SIGN_IN_REQUIRED');if(!subscription)throw Error('SUBSCRIPTION_REQUIRED');return {accountId:id(1),userId:id(2)};},limitRequest:async()=>{if(rateLimited)throw Error();},workspaceAssistantContext:async account=>{contextReads++;assert.equal(account,id(1));return context;},routeWorkspaceQuestion:async()=>{classifications++;return {intent:'offer',propertyId:id(5),model:null,providerId:null,usage:null,raw:null};},db:async(path,method,body)=>{
 paths.push({path,method,body});
 if(path==='rpc/icash_begin_workspace_question'){assert.equal(body.p_account,id(1));assert.equal(body.p_user,id(2));return {id:id(3),fresh,state:priorState,answer:fresh?null:priorState==='complete'?responseAnswer:null,createdAt:context.checkedAt};}
 assert(path.includes('account_id=eq.'+id(1)),'Every history/context write is tenant scoped');
 if(method==='PATCH')return [{id:id(3),...body}];
 if(path.includes('id=eq.'+id(99)))return [];
 return [];
}};
const route=await load('app/api/work/assistant/route.ts',deps,'__assistantRoute');
const body={requestId:id(4),question:'Explain this offer',timezone:'America/Chicago',screeningId:id(5)};
const req=data=>new Request('https://www.geticashx.com/api/work/assistant',{method:'POST',headers:{origin:'https://www.geticashx.com'},body:JSON.stringify(data)});
authorized=false;assert.equal((await route.POST(req(body))).status,401);assert.equal(paths.length,0);authorized=true;
subscription=false;assert.equal((await route.POST(req(body))).status,402);assert.equal(paths.length,0);subscription=true;
origin=false;assert.equal((await route.POST(req(body))).status,403);assert.equal(paths.length,0);origin=true;
assert.equal((await route.POST(req({...body,accountId:id(99)}))).status,400);assert.equal(paths.length,0);
assert.equal((await route.POST(req({...body,timezone:'No/Such/Zone'}))).status,400);assert.equal(paths.length,0);
rateLimited=true;assert.equal((await route.POST(req(body))).status,429);assert.equal(paths.length,0);rateLimited=false;
let r=await route.POST(req(body));assert.equal(r.status,200);assert.match(r.body.answer.text,/96,270.50/);assert(paths.some(p=>p.body?.state==='complete'&&p.body.answer));assert.equal(contextReads,1);assert.equal(classifications,1);
fresh=false;paths=[];r=await route.POST(req(body));assert.equal(r.status,200);assert.equal(contextReads,1);assert.equal(classifications,1);assert.equal(paths.length,1,'Duplicate requests reuse persisted answer without model or work calls');
priorState='pending';assert.equal((await route.POST(req(body))).status,202);priorState='error';assert.equal((await route.POST(req(body))).status,409);
assert.equal((await route.GET(new Request('https://www.geticashx.com/api/work/assistant?id='+id(99)))).status,404);
assert.equal((await route.GET(new Request('https://www.geticashx.com/api/work/assistant?id=not-uuid'))).status,400);
assert(paths.every(p=>p.path.startsWith('icash_workspace_questions')||p.path==='rpc/icash_begin_workspace_question'),'Asking never starts outreach, charges, or modifies a deal');
console.log('PASS account assistant: exact saved math, bounded routing, no invented actions, membership/tenant/origin checks, persistent replies, replay and rate limits.');
