import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {filterProperties,needsAttention,propertyGroup,messageSpeaker,safeLocalTime} from '../components/workspace-view.ts';
import {makeWorkspaceFixture,uuid} from './fixtures/workspace-volume.mjs';
const work=makeWorkspaceFixture({count:10000});
assert.equal(work.properties.length,6,'a high-volume fixture remains bounded');
assert.equal(work.hasMore,true);
assert.equal(filterProperties(work.properties,work,'all').length,6);
assert.equal(filterProperties(work.properties,work,'all','100 eXaMpLe').length,1);
assert.equal(filterProperties(work.properties,work,'all','not present').length,0);
assert.equal(filterProperties(work.properties,work,'attention').length,6);
assert.equal(needsAttention(uuid(1),work),true);
assert.equal(needsAttention(uuid(1),{...work,textAttention:[],propertyAttentionIds:[uuid(1)]}),true,'independent queue pages do not hide property attention');
const cleared={...work,textAttention:[],propertyAttentionIds:[]};
assert.equal(propertyGroup(uuid(1),cleared),'active');
assert.equal(propertyGroup(uuid(5),cleared),'history');
assert.equal(propertyGroup(uuid(6),cleared),'history');
assert.equal(needsAttention(uuid(1),{...cleared,handoffs:[{screening_id:uuid(1),state:'acknowledged'}]}),false,'seen handoffs do not look like new requests');
assert.equal(needsAttention(uuid(1),{...cleared,callRequests:[{screening_id:uuid(1),state:'handled'}]}),false);
assert.equal(needsAttention(uuid(1),{...cleared,signing:[{deal_id:cleared.deals[0].id,state:'customer_signature_needed',test_mode:true}]}),true,'test signatures still require action without implying production completion');
assert.equal(messageSpeaker('outgoing','seller'),'From your bot number','unknown actors are not claimed to be manual or AI');
assert.equal(messageSpeaker('incoming','buyer'),'Buyer');
assert.equal(safeLocalTime('bad'),'Time unavailable');
assert.ok(safeLocalTime('2026-09-30T12:00:00Z','invalid/timezone').length);
const deep=makeWorkspaceFixture({screeningId:uuid(43)});assert.equal(deep.properties[0].id,uuid(43));assert.equal(deep.hasMore,false);
assert.equal(makeWorkspaceFixture({attentionPage:1}).textAttention.length,6);assert.equal(makeWorkspaceFixture({attentionPage:2}).textAttention.length,1);assert.equal(makeWorkspaceFixture({attentionPage:2}).attentionHasMore,false);
assert.equal(makeWorkspaceFixture({count:0}).properties.length,0);
const source=readFileSync(new URL('../components/live-workspace.tsx',import.meta.url),'utf8');
assert.ok(!source.includes('focused.current'),'open forms must not stop metadata refresh');
assert.ok(source.includes('attentionPage')&&source.includes('screeningId')&&source.includes('searchSupported'));
assert.ok(source.includes('Take over')&&source.includes('Already-started work may finish'));
const messages=readFileSync(new URL('../components/deal-messages.tsx',import.meta.url),'utf8');assert.ok(messages.includes('drafts[current.id]'));assert.ok(messages.includes('request.current.key'));assert.ok(messages.includes('Check latest status'));
const review=readFileSync(new URL('../components/contract-review-guide.tsx',import.meta.url),'utf8');
assert.ok(!review.includes("!t.closingDate&&'Closing date'"),'legitimate default closing clause is not marked missing');
assert.ok(review.includes('Blank is not $0'));assert.ok(review.includes('Within 30 calendar days after the effective date'));
assert.ok(source.includes('date of the last required signature'));assert.ok(source.includes('enter 0 only if no earnest money is intended'));
const home=readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');
assert.match(home,/<a className="workspace-help" href="\/support" target="_blank" rel="noopener noreferrer" aria-label="Help and support \(opens in a new tab\)"><span aria-hidden="true">\?<\/span> Help<\/a>\{account\?\.signedIn\?/,'Help remains available in the header before the signed-in branch, with accessible destination and preserved drafts');
console.log('Workspace volume, evidence, search, grouping, labels and recovery tests passed');
