import {fundingTermsText,earlyAccessDailyDisclosure} from '@/lib/funding-consent';
import Image from 'next/image';
import Link from 'next/link';
import {productRiskNotice,contractRiskNotice} from '@/lib/product-disclosures';
export const metadata={title:'Costs & disclosures | iCash X',description:'Understand daily billing, software usage, contract responsibilities and the risk of losing money.'};
export default function CostsAndDisclosures(){return <main className="legal-page"><nav className="legal-nav"><Link href="/" aria-label="iCash X home"><Image src="/icash-x-logo.png" alt="iCash X" width={116} height={65}/></Link><Link href="/">← Back to app</Link></nav><div className="legal-content"><span className="eyebrow">KNOW BEFORE YOU FUND</span><h1>Costs &amp; risks</h1><p className="legal-intro">{productRiskNotice}</p>
<section><h2>What you are buying</h2><p>iCash X provides AI-assisted software for property research, permitted outreach, follow-up and transaction coordination. Funding buys service usage—not a property, investment, guaranteed contract, buyer, income or completed business. Features depend on setup, permissions, available data and provider availability. Check the actual status shown in your workspace.</p><p>Usage charges reduce your credit balance at the applicable customer rates. These rates may include a margin and are not the same as iCash X’s provider costs. Credits are a service balance, not a bank account or an investment. Property deposits and closing funds are separate from software credits.</p></section>
<section id="daily-billing"><h2>Daily billing and stopping</h2><p>Before payment, checkout shows the daily amount and requires your authorization. Daily billing renews every 24 hours from the initial billing time until stopped. Budget changes apply at the next renewal. Use “Stop bot &amp; daily billing” in your workspace to cancel future renewals. A payment or task already in progress may finish. Unused credits remain on your account. Stopping does not undo completed work or cancel signed property contracts.</p><p>Handling one property yourself pauses automation for that property; it does not cancel your account’s daily billing. Read and separately approve any auto-sign authorization. Neither a billing authorization nor an auto-sign setting guarantees results.</p></section>
<section id="early-access"><h2>Early-access funding</h2><p>Call connectivity has been tested. The complete customer-funded workflow has not yet been verified end to end. Live activity remains subject to account setup, available funds, opt-outs and other operating checks.</p><p>{earlyAccessDailyDisclosure}</p><p>Early-access checkout requires a separate acknowledgment of these limitations. Daily funding uses the daily billing and stopping terms above. A separately labeled one-time credit purchase has no daily renewal.</p></section>
<section id="one-time"><h2>One-time credit purchases</h2><p>{fundingTermsText}</p></section>
<section><h2>You can lose money</h2><p>Software activity can use your entire budget without producing an interested seller, signed agreement, buyer or closing. Transactions may also involve earnest money, inspections, title charges, legal fees, buyer defaults and other losses. You could lose all money committed to a transaction and incur additional contractual obligations. Spend only what you can afford to lose.</p><p>To the extent permitted by applicable law, iCash X does not assume responsibility for losses caused by market changes, third-party defaults or your independent transaction decisions, and does not insure your capital or promise to reimburse unsuccessful transactions. This does not exclude liability that cannot legally be excluded, excuse our own fraud or unlawful conduct, or waive mandatory consumer rights. A disclosure alone does not determine liability in a particular dispute.</p></section>
<section><h2>Review before you sign</h2><p>{contractRiskNotice}</p><p>Verify ownership, authority to sign, legal descriptions, liens, title, values, repairs, access and special conditions with appropriate professionals. An estimated value is not a verified appraisal or guaranteed resale value. A contract, buyer match, deposit request or scheduled closing is not proof of payment. Confirm receipt of funds with the closing agent.</p><p>Buyer-paid closing costs and non-refundable deposits apply only as provided in the signed agreement and applicable law, including any exceptions. Changes to executed terms may require a signed amendment. Do not rely on a chat summary to alter an agreement.</p></section>
<section id="customer-responsibilities"><h2>Your responsibilities</h2><p>You make your own decisions about leads, outreach, contracts and investments. iCash X provides software and does not guarantee deals, profits or recovery of committed capital. You are responsible for lawful use, obtaining and keeping evidence of required contact permissions, honoring opt-outs, and reviewing the suitability of your transaction documents. iCash X does not independently verify recipient consent or legal suitability. Contact data, a do-not-call result, and acceptance of platform terms do not establish recipient consent. These responsibilities do not remove obligations that applicable law places on iCash X.</p></section>
<section><h2>AI and local requirements</h2><p>AI can misunderstand conversations, miss details and make mistakes. iCash X software and generated documents are not legal, tax, investment, appraisal or title advice. Consult qualified professionals for your transaction. Wholesaling, licensing, assignment, disclosure, outreach and recording requirements vary by location; software access does not create an exemption. Respect contact permissions and opt-out requests.</p></section>
<section><h2>Examples and estimates</h2><p>Any labeled demonstration is illustrative. Example profits, projected activity and estimated timelines are not promises or typical-results claims. Actual activity and signed-document status must be supported by records. No amount of funding guarantees a successful deal.</p></section>
<p className="legal-draft">Updated October 3, 2026 · These disclosures do not replace your signed transaction documents or mandatory legal rights.</p></div></main>;}
