import {workCreditTerms} from '@/lib/membership-policy';
import {earlyAccessDisclosure} from '@/lib/funding-consent';
import Image from 'next/image';
import Link from 'next/link';
import {productRiskNotice,contractRiskNotice} from '@/lib/product-disclosures';
export const metadata={title:'Costs & disclosures | iCash X',description:'Understand monthly software access, manual credit purchases, usage pricing, and property transaction responsibilities.'};
export default function CostsAndDisclosures(){return <main className="legal-page"><nav className="legal-nav"><Link href="/" aria-label="iCash X home"><Image src="/icash-x-logo.png" alt="iCash X" width={116} height={65}/></Link><Link href="/">← Back to app</Link></nav><div className="legal-content"><span className="eyebrow">KNOW BEFORE YOU FUND</span><h1>Costs &amp; risks</h1><p className="legal-intro">{productRiskNotice}</p>
<section><h2>What you are buying</h2><p>iCash X provides AI-assisted software for property research, permitted outreach, follow-up and transaction coordination. Funding buys service usage—not a property, investment, guaranteed contract, buyer, income or completed business. Features depend on setup, permissions, available data and provider availability. Check the actual status shown in your workspace.</p><p>Usage charges reduce your credit balance at the applicable customer rates. These rates may include a margin and are not the same as iCash X’s provider costs. Credits are a service balance, not a bank account or an investment. Property deposits and closing funds are separate from software credits.</p></section>
<section id="software"><h2>Software access and work credits</h2><p>Software access is $50 per month, renewing monthly until cancelled. The subscription includes $0 in work credits. Checkout shows the exact price before you authorize it. Existing subscriptions retain their accepted price.</p><p>Use Add money in your workspace: $10, $25, $50, or a custom amount from $10 to $1,000. Every recharge is manual and paid once. Credit purchases do not start daily billing or automatic refills. Your bot starts eligible work after payment is confirmed and stops new work when available credits are insufficient.</p><p>An active, paid subscription is required for workspace access and bot work. Unused credits stay on your account if access stops. Pause bot stops new automated work; it does not cancel the monthly subscription. Manage or cancel subscription renewals in Settings → Software subscription. Billing remains available when access needs to be restored.</p></section>
<section id="one-time"><h2>One-time credit purchases</h2><p>{workCreditTerms}</p><p>Checkout shows the exact amount and credit allocation before payment. Previously authorized work may finish after a pause. Unused credits stay in the account. Pausing does not undo completed work or cancel signed property contracts.</p></section>
<section id="daily-billing"><h2>Previous daily plans</h2><p>This section applies only to previously authorized daily plans. Your selected amount is charged every 24 hours from the initial billing time until stopped. The payment adds the same amount in service credits. New usage uses a 3× cost multiplier; a cost basis may include disclosed provider estimates and allocated operating costs. Credit reservations can include a buffer, with unused reserved amounts released on settlement. Historical charges and reservations keep their original price versions.</p><p>The spending limit includes usage in the preceding 24 hours plus outstanding reservations. Work that does not fit waits; we do not borrow from a future payment or charge automatic overages. Unused credits stay in your account. A higher budget increases spending capacity, not guaranteed results. A lead priced above your entire daily limit requires a higher limit you authorize.</p><p>Budget changes take effect at the next daily renewal, with no immediate prorated charge. Stop daily billing or Pause bot cancels future daily renewals. A payment already in progress or previously authorized work may complete. There is no separately added processing fee or tax at checkout. Review the exact amount, renewal schedule, and current feature availability before paying.</p></section><section id="early-access"><h2>Early-access funding</h2><p>{earlyAccessDisclosure}</p><p>Early-access credit checkout requires acknowledgment of the limitations shown before payment. Funding does not grant contact permission or release unavailable services.</p></section>
<section id="seller-leads"><h2>Qualified seller leads</h2><p>For newly priced leads, the customer price is 3× the recorded property-research and operating cost basis, rounded up to a cent. Advertising spend is tracked separately and does not delay delivery. The price is fixed when the lead is first assigned. A maximum bid is the most a bot may spend, not a charge or a promise of allocation. Qualified leads are assigned only when permission to receive them, current market review, funded credits and spending limits permit. Property estimates are screening inputs, not approved offers or evidence of ownership.</p></section>
<section><h2>You can lose money</h2><p>Software activity can use your entire budget without producing an interested seller, signed agreement, buyer or closing. Transactions may also involve earnest money, inspections, title charges, legal fees, buyer defaults and other losses. You could lose all money committed to a transaction and incur additional contractual obligations. Spend only what you can afford to lose.</p><p>To the extent permitted by applicable law, iCash X does not assume responsibility for losses caused by market changes, third-party defaults or your independent transaction decisions, and does not insure your capital or promise to reimburse unsuccessful transactions. This does not exclude liability that cannot legally be excluded, excuse our own fraud or unlawful conduct, or waive mandatory consumer rights. A disclosure alone does not determine liability in a particular dispute.</p></section>
<section><h2>Review before you sign</h2><p>{contractRiskNotice}</p><p>Verify ownership, authority to sign, legal descriptions, liens, title, values, repairs, access and special conditions with appropriate professionals. An estimated value is not a verified appraisal or guaranteed resale value. A contract, buyer match, deposit request or scheduled closing is not proof of payment. Confirm receipt of funds with the closing agent.</p><p>Buyer-paid closing costs and non-refundable deposits apply only as provided in the signed agreement and applicable law, including any exceptions. Changes to executed terms may require a signed amendment. Do not rely on a chat summary to alter an agreement.</p></section>
<section id="customer-responsibilities"><h2>Your responsibilities</h2><p>You make your own decisions about leads, outreach, contracts and investments. iCash X provides software and does not guarantee deals, profits or recovery of committed capital. You are responsible for lawful use, obtaining and keeping evidence of required contact permissions, honoring opt-outs, and reviewing the suitability of your transaction documents. iCash X does not independently verify recipient consent or legal suitability. Contact data, a do-not-call result, and acceptance of platform terms do not establish recipient consent. These responsibilities do not remove obligations that applicable law places on iCash X.</p></section>
<section><h2>AI and local requirements</h2><p>AI can misunderstand conversations, miss details and make mistakes. iCash X software and generated documents are not legal, tax, investment, appraisal or title advice. Consult qualified professionals for your transaction. Wholesaling, licensing, assignment, disclosure, outreach and recording requirements vary by location; software access does not create an exemption. Respect contact permissions and opt-out requests.</p></section>
<section><h2>Examples and estimates</h2><p>Any labeled demonstration is illustrative. Example profits, projected activity and estimated timelines are not promises or typical-results claims. Actual activity and signed-document status must be supported by records. No amount of funding guarantees a successful deal.</p></section>
<p className="legal-draft">Updated October 5, 2026 · These disclosures do not replace your signed transaction documents or mandatory legal rights.</p></div></main>;}
