'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,Check,Globe2,MapPin,Play,Pause,Phone,Search,FileCheck,Users,LoaderCircle,SlidersHorizontal} from 'lucide-react';
import {BotBrand,BotMark} from './bot-brand';
import {FundingCheckout} from './funding-checkout';
import {defaultBotProfile,setupThemes,setupProfileSchema,type BotProfile,type BotSetup,type SetupVoice} from '@/lib/bot-setup';
import {launchMarketCandidates} from '@/config/launch-market-candidates';
const steps=['Name','Look','Voice','Market'];
const voices=[{key:'sarah',name:'Sarah',description:'Warm & conversational'},{key:'chris',name:'Chris',description:'Relaxed & direct'},{key:'jessica',name:'Jessica',description:'Clear & friendly'}] as const;
const capabilities=[{icon:Search,title:'Find potential deals',detail:'Research properties and check the numbers.'},{icon:Phone,title:'Talk to sellers',detail:'Permitted calls, texts and follow-ups.'},{icon:FileCheck,title:'Prepare agreements',detail:'Work toward an offer and approved contract.'},{icon:Users,title:'Find buyers & coordinate closing',detail:'Match buyers and help keep the deal moving.'}];
export function BotSetupFlow({onBrand,onSignedIn}:{onBrand:(profile:BotProfile)=>void;onSignedIn:()=>void}){
 const [setup,setSetup]=useState<BotSetup|null>(null),[profile,setProfile]=useState<BotProfile>(defaultBotProfile),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[catalog,setCatalog]=useState<SetupVoice[]>([]),[audioError,setAudioError]=useState(''),[playing,setPlaying]=useState('');
 const audio=useRef<HTMLAudioElement|null>(null),heading=useRef<HTMLHeadingElement>(null),ready=useRef(false),init=useRef<Promise<BotSetup>|null>(null);
 function track(event:string){void fetch('/api/setup/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event}),keepalive:true}).catch(()=>{});}
 async function load(){setLoading(true);setError('');try{
  // Share the initialization promise across Strict Mode effect replays.
  if(!init.current)init.current=fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'init'})}).then(async r=>{const d=await r.json();if(!r.ok||!d.setup)throw Error(d.error??'Could not open your setup.');return d.setup;});
  const s=await init.current;setSetup(s);setProfile({...defaultBotProfile,...s.profile});setStep(s.stage);if(s.stage>0)track('returned');
 }catch{init.current=null;setError('Could not open your setup. Please retry.');}finally{setLoading(false);}}
 useEffect(()=>{void load();void fetch('/api/setup/voices').then(r=>r.json()).then(d=>setCatalog(d.voices??[])).catch(()=>setCatalog([]));return()=>{audio.current?.pause();};},[]);
 useEffect(()=>{onBrand(profile);},[profile,onBrand]);
 useEffect(()=>{if(!setup)return;track(['name_viewed','style_viewed','voice_viewed','market_viewed','funding_viewed'][step]);if(ready.current)heading.current?.focus();ready.current=true;audio.current?.pause();setPlaying('');},[step,setup?.id]);
 function change<K extends keyof BotProfile>(key:K,value:BotProfile[K]){setProfile(p=>({...p,[key]:value}));setError('');}
 async function advance(){if(!setup)return;setError('');const parsed=setupProfileSchema.safeParse(profile);if(!parsed.success){setError(step===0?'Enter your first name or business name.':'Choose a city and state, or use Nationwide.');return;}
  setBusy(true);try{const next=Math.min(4,step+1);const r=await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',profile:parsed.data,stage:next,revision:setup.revision})});const d=await r.json();if(!r.ok)throw Error(d.error);setSetup(d.setup);setStep(next);}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.');}finally{setBusy(false);}}
 async function play(key:string){setAudioError('');if(playing===key){audio.current?.pause();setPlaying('');return;}audio.current?.pause();const voice=catalog.find(v=>v.key===key);if(!voice){setAudioError('This preview is temporarily unavailable. Your voice choice can still be saved.');return;}const a=new Audio(voice.previewUrl);audio.current=a;a.onended=()=>setPlaying('');a.onerror=()=>{setPlaying('');setAudioError('Could not play the preview. Tap play to retry.');};try{await a.play();setPlaying(key);track('voice_played');}catch{setPlaying('');setAudioError('Could not play the preview. Tap play to retry.');}}
 const theme=setupThemes[profile.theme];const style={'--bot-color':theme.color,'--bot-soft':theme.soft} as CSSProperties;
 if(loading)return <div className="setup-loading" role="status"><LoaderCircle size={24} className="setup-spin"/><p>Opening your bot setup…</p></div>;
 if(!setup)return <div className="setup-loading"><p role="alert">{error}</p><button className="setup-primary" onClick={()=>void load()}>Retry</button></div>;
 return <section className={`bot-setup ${step===4?'setup-complete':''}`} style={style} aria-label="Build your real estate bot">
  <div className="setup-progress"><span>{step===4?<><Check size={14}/> Setup saved</>:<>Make it yours <b>{step+1} / 4</b></>}</span>{step<4?<div aria-label={`Step ${step+1} of 4`}>{steps.map((name,i)=><i key={name} className={i<=step?'active':''}/>)}</div>:<button onClick={()=>{setStep(0);}}><SlidersHorizontal size={14}/> Edit setup</button>}</div>
  <div className="setup-layout">
   <aside className="setup-preview" aria-label="Your bot preview"><div className="setup-preview-top"><span>YOUR BOT</span><span className="setup-preview-status">{step===4?'Setup saved':'Live preview'}</span></div><BotBrand profile={profile}/><div className="setup-preview-meta"><span><MapPin size={13}/>{profile.marketMode==='nationwide'?'Nationwide':profile.market||'Choose a city'}</span><span><Phone size={13}/>{voices.find(v=>v.key===profile.voice)?.name}</span></div><div className="setup-preview-capabilities">{capabilities.map((c,i)=><div key={c.title} className={i===step?'setup-current-feature':''}><span className="setup-feature-icon"><c.icon size={17}/></span><div><strong>{c.title}</strong><small>{c.detail}</small></div><span className="setup-feature-number">0{i+1}</span></div>)}</div><p className="setup-preview-note">Your plan—not live activity. Outreach starts only after funding and required setup checks.</p></aside>
   <div className="setup-form">
    {step<4&&step>0&&<button className="setup-back" disabled={busy} onClick={()=>{setStep(step-1);setError('');}}><ArrowLeft size={15}/> Back</button>}
    {step===0&&<><span className="setup-eyebrow">REAL ESTATE WHOLESALING, MADE EASY</span><h1 ref={heading} tabIndex={-1}>Your AI bot.<br/>Made for you.</h1><p className="setup-intro">Find properties. Talk to sellers. Work toward a deal. Start by making it yours.</p><form onSubmit={e=>{e.preventDefault();void advance();}}><label className="setup-label" htmlFor="bot-name">Your first name or business name</label><input className="setup-input" id="bot-name" autoComplete="organization" maxLength={64} value={profile.displayName} onChange={e=>change('displayName',e.target.value)} placeholder="e.g. Jordan or Oak Street Properties" required/><p className="setup-hint">No company needed. You can change this later.</p><button className="setup-primary" disabled={busy||!profile.displayName.trim()}>{busy?<><LoaderCircle size={18} className="setup-spin"/> Saving your name…</>:<>{setup.variant==='outcome'?'Build my real estate bot':'Make it mine'}<ArrowRight size={18}/></>}</button></form><p className="setup-free">Free to set up · No card needed<br/><span>Choose a paid daily budget when you’re ready to run.</span></p></>}
    {step===1&&<><span className="setup-eyebrow">A BOT THAT FEELS LIKE YOURS</span><h1 ref={heading} tabIndex={-1}>Pick your look.</h1><p className="setup-intro">Your name. Your colors. Your own mark.</p><fieldset className="setup-fieldset"><legend>Color</legend><div className="setup-colors">{Object.entries(setupThemes).map(([key,t])=><button key={key} aria-label={t.name} aria-pressed={profile.theme===key} onClick={()=>change('theme',key as BotProfile['theme'])}><span style={{background:t.color}}>{profile.theme===key&&<Check size={20}/>}</span><small>{t.name}</small></button>)}</div></fieldset><fieldset className="setup-fieldset"><legend>Your logo <span>Made from your name</span></legend><div className="setup-logos">{(['monogram','roof','wordmark'] as const).map((logo,i)=><button key={logo} aria-pressed={profile.logo===logo} onClick={()=>change('logo',logo)}><BotMark profile={{...profile,logo}}/><span>{['Signature','Property','Bold'][i]}</span>{profile.logo===logo&&<Check size={14} className="logo-selected"/>}</button>)}</div></fieldset><button className="setup-primary" disabled={busy} onClick={()=>void advance()}>{busy?'Saving your look…':'Use this look'}<ArrowRight size={18}/></button></>}
    {step===2&&<><span className="setup-eyebrow">HEAR YOUR BOT</span><h1 ref={heading} tabIndex={-1}>Choose a voice.</h1><p className="setup-intro">Tap play. Pick the one you like.</p><div className="setup-voices" role="group" aria-label="AI voice">{voices.map(v=><div key={v.key} className={profile.voice===v.key?'selected':''}><button className="setup-voice-choice" aria-pressed={profile.voice===v.key} onClick={()=>change('voice',v.key)}><span className="setup-voice-avatar">{v.name[0]}</span><span><strong>{v.name}{v.key==='sarah'&&<small>Recommended</small>}</strong><span>{v.description}</span></span><span className="setup-radio">{profile.voice===v.key&&<Check size={12}/>}</span></button><button className="setup-voice-play" aria-label={`${playing===v.key?'Pause':'Play'} ${v.name} preview`} onClick={()=>void play(v.key)}>{playing===v.key?<Pause size={17}/>:<Play size={17}/>}</button></div>)}</div><p className="setup-hint">AI voice previews from ElevenLabs. You can change your preference later.</p>{audioError&&<p role="status" className="setup-error">{audioError}</p>}<button className="setup-primary" disabled={busy} onClick={()=>void advance()}>{busy?'Saving your voice…':'Use this voice'}<ArrowRight size={18}/></button></>}
    {step===3&&<><span className="setup-eyebrow">CHOOSE WHERE IT WORKS</span><h1 ref={heading} tabIndex={-1}>Where should we look?</h1><p className="setup-intro">Choose a city, or let your bot explore available markets nationwide.</p><div className="setup-markets"><button aria-pressed={profile.marketMode==='nationwide'} onClick={()=>{change('marketMode','nationwide');change('market','Nationwide');}}><Globe2 size={22}/><span><strong>Nationwide</strong><small>Explore available U.S. markets</small></span>{profile.marketMode==='nationwide'&&<Check size={18}/>}</button><button aria-pressed={profile.marketMode==='city'} onClick={()=>{change('marketMode','city');change('market','');}}><MapPin size={22}/><span><strong>A specific city</strong><small>Keep the focus where you want it</small></span>{profile.marketMode==='city'&&<Check size={18}/>}</button></div>{profile.marketMode==='city'&&<><label className="setup-label" htmlFor="bot-city">City and state</label><input className="setup-input" id="bot-city" list="setup-cities" placeholder="e.g. Houston, TX" value={profile.market} onChange={e=>change('market',e.target.value)} maxLength={80}/><datalist id="setup-cities">{launchMarketCandidates.map(m=><option key={m.id} value={`${m.name}, ${m.states.join('-')}`}/>)}</datalist></>}<p className="setup-hint">Availability and local requirements are checked before outreach. A market choice doesn’t guarantee a deal.</p><button className="setup-primary" disabled={busy||(profile.marketMode==='city'&&profile.market.trim().length<2)} onClick={()=>void advance()}>{busy?<><LoaderCircle size={18} className="setup-spin"/> Saving your bot…</>:<>Create my bot<ArrowRight size={18}/></>}</button></>}
    {step===4&&<><span className="setup-ready-icon"><Check size={23}/></span><span className="setup-eyebrow">MADE FOR {profile.displayName.toUpperCase()}</span><h1 ref={heading} tabIndex={-1}>Your bot is set up.</h1><p className="setup-intro">You made it yours. Next, choose the daily budget that powers its work.</p><div className="setup-ready-summary"><span><Check size={14}/> Brand saved</span><span><Check size={14}/> Voice selected</span><span><Check size={14}/> Market selected</span></div><div className="setup-funding"><FundingCheckout onSignedIn={onSignedIn}/></div><details className="setup-details"><summary>What happens next?</summary><p>When live access is available, funding pays for property research, permitted seller outreach and follow-up. Identity, contact permissions and market checks must pass before your bot starts.</p><p>Agreements use your verified legal name or company, not just the display name above. Contracts, buyers and closing coordination depend on the actual deal. No deal or earnings are guaranteed.</p></details></>}
    {error&&<p role="alert" className="setup-error">{error}</p>}
   </div>
  </div>
  {step<4&&<div className="setup-bottom-note"><span>Your choices are saved as you go.</span><span>Powered by iCash X</span></div>}
 </section>;
}
