'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,Check,Globe2,MapPin,Play,Pause,LoaderCircle,SlidersHorizontal} from 'lucide-react';
import {BotMark} from './bot-brand';
import {FundingCheckout} from './funding-checkout';
import {defaultBotProfile,setupThemes,setupProfileSchema,type BotProfile,type BotSetup,type SetupVoice} from '@/lib/bot-setup';
import {launchMarketCandidates} from '@/config/launch-market-candidates';
const steps=['Name','Logo','Voice','Plan'];
const voices=[{key:'sarah',name:'Sarah',description:'Warm & conversational'},{key:'chris',name:'Chris',description:'Relaxed & direct'},{key:'jessica',name:'Jessica',description:'Clear & friendly'}] as const;
export function BotSetupFlow({onBrand,onSignedIn}:{onBrand:(profile:BotProfile)=>void;onSignedIn:()=>void}){
 const [setup,setSetup]=useState<BotSetup|null>(null),[profile,setProfile]=useState<BotProfile>(defaultBotProfile),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[catalog,setCatalog]=useState<SetupVoice[]>([]),[audioError,setAudioError]=useState(''),[playing,setPlaying]=useState('');
 const [designs,setDesigns]=useState<{title:string;paths:string[]}[]>([]),[logoState,setLogoState]=useState('empty');
 const logoName=useRef('');const nameEdited=useRef(false);
 useEffect(()=>{if(step!==1||!setup?.profile.displayName||logoName.current===setup.profile.displayName)return;logoName.current=setup.profile.displayName;let cancelled=false;let timer:ReturnType<typeof setTimeout>;setLogoState('creating');setDesigns([]);const apply=(d:{state:string;designs?:{title:string;paths:string[]}[]})=>{if(cancelled)return;setLogoState(d.state);if(d.designs){setDesigns(d.designs);setProfile(p=>({...p,aiLogo:p.aiLogo??0}));}if(d.state==='creating')timer=setTimeout(()=>{void fetch('/api/setup/logo').then(r=>r.json()).then(apply).catch(()=>setLogoState('unavailable'));},1500);};void fetch('/api/setup/logo',{method:'POST'}).then(r=>r.json()).then(apply).catch(()=>{if(!cancelled)setLogoState('unavailable');});return()=>{cancelled=true;clearTimeout(timer);logoName.current='';};},[step,setup?.profile.displayName]);
 const audio=useRef<HTMLAudioElement|null>(null),heading=useRef<HTMLHeadingElement>(null),ready=useRef(false),init=useRef<Promise<BotSetup>|null>(null);
 function track(event:string){void fetch('/api/setup/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event}),keepalive:true}).catch(()=>{});}
 async function load(){setLoading(true);setError('');try{
  // Share the initialization promise across Strict Mode effect replays.
  if(!init.current)init.current=fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'init'})}).then(async r=>{const d=await r.json();if(!r.ok||!d.setup)throw Error(d.error??'Could not open your setup.');return d.setup;});
  const s=await init.current;setSetup(s);setProfile(p=>({...defaultBotProfile,...s.profile,...(nameEdited.current?{displayName:p.displayName,aiLogo:null}:{})}));if(!nameEdited.current)setStep(s.stage);if(s.stage>0)track('returned');
 }catch{init.current=null;setError('Could not open your setup. Please retry.');}finally{setLoading(false);}}
 useEffect(()=>{void load();void fetch('/api/setup/voices').then(r=>r.json()).then(d=>setCatalog(d.voices??[])).catch(()=>setCatalog([]));return()=>{audio.current?.pause();};},[]);
 useEffect(()=>{onBrand(profile);},[profile,onBrand]);
 useEffect(()=>{if(!setup)return;track(['name_viewed','style_viewed','voice_viewed','market_viewed','funding_viewed'][step]);if(ready.current)heading.current?.focus();ready.current=true;audio.current?.pause();setPlaying('');},[step,setup?.id]);
 function change<K extends keyof BotProfile>(key:K,value:BotProfile[K]){if(key==='displayName')nameEdited.current=true;setProfile(p=>({...p,[key]:value,...(key==='displayName'?{aiLogo:null}:{})}));setError('');}
 async function advance(){if(busy)return;setError('');const parsed=setupProfileSchema.safeParse(profile);if(!parsed.success){setError(step===0?'Enter your first name or business name.':'Choose a city and state, or use Nationwide.');return;}
  setBusy(true);try{const current=setup??await init.current;if(!current)throw Error('Could not connect. Please retry.');const next=Math.min(4,step+1);const r=await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',profile:parsed.data,stage:next,revision:current.revision})});const d=await r.json();if(!r.ok)throw Error(d.error);setSetup(d.setup);setStep(next);}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.');}finally{setBusy(false);}}
 async function play(key:string){change('voice',key as BotProfile['voice']);setAudioError('');if(playing===key){audio.current?.pause();setPlaying('');return;}audio.current?.pause();const voice=catalog.find(v=>v.key===key);if(!voice){setAudioError('This preview is temporarily unavailable. Your voice choice can still be saved.');return;}const a=new Audio(voice.previewUrl);audio.current=a;a.onended=()=>setPlaying('');a.onerror=()=>{setPlaying('');setAudioError('Could not play the preview. Tap play to retry.');};try{await a.play();setPlaying(key);track('voice_played');}catch{setPlaying('');setAudioError('Could not play the preview. Tap play to retry.');}}
 const theme=setupThemes[profile.theme];const style={'--bot-color':theme.color,'--bot-soft':theme.soft} as CSSProperties;
 if(!setup&&!loading)return <div className="setup-loading"><p role="alert">{error}</p><button className="setup-primary" onClick={()=>void load()}>Retry</button></div>;
 return <section className={`bot-setup ${step===4?'setup-complete':''}`} style={style} aria-label="Build your real estate bot">
  <div className="setup-progress"><span>{step===4?<><Check size={14}/> Setup saved</>:<>Make it yours <b>{step+1} / 4</b></>}</span>{step<4?<div aria-label={`Step ${step+1} of 4`}>{steps.map((name,i)=><i key={name} className={i<=step?'active':''}/>)}</div>:<button onClick={()=>{setStep(0);}}><SlidersHorizontal size={14}/> Edit setup</button>}</div>
  <div className="setup-layout">
   <div className="setup-form setup-step-enter" key={step}>
    {step<4&&step>0&&<button className="setup-back" disabled={busy} onClick={()=>{setStep(step-1);setError('');}}><ArrowLeft size={15}/> Back</button>}
    {step===0&&<><span className="setup-eyebrow">REAL ESTATE WHOLESALING, MADE EASY</span><h1 ref={heading} tabIndex={-1}>Your AI bot.<br/>Made for you.</h1><p className="setup-intro">Find sellers. Make offers. Find cash buyers. Your AI helps handle the work.</p><form onSubmit={e=>{e.preventDefault();void advance();}}><label className="setup-label" htmlFor="bot-name">Your first name or business name</label><input className="setup-input" id="bot-name" autoComplete="organization" maxLength={64} value={profile.displayName} onChange={e=>change('displayName',e.target.value)} placeholder="e.g. Jordan or Oak Street Properties" required/><p className="setup-hint">No company needed.</p><button className="setup-primary" disabled={busy||!profile.displayName.trim()}>{busy?<><LoaderCircle size={18} className="setup-spin"/> Saving your name…</>:<>{setup?.variant==='outcome'?'Build my bot':'Make it mine'}<ArrowRight size={18}/></>}</button></form><p className="setup-free">Free to set up · No card needed<br/><span>Paid daily budget to run. Stop anytime.</span></p></>}
    {step===1&&<><h1 ref={heading} tabIndex={-1}>Pick your look.</h1><p className="setup-intro">Made for {profile.displayName}.</p><fieldset className="setup-fieldset"><legend>Color</legend><div className="setup-colors">{Object.entries(setupThemes).map(([key,t])=><button key={key} aria-label={t.name} aria-pressed={profile.theme===key} onClick={()=>change('theme',key as BotProfile['theme'])}><span style={{background:t.color}}>{profile.theme===key&&<Check size={20}/>}</span><small>{t.name}</small></button>)}</div></fieldset><fieldset className="setup-fieldset"><legend>Your logo</legend>{logoState==='creating'?<p className="setup-logo-status" role="status"><LoaderCircle className="setup-spin" size={18}/> Designing your logos…</p>:designs.length>0?<div className="setup-logos">{designs.map((d,i)=><button key={i} aria-pressed={profile.aiLogo===i} onClick={()=>change('aiLogo',i)}><svg viewBox="0 0 100 100" width="60" height="60" fill="none" stroke={theme.color} strokeWidth="5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{d.paths.map((path,n)=><path key={n} d={path}/>)}</svg><span>{d.title}</span>{profile.aiLogo===i&&<Check size={14} className="logo-selected"/>}</button>)}</div>:<div className="setup-logo-status"><BotMark profile={{...profile,aiLogo:null}}/><p>AI logos unavailable. Keep your initials for now.</p></div>}</fieldset><button className="setup-primary" disabled={busy} onClick={()=>void advance()}>{busy?'Saving your look…':'Continue'}<ArrowRight size={18}/></button></>}
    {step===2&&<><h1 ref={heading} tabIndex={-1}>Choose a voice.</h1><p className="setup-intro">This voice talks to sellers and discusses offers.</p><div className="setup-voices" role="group" aria-label="AI voice">{voices.map(v=><div key={v.key} className={profile.voice===v.key?'selected':''}><button className="setup-voice-choice" aria-pressed={profile.voice===v.key} onClick={()=>change('voice',v.key)}><span className="setup-voice-avatar">{v.name[0]}</span><span><strong>{v.name}{v.key==='sarah'&&<small>Recommended</small>}</strong><span>{v.description}</span></span><span className="setup-radio">{profile.voice===v.key&&<Check size={12}/>}</span></button><button className="setup-voice-play" aria-label={`${playing===v.key?'Pause':'Play'} ${v.name} preview`} onClick={()=>void play(v.key)}>{playing===v.key?<Pause size={17}/>:<Play size={17}/>}</button></div>)}</div><p className="setup-hint">Tap play to hear and select a voice.</p>{audioError&&<p role="status" className="setup-error">{audioError}</p>}<button className="setup-primary" disabled={busy} onClick={()=>void advance()}>{busy?'Saving your voice…':'Continue'}<ArrowRight size={18}/></button></>}
    {step===3&&<><h1 ref={heading} tabIndex={-1}>Where should we look?</h1><p className="setup-intro">Let your bot choose, or pick your city.</p><div className="setup-markets"><button aria-pressed={profile.marketMode==='nationwide'} onClick={()=>{change('marketMode','nationwide');change('market','Nationwide');}}><Globe2 size={22}/><span><strong>Nationwide</strong><small>Let the bot choose</small></span>{profile.marketMode==='nationwide'&&<Check size={18}/>}</button><button aria-pressed={profile.marketMode==='city'} onClick={()=>{change('marketMode','city');change('market','');}}><MapPin size={22}/><span><strong>A specific city</strong><small>Choose your area</small></span>{profile.marketMode==='city'&&<Check size={18}/>}</button></div>{profile.marketMode==='city'&&<><label className="setup-label" htmlFor="bot-city">City and state</label><input className="setup-input" id="bot-city" list="setup-cities" placeholder="e.g. Houston, TX" value={profile.market} onChange={e=>change('market',e.target.value)} maxLength={80}/><datalist id="setup-cities">{launchMarketCandidates.map(m=><option key={m.id} value={`${m.name}, ${m.states.join('-')}`}/>)}</datalist></>}<div className="setup-toolkit"><details className="setup-details setup-included"><summary><span>Contracts &amp; buyer matching</span><small>Customize</small></summary><label><input type="checkbox" checked={profile.contracts} onChange={e=>change('contracts',e.target.checked)}/><span><strong>Free contract templates</strong><small>Set the terms with sellers and buyers.</small></span></label><label><input type="checkbox" checked={profile.buyers} onChange={e=>change('buyers',e.target.checked)}/><span><strong>Find cash buyers</strong><small>Match buyers after you have a signed seller agreement.</small></span></label></details><details className="setup-details"><summary>How it works · Preview contracts</summary><div className="setup-deal-example"><span>Agree with seller <b>$100,000</b></span><ArrowRight size={18}/><span>Assign to buyer <b>$120,000</b></span></div><p><strong>Example: $20,000 gross spread.</strong> Costs reduce what you keep. This is an illustration, not a deal or earnings promise.</p>{profile.contracts&&<div className="setup-document-links"><a href="/api/setup/documents?kind=purchase" target="_blank" rel="noopener">Preview seller agreement ↗</a><a href="/api/setup/documents?kind=assignment" target="_blank" rel="noopener">Preview buyer agreement ↗</a></div>}<p>Templates are unsigned drafts. Property details, legal names and required local terms must be completed before signing.</p></details></div><p className="setup-hint">Local requirements apply. No guaranteed deals.</p><button className="setup-primary" disabled={busy||(profile.marketMode==='city'&&profile.market.trim().length<2)} onClick={()=>void advance()}>{busy?<><LoaderCircle size={18} className="setup-spin"/> Saving your bot…</>:<>Finish setup<ArrowRight size={18}/></>}</button></>}
    {step===4&&<><span className="setup-ready-icon"><Check size={23}/></span><span className="setup-eyebrow">MADE FOR {profile.displayName.toUpperCase()}</span><h1 ref={heading} tabIndex={-1}>Your bot is ready.</h1><p className="setup-intro">Choose a daily budget to power its work.</p><details className="setup-details setup-saved"><summary><Check size={15}/> Your setup is saved <small>View</small></summary><div className="setup-ready-summary"><span>Brand: {profile.displayName}</span><span>Voice: {voices.find(v=>v.key===profile.voice)?.name}</span><span>Market: {profile.market}</span>{profile.contracts&&<span>Contract templates included</span>}{profile.buyers&&<span>Buyer matching selected</span>}</div></details><div className="setup-funding"><FundingCheckout onSignedIn={onSignedIn}/></div><details className="setup-details"><summary>What happens next?</summary><p>When live access is available, funding pays for property research, permitted seller outreach and follow-up. Identity, contact permissions and market checks must pass before your bot starts.</p><p>Agreements use your verified legal name or company, not just the display name above. Contracts, buyers and closing coordination depend on the actual deal. No deal or earnings are guaranteed.</p></details></>}
    {error&&<p role="alert" className="setup-error">{error}</p>}
   </div>
  </div>
  {step<4&&<div className="setup-bottom-note"><span>Saved as you go. Change anything later.</span></div>}
 </section>;
}
