'use client';
import {ArrowUpRight,Wallet,ShieldCheck} from 'lucide-react';
import {creditAmount} from '@/lib/workspace-progress';
export function CreditsWallet({balanceCents,reservedCents,stale=false,onChange}:{balanceCents?:number;reservedCents?:number;stale?:boolean;onChange:(code?:string)=>void}){
 const empty=balanceCents===0;
 return <section className="daily-budget-bar credits-wallet" aria-label="Your work credits"><div className="daily-budget-top"><div><span className="workspace-eyebrow"><Wallet size={14} aria-hidden="true"/>WORK CREDITS</span><strong>{stale?'Checking balance':creditAmount(balanceCents)}</strong><small className="credit-balance-caption">Available for AI work</small></div><button id="workspace-funding-toggle" type="button" className="budget-increase" onClick={()=>onChange(empty?'budget_ten':'budget_25')}>{empty?'Add your first credits':'Add credits'}<ArrowUpRight size={17} aria-hidden="true"/></button></div><div className="daily-budget-bottom"><span>{empty?'Start with $10. Increase when you’re ready.':'Prepaid. Your AI works within this balance.'}</span><span className="wallet-no-refill">No auto-refill</span></div>{!!reservedCents&&<small className="daily-budget-reserved">{creditAmount(reservedCents)} reserved for work already in progress</small>}<details className="budget-guardrails"><summary><ShieldCheck size={14} aria-hidden="true"/>How usage is controlled</summary><p>Each paid task must fit your available credits and spending limits. New work stops when there isn’t enough available. Your card is never charged to refill credits automatically.</p><p>Contact permissions, hours, and service readiness are checked before calls or texts. Uncertain sends stay held for review. Your software subscription is separate.</p></details></section>;
}

export function DailyBudgetBar({budgetCents,balanceCents,reservedCents,active,stale=false,onChange}:{budgetCents?:number;balanceCents?:number;reservedCents?:number;active?:boolean;stale?:boolean;onChange:(code?:string)=>void}){
 return <section className="daily-budget-bar daily-workspace-budget" aria-label="Your daily budget"><div className="daily-budget-top"><div><span className="workspace-eyebrow"><Wallet size={14}/>YOUR DAILY BUDGET</span><strong>{stale?'Checking':active?creditAmount(budgetCents):'$10.00'}<em>/ day</em></strong><small className="credit-balance-caption">{active?'A firm limit. You choose when to increase it.':'Start small. Set your own pace.'}</small></div><button id="workspace-funding-toggle" type="button" className="budget-increase" onClick={()=>onChange()}>{active?'Adjust budget':'Choose daily budget'}<ArrowUpRight size={17}/></button></div><div className="daily-budget-bottom"><span>{creditAmount(balanceCents)} available{reservedCents?` · ${creditAmount(reservedCents)} reserved`:''}</span><span>Stop anytime</span></div><details className="budget-guardrails"><summary><ShieldCheck size={14}/>How your daily budget works</summary><p>Your selected amount renews every 24 hours until you stop bot and daily billing. Unused credits stay in your account. New work must fit your available balance and daily spending limit; work that doesn’t fit waits.</p><p>Higher budgets give the same AI more spending room. Lead availability, calling readiness, and property checks still apply. No lead or deal is guaranteed.</p></details></section>;
}
