'use client';
import {ArrowUpRight,Wallet,ShieldCheck} from 'lucide-react';
import {creditAmount} from '@/lib/workspace-progress';
export function CreditsWallet({balanceCents,reservedCents,stale=false,onChange}:{balanceCents?:number;reservedCents?:number;stale?:boolean;onChange:(code?:string)=>void}){
 const empty=balanceCents===0;
 return <section className="daily-budget-bar credits-wallet" aria-label="Your work credits"><div className="daily-budget-top"><div><span className="workspace-eyebrow"><Wallet size={14} aria-hidden="true"/>WORK CREDITS</span><strong>{stale?'Checking balance':creditAmount(balanceCents)}</strong><small className="credit-balance-caption">Available for AI work</small></div><button id="workspace-funding-toggle" type="button" className="budget-increase" onClick={()=>onChange(empty?'budget_ten':'budget_25')}>{empty?'Add your first credits':'Add credits'}<ArrowUpRight size={17} aria-hidden="true"/></button></div><div className="daily-budget-bottom"><span>{empty?'Start with $10. Increase when you’re ready.':'Prepaid. Your AI works within this balance.'}</span><span className="wallet-no-refill">No auto-refill</span></div>{!!reservedCents&&<small className="daily-budget-reserved">{creditAmount(reservedCents)} reserved for work already in progress</small>}<details className="budget-guardrails"><summary><ShieldCheck size={14} aria-hidden="true"/>How usage is controlled</summary><p>Each paid task must fit your available credits and spending limits. New work stops when there isn’t enough available. Your card is never charged to refill credits automatically.</p><p>Contact permissions, hours, and service readiness are checked before calls or texts. Uncertain sends stay held for review. Your software subscription is separate.</p></details></section>;
}

export function DailyBudgetBar({budgetCents,balanceCents,reservedCents,active,stale=false,onChange}:{budgetCents?:number;balanceCents?:number;reservedCents?:number;active?:boolean;stale?:boolean;onChange:(code?:string)=>void}){
 // The account API already returns the balance net of reservations.
 const available=balanceCents;
 return <section className="daily-budget-bar daily-workspace-budget" aria-label="Your daily budget"><button id="workspace-funding-toggle" type="button" className="workspace-budget-button" aria-haspopup="dialog" onClick={()=>onChange()}><span>Daily budget</span><strong>{stale?'Checking':typeof budgetCents==='number'&&budgetCents>=1000?creditAmount(budgetCents):'$10.00'}<em>/ day</em></strong><span className="budget-edit-label">Change</span></button><small className="workspace-available">{stale?'Updating balance…':`${creditAmount(available)} available`}</small></section>;
}
