'use client';
import {fundingTermsVersion,earlyAccessTermsVersion,earlyAccessDailyDisclosure} from '@/lib/funding-consent';
import {useEffect,useState,useRef} from 'react';
import {processingFeeCents} from '@/lib/funding-fees';
import {AccountAccess} from '@/components/account-access';
import {dailyConsentVersion,dailyConsent} from '@/lib/daily-consent';
type Pack={code:string;price_cents:number;credit_cents:number;enabled:boolean};
type Funding={earlyAccess?:boolean;privatePaymentCheck?:boolean;mode:'test'|'live'|null;enabled:boolean;packs?:Pack[];priceCents?:number;paidCents?:number;needsClaim?:boolean;email?:string};
export function FundingCheckout({onSignedIn,initialCode}:{onSignedIn:()=>void;initialCode?:string}){
 const [paymentReturn,setPaymentReturn]=useState(false);const polling=useRef(false);const notified=useRef(false);
 const [status,setStatus]=useState<Funding|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[accepted,setAccepted]=useState(false),[code,setCode]=useState(initialCode??"budget_ten");
 const [privateAccepted,setPrivateAccepted]=useState(false),[acceptedScope,setAcceptedScope]=useState('');
 const checkoutInFlight=useRef(false),mounted=useRef(true),preferredCode=useRef(initialCode);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const [daily,setDaily]=useState<{ready:boolean;plan:{state:string;budgetCents:number|null;nextCharge:number|null}|null}|null>(null),[notice,setNotice]=useState('');
 async function refresh(){try{const billing=await fetch('/api/billing/daily',{cache:'no-store'});const sessionId=new URLSearchParams(window.location.search).get('session_id');const r=await fetch('/api/funding/status'+(sessionId?'?session_id='+encodeURIComponent(sessionId):''),{cache:'no-store'});if(!r.ok)throw new Error();const funding:Funding=await r.json();setStatus(funding);setError('');const d=billing.ok?await billing.json():{ready:false,plan:null};setDaily(d);if(d.plan?.budgetCents){const active=funding.packs?.find(p=>p.price_cents===d.plan.budgetCents);if(active&&!preferredCode.current)setCode(active.code);}}catch{setAccepted(false);setError('Could not check funding. Please retry.');}}
 useEffect(()=>{setPaymentReturn(new URLSearchParams(window.location.search).get('payment')==='funded');void refresh();},[]);
 useEffect(()=>{if(!paymentReturn||status?.paidCents||status?.needsClaim)return;let tries=0;const timer=setInterval(()=>{if(polling.current||document.hidden)return;if(++tries>12){clearInterval(timer);return;}polling.current=true;void refresh().finally(()=>{polling.current=false;});},5000);return()=>clearInterval(timer);},[paymentReturn,status?.paidCents,status?.needsClaim]);
 useEffect(()=>{if(paymentReturn&&status?.paidCents&&!status.needsClaim&&!notified.current){notified.current=true;const url=new URL(window.location.href);url.searchParams.delete('payment');url.searchParams.delete('session_id');window.history.replaceState(null,'',url.pathname+url.search+url.hash);onSignedIn();}},[paymentReturn,status?.paidCents,status?.needsClaim,onSignedIn]);
 const packs=(status?.packs??[]).filter(p=>p.price_cents>=1000&&(status?.mode!=='live'||p.enabled));
 const selected=packs.find(p=>p.code===code);const amount=selected?.price_cents??1000;
 const earlyAccess=status?.earlyAccess===true;
 const days=1;
 const total=amount*days;
 const fee=processingFeeCents(total),subtotal=total+fee;
 const consentScope=JSON.stringify([code,subtotal,selected?.credit_cents,earlyAccess,status?.mode,status?.enabled,daily?.ready,daily?.plan?.state,daily?.plan?.nextCharge,dailyConsentVersion,earlyAccessTermsVersion]);
 const repeatChange=daily?.plan?.state==='active'&&!earlyAccess;
 const consentAccepted=accepted&&acceptedScope===consentScope;
 useEffect(()=>{setAccepted(false);},[consentScope]);
 async function checkout(){if(checkoutInFlight.current||busy||!selected||!daily?.ready||(!consentAccepted&&!repeatChange))return;checkoutInFlight.current=true;setBusy(true);setError('');void fetch('/api/setup/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:'checkout_clicked'})}).catch(()=>{});try{const r=await fetch('/api/billing/daily',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accepted:consentAccepted||repeatChange,version:dailyConsentVersion,earlyAccessAccepted:earlyAccess&&consentAccepted,earlyAccessVersion:earlyAccessTermsVersion,action:daily?.plan?.state==='active'?'change':'start',packCode:code,days,totalCents:subtotal})});const d=await r.json();if(!mounted.current)return;if(!r.ok)throw new Error(d.error);if(d.saved){setNotice(d.message);preferredCode.current=undefined;setBusy(false);setAccepted(false);await refresh();return;}const url=new URL(d.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw new Error('Could not open secure checkout.');window.location.assign(url.href);}catch(e){setError(e instanceof Error?e.message:'Please retry.');setBusy(false);}finally{checkoutInFlight.current=false;}}
 if(paymentReturn&&status&&!status.paidCents&&!status.needsClaim)return <div role="status"><h3>Confirming your payment</h3><p>Your balance appears after payment is confirmed. Please don’t pay again.</p><button className="demo-button" onClick={()=>void refresh()}>Check payment</button>{error&&<p role="alert">{error}</p>}</div>;
 if(!status)return <p role="status">Checking funding…{error&&<button onClick={()=>void refresh()}>Retry</button>}</p>;
 return <div className="boost-widget">
  {status.privatePaymentCheck&&<section className="budget-explainer"><strong>Private live payment check</strong><p>$3 once. Real payment. No renewal. Bot availability is unchanged.</p><a className="funding-terms-link" href="/costs-and-disclosures#one-time" target="_blank" rel="noopener noreferrer">Purchase terms ↗</a><label className="funding-consent"><input type="checkbox" checked={privateAccepted} onChange={e=>setPrivateAccepted(e.target.checked)}/><span>I authorize this one-time $3 credit purchase.</span></label><button className="fund-button full" disabled={busy||!privateAccepted} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/funding/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accepted:true,version:fundingTermsVersion,packCode:'private_check_three',days:1,totalCents:300})});const d=await r.json();if(!mounted.current)return;if(!r.ok)throw Error(d.error);const u=new URL(d.url);if(u.protocol!=='https:'||u.hostname!=='checkout.stripe.com')throw Error('Invalid checkout link');window.location.assign(u.href);}catch(e){setError(e instanceof Error?e.message:'Please retry.');setBusy(false);}}}>Pay $3 once</button></section>}
  {status.mode==='test'&&<p className="boost-caption">Test mode · No real money or live work.</p>}
  {status.needsClaim?<><h3>Your payment is confirmed</h3><p>Verify your email once to open your workspace. No password needed.</p><AccountAccess initialEmail={status.email??''} onSignedIn={onSignedIn}/></>:<>
   <div className="budget-presets" role="group" aria-label="Daily budget options">{packs.filter(p=>[1000,2500,5000,10000].includes(p.price_cents)).map(p=><button type="button" key={p.code} aria-pressed={p.code===code} disabled={busy} onClick={()=>{setCode(p.code);setAccepted(false);setNotice('');}}><strong>${p.price_cents/100}</strong><span>/day</span></button>)}</div>
   <details className="budget-custom-amount"><summary>More daily budgets</summary><div className="boost-duration boost-budget-slider"><label htmlFor="boost-amount">Daily budget <strong>${(amount/100).toLocaleString()}/day</strong></label><input id="boost-amount" type="range" min="0" max={Math.max(0,packs.length-1)} step="1" value={Math.max(0,packs.findIndex(p=>p.code===code))} disabled={busy||packs.length<2} aria-valuetext={`$${(amount/100).toLocaleString()} per day`} onChange={e=>{const pack=packs[Number(e.target.value)];if(pack){setCode(pack.code);setAccepted(false);}}}/><div className="boost-range-labels" aria-hidden="true"><span>$10</span><span>${((packs.at(-1)?.price_cents??1000)/100).toLocaleString()}</span></div></div></details>
   <p id="funding-summary" hidden={repeatChange} className="boost-caption billing-renewal">${(subtotal/100).toFixed(2)}/day, renewing every 24 hours until you stop bot &amp; daily billing. {earlyAccess?'Outreach isn’t active yet; funding won’t start it. Charges continue while unavailable; unused credits remain.':'Unused credits remain on your account.'} No deal or start date is guaranteed.</p>
   {!repeatChange&&<label className="funding-consent"><input type="checkbox" checked={consentAccepted} disabled={busy||!selected||!daily?.ready} aria-describedby="funding-summary" onChange={e=>{setAccepted(e.target.checked);setAcceptedScope(consentScope);}}/><span>I authorize ${(subtotal/100).toFixed(2)}/day and agree to the full terms below{earlyAccess?', including continued charges while outreach is unavailable':''}.</span></label>}
   <details className="boost-terms"><summary>Full billing and availability terms</summary><p>{dailyConsent}</p>{earlyAccess&&<p>{earlyAccessDailyDisclosure}</p>}<a className="funding-terms-link" href="/costs-and-disclosures#daily-billing" target="_blank" rel="noopener noreferrer">All costs and terms ↗</a></details>
   {daily?.plan?.nextCharge&&<p className="boost-caption">Next renewal: {new Date(daily.plan.nextCharge*1000).toLocaleString()}. Budget changes start then.</p>}
   {repeatChange&&<p className="budget-change-confirmation">Confirming authorizes ${(subtotal/100).toFixed(2)} every day from the next renewal until you stop. No charge now. Your saved payment method stays in place.</p>}
   <button className="fund-button full" disabled={busy||!selected||!daily?.ready||(!consentAccepted&&!repeatChange)} onClick={()=>void checkout()}>{busy?repeatChange?'Saving your budget…':'Opening secure checkout…':`${daily?.plan?.state==='active'?'Confirm daily budget':earlyAccess?'Start daily funding':'Start bot'} — $${(subtotal/100).toFixed(2)}/day`}</button>
   {notice&&<p role="status">{notice}</p>}
   {!daily?.ready&&<p className="boost-caption" role="status">Daily funding is currently unavailable. Please retry.</p>}
  </>}
   {daily?.plan&&<button className="boost-refresh" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/billing/daily',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'stop'})});if(!r.ok)throw new Error();setNotice('Daily billing stopped. No future renewals.');await refresh();}catch{setError('Cancellation is pending. Please retry; your stop request is saved.');}finally{setBusy(false);}}}>Stop bot & daily billing</button>}
  {error&&<p role="alert">{error}<button className="demo-button" onClick={()=>void refresh()}>Retry</button></p>}
  {!!status.paidCents&&<button className="boost-refresh" onClick={()=>void refresh()}>Refresh payment status</button>}
 </div>;
}
