'use client';
import {fundingReasonAtAmount} from '@/lib/credit-refill-recommendation';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ShieldCheck,RefreshCw} from 'lucide-react';
import {autoRechargeVersion,autoRechargeSummary,autoRechargeTerms} from '@/lib/auto-recharge-policy';
import {customFundingCode,fundingAmountCents} from '@/lib/funding-amount';
import {StripeEmbeddedCheckout} from './stripe-embedded-checkout';
import {AccountAccess} from './account-access';
import {earlyAccessTermsVersion,earlyAccessDisclosure} from '@/lib/funding-consent';
import {workCreditTerms,workCreditTermsVersion,priceLabel} from '@/lib/membership-policy';
type Pack={code:string;price_cents:number;credit_cents:number;enabled:boolean};
type Funding={embeddedReady?:boolean;recommendedCents?:number;autoRecharge?:{enabled:boolean;amount_cents?:number;issue?:string|null};earlyAccess?:boolean;mode:'test'|'live'|null;enabled:boolean;packs?:Pack[];custom?:{enabled:boolean;minCents:number;maxCents:number};paidCents?:number;needsClaim?:boolean;email?:string};
export function FundingCheckout({onSignedIn,initialCode,initialAmountCents,reason,outOfCredits=false}:{onSignedIn:()=>void;initialCode?:string;initialAmountCents?:number;reason?:string;outOfCredits?:boolean}){
 const [status,setStatus]=useState<Funding|null>(null),[code,setCode]=useState(initialCode??'budget_ten'),[customAmount,setCustomAmount]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[paymentReturn,setPaymentReturn]=useState(false);
 const [checkoutForm,setCheckoutForm]=useState<{clientSecret:string;publishableKey:string}|null>(null);
 const sessionRef=useRef<string|null>(null);
 const [autoRecharge,setAutoRecharge]=useState(false),[turningOff,setTurningOff]=useState(false);
 const picked=useRef(!!initialCode),recommended=useRef(false);
 const inFlight=useRef(false),polling=useRef(false),notified=useRef(false),alive=useRef(true);
 async function refresh(){if(polling.current)return;polling.current=true;try{const sessionId=sessionRef.current??new URLSearchParams(window.location.search).get('session_id');const r=await fetch('/api/funding/status'+(sessionId?'?session_id='+encodeURIComponent(sessionId):''),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(alive.current){setStatus(d);if(sessionId&&d.paidCents)setPaymentReturn(true);setError('');}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not check credits. Please retry.');}finally{polling.current=false;}}
 useEffect(()=>{alive.current=true;setPaymentReturn(new URLSearchParams(window.location.search).get('payment')==='funded');void refresh();return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!paymentReturn||status?.paidCents||status?.needsClaim)return;let tries=0;const timer=setInterval(()=>{if(!document.hidden&&++tries<=12)void refresh();},5000);return()=>clearInterval(timer);},[paymentReturn,status?.paidCents,status?.needsClaim]);
 useEffect(()=>{if(paymentReturn&&status?.paidCents&&!status.needsClaim&&!notified.current){notified.current=true;const url=new URL(window.location.href);url.searchParams.delete('payment');url.searchParams.delete('session_id');window.history.replaceState(null,'',url.pathname+url.search+url.hash);onSignedIn();}},[paymentReturn,status?.paidCents,status?.needsClaim,onSignedIn]);
 const packs=(status?.packs??[]).filter(p=>p.price_cents>=1000&&p.price_cents<=100000&&(status?.mode!=='live'||p.enabled)),selected=packs.find(p=>p.code===code);
 function chooseAmount(cents:number){picked.current=true;const pack=packs.find(p=>p.price_cents===cents);if(pack){setCode(pack.code);setCustomAmount('');}else{setCode(customFundingCode);setCustomAmount(String(cents/100));}}
 useEffect(()=>{if(!status||picked.current||recommended.current)return;recommended.current=true;const cents=initialAmountCents??status.recommendedCents??1000;const pack=(status.packs??[]).find(p=>p.enabled&&p.price_cents===cents);if(pack)setCode(pack.code);else if(status.custom?.enabled){setCode(customFundingCode);setCustomAmount(String(cents/100));}},[status,outOfCredits,initialAmountCents]);
 const isCustom=code===customFundingCode,amount=isCustom?fundingAmountCents(customAmount):selected?.price_cents??null;
 const canPay=!!status?.enabled&&amount!==null&&(!isCustom||status.custom?.enabled===true);
 async function checkout(){if(inFlight.current||!canPay)return;inFlight.current=true;setBusy(true);setError('');try{const r=await fetch('/api/funding/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accepted:true,version:workCreditTermsVersion,earlyAccessAccepted:status.earlyAccess===true,earlyAccessVersion:earlyAccessTermsVersion,packCode:code,days:1,totalCents:amount,...(status.embeddedReady?{embedded:true}:{}),...(autoRecharge?{autoRecharge:true,autoRechargeVersion}:{}),...(isCustom?{customAmountCents:amount}:{})})});const d=await r.json();if(!alive.current)return;if(!r.ok)throw Error(d.error);if(d.clientSecret&&d.publishableKey&&d.sessionId){sessionRef.current=d.sessionId;setStatus(null);const url=new URL(window.location.href);url.searchParams.set('session_id',d.sessionId);url.searchParams.set('payment','checkout');url.hash='funding';window.history.replaceState(null,'',url.pathname+url.search+url.hash);setCheckoutForm({clientSecret:d.clientSecret,publishableKey:d.publishableKey});return;}const url=new URL(d.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw Error('Could not open secure checkout.');window.location.assign(url.href);}catch(e){setError(e instanceof Error?e.message:'Could not open checkout.');}finally{inFlight.current=false;if(alive.current)setBusy(false);}}
 async function turnOff(){if(turningOff)return;setTurningOff(true);try{const r=await fetch('/api/funding/auto-recharge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:false})});const d=await r.json();if(!r.ok)throw Error(d.error);setAutoRecharge(false);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not turn off auto recharge.');}finally{setTurningOff(false);}}
 if(checkoutForm)return <div><StripeEmbeddedCheckout {...checkoutForm} onComplete={()=>{setCheckoutForm(null);setPaymentReturn(true);const url=new URL(window.location.href);url.searchParams.set('payment','funded');window.history.replaceState(null,'',url.pathname+url.search+url.hash);void refresh();}}/><button type="button" className="workspace-quiet" onClick={()=>{setCheckoutForm(null);void refresh();}}>Change amount</button>{error&&<p role="alert">{error}</p>}</div>;
 if(paymentReturn&&!status?.paidCents&&!status?.needsClaim)return <div role="status"><h3>Confirming your credits</h3><p>Your balance updates after payment is confirmed. Please don’t pay again.</p><button className="workspace-quiet" onClick={()=>void refresh()}>Check payment</button>{error&&<p role="alert">{error}</p>}</div>;
 if(status?.needsClaim)return <div><h3>Your payment is confirmed</h3><p>Verify your payment email to open your workspace.</p><AccountAccess initialEmail={status.email??''} onSignedIn={onSignedIn}/></div>;
 return <section className="credit-checkout" aria-label="Add money">
  <p className="credit-checkout-intro">{(reason?fundingReasonAtAmount(reason,amount):undefined)??(outOfCredits?'Add credits so I can continue property research, calls, texts, and eligible AI work.':(status?.recommendedCents??0)>=5000?'Add more credits for fewer interruptions.':'Choose an amount to start your bot.')}</p>
  {!status&&<p role="status">Checking available credit amounts…</p>}
  {status?.mode==='test'&&<p className="membership-note">Test checkout · No live work.</p>}
  <div className="credit-pack-options" role="group" aria-label="Amount to add">{[1000,2500,5000,10000,25000].map(cents=>{const pack=packs.find(p=>p.price_cents===cents);return <button type="button" key={cents} aria-pressed={amount===cents} disabled={busy||(!pack&&!status?.custom?.enabled)} onClick={()=>chooseAmount(cents)}><strong>{priceLabel(cents)}</strong>{(initialAmountCents??status?.recommendedCents)===cents&&<span>Recommended</span>}</button>;})}<button type="button" aria-pressed={isCustom&&![1000,2500,5000,10000,25000].includes(amount??0)} disabled={busy||!status?.custom?.enabled} onClick={()=>{picked.current=true;setCode(customFundingCode);setCustomAmount('');}}><strong>Custom</strong></button></div>
  {isCustom&&<label className="credit-custom-amount" htmlFor="custom-credit-amount">Amount in dollars<input id="custom-credit-amount" type="text" inputMode="decimal" autoComplete="off" placeholder="10.00" value={customAmount} disabled={busy} aria-describedby="custom-credit-hint" onChange={e=>setCustomAmount(e.target.value)}/><small id="custom-credit-hint">$10–$1,000{customAmount&&amount===null?' · Enter a valid amount.':''}</small></label>}
  {amount!==null&&<div className="credit-purchase-summary"><span>One-time purchase</span><strong>{priceLabel(amount)}</strong><small>{priceLabel(isCustom?amount:selected?.credit_cents??amount)} added to credits</small></div>}
  {status&&<div className="credit-recharge-section">
   {status.autoRecharge?.enabled?<div className="credit-recharge-current"><div><strong><RefreshCw size={17}/>Auto recharge is on</strong><p>{autoRechargeSummary(status.autoRecharge.amount_cents??amount??1000)}</p></div><button type="button" disabled={turningOff||busy} onClick={()=>void turnOff()}>{turningOff?'Turning off…':'Turn off'}</button></div>:<label className="credit-auto-recharge" data-checked={autoRecharge}><input type="checkbox" checked={autoRecharge} disabled={busy||!canPay} onChange={e=>setAutoRecharge(e.target.checked)}/><span><strong><RefreshCw size={18}/>Keep my bot working</strong><b>Enable auto recharge</b><small>{amount!==null?autoRechargeSummary(amount):'Choose an amount for auto recharge.'}</small></span></label>}
   {status.autoRecharge?.issue&&<p role="status" className="credit-recharge-issue">{status.autoRecharge.issue}</p>}
  </div>}
  <p className="credit-purchase-terms" id="credit-purchase-terms">Your bot starts eligible work after payment.</p>
  <details className="credit-full-terms"><summary>Full purchase terms</summary>{status?.earlyAccess&&<p>{earlyAccessDisclosure}</p>}<p>{workCreditTerms}{autoRecharge&&amount!==null?' '+autoRechargeTerms(amount):''}</p><a href="/costs-and-disclosures#one-time" target="_blank" rel="noopener noreferrer">All costs &amp; terms</a></details>
  <button className="fund-button full" disabled={busy||!canPay} aria-describedby="credit-purchase-terms" onClick={()=>void checkout()}>{busy?'Opening secure checkout…':amount!==null?`Add ${priceLabel(amount)} & continue`:'Enter an amount'}<ArrowRight size={17}/></button>
  <p className="credit-purchase-safe"><ShieldCheck size={14}/>{autoRecharge||status?.autoRecharge?.enabled?'You control auto recharge.':'One-time payment · Add more whenever you want.'}</p>
  {status&&!status.enabled&&<p role="status">Credit purchases are currently unavailable. <button onClick={()=>void refresh()}>Check again</button></p>}
  {error&&<p role="alert">{error} <button onClick={()=>void refresh()}>Retry</button></p>}
 </section>;
}
