'use client';
import {useEffect,useState} from 'react';
import {SigningControls,SigningAttention,type SigningEnvelope} from '@/components/signing-controls';
import {dealTermsSchema,type DealTerms,type DocumentKind} from '@/lib/deal-documents';
type Property={id:string;completed_at:string;result:{property:{address:string;propertyId:string;legalDescription?:string|null};financialCheck:{status:string;reason:string};preliminarySellerCeilingCents:number|null}};
type Deal={id:string;screening_id:string;terms:DealTerms;stage:string};
type Handoff={id:string;screening_id:string;party:string;reason:string;summary:string;next_action:string;state:string};
type Conversation={id:string;screening_id:string;party:string;result:{summary:string;transcript:{role:string;message:string}[]}};
type Work={signatureActions:{id:string;kind:string;test_mode:boolean}[];signing:SigningEnvelope[];signingConfigured:boolean;handoffs:Handoff[];conversations:Conversation[];callbacks:{id:string;screening_id:string;due_at:string;timezone:string;state:string}[];properties:Property[];deals:Deal[];contacts:{screening_id:string}[];hasMore:boolean;controls:{property_id:string}[]};
async function post(path:string,data:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw new Error(out.error||'Please retry.');return out;}
export function LiveWorkspace({principal}:{principal:string}){
 const [work,setWork]=useState<Work|null>(null),[error,setError]=useState(''),[page,setPage]=useState(0);
 useEffect(()=>{let active=true;async function load(){if(document.hidden)return;try{const r=await fetch(`/api/work/activity?page=${page}`,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();if(active){setWork(d);setError('');}}catch{if(active)setError('Could not refresh activity. Your saved work is unchanged.');}}void load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer);};},[page]);
 return <div className="live-work"><h3>{principal?`${principal}, your workspace`:'Your workspace'}</h3><p className="live-caption">Real work appears here as it happens.</p>{error&&<p role="alert">{error}</p>}{!work&&!error&&<p role="status">Loading your work…</p>}{work?.properties.length===0&&<p>No properties have been analyzed for your account yet. Live acquisition is still being configured.</p>}
 {work?.signatureActions?.map(e=><SigningAttention key={e.id} envelope={e}/>)}
 {work?.handoffs?.length? <section className="needs-you" aria-label="Needs you"><h3>🙋 Needs you</h3>{work.handoffs.map(h=><HandoffCard key={h.id} handoff={h}/>)}</section>:null}
 {work?.properties.map(p=><article className="live-property" key={p.id}><div className="live-property-heading"><strong>{p.result.property.address}</strong><span>{p.result.financialCheck.status==='eligible'?'Numbers worth reviewing':'Needs review'}</span></div><small>🔎 Analyzed {new Date(p.completed_at).toLocaleString()}</small>{work.contacts.some(c=>c.screening_id===p.id)&&<p>👤 Owner information received</p>}<details><summary>See property & documents</summary><p>{p.result.financialCheck.reason}</p>{p.result.preliminarySellerCeilingCents!==null&&<p>Preliminary seller ceiling: ${(p.result.preliminarySellerCeilingCents/100).toLocaleString()}. This is not an agreed offer.</p>}{work.conversations?.filter(c=>c.screening_id===p.id).map(c=><details key={c.id}><summary>💬 {c.party==='seller'?'Seller':'Buyer'} conversation</summary><p>{c.result.summary}</p><div className="conversation-messages">{c.result.transcript.map((t,i)=><p key={i} className={t.role==='agent'?'agent-message':'contact-message'}><small>{t.role==='agent'?'iCash X':c.party==='seller'?'Seller':'Buyer'}</small>{t.message}</p>)}</div></details>)}
 {work.callbacks?.filter(c=>c.screening_id===p.id).map(c=><p key={c.id}>📅 Requested callback: {new Date(c.due_at).toLocaleString(undefined,{timeZone:c.timezone})} ({c.timezone}). {c.state==='held_for_human'?'Waiting for you.':c.state==='canceled'?'Canceled.':c.state==='missed'?'Time passed—needs review.':c.state==='dispatched'?'Call dispatched.':'Saved; automatic dialing is not confirmed.'}</p>)}
 <DealTools signing={work.signing??[]} signingConfigured={work.signingConfigured} property={p} principal={principal} initial={work.deals.find(d=>d.screening_id===p.id)} initialManual={work.controls?.some(c=>c.property_id===p.result.property.propertyId)??false}/></details></article>)}
 {work&&(page>0||work.hasMore)&&<div className="live-pages"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Newer</button><span>Page {page+1}</span><button disabled={!work.hasMore} onClick={()=>setPage(p=>p+1)}>Older</button></div>}</div>;
}
function DealTools({property,principal,initial,initialManual,signing,signingConfigured}:{property:Property;principal:string;initial?:Deal;initialManual:boolean;signing:SigningEnvelope[];signingConfigured:boolean}){
 const [manual,setManual]=useState(initialManual);
 const [terms,setTerms]=useState<DealTerms>(()=>initial?.terms??dealTermsSchema.parse({address:property.result.property.address,buyer:principal,legalDescription:property.result.property.legalDescription??''}));
 const [dealId,setDealId]=useState(initial?.id??''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [showStart,setShowStart]=useState(''),[showBuyer,setShowBuyer]=useState('');
 const update=(key:keyof DealTerms,value:string|number|null)=>setTerms(t=>({...t,[key]:value}));
 async function save(){const d=await post('/api/work/deals',{screeningId:property.id,terms});setDealId(d.id);setTerms(d.terms);return d.id as string;}
 async function document(kind:DocumentKind){setBusy(true);setMessage('');try{const id=await save();const d=await post('/api/work/documents',{dealId:id,kind});const url=URL.createObjectURL(new Blob([d.html],{type:'text/html'}));const a=window.document.createElement('a');a.href=url;a.download=d.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Unsigned draft downloaded. Review the terms and required state addenda before signing.');}catch(e){setMessage(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
 async function propose(){setBusy(true);try{const id=dealId||await save();const start=new Date(showStart);const d=await post('/api/work/showings',{dealId:id,buyer:showBuyer,start:start.toISOString(),end:new Date(start.getTime()+1800000).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});setMessage(d.message);}catch(e){setMessage(e instanceof Error?e.message:'Choose a valid time.');}finally{setBusy(false);}}
 const amount=(key:'priceCents'|'assignmentFeeCents'|'earnestCents'|'assignmentDepositCents',label:string)=><label>{label}<input inputMode="decimal" type="number" min="0" step="0.01" value={terms[key]===null?'':terms[key]!/100} onChange={e=>update(key,e.target.value===''?null:Math.round(Number(e.target.value)*100))}/></label>;
 return <div className="deal-tools"><button disabled={busy} onClick={async()=>{setBusy(true);try{await post("/api/work/control",{action:manual?"return_to_bot":"takeover",screeningId:property.id});setManual(!manual);setMessage(manual?"Returned to bot controls. Setup, credits and permissions still apply.":"You have control. New owner enrichment is stopped; already-started work may finish.");}catch{setMessage("Could not change control. Retry.");}finally{setBusy(false);}}}>{manual?"Return to bot":"Take over this property"}</button><p><strong>Contract name:</strong> {principal||'Add your company or full name in Account details.'}</p><div className="deal-fields"><label>Seller’s full legal name(s)<input value={terms.seller} onChange={e=>update('seller',e.target.value)}/></label>{amount('priceCents','Purchase price ($)')}</div><details><summary>Contract terms</summary><div className="deal-fields"><label>Price status<select value={terms.priceSource} onChange={e=>update('priceSource',e.target.value)}><option value="proposed">Proposed—not yet agreed</option><option value="seller_reported">Seller agreed, reported by me</option></select></label><label>State (e.g. TX)<input maxLength={2} value={terms.state} onChange={e=>update('state',e.target.value.toUpperCase())}/></label><label>Legal description<textarea value={terms.legalDescription} onChange={e=>update('legalDescription',e.target.value)}/></label><label>Inspection days (proposed)<input type="number" min="0" max="90" value={terms.inspectionDays} onChange={e=>update('inspectionDays',Number(e.target.value))}/></label><label>Contract effective date<input type="date" value={terms.effectiveDate} onChange={e=>update('effectiveDate',e.target.value)}/></label><label>Closing date<input type="date" value={terms.closingDate} onChange={e=>update('closingDate',e.target.value)}/></label>{amount('earnestCents','Seller-contract earnest money ($)')}<label>Cash buyer’s legal name<input value={terms.assignee} onChange={e=>update('assignee',e.target.value)}/></label>{amount('assignmentFeeCents','Assignment fee ($)')}{amount('assignmentDepositCents','Buyer deposit ($)')}<label>Title / escrow company<input value={terms.escrowAgent} onChange={e=>update('escrowAgent',e.target.value)}/></label><label>Title email<input type="email" value={terms.titleEmail} onChange={e=>update('titleEmail',e.target.value)}/></label><label>Preferred proceeds method<select value={terms.payoutMethod} onChange={e=>update('payoutMethod',e.target.value)}><option value="wire">Wire transfer</option><option value="ach">ACH</option><option value="check">Check</option><option value="zelle">Zelle, if closing agent supports it</option><option value="cash_app">Cash App, if closing agent supports it</option></select></label></div><small>Buyer-paid closing charges are included, with required exceptions. Deposit release follows the signed agreement and escrow instructions. Never enter bank details here.</small></details>
 <div className="deal-actions">{(['purchase','assignment','buyer_package','title_packet'] as DocumentKind[]).map((kind,i)=><button key={kind} disabled={busy||!principal} onClick={()=>void document(kind)}>{['Purchase draft','Assignment draft','Buyer package','Title request'][i]}</button>)}</div><small>Documents are unsigned drafts. Required addenda may add pages. Nothing is sent automatically.</small>
 <SigningControls dealId={dealId} save={save} envelopes={signing.filter(e=>e.deal_id===dealId)} configured={signingConfigured} stage={initial?.stage??'draft'}/><details><summary>Arrange a showing</summary><label>Buyer name<input value={showBuyer} onChange={e=>setShowBuyer(e.target.value)}/></label><label>Proposed time ({Intl.DateTimeFormat().resolvedOptions().timeZone})<input type="datetime-local" value={showStart} onChange={e=>setShowStart(e.target.value)}/></label><button disabled={busy||!showStart||!showBuyer} onClick={()=>void propose()}>Hold a 30-minute time</button><p>Seller/occupant and buyer must confirm. No invitation is sent yet.</p></details>{message&&<p role="status">{message}</p>}</div>;
}

function HandoffCard({handoff:h}:{handoff:Handoff}){
 const [state,setState]=useState(h.state),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <article className="handoff-card"><strong>{h.party==='buyer'?'Buyer':'Seller'} needs a person</strong><p>{h.reason}</p><details><summary>See summary & next step</summary><p>{h.summary}</p><p>{h.next_action}</p><small>Automation is paused for this property. Return control from the property only when you are ready.</small></details>{state==='open'&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await post('/api/work/handoffs',{id:h.id});setState('acknowledged');}catch{setError('Could not save. Please retry.');}finally{setBusy(false);}}}>I’ll handle this</button>}{state==='acknowledged'&&<small>You’re handling this. Bot stays paused.</small>}{error&&<p role="alert">{error}</p>}</article>;
}
