'use client';
import {useEffect,useState,useRef} from 'react';
type Data={contacts:{phone:string;available:boolean;reason:string}[];reason?:string};
export function ManualCallOptions({screeningId,onTakeover}:{screeningId:string;onTakeover?:()=>void}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[checked,setChecked]=useState(0),[busy,setBusy]=useState(false);const lock=useRef(false);
 async function call(phone:string){if(lock.current)return;if(Date.now()-checked>30000){setRefresh(v=>v+1);setError('Refreshing this contact. Try again once it loads.');return;}lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/work/manual-call',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({screeningId,phone})});const d=await r.json();if(!r.ok||d.manual!==true||d.dialUrl!==`tel:${phone}`)throw Error(d.error||'Could not start the call.');onTakeover?.();window.location.assign(d.dialUrl);}catch(e){setError(e instanceof Error?e.message:'Could not start the call.');}finally{lock.current=false;setBusy(false);}}
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');void fetch(`/api/work/manual-call?screeningId=${encodeURIComponent(screeningId)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();const next=await r.json() as Data;if(!controller.signal.aborted){setData(next);setChecked(Date.now());}}).catch(()=>{if(!controller.signal.aborted)setError('Could not check call permission.');});const timer=setInterval(()=>setRefresh(v=>v+1),30000);return()=>{controller.abort();clearInterval(timer);};},[screeningId,refresh]);
 return <section className="manual-call-options" aria-label="Call from your phone"><h5>Call this contact</h5><small>Pauses the bot on this lead and opens your phone dialer. Phone calls aren’t recorded here.</small>{!data&&!error&&<p role="status">Checking call permission…</p>}{error&&<p role="alert">{error} <button onClick={()=>setRefresh(v=>v+1)}>Retry</button></p>}{data&&!data.contacts.length&&<><p>{data.reason??'No phone number available.'}</p><button disabled>Call unavailable</button></>}{data?.contacts.map(contact=><div className="manual-call-contact" key={contact.phone}><strong>Listed contact · {contact.phone}</strong><small>{contact.reason}</small>{contact.available&&/^\+1[2-9][0-9]{9}$/.test(contact.phone)?<button type="button" disabled={busy} onClick={()=>void call(contact.phone)}>{busy?'Taking control…':'Call from my phone'}</button>:<button disabled>Call unavailable</button>}</div>)}</section>;
}
