'use client';
import {useEffect,useRef,useState} from 'react';
import {priceLabel} from '@/lib/membership-policy';
export function MembershipSettings(){
 const [data,setData]=useState<{state:string;priceCents:number;paidThrough:string|null;cancelAtPeriodEnd:boolean;accessible:boolean}|null>(null),[loaded,setLoaded]=useState(false),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const operation=useRef(false);
 async function load(){try{const r=await fetch('/api/billing/membership',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();setData(d.membership);setLoaded(true);}catch{setMessage('Could not load your software subscription.');}}
 useEffect(()=>{void load();},[]);
 async function act(action:'cancel'|'manage'){if(operation.current)return;operation.current=true;setBusy(true);setMessage('');try{const r=await fetch('/api/billing/membership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.url){const url=new URL(d.url);if(url.protocol!=='https:'||url.hostname!=='billing.stripe.com')throw Error('Billing portal unavailable.');window.location.assign(url.href);}else{setMessage(d.message);setConfirm(false);await load();}}catch(e){setMessage(e instanceof Error?e.message:'Could not confirm this change.');}finally{operation.current=false;setBusy(false);}}
 return <div className="membership-settings">{data?<><p><strong>{priceLabel(data.priceCents)}/month</strong> · Software access</p><p>{data.cancelAtPeriodEnd?'Future renewals are cancelled.':data.accessible?'Monthly renewal is active.':'Your subscription needs attention.'}{data.paidThrough?` Paid through ${new Date(data.paidThrough).toLocaleDateString()}.`:''} Work credits are separate.</p>{!data.accessible&&['pending','cancelled'].includes(data.state)&&<a href="/join">{data.state==='pending'?'Resume software checkout':'Restart software access'}</a>}<button disabled={busy} onClick={()=>void act('manage')}>Manage payment &amp; invoices</button>{!data.cancelAtPeriodEnd&&<button disabled={busy} onClick={()=>setConfirm(true)}>Cancel monthly renewal</button>}{confirm&&<div className="membership-cancel-review"><p>Stop future software renewals? Your access continues through the paid period. Work credits remain on your account.</p><button disabled={busy} onClick={()=>setConfirm(false)}>Keep subscription</button><button disabled={busy} onClick={()=>void act('cancel')}>Confirm cancellation</button></div>}</>:<p>{loaded?'No monthly software subscription is linked to this account.':'Loading subscription…'}</p>}{message&&<p role="status">{message}</p>}</div>;
}
