'use client';
import {webinarBrowserEvent} from '@/lib/webinar-browser-events';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,ShieldCheck} from 'lucide-react';
import {PostPurchaseSetup} from './post-purchase-setup';
import {StripeEmbeddedCheckout} from './stripe-embedded-checkout';
import {membershipTermsVersion,priceLabel,type MembershipOffer} from '@/lib/membership-policy';
type Status={offer:MembershipOffer;ready:boolean;mode:'live'|'test';needsClaim:boolean;embeddedReady:boolean;customerName:string;email:string|null;membership:{state:string;priceCents:number;accessible:boolean;paidThrough:string|null;cancelAtPeriodEnd:boolean}|null};
export function MembershipCheckout({onSignedIn,embedded=false,onEngaged}:{onSignedIn:()=>void;embedded?:boolean;onEngaged?:()=>void}){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[returning,setReturning]=useState(false);
 const [checkoutForm,setCheckoutForm]=useState<{clientSecret:string;publishableKey:string}|null>(null);
 const operation=useRef(false),alive=useRef(true),reading=useRef(false),consent=useRef(''),sessionRef=useRef<string|null>(null),engaged=useRef(false);
 function engage(){if(!engaged.current){engaged.current=true;onEngaged?.();}}
 async function load(){if(reading.current)return;reading.current=true;try{const sessionId=sessionRef.current;const response=await fetch('/api/billing/membership'+(sessionId?'?session_id='+encodeURIComponent(sessionId):''),{cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error);if(alive.current){setData(result);setError('');const next=`${result.offer.revision}:${result.offer.priceCents}`;if(consent.current!==next){setAccepted(false);consent.current=next;}if(result.membership?.accessible)engage();}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Could not load checkout.');}finally{reading.current=false;}}
 useEffect(()=>{alive.current=true;const params=new URLSearchParams(window.location.search);sessionRef.current=params.get('session_id');setReturning(params.get('membership')==='paid');void load();return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!returning||data?.membership?.accessible)return;let tries=0;const timer=setInterval(()=>{if(!document.hidden&&++tries<=12)void load();if(tries>=12)clearInterval(timer);},5000);return()=>clearInterval(timer);},[returning,data?.membership?.accessible]);
 async function checkout(){if(operation.current||!data?.ready||!accepted)return;operation.current=true;setBusy(true);setError('');engage();try{const r=await fetch('/api/billing/membership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'checkout',accepted:true,version:membershipTermsVersion,revision:data.offer.revision,totalCents:data.offer.priceCents,...(embedded&&data.embeddedReady?{embedded:true}:{})})});const out=await r.json();if(!alive.current)return;if(!r.ok)throw Error(out.error);if(data.mode==='live')webinarBrowserEvent('checkout_started');if(out.clientSecret&&out.publishableKey&&out.sessionId){sessionRef.current=out.sessionId;setCheckoutForm({clientSecret:out.clientSecret,publishableKey:out.publishableKey});return;}const url=new URL(out.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw Error('Secure checkout could not open.');window.location.assign(url.href);}catch(e){await load();if(alive.current)setError(e instanceof Error?e.message:'Checkout could not open.');}finally{operation.current=false;if(alive.current)setBusy(false);}}
 if(data?.membership?.accessible)return <PostPurchaseSetup email={data.email??''} customerName={data.customerName??''} needsClaim={data.needsClaim} onWorkspace={onSignedIn}/>;
 if(returning)return <div className="membership-success" role="status"><h2>Confirming your payment</h2><p>Your purchase is being checked. Please don’t pay again.</p>{error&&<p role="alert">{error}</p>}<button className="workspace-quiet" onClick={()=>void load()}>Check payment</button></div>;
 if(checkoutForm)return <div><StripeEmbeddedCheckout {...checkoutForm} onComplete={()=>{setCheckoutForm(null);setReturning(true);void load();}}/><p className="membership-secure"><ShieldCheck size={14}/>Your information stays with your purchase.</p>{error&&<p role="alert">{error}</p>}<button className="membership-embedded-back" onClick={()=>{setCheckoutForm(null);void load();}}>Back to offer</button></div>;
 return <section className="membership-checkout" aria-label="Software checkout">
  <span className="membership-caption">ICASH X SOFTWARE ACCESS</span><div className="membership-price">{data?<>{priceLabel(data.offer.priceCents)}<small>/month</small></>:<span>Checking price…</span>}</div>
  <p className="membership-description">Your AI workspace. Your contacts, conversations, and deal tools in one place.</p>
  <ul className="membership-includes">{['Your personalized AI bot','Property research & cash offer estimates','Call & text conversation history','Buyer matching & contract tools','AI guidance for the next step'].map(label=><li key={label}><Check size={15} aria-hidden="true"/>{label}</li>)}</ul>
  <div className="membership-credits-note"><strong>Work credits are separate</strong><p>Start with a $0 work balance. Add $10, $25, $50, $100, or more inside your workspace. Credits fund eligible AI activity. No daily billing or automatic credit refill.</p></div>
  {data?.mode==='test'&&<p className="membership-note">Test checkout · No live work.</p>}
  <p className="membership-renewal" id="membership-terms">{data?priceLabel(data.offer.priceCents):'The displayed price'} billed monthly until cancelled. Cancel future renewals in Settings. No work credits are included. Live work requires setup and available services; no deal or income is guaranteed.</p>
  <label className="membership-consent"><input type="checkbox" checked={accepted} disabled={busy||!data?.ready} onChange={e=>setAccepted(e.target.checked)} aria-describedby="membership-terms"/><span>I authorize the monthly software subscription above.</span></label>
  <button className="setup-primary" disabled={busy||!accepted||!data?.ready} onClick={()=>void checkout()}>{busy?'Opening secure checkout…':data?`Get software access — ${priceLabel(data.offer.priceCents)}/month`:'Checking checkout…'}<ArrowRight size={17}/></button>
  <p className="membership-secure"><ShieldCheck size={14} aria-hidden="true"/>{embedded&&data?.embeddedReady?'Secure payment here through Stripe':'Continues to secure Stripe checkout'}</p>
  {data&&!data.ready&&<p role="status">Checkout is currently unavailable. <button onClick={()=>void load()}>Check again</button></p>}{error&&<p className="membership-error" role="alert">{error} <button onClick={()=>void load()}>Retry</button></p>}
 </section>;
}
