'use client';
import {useEffect,useRef,useState} from 'react';
type Receipt={id:string;createdAt:string;status:string;callEnded:boolean;audioAvailable:boolean;durationSeconds:number|null;audioExpiresAt:string|null;holdCents:number;chargedCents:number|null;billingMode:'automatic'|'manual_review';reviewRequired:boolean;recordingCostMicros:number|null;recordingCostBasis:string;storageEstimateMicros:number|null;speechGatherEstimateMicros:number|null;providerRecordingSid:string|null;retentionDays:number;costBasis:string};
const states:Record<string,string>={reserved:'Waiting for consent setup',setup_pending:'Preparing consent',consent_pending:'Awaiting recording permission',declined:'Recording declined; ending call',starting:'Starting recording',recording:'Recording in progress',stopping:'Ending call',processing:'Awaiting verified recording',available:'Recording available',absent:'Audio unavailable',failed:'Recording setup failed',expired:'Audio expired',deletion_pending:'Audio deletion pending',deleted:'Audio deleted'};
const dollars=(n:number,divisor=100)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:divisor===100?2:6}).format(n/divisor);
function read(value:unknown):Receipt[]{
 const x=value as {recordings?:unknown};if(!x||!Array.isArray(x.recordings)||x.recordings.length>20)throw Error('INVALID_RECEIPTS');
 return x.recordings.map(value=>{const r=value as Receipt;
  if(!r||typeof r.id!=='string'||!/^[a-f0-9-]{36}$/i.test(r.id)||!Object.hasOwn(states,r.status)||!['automatic','manual_review'].includes(r.billingMode)||typeof r.callEnded!=='boolean'||typeof r.reviewRequired!=='boolean'||typeof r.audioAvailable!=='boolean'||typeof r.createdAt!=='string'||!Number.isFinite(Date.parse(r.createdAt))||!Number.isSafeInteger(r.holdCents)||r.holdCents<1||r.chargedCents!==null&&(!Number.isSafeInteger(r.chargedCents)||r.chargedCents<0)||r.durationSeconds!==null&&(!Number.isInteger(r.durationSeconds)||r.durationSeconds<0||r.durationSeconds>600)||r.audioExpiresAt!==null&&!Number.isFinite(Date.parse(r.audioExpiresAt))||r.audioAvailable&&(r.status!=='available'||!r.audioExpiresAt)||[r.recordingCostMicros,r.storageEstimateMicros,r.speechGatherEstimateMicros].some(n=>n!==null&&(!Number.isSafeInteger(n)||n<0)))throw Error('INVALID_RECEIPTS');return r;});
}
export function ReceptionRecordings(){
 const [state,setState]=useState<{phase:'loading'|'error'|'ready';rows:Receipt[]}>({phase:'loading',rows:[]}),[revision,setRevision]=useState(0),busy=useRef(false);
 useEffect(()=>{const controller=new AbortController();busy.current=true;setState({phase:'loading',rows:[]});void fetch('/api/work/reception-recording',{cache:'no-store',credentials:'same-origin',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('UNAVAILABLE');return read(await r.json());}).then(rows=>{if(!controller.signal.aborted)setState({phase:'ready',rows});}).catch(()=>{if(!controller.signal.aborted)setState({phase:'error',rows:[]});}).finally(()=>{if(!controller.signal.aborted)busy.current=false;});return()=>controller.abort();},[revision]);
 return <section aria-label="Private incoming call recordings"><p>Audio is private to this business and expires 30 days after recording starts. Written transcript retention is separate. Anyone who can play audio in a browser can save a copy.</p>
  <button type="button" disabled={state.phase==='loading'} onClick={()=>{if(!busy.current){busy.current=true;setRevision(n=>n+1);}}}>Refresh recordings</button>
  {state.phase==='loading'&&<p role="status">Loading recordings…</p>}{state.phase==='error'&&<p role="alert">Could not load reception recordings. Sign in with the owning account and retry.</p>}
  {state.phase==='ready'&&!state.rows.length&&<p>No recorded incoming calls are available. Historical unrecorded calls do not acquire audio retroactively.</p>}
  {state.rows.map(r=><article key={r.id} style={{marginTop:24,padding:20,border:'1px solid #ddd',borderRadius:12}}><h2>{new Date(r.createdAt).toLocaleString()}</h2><p>{r.status==='declined'&&r.callEnded?'Recording declined; call ended':states[r.status]}</p>
   <p>Reserved maximum: {dollars(r.holdCents)}. This reservation is not a charge. Settled charge: {r.chargedCents===null?'Pending':dollars(r.chargedCents)}.</p>
   <p>{r.billingMode==='automatic'?'Billing uses the policy approved for this call. Missing or conflicting cost evidence may require review.':'This session requires its original per-call cost review.'}</p>
   {r.reviewRequired&&<p role="alert">A later provider receipt conflicts with the settled costs. The original charge is preserved; this needs review before any adjustment.</p>}
   <p>Recorded duration: {r.durationSeconds===null?'Not reported':r.durationSeconds+' seconds'}. Audio expiry: {r.audioExpiresAt?new Date(r.audioExpiresAt).toLocaleString():'Not reported'}.</p>
   {r.audioAvailable&&r.audioExpiresAt&&Date.parse(r.audioExpiresAt)>Date.now()&&<audio key={r.id} controls preload="none" aria-label="Incoming call recording" src={'/api/work/reception-recording/audio?id='+encodeURIComponent(r.id)}/>}
   <p>Recording: {r.recordingCostMicros===null?'Pending':dollars(r.recordingCostMicros,1000000)+' ('+r.recordingCostBasis+')'}. Storage estimate: {r.storageEstimateMicros===null?'Pending':dollars(r.storageEstimateMicros,1000000)}. Spoken-consent estimate: {r.speechGatherEstimateMicros===null?'Pending':dollars(r.speechGatherEstimateMicros,1000000)}.</p><p>Audio does not verify provider costs. Full settlement requires separate reviewed cost evidence.</p>
  </article>)}
 </section>;
}
