'use client';
import {useRef,useState,type FormEvent} from 'react';
import {ArrowRight,Check,MapPin,Phone,ShieldCheck,House,ArrowLeft} from 'lucide-react';
import {sellerBrand,sellerConsentVersion,sellerConsentText,sellerSharingText} from '@/lib/seller-leads';
export function SellerIntake(){
 const [step,setStep]=useState<'address'|'contact'>('address');const nameInput=useRef<HTMLInputElement>(null);
 const [name,setName]=useState(''),[address,setAddress]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[consented,setConsented]=useState(false),[owner,setOwner]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[trap,setTrap]=useState('');const request=useRef(''),lock=useRef(false);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');if(!request.current)request.current=crypto.randomUUID();try{
  const q=new URLSearchParams(window.location.search),rawSource=q.get('utm_source')?.toLowerCase()||'direct',source=rawSource==='facebook'||rawSource==='instagram'?'meta':['meta','google','youtube','tiktok'].includes(rawSource)?rawSource:'direct';
  const campaign=(q.get('campaign')||q.get('utm_campaign')||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100),clickId=(q.get('fbclid')||q.get('gclid')||q.get('ttclid')||'').replace(/[^a-zA-Z0-9_.:-]/g,'').slice(0,300);
  const r=await fetch('/api/seller/intake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,address,phone,email,consented,ownerConfirmed:owner,consentVersion:sellerConsentVersion,requestId:request.current,campaign,source,clickId,honeypot:trap})});const d=await r.json();if(!r.ok)throw Error(d.error||'Please retry.');setDone(true);
 }catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{lock.current=false;setBusy(false);}}
 return <main className="seller-shell">
 <header className="seller-header"><a className="seller-wordmark" href="/sell" aria-label={sellerBrand+' home'}><span className="seller-brand-mark"><House size={25}/></span><span>HomeOffer<span className="seller-network">NETWORK</span></span></a><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="/sell/privacy">Your privacy</a></nav></header>
 <section className="seller-hero"><div className="seller-story">
 <span className="seller-kicker">A FRESH START, ON YOUR TERMS</span>
 <h1>Your home.<br/>Your next <em>chapter.</em></h1>
 <p className="seller-intro">Explore a cash offer for your home. Start with your address. Decide what comes next.</p>
 <div className="seller-card">{done?<div className="seller-success" role="status"><span><Check size={30}/></span><h2>Your request is in.</h2><p>We’ll check your property and match it with available buyers. Buyers may contact you at different times. You choose whether to continue.</p><a href="/sell/privacy">Your information & contact choices</a></div>:step==='address'?<form className="seller-address-form" onSubmit={e=>{e.preventDefault();if(address.trim().length<8)return;setError('');setStep('contact');requestAnimationFrame(()=>nameInput.current?.focus());}}>
 <label htmlFor="seller-address">Where’s your property?</label><div className="seller-address-bar"><MapPin size={22}/><input id="seller-address" name="street-address" autoComplete="street-address" enterKeyHint="next" required minLength={8} maxLength={300} value={address} onChange={e=>{setAddress(e.target.value);request.current='';}} placeholder="Enter your home address"/><button type="submit" aria-label="Continue with this address"><ArrowRight size={24}/></button></div><p className="seller-address-hint">Include your city, state and ZIP.</p><div className="seller-benefits"><span><Check size={15}/>No obligation</span><span><Check size={15}/>No account needed</span></div>
 </form>:<><button className="seller-back" onClick={()=>setStep('address')}><ArrowLeft size={15}/>Change address</button><p className="seller-selected-address"><MapPin size={16}/>{address}</p><h2>Who can buyers contact?</h2><form onSubmit={submit}><label htmlFor="seller-name">Your name</label><input ref={nameInput} id="seller-name" name="name" autoComplete="name" required maxLength={100} value={name} onChange={e=>{setName(e.target.value);request.current='';}} placeholder="First and last name" disabled={busy}/><label htmlFor="seller-phone">Best phone number</label><div className="seller-input-icon"><Phone size={17}/><input id="seller-phone" name="tel" type="tel" autoComplete="tel" required maxLength={30} value={phone} onChange={e=>{setPhone(e.target.value);request.current='';}} placeholder="(555) 123-4567" disabled={busy}/></div><label htmlFor="seller-email">Email (optional)</label><input id="seller-email" name="email" type="email" autoComplete="email" maxLength={254} value={email} onChange={e=>{setEmail(e.target.value);request.current='';}} placeholder="you@example.com" disabled={busy}/><div className="seller-trap" aria-hidden="true"><label>Leave this empty<input tabIndex={-1} autoComplete="off" value={trap} onChange={e=>setTrap(e.target.value)}/></label></div><label className="seller-choice"><input type="checkbox" checked={owner} onChange={e=>{setOwner(e.target.checked);request.current='';}} required disabled={busy}/><span>I own this property or am authorized to discuss its sale.</span></label><label className="seller-choice seller-ai-consent"><input type="checkbox" checked={consented} onChange={e=>{setConsented(e.target.checked);request.current='';}} disabled={busy}/><span>{sellerConsentText}</span></label><button className="seller-submit" disabled={busy||!owner}>{busy?'Saving your request…':'Request my cash offer'}<ArrowRight size={18}/></button>{error&&<p role="alert" className="seller-error">{error}</p>}<span className="seller-form-note"><ShieldCheck size={14}/>No payment. No obligation to sell.</span><p className="seller-privacy-note">By submitting, you acknowledge our <a href="/sell/privacy">Privacy & sharing notice</a>. Contact consent is optional.</p></form></>}</div>
 </div><div className="seller-visual"><img src="/homeoffer-neighborhood.webp" width={1536} height={1024} alt="A welcoming neighborhood in the warm evening light" fetchPriority="high"/><div className="seller-photo-caption"><span>ROOM FOR WHAT’S NEXT</span><p>A new beginning<br/>starts at home.</p></div><span className="seller-photo-note">Illustrative neighborhood</span></div></section>
 <section id="how-it-works" className="seller-how"><div><span className="seller-kicker">FROM ADDRESS TO OPPORTUNITY</span><h2>A simpler way forward.</h2><p>You stay in control, every step of the way.</p></div><ol><li><span>01</span><h3>Start with your address</h3><p>Tell us where your property is and how to reach you.</p></li><li><span>02</span><h3>Connect with cash buyers</h3><p>We share your request with matched, independent buyers in our network.</p></li><li><span>03</span><h3>Choose your next move</h3><p>Discuss your options and any offers. Accept only what works for you.</p></li></ol></section>
 <footer className="seller-footer"><strong>HomeOffer Network</strong><p>{sellerSharingText}</p><a href="/sell/privacy">Privacy & contact choices</a><span>© {new Date().getFullYear()} HomeOffer Network</span></footer></main>;
}
