'use client';
import {useEffect,useState} from 'react';
import {normalizeSigningPhone} from '@/lib/signing-phone';
export type SigningEnvelope={id:string;deal_id:string;kind:'purchase'|'assignment';state:string;test_mode:boolean};
const labels:Record<string,string>={creating:'Preparing signing request',awaiting_counterparty:'Waiting for the other party to sign',customer_signature_needed:'Action required: review and sign',completed:'All signatures verified',test_completed:'Test signing completed',needs_review:'Signing request needs review'};
export function SigningControls({dealId,save,envelopes,configured,stage,reviewVersion}:{dealId:string;save:()=>Promise<string>;envelopes:SigningEnvelope[];configured:boolean;stage:string;reviewVersion:string}){
 const [signers,setSigners]=useState([{name:'',phone:''}]),[confirmed,setConfirmed]=useState(false),[autoSign,setAutoSign]=useState(false),[signature,setSignature]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{setConfirmed(false);setAutoSign(false);setSignature('');},[reviewVersion]);
 const kind=stage==='draft'?'purchase':'assignment';
 async function action(body:unknown){const r=await fetch('/api/work/signing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
 return <details className="signing-controls"><summary>✍️ Contracts & signatures{envelopes.some(e=>e.state==='customer_signature_needed')?' — Needs you':''}</summary>
 {envelopes.map(e=><div key={e.id} className="handoff-card"><strong>{e.kind==='purchase'?'Purchase':'Assignment'}: {labels[e.state]??'Checking status'}</strong>{e.test_mode&&<p>Test document—not a binding contract.</p>}{e.state==='customer_signature_needed'&&<button disabled={busy} onClick={()=>void run(async()=>{const d=await action({action:'link',id:e.id});window.location.assign(d.url);})}>Review & sign</button>}{['completed','test_completed'].includes(e.state)?<div><a href={`/api/work/signing?id=${e.id}`}>Download signed PDF</a><a href={`/api/work/signing?id=${e.id}&audit=true`}>Download audit trail</a></div>:<button disabled={busy} onClick={()=>void run(async()=>{const d=await action({action:'refresh',id:e.id});setMessage(labels[d.status]??'Status checked.');})}>Check signature status</button>}{!['completed','test_completed'].includes(e.state)&&<button disabled={busy} onClick={()=>void run(async()=>{const d=await action({action:'revoke_auto',id:e.id});setMessage(d.message);})}>Turn off auto-sign</button>}</div>)}
 {!configured?<p>Electronic signing setup is being completed. Draft downloads are available above.</p>:!envelopes.some(e=>e.kind===kind)&&<><p>{kind==='purchase'?'Every required seller signs first. Then you review and sign.':'The cash buyer signs first. Then you review and sign.'}</p>{signers.map((s,i)=><div className="deal-fields" key={i}><label>{kind==='purchase'?'Seller':'Cash buyer'} {i+1} legal name<input autoComplete="off" value={s.name} onChange={e=>setSigners(a=>a.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/></label><label>Signing phone<input type="tel" placeholder="+1" autoComplete="tel" value={s.phone} onChange={e=>setSigners(a=>a.map((v,n)=>n===i?{...v,phone:e.target.value}:v))}/></label>{i>0&&<button onClick={()=>setSigners(a=>a.filter((_,n)=>n!==i))}>Remove signer</button>}</div>)}{signers.length<8&&<button onClick={()=>setSigners(a=>[...a,{name:'',phone:''}])}>Add required signer</button>}<label className="signing-confirm"><input type="checkbox" checked={autoSign} onChange={e=>setAutoSign(e.target.checked)}/>Auto-sign this exact agreement after the other parties sign.</label>{autoSign&&<label>Your full legal name for your typed electronic signature<input value={signature} onChange={e=>setSignature(e.target.value)}/><small>By sending, I authorize iCash X to apply this electronic signature to this exact agreement after the other parties sign. This authorization expires after 30 days and does not cover changed terms or future deals.</small></label>}<label className="signing-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the agreed terms, legal description and all required signers. Send this agreement for signatures.</label><button disabled={busy||!confirmed||(autoSign&&signature.trim().length<2)||signers.some(s=>!s.name||!normalizeSigningPhone(s.phone))} onClick={()=>void run(async()=>{const id=await save();const d=await action({action:'send',dealId:id||dealId,kind,signers:signers.map(s=>({...s,phone:normalizeSigningPhone(s.phone)})),confirmed:true,...(autoSign?{autoSignature:signature}:{})});setMessage(d.message);setConfirmed(false);})}>Text contract link</button><small>The seller gets a secure text link. Once they sign, your workspace shows Review & sign.</small></>}{message&&<p role="status">{message}</p>}</details>;
}
export function SigningAttention({envelope:e}:{envelope:{id:string;kind:string;test_mode:boolean}}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="needs-you"><strong>✍️ Action required: review & sign</strong><p>{e.kind==='purchase'?'The seller signatures are complete. Your signature is next. Read the full agreement before accepting.':'The cash buyer has signed. Your signature is next. Read the full agreement before accepting.'}{e.test_mode?' This is a test document.':''}</p><details><summary>What happens when I sign?</summary><p>{e.kind==='purchase'?'You accept the purchase terms, including the purchase price, inspection period and closing deadline.':'You accept the assignment terms, including the fee, buyer deposit and closing-cost allocation.'} If anything differs from what you agreed, do not sign. Open the property’s contracts to review or handle it yourself.</p></details><button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/work/signing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'link',id:e.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);window.location.assign(d.url);}catch(err){setError(err instanceof Error?err.message:'Please retry.');setBusy(false);}}}>Review & sign</button>{error&&<p role="alert">{error}</p>}</section>;
}
