'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {FundingDialog} from '@/components/funding-dialog';
import {priceLabel} from '@/lib/membership-policy';
type Allowance={day:string;limitCents:number;spentCents:number;reservedCents:number;remainingCents:number;availableCents:number;extraCents:number;resetsAt:string};
export function SpendingAllowance(){
 const [data,setData]=useState<Allowance|null>(null),[open,setOpen]=useState(false),[amount,setAmount]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const locked=useRef(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/work/allowance',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();const d=await r.json();setData(d);setError('');return d as Allowance;}catch{setError('Could not refresh today’s allowance.');return null;}},[]);
 useEffect(()=>{void load();const t=setInterval(()=>{if(!document.hidden)void load();},30000);return()=>clearInterval(t);},[load]);
 const maximum=data?Math.max(0,data.availableCents-data.remainingCents):0;
 const extra=Math.round(Number(amount)*100),valid=/^\d+(\.\d{1,2})?$/.test(amount)&&Number.isSafeInteger(extra)&&extra>0&&extra<=maximum;
 async function save(){if(!data||!valid||locked.current)return;locked.current=true;setBusy(true);setError('');try{const r=await fetch('/api/work/allowance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({day:data.day,extraTotalCents:data.extraCents+extra}),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setOpen(false);setAmount('');}catch(e){setError(e instanceof Error?e.message:'Could not save.');await load();}finally{locked.current=false;setBusy(false);}}
 return <section className="spending-allowance" aria-label="Today’s spending allowance"><div><span>Today’s allowance</span><strong>{data?`${priceLabel(data.remainingCents)} remaining`:'Checking…'}</strong>{data&&<small>Up to {priceLabel(data.limitCents)} today · 50% daily pace</small>}</div>{data&&maximum>0&&<button type="button" onClick={()=>{setOpen(true);setError('');setAmount((Math.min(500,maximum)/100).toFixed(2));}}>Allow more spending today</button>}{data?.remainingCents===0&&data.availableCents>0&&<p>Today’s allowance is committed. Allow more or wait for tomorrow’s reset.</p>}{error&&!open&&<p role="status">{error} <button onClick={()=>void load()}>Retry</button></p>}{open&&data&&<FundingDialog title="Allow more spending today" onClose={()=>{if(!busy)setOpen(false);}}><form className="allowance-form" onSubmit={e=>{e.preventDefault();void save();}}><p>Use more of your existing credits today. No card charge.</p><label htmlFor="allowance-extra">Additional amount</label><div className="allowance-input"><span>$</span><input id="allowance-extra" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} disabled={busy}/></div><small>Up to {priceLabel(maximum)} more is available.</small>{valid&&<p>New daily limit: <strong>{priceLabel(data.limitCents+extra)}</strong></p>}<p>Resets at midnight Central. Your bot stays paused if you paused it.</p><button className="fund-button" disabled={!valid||busy}>{busy?'Saving…':'Confirm today’s allowance'}</button>{error&&<p role="alert">{error}</p>}</form></FundingDialog>}</section>;
}
