'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {OperatorExceptions} from '@/components/operator-exceptions';
import type {SupportEvidence} from '@/lib/support-policy';
type Ticket={id:string;account_id:string;subject:string;status:string;updated_at?:string};
type Message={id:string;role:string;content:string;created_at:string};
type CancelReview={id:string;account_id:string;mode:'live'|'test';state:string;result:string|null;receipt_state?:string};
export function SupportDashboard(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<Ticket|null>(null),[messages,setMessages]=useState<Message[]>([]),[evidence,setEvidence]=useState<SupportEvidence[]>([]),[cancellations,setCancellations]=useState<CancelReview[]>([]);
 const [deployment,setDeployment]=useState(''),[reply,setReply]=useState(''),[status,setStatus]=useState('open'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');const sequence=useRef(0);const pendingSave=useRef<{id:string;body:string}|null>(null);
 const loadQueue=useCallback(async()=>{try{const r=await fetch('/api/support/admin',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setTickets(d.threads);setCancellations(d.cancellations);setDeployment(d.deployment.detail);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load support.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void loadQueue();},[loadQueue]);
 async function open(id:string){const seq=++sequence.current;setBusy(true);setError('');try{const r=await fetch('/api/support/admin?threadId='+id,{cache:'no-store'});const d=await r.json();if(seq!==sequence.current)return;if(!r.ok)throw Error(d.error);setSelected(d.thread);setStatus(d.thread.status);setMessages(d.messages);setEvidence(d.evidence);setReply('');setNotice('');}catch(e){if(seq===sequence.current)setError(e instanceof Error?e.message:'Could not load the ticket.');}finally{if(seq===sequence.current)setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);setError('');const body=JSON.stringify({threadId:selected.id,status,...(reply.trim()?{reply:reply.trim()}:{})});if(!pendingSave.current||pendingSave.current.body!==body)pendingSave.current={id:crypto.randomUUID(),body};try{const r=await fetch('/api/support/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(body),requestId:pendingSave.current.id})});const d=await r.json();if(!r.ok)throw Error(d.error);pendingSave.current=null;await open(selected.id);await loadQueue();setNotice('Update saved. The customer can see it in their support conversation.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 return <section className="support-shell support-admin"><header className="support-heading"><div><p className="support-eyebrow">Owner support desk</p><h1>Customer conversations</h1></div><a href="/">Workspace</a></header><p className="support-intro">Only explicitly provisioned operators can access this queue. Replies are posted in the customer’s support conversation.</p>{deployment&&<p className="support-notice">{deployment}</p>}{error&&<p role="alert" className="support-error">{error}</p>}{notice&&<p role="status" className="support-notice">{notice}</p>}
  <button disabled={busy||loading} onClick={()=>void loadQueue()}>Refresh queue</button><p className="support-intro"><a href="/support/buyer-reviews">Buyer evidence review desk</a> · Separate authority-review access required</p>
  {cancellations.length>0&&<details className="support-notice"><summary>{cancellations.length} cancellation requests need checking</summary>{cancellations.map(c=><p key={c.id}><strong>{c.state.replaceAll('_',' ')} ({c.mode})</strong> · Account {c.account_id}<br/>{c.result??(c.state==='awaiting_confirmation'?'Awaiting owner confirmation. Nothing was cancelled by the email.':'Confirmed stop request is still processing.')}{c.receipt_state&&['claimed','needs_review','suppressed','rate_limited'].includes(c.receipt_state)&&<><br/>Email receipt: {c.receipt_state.replaceAll('_',' ')}. Verify delivery before contacting the owner; do not resend blindly.</>}<br/>Request {c.id}</p>)}</details>}
  <OperatorExceptions/>
  <div className="support-admin-grid"><nav className="support-ticket-list" aria-label="Support tickets">{loading?<p>Loading…</p>:tickets.length===0?<p>No support conversations to show.</p>:tickets.map(t=><button key={t.id} aria-pressed={selected?.id===t.id} disabled={busy} onClick={()=>void open(t.id)}>{t.subject}<small>{t.status.replaceAll('_',' ')}{t.updated_at?' · '+new Date(t.updated_at).toLocaleDateString():''}</small></button>)}</nav><div>{selected?<><h2>{selected.subject}</h2><p className="support-intro">Account {selected.account_id} · Ticket {selected.id}</p><details className="support-admin-evidence"><summary>Fresh account checks</summary><ul>{evidence.map(e=><li key={e.key}>{e.detail}<br/><small>{e.source} · {new Date(e.observedAt).toLocaleString()}</small></li>)}</ul></details><div className="support-messages">{messages.map(m=><article key={m.id} className={`support-message support-message-${m.role}`}><strong>{m.role} · {new Date(m.created_at).toLocaleString()}</strong><p>{m.content}</p></article>)}</div><form onSubmit={save}><label htmlFor="operator-reply">Reply to customer</label><textarea id="operator-reply" value={reply} onChange={e=>setReply(e.target.value)} maxLength={3000} disabled={busy}/><label>Status<select value={status} onChange={e=>setStatus(e.target.value)} disabled={busy}>{['open','escalated','waiting_on_customer','resolved'].map(s=><option value={s} key={s}>{s.replaceAll('_',' ')}</option>)}</select></label><button className="support-primary" disabled={busy}>{busy?'Saving…':reply.trim()?'Post reply and update':'Update status'}</button></form></>:<p className="support-intro">Choose a conversation to see its history and current checks.</p>}</div></div>
 </section>;
}
