'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {AccountAccess} from '@/components/account-access';
import type {SupportEvidence} from '@/lib/support-policy';
type Message={id:string;role:string;content:string;evidence:SupportEvidence[];created_at:string};
type Thread={id:string;subject:string;status:string};
type Cancellation={id:string;source:string;state:string;result:string|null};
export function SupportChat({onClose}:{onClose?:()=>void}){
 const [threads,setThreads]=useState<Thread[]>([]),[messages,setMessages]=useState<Message[]>([]),[thread,setThread]=useState<string|null>(null);
 const [draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[needsSignIn,setNeedsSignIn]=useState(false);
 const [cancellations,setCancellations]=useState<Cancellation[]>([]),[confirmation,setConfirmation]=useState<{token:string;summary:string}|null>(null),[ack,setAck]=useState(false),[notice,setNotice]=useState('');
 const request=useRef<{id:string;text:string}|null>(null);const historyEnd=useRef<HTMLDivElement>(null);const readSequence=useRef(0);
 const load=useCallback(async(id?:string)=>{const sequence=++readSequence.current;setLoading(true);try{const r=await fetch('/api/support'+(id?'?threadId='+id:''),{cache:'no-store'});const d=await r.json();if(sequence!==readSequence.current)return;if(r.status===401){setNeedsSignIn(true);return;}if(!r.ok)throw Error(d.error);setNeedsSignIn(false);setThreads(d.threads);setMessages(d.messages);setThread(d.threadId);setCancellations(d.cancellations);setError('');}catch(e){if(sequence===readSequence.current)setError(e instanceof Error?e.message:'Could not load support.');}finally{if(sequence===readSequence.current)setLoading(false);}},[]);
 useEffect(()=>{void load();return()=>{readSequence.current++;};},[load]);
 useEffect(()=>{historyEnd.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages]);
 async function send(e:React.FormEvent){e.preventDefault();if(!draft.trim()||busy)return;setBusy(true);setError('');const text=draft.trim();if(!request.current||request.current.text!==text)request.current={id:crypto.randomUUID(),text};
  try{const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:request.current.id,...(thread?{threadId:thread}:{}),message:text})});const d=await r.json();if(!r.ok)throw Error(d.error);setDraft('');request.current=null;await load(d.threadId);if(d.pending)setNotice('Your message is saved, but its reply is not yet confirmed. Refresh the conversation or ask the team.');}catch(e){setError(e instanceof Error?e.message:'Could not send. Your draft is still here.');}finally{setBusy(false);}
 }
 async function escalate(){if(!thread||busy)return;setBusy(true);try{const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'escalate',threadId:thread})});const d=await r.json();if(!r.ok)throw Error(d.error);await load(thread);setNotice('Sent to the support team. Check this conversation for a reply.');}catch(e){setError(e instanceof Error?e.message:'Could not send to the team.');}finally{setBusy(false);}}
 async function cancel(action:'prepare'|'confirm',requestId?:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/support/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='prepare'?{action,...(requestId?{requestId}:{})}:{action,token:confirmation?.token,acknowledged:ack})});const d=await r.json();if(!r.ok)throw Error(d.error);if(action==='prepare'){setConfirmation(d);setAck(false);}else{setConfirmation(null);setNotice(d.message);await load(thread??undefined);}}catch(e){setError(e instanceof Error?e.message:'Could not confirm cancellation.');}finally{setBusy(false);}}
 if(needsSignIn)return <section className="support-shell"><h1>Let’s get you some help</h1><p>Sign in so we can check only your account.</p><AccountAccess onSignedIn={()=>void load()}/><a href="/">Back to workspace</a></section>;
 return <section className="support-shell" aria-label="Support conversation">
  <header className="support-heading"><div><p className="support-eyebrow">iCash X support</p><h1>How can we help?</h1></div>{onClose?<button onClick={onClose} type="button">Close</button>:<a href="/">Back to workspace</a>}</header>
  <p className="support-intro">Describe what happened. AI helps choose relevant account checks. It can’t spend money, change your account, or repeat calls. A person can review anything it can’t resolve.</p>
  <div className="support-tools">{threads.length>1&&<label>Conversation<select value={thread??''} disabled={busy} onChange={e=>void load(e.target.value)}>{threads.map(t=><option value={t.id} key={t.id}>{t.subject.slice(0,50)} · {t.status.replaceAll('_',' ')}</option>)}</select></label>}<button disabled={busy||loading} onClick={()=>void load(thread??undefined)}>Refresh status</button>{thread&&<span className="support-status">{threads.find(t=>t.id===thread)?.status.replaceAll('_',' ')}</span>}</div>
  {cancellations.filter(c=>c.state!=='cancelled').map(c=><div className="support-notice" key={c.id}><p>{c.state==='awaiting_confirmation'?`${c.source==='email'?'An email requested cancellation. ':''}Nothing has been cancelled. Sign-in and confirmation are required.`:c.result??'Your confirmed cancellation is still being checked.'}</p>{c.state!=='processing'&&<button disabled={busy} onClick={()=>void cancel('prepare',c.id)}>Review this request</button>}</div>)}
  <div className="support-messages" role="log" aria-live="polite" aria-busy={busy||loading}>{loading&&!messages.length?<p>Loading your conversation…</p>:!messages.length?<div className="support-empty"><h2>Start with what feels wrong</h2><p>For example: “Why is my bot paused?” or “Is my daily plan still active?”</p></div>:messages.map(m=><article key={m.id} className={`support-message support-message-${m.role}`}><strong>{m.role==='user'?'You':m.role==='operator'?'Support team':m.role==='system'?'Update':'Account assistant'}</strong><p>{m.content}</p>{m.evidence?.length>0&&<details><summary>View the checks behind this answer</summary><ul>{m.evidence.map(e=><li key={e.key}><strong>{e.status==='unknown'?'Could not verify':e.status==='attention'?'Needs attention':'Checked'}:</strong> {e.detail}<small>Source: {e.source} · {new Date(e.observedAt).toLocaleString()}</small></li>)}</ul></details>}</article>)}<div ref={historyEnd}/></div>
  {error&&<p className="support-error" role="alert">{error}</p>}{notice&&<p className="support-notice" role="status">{notice}</p>}
  <form onSubmit={send} className="support-composer"><label htmlFor="support-message">Your message</label><textarea id="support-message" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000} rows={3} placeholder="What happened?" disabled={busy}/><div><small>Don’t include passwords, payment details, or private documents.</small><button className="support-primary" disabled={busy||loading||!draft.trim()}>{busy?'Checking…':'Send message'}</button></div></form>
  <div className="support-actions"><button disabled={busy||!thread} onClick={()=>void escalate()}>Ask the team</button><button disabled={busy||loading} onClick={()=>void cancel('prepare')}>Review cancellation</button></div>
  {confirmation&&<section className="support-confirm" aria-labelledby="support-cancel-heading"><h2 id="support-cancel-heading">Stop future work and renewals?</h2><p>{confirmation.summary}</p><label><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/> I want to pause my bot and stop future daily renewals</label><div><button disabled={busy} onClick={()=>{setConfirmation(null);setAck(false);}}>Keep my current settings</button><button className="support-primary" disabled={busy||!ack} onClick={()=>void cancel('confirm')}>Confirm cancellation</button></div><small>This confirmation expires in 10 minutes.</small></section>}
 </section>;
}
