'use client';
import {finalSalePolicy} from '@/lib/final-sale-policy';
import {VipBotName} from '@/components/vip-bot-name';
import {VipCustomVoice} from '@/components/vip-custom-voice';
import {useState,useRef} from 'react';
import {FundingDialog} from '@/components/funding-dialog';
import {vipBenefits,vipTermsVersion} from '@/lib/vip-policy';
export function VipPlan({vip,pendingDowngrade,vipUntil,paidThrough,discountActive=false,initialUpgradeReview=false,onChanged}:{vip:boolean;pendingDowngrade:boolean;vipUntil:string|null;paidThrough:string|null;discountActive?:boolean;initialUpgradeReview?:boolean;onChanged:()=>Promise<void>}){
 const [review,setReview]=useState<'upgrade'|'downgrade'|'keep_vip'|null>(initialUpgradeReview&&!vip?'upgrade':null),[busy,setBusy]=useState(false),[error,setError]=useState('');const locked=useRef(false);
 const [accepted,setAccepted]=useState(false);
 const renewal=paidThrough?new Date(paidThrough).toLocaleDateString(): 'your next renewal';
 async function submit(){if(!review||locked.current||(review==='upgrade'&&!accepted))return;locked.current=true;setBusy(true);setError('');try{const r=await fetch('/api/billing/vip',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:review,accepted:true,version:vipTermsVersion}),signal:AbortSignal.timeout(40000)});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.url){const u=new URL(d.url);if(u.protocol!=='https:'||u.hostname!=='checkout.stripe.com')throw Error('Checkout unavailable');window.location.assign(u.href);}else{setReview(null);await onChanged();}}catch(e){setError(e instanceof Error?e.message:'Could not confirm. Refresh before retrying.');await onChanged();}finally{locked.current=false;setBusy(false);}}
 return <section className="vip-plan"><div className="vip-plan-heading"><span>{vip?'VIP active':'Upgrade to VIP'}</span><strong>$100<small>/month total</small></strong></div><ul>{vipBenefits.map(b=><li key={b}>{b}</li>)}</ul>{vip&&<><VipBotName/><VipCustomVoice/></>}{pendingDowngrade&&<p>Standard starts {vipUntil?new Date(vipUntil).toLocaleDateString():renewal}. Your purchased leads and credits stay with you.</p>}<button type="button" className={vip&&!pendingDowngrade?'membership-payment-link':'fund-button'} onClick={()=>{setError('');setAccepted(false);setReview(vip?pendingDowngrade?'keep_vip':'downgrade':'upgrade');}}>{vip?pendingDowngrade?'Keep VIP':'Downgrade to Standard':'Upgrade for $50'}</button>{review&&<FundingDialog title={review==='upgrade'?'Upgrade to VIP':review==='downgrade'?'Switch to Standard':'Keep VIP'} onClose={()=>{if(!busy)setReview(null);}}><div className="vip-review">{review==='upgrade'?<><h3>$50 today</h3><p>VIP starts after payment. Your next renewal is $100 on {renewal}. Your renewal date stays the same.</p></>:review==='downgrade'?<><h3>$0 today</h3><p>Keep VIP through {renewal}, then renew at $50/month. VIP discounts end when your paid VIP period ends.</p></>:<><h3>$0 today</h3><p>Continue VIP and renew at $100 on {renewal}.</p></>}{discountActive&&<p>Your existing subscription discount continues for its remaining term and applies to the new monthly price.</p>}<p>Work credits are separate. Your leads, credits, conversations, and contracts stay saved.</p>{review==='upgrade'&&<><p>{finalSalePolicy}</p><label className="membership-consent"><input type="checkbox" checked={accepted} disabled={busy} onChange={e=>setAccepted(e.target.checked)}/><span>I accept the VIP purchase and final-sale policy.</span></label></>}<button className="fund-button" disabled={busy||(review==='upgrade'&&!accepted)} onClick={()=>void submit()}>{busy?'Confirming…':review==='upgrade'?'Continue to $50 payment':'Confirm plan change'}</button>{error&&<p role="alert">{error}</p>}</div></FundingDialog>}</section>;
}
