'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,CheckCircle2,ChevronRight,Clock,Eye,RefreshCw,ShoppingBag,ShoppingCart,CreditCard,Plus,Play,Settings2,Sun,Moon,Sparkles} from 'lucide-react';
import {dailyCloseRate,emptyFunnel,periodLabels,type ReportPeriod,type WebinarReport} from '@/lib/webinar-reporting';
import {webinarRequest} from '@/lib/webinar-client';
import {webinarLink} from '@/lib/webinar-links';
import {webinarSite} from '@/lib/webinar-site';
import {formatWatchTime,type Webinar} from '@/lib/webinar-policy';

const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(cents/100);
const zones=['America/Chicago','America/New_York','America/Denver','America/Los_Angeles','America/Phoenix','America/Anchorage','Pacific/Honolulu','Europe/London','UTC'];
export function WebinarDailyDashboard({webinars,onCreate,onEdit,onOptimizer,expanded=false}:{webinars:Webinar[];onCreate?:()=>void;onEdit?:(w:Webinar)=>void;onOptimizer?:()=>void;expanded?:boolean}){
 const [period,setPeriod]=useState<ReportPeriod>('today'),[timezone,setTimezone]=useState('America/Chicago'),[data,setReport]=useState<WebinarReport|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{try{const saved=localStorage.getItem('webinar-report-timezone');if(saved&&zones.includes(saved))setTimezone(saved);}catch{/* Reporting works without preference storage. */}},[]);
 useEffect(()=>{
  const controller=new AbortController();let disposed=false,loading=false;
  setReport(null);setError('');
  async function load(){if(loading)return;loading=true;setBusy(true);try{
   const data=await webinarRequest<WebinarReport>(`/api/webinar/reports?period=${period}&timezone=${encodeURIComponent(timezone)}`,{cache:'no-store',signal:controller.signal});
   if(!disposed){setReport(data);setError('');}
  }catch(e){if(!disposed)setError(e instanceof Error?e.message:'Could not load results.');}finally{loading=false;if(!disposed)setBusy(false);}}
  const visible=()=>{if(!document.hidden)void load();};void load();const timer=setInterval(visible,60000);document.addEventListener('visibilitychange',visible);
  return()=>{disposed=true;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);};
 },[period,timezone,refresh]);
 const report=data?.period===period&&data.timezone===timezone?data:null;
 const summary=report?.summary,active=webinars.filter(w=>w.status==='published'&&w.videoUrl),hasNight=active.some(w=>w.nightEnabled&&w.nightVersion?.videoUrl),hasMain=active.length>0;
 const metrics=[{key:'viewers',label:'Viewers',detail:'Unique people who started',icon:Eye},{key:'addToCart',label:'Add to cart',detail:'People who selected an offer',icon:ShoppingCart},{key:'checkouts',label:'Checkouts',detail:'Verified checkout starts',icon:CreditCard},{key:'purchases',label:'Purchases',detail:'Confirmed live payments',icon:ShoppingBag}] as const;
 return <div className="ws-daily-dashboard">
  <div className="ws-report-toolbar"><div><span className="ws-report-kicker">YOUR DAILY PERFORMANCE</span><h2>{periodLabels[period]} at a glance</h2><p>{report?`${report.startDate}${report.startDate!==report.endDate?' – '+report.endDate:''}`:'Loading your results…'}<span> · {timezone.replace('America/','').replaceAll('_',' ')}</span></p></div><div className="ws-report-controls"><div className="ws-report-period" aria-label="Report period">{(Object.keys(periodLabels) as ReportPeriod[]).map(value=><button key={value} aria-pressed={period===value} onClick={()=>setPeriod(value)}>{periodLabels[value]}</button>)}</div><button className="ws-secondary ws-refresh-report" disabled={busy} onClick={()=>setRefresh(n=>n+1)} aria-label="Refresh results"><RefreshCw size={16} className={busy?'ws-spinning':''}/></button></div></div>
  {error&&<div className="ws-alert" role="alert">{error}<button className="wb-text" onClick={()=>setRefresh(n=>n+1)}>Try again</button></div>}
  <div className="ws-funnel-cards" aria-busy={busy}>{metrics.map((metric,index)=><article key={metric.key}><div className="ws-metric-label"><span>{metric.label}</span><span className={`ws-metric-icon ws-metric-${index}`}><metric.icon size={19}/></span></div><strong>{summary?summary[metric.key].toLocaleString():'—'}</strong><small>{metric.detail}</small>{index<3&&<ChevronRight className="ws-funnel-chevron" size={15}/>}</article>)}</div>
  <div className="ws-revenue-strip"><div className="ws-revenue-main"><span>Revenue collected</span><strong>{summary?money(summary.revenueCents):'—'}</strong><small>Verified {webinarSite.brandName} payments</small></div><div><span>Conversion rate</span><strong>{summary?dailyCloseRate(summary):'—'}</strong><small>Viewers who bought in this period</small></div><div><span>Avg. watch time</span><strong>{summary?.startedSessions?formatWatchTime(summary.averageWatchSeconds):'—'}</strong><small>{summary?.startedSessions?`${summary.averageWatchPercent.toFixed(1)}% of the recording`:'Playback time per started session'}</small></div><div><span>Leads captured</span><strong>{summary?summary.leads.toLocaleString():'—'}</strong><small>Saved contact details</small></div></div>
  <div className="ws-report-caption"><span><span className="ws-status-dot"/>{busy?'Updating…':report?`Updated ${new Intl.DateTimeFormat('en-US',{timeZone:timezone,hour:'numeric',minute:'2-digit'}).format(new Date(report.generatedAt))} · refreshes every minute`:'Results unavailable'}</span><label>Reporting timezone<select aria-label="Reporting timezone" value={timezone} onChange={e=>{setTimezone(e.target.value);try{localStorage.setItem('webinar-report-timezone',e.target.value);}catch{/* Optional preference. */}}}>{zones.map(zone=><option key={zone} value={zone}>{zone.replaceAll('_',' ')}</option>)}</select></label></div>
  {!expanded&&<div className="ws-coverage"><span className="ws-coverage-icons"><Sun size={20}/><Moon size={16}/></span><div><b>{hasMain&&!hasNight?'Your main webinar covers day and night':hasNight&&hasMain?'Day and night switching is ready':active.length?'Your webinar is ready around the clock':'One video is enough to start'}</b><p>{hasMain&&!hasNight?'Keep using this video 24/7. When you publish a night version, local-time switching starts automatically.':hasNight&&hasMain?'New viewers get the right version for their local time. Returning viewers keep their saved place.':'Publish your first video for both day and night. Add a separate night recording whenever you’re ready.'}</p></div>{onOptimizer&&<button className="wb-text" onClick={onOptimizer}>Time settings <ArrowUpRight size={14}/></button>}</div>}
  <section className="ws-card ws-daily-webinars"><div className="ws-card-heading"><div><h2>{expanded?'Results by webinar':'My webinars'} <span className="ws-count-pill">{webinars.length}</span></h2><p>{periodLabels[period]} · all saved versions included</p></div>{onCreate&&<button className="wb-primary" onClick={onCreate}><Plus size={16}/>New webinar</button>}</div>
   {webinars.length?<div className="ws-table-wrap"><table><thead><tr><th>Webinar / version</th><th>Viewers</th><th>Avg. watch time</th><th>Conversion</th>{expanded&&<><th>Add to cart</th><th>Checkouts</th></>}<th>Purchases</th><th>Revenue</th>{onEdit&&<th><span className="wb-sr">Actions</span></th>}</tr></thead><tbody>{webinars.flatMap(w=>(['day',...(w.nightVersion?['night']:[])] as ('day'|'night')[]).map(version=>{
    const row=report?.recordings?.find(r=>r.webinarId===w.id&&r.version===version)??emptyFunnel;
    const length=version==='night'?w.nightVersion!.durationSeconds:w.durationSeconds;
    return <tr key={w.id+version}><td><div className="ws-webinar-row-name"><span className="ws-webinar-row-icon">{version==='day'?<Sun size={17}/>:<Moon size={17}/>}</span><div>{onEdit?<button className="ws-webinar-title-button" onClick={()=>onEdit(w)}>{w.title}</button>:<b>{w.title}</b>}<small><span className="ws-version-badge">{version==='day'?'Day':'Night'}</span> · <span className={`ws-row-status ${w.status}`}>{w.status==='published'?version==='night'&&!w.nightEnabled?'Paused':'Published':'Draft'}</span> · {formatWatchTime(length)}</small><small className="ws-permanent-link">{webinarLink(w)}</small></div></div></td><td>{report?row.viewers:'—'}</td><td><b>{report&&row.startedSessions?formatWatchTime(row.averageWatchSeconds):'—'}</b>{report&&row.startedSessions>0&&<small className="ws-table-sub">{row.averageWatchPercent.toFixed(1)}% watched · {row.completions} completed</small>}</td><td><strong className="ws-conversion-number">{report?dailyCloseRate(row):'—'}</strong><small className="ws-table-sub">{report?`${row.cohortBuyers} of ${row.viewers} viewers`:'Loading'}</small></td>{expanded&&<><td>{report?row.addToCart:'—'}</td><td>{report?row.checkouts:'—'}</td></>}<td><b>{report?row.purchases:'—'}</b></td><td><b>{report?money(row.revenueCents):'—'}</b></td>{onEdit&&<td><div className="ws-row-actions"><button className="ws-secondary" onClick={()=>onEdit(w)}><Settings2 size={14}/>Edit</button><a className="wb-icon" aria-label={`Preview ${w.title} ${version}`} href={`/webinar?preview=${w.id}&variant=${version}`} target="_blank" rel="noopener noreferrer"><ArrowUpRight size={17}/></a></div></td>}</tr>;
   }))}</tbody></table></div>:<div className="ws-first-session ws-first-session-compact"><span className="ws-large-icon"><Play size={28}/></span><h2>Start with one webinar.</h2><p>Upload your video, choose when the offer appears, add your chat, and publish. It can run day and night.</p><div className="ws-empty-steps"><span>1 · Video</span><span>2 · Offers</span><span>3 · Chat</span><span>4 · Publish</span></div>{onCreate&&<button className="wb-primary" onClick={onCreate}><Plus size={16}/>Create my first webinar</button>}</div>}
  </section>
  {report&&report.days.length>1&&<section className="ws-card"><div className="ws-card-heading"><div><h2>Day by day</h2><p>Actual activity on each reporting day</p></div><Clock size={18}/></div><div className="ws-table-wrap"><table><thead><tr><th>Date</th><th>Viewers</th><th>Add to cart</th><th>Checkouts</th><th>Purchases</th><th>Revenue</th></tr></thead><tbody>{[...report.days].reverse().map(day=><tr key={day.date}><td>{day.date}</td><td>{day.viewers}</td><td>{day.addToCart}</td><td>{day.checkouts}</td><td><b>{day.purchases}</b></td><td>{money(day.revenueCents)}</td></tr>)}</tbody></table></div></section>}
  <details className="ws-report-definitions"><summary><CheckCircle2 size={14}/>How your numbers are counted</summary><p>Views, offer selections and checkouts count unique people in this period. Purchases and revenue use the payment date, including buyers who watched earlier. Conversion rate uses people who started watching and purchased within the selected period. This is collected revenue, not profit or projected daily billing. Tests, owner previews and reviewed or refunded payments are excluded. External checkout providers require a verified payment connection.</p><p>Average watch time is recorded playback per session that started in this period, capped at the recording length. Pauses and time with the video stopped do not add watch time. Sessions can resume; the latest saved playback checkpoint is used.</p><p>“Add to cart” means selecting an offer or starting checkout; it does not mean the visitor paid. Checkout starts are recorded when the payment system creates a live checkout. New cart and checkout tracking begins with this update. Day and Night are attributed to the recording actually shown, even if local time changes while a visitor watches.</p></details>

 </div>;
}
