'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Upload,Play,Save,Trash2,Video,MessageSquare,Mail,BarChart3,LayoutDashboard,ArrowRight,ArrowLeft,Clock,Sun,Moon,Users,Sparkles,Check,Copy,ExternalLink} from 'lucide-react';
import {AccountAccess} from '@/components/account-access';
import {newWebinar,formatWatchTime,type Webinar,type WebinarSettings} from '@/lib/webinar-policy';
import {importWebinarChat} from '@/lib/webinar-import';
import {uploadWebinarFile} from '@/lib/webinar-upload';
import {webinarSite} from '@/lib/webinar-site';
import {WebinarTimeInput} from '@/components/webinar-time-input';
import {WebinarTimersEditor} from '@/components/webinar-timers-editor';
import {WebinarOffersEditor} from '@/components/webinar-offers-editor';
import {WebinarAudienceEditor} from '@/components/webinar-audience-editor';
import {WebinarDashboard,WebinarResults,WebinarReview} from '@/components/webinar-dashboard';
import {WebinarIntelligence} from '@/components/webinar-intelligence';
import {WebinarFollowupSettings,type FollowupReadiness,type FollowupStats} from '@/components/webinar-followup-settings';
import {WebinarGrowthSettings} from '@/components/webinar-growth-settings';
import {chatPresets,presetChat} from '@/lib/webinar-variants';
import {webinarLink} from '@/lib/webinar-links';
import {createNightRecording,editingRecording,patchRecording,type RecordingVersion} from '@/lib/webinar-recordings';
import {webinarRequest} from '@/lib/webinar-client';
type Tab='intelligence'|'dashboard'|'session'|'offers'|'timers'|'chat'|'review'|'followups'|'analytics'|'growth';
async function request(path:string,body?:unknown){return webinarRequest<any>(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});}
export function WebinarStudio(){
 const [webinars,setWebinars]=useState<Webinar[]>([]),[storedDraft,setDraft]=useState<Webinar|null>(null),[isNew,setIsNew]=useState(false),[dirty,setDirty]=useState(false),[settingsDirty,setSettingsDirty]=useState(false),[settings,setSettings]=useState<WebinarSettings|null>(null),[tab,setTab]=useState<Tab>('dashboard'),[loading,setLoading]=useState(true),[denied,setDenied]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[upload,setUpload]=useState<number|null>(null),[transcript,setTranscript]=useState(''),[aiReady,setAiReady]=useState(false),[embeddedCheckoutReady,setEmbeddedCheckoutReady]=useState(false),[metaReady,setMetaReady]=useState(false),[metaHealth,setMetaHealth]=useState({sent:0,pending:0,failed:0}),[version,setVersion]=useState<RecordingVersion>('day');
 const [followupReadiness,setFollowupReadiness]=useState<FollowupReadiness|null>(null),[followupStats,setFollowupStats]=useState<FollowupStats|null>(null);
 const draft=storedDraft?editingRecording(storedDraft,version):null;
 const fileInput=useRef<HTMLInputElement>(null),chatInput=useRef<HTMLInputElement>(null),abortUpload=useRef<AbortController|null>(null);
 async function load(){setLoading(true);setError('');try{const d=await request('/api/webinar/studio');setWebinars(d.webinars);setSettings(d.settings);setAiReady(d.aiReady);setEmbeddedCheckoutReady(d.embeddedCheckoutReady);setFollowupReadiness(d.followupReadiness);setFollowupStats(d.followupStats);setMetaReady(d.metaReady);setMetaHealth(d.metaHealth);setDenied(false);setDraft(current=>d.webinars.find((w:Webinar)=>w.id===current?.id)??d.webinars[0]??null);}catch(e){if((e as {status?:number}).status===403)setDenied(true);else setError(e instanceof Error?e.message:'Could not load studio.');}finally{setLoading(false);}}
 useEffect(()=>{void load();return()=>abortUpload.current?.abort();},[]);
 useEffect(()=>{if(!dirty&&!settingsDirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,settingsDirty]);
 function update(patch:Partial<Webinar>){setDraft(d=>d?patchRecording(d,version,patch):d);setDirty(true);setNotice('');}
 function changeSettings(value:WebinarSettings){setSettings(value);setSettingsDirty(true);setNotice('');}
 function setDuration(value:number){if(!draft)return;update({durationSeconds:value,nameAt:Math.min(draft.nameAt,value),contactAt:Math.min(draft.contactAt,value),pitchAt:Math.min(draft.pitchAt,value),timers:(draft.timers??[]).map(t=>({...t,at:Math.min(t.at,value)})),offers:draft.offers.map(o=>({...o,at:Math.min(o.at,value)})),purchaseNotifications:{...draft.purchaseNotifications,startAt:draft.purchaseNotifications.startAt===null?null:Math.min(draft.purchaseNotifications.startAt,value)}});}
 function duplicate(){if(!storedDraft||busy)return;void createDraft({...storedDraft,id:crypto.randomUUID(),publicCode:null,revision:1,title:storedDraft.title+' — copy',status:'draft'});}
 function select(w:Webinar){if(busy)return;if(dirty&&!window.confirm('Discard your unsaved changes?'))return;abortUpload.current?.abort();setUpload(null);setVersion('day');setDraft(w);setIsNew(false);setDirty(false);setTab('session');setError('');setNotice('');}
 function create(){if(busy)return;if(dirty&&!window.confirm('Discard your unsaved changes?'))return;void createDraft(newWebinar(crypto.randomUUID()));}
 async function createDraft(webinar:Webinar){abortUpload.current?.abort();setUpload(null);setBusy(true);setError('');try{const d=await request('/api/webinar/studio',{action:'save',webinar,isNew:true});setDraft(d.webinar);setVersion('day');setWebinars(w=>[d.webinar,...w.filter(x=>x.id!==d.webinar.id)]);setIsNew(false);setDirty(false);setTab('session');setNotice('Webinar created. Your permanent link is ready.');}catch(e){setDraft(webinar);setVersion('day');setIsNew(true);setDirty(true);setTab('session');setError(e instanceof Error?e.message:'Could not create the webinar. Save to try again.');}finally{setBusy(false);}}
 function addNight(){if(!storedDraft||busy||upload!==null)return;setDraft({...storedDraft,nightVersion:createNightRecording(storedDraft),nightEnabled:true});setVersion('night');setDirty(true);setTab('session');setNotice('Upload your night recording, then save. New sessions will switch automatically by local time.');}
 async function save(status?:Webinar['status']){if(!storedDraft||busy)return;setBusy(true);setError('');try{const d=await request('/api/webinar/studio',{action:'save',webinar:{...storedDraft,...(status?{status}:{})},isNew});setDraft(d.webinar);setWebinars(w=>[d.webinar,...w.filter(x=>x.id!==d.webinar.id)]);setIsNew(false);setDirty(false);setNotice(d.webinar.status==='published'?'Published. New visitors can now see this session.':'Draft saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 async function uploadFile(file:File){if(!draft)return;const draftId=draft.id,uploadVersion=version;setError('');setUpload(0);const controller=new AbortController();abortUpload.current=controller;try{const url=await uploadWebinarFile(file,n=>setUpload(n),controller.signal);setDraft(d=>d?.id===draftId?patchRecording(d,uploadVersion,{videoUrl:url}):d);setDirty(true);setNotice('Video uploaded. Review its duration and save the session.');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Upload failed.');}finally{setUpload(null);}}
 async function importFile(file:File){try{const chat=importWebinarChat(await file.text());update({chat});setNotice(`${chat.length} messages imported. Review timestamps, then save.`);}catch(e){setError(e instanceof Error?e.message:'Could not read chat.');}}
 async function generateChat(){if(!draft||busy)return;setBusy(true);setError('');try{const d=await request('/api/webinar/studio/draft',{transcript,duration:draft.durationSeconds});update({chat:d.chat});setNotice('AI draft ready. Review the notes and timing before saving.');}catch(e){setError(e instanceof Error?e.message:'Could not draft chat.');}finally{setBusy(false);}}
 async function saveFollowups(){if(!settings||busy)return;setBusy(true);setError('');try{const d=await request('/api/webinar/studio',{action:'settings',settings});setFollowupReadiness(d.followupReadiness);setSettingsDirty(false);setNotice('Your platform settings are saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 async function generateVariations(){if(!draft||busy)return;setBusy(true);setError('');try{const d=await request('/api/webinar/studio/variations',{chat:draft.chat,style:draft.chatStyle,faq:draft.faq});update({chat:d.chat,variationEnabled:true});setNotice('Alternate messages are ready below. Review or edit them, then save. Each new session gets a frozen mix.');}catch(e){setError(e instanceof Error?e.message:'Could not generate variations.');}finally{setBusy(false);}}
 function applyPreset(key:keyof typeof chatPresets){const chat=presetChat(key);if(!draft)return;if(chat.some(c=>c.at>draft.durationSeconds)){setError('Set the actual video duration before adding this timeline.');return;}update({chat});setNotice('Timing preset added as AI session notes. Match the moments to your video before saving.');}
 async function toggleIntelligence(enabled:boolean){setBusy(true);try{await request('/api/webinar/intelligence',{enabled});setSettings(s=>s?{...s,optimizer:{...s.optimizer,enabled}}:s);}finally{setBusy(false);}}
 const editing=['session','offers','timers','chat','review'].includes(tab);
 const steps=[{id:'session',label:'Video & details',icon:Video},{id:'offers',label:'Offers',icon:Sparkles},{id:'timers',label:'Timers',icon:Clock},{id:'chat',label:'Chat & AI',icon:MessageSquare},{id:'review',label:'Review & publish',icon:Check}] as const;
 const stepIndex=steps.findIndex(t=>t.id===tab);
 const titles={intelligence:'Webinar Intelligence',dashboard:'My webinars',session:draft?.title||'Create a webinar',offers:draft?.title||'Offers',timers:draft?.title||'Timers',chat:draft?.title||'Chat & AI',review:draft?.title||'Review & publish',growth:'Settings',analytics:'Daily results',followups:'Follow-ups'};

 return <div className="ws-shell">
  <header className="ws-header"><a href="/" className="wb-wordmark">{webinarSite.brandName}<small>WEBINAR STUDIO</small></a><a className="ws-workspace-link" href="/">Back to workspace</a></header>
  {denied?<main className="ws-auth"><span className="wb-eyebrow">PRIVATE STUDIO</span><h1>Your sessions. Your flow.</h1><p>Sign in with the iCash X owner account to manage webinars.</p><AccountAccess onSignedIn={()=>void load()}/></main>:<div className="ws-body">
   <nav className="ws-sidebar" aria-label="Webinar studio"><div className="ws-global-nav">{([{id:'dashboard',label:'My webinars',icon:LayoutDashboard},{id:'intelligence',label:'Intelligence',icon:Sparkles},{id:'growth',label:'Settings',icon:Clock},{id:'analytics',label:'Daily results',icon:BarChart3},{id:'followups',label:'Follow-ups',icon:Mail}] as const).map(item=><button key={item.id} aria-current={tab===item.id?'page':undefined} onClick={()=>setTab(item.id)}><item.icon size={18}/>{item.label}</button>)}</div><div className="ws-sidebar-title"><span>YOUR SESSIONS</span><button className="wb-icon" aria-label="New session" onClick={create}><Plus size={19}/></button></div>
    {webinars.map(w=>{const Icon=w.nightVersion?Moon:Sun;return <button key={w.id} onClick={()=>select(w)} className={`ws-session-link ${editing&&draft?.id===w.id?'selected':''}`}><span className="ws-session-icon"><Icon size={19}/></span><span><b>{w.title}</b><small>{w.nightVersion?'Day + night':'Day'} · {w.status}</small></span></button>;})}
    {isNew&&draft&&<div className="ws-session-link selected"><span className="ws-session-icon"><Video size={19}/></span><span><b>{draft.title}</b><small>New draft</small></span></div>}
    <button className="ws-add-session" onClick={create}><Plus size={16}/>Add a session</button>
    {storedDraft?.publicCode&&<div className="ws-sidebar-bottom"><span className="ws-sidebar-label">THIS WEBINAR’S LINK</span><a href={webinarLink(storedDraft)} target="_blank" rel="noopener noreferrer">{webinarLink(storedDraft)} <ExternalLink size={14}/></a><button onClick={()=>void navigator.clipboard.writeText(location.origin+webinarLink(storedDraft)).then(()=>setNotice('Webinar link copied.')).catch(()=>setError('Copy the link shown above.'))}><Copy size={14}/>Copy link</button></div>}
   </nav>
   <main className="ws-main">
    <div className="ws-heading"><div><span className="wb-eyebrow">YOUR AUTOMATED WEBINAR PLATFORM</span><h1>{titles[tab]}</h1><p>{dirty?'You have unsaved changes.':tab==='dashboard'||tab==='analytics'?'See what happened today. Make your next move.':'Set it up once. Your webinar handles the rest.'}</p></div>{editing&&draft?<div className="ws-heading-actions"><button className="ws-secondary" disabled={busy||upload!==null} onClick={duplicate}><Copy size={16}/>Duplicate</button><a className={`ws-secondary ${isNew?'disabled':''}`} href={isNew?undefined:`/webinar?preview=${draft.id}&variant=${version}`} target="_blank" rel="noopener noreferrer"><Play size={16}/>Preview saved</a><button className="wb-primary" onClick={()=>void save()} disabled={busy||upload!==null}><Save size={16}/>{busy?'Saving…':'Save changes'}</button></div>:tab==='dashboard'?<button className="wb-primary" onClick={create}><Plus size={17}/>Create webinar</button>:null}</div>
    {editing&&storedDraft&&<div className="ws-recording-bar"><div className="ws-recording-tabs" aria-label="Recording version"><button disabled={busy||upload!==null} aria-pressed={version==='day'} onClick={()=>setVersion('day')}><Sun size={16}/>Day</button>{storedDraft.nightVersion?<button disabled={busy||upload!==null} aria-pressed={version==='night'} onClick={()=>setVersion('night')}><Moon size={16}/>Night</button>:<button className="ws-add-night" disabled={busy||upload!==null} onClick={addNight}><Plus size={15}/>Add night version</button>}</div><p>{storedDraft.nightVersion?<label className="wb-check"><input type="checkbox" checked={storedDraft.nightEnabled} onChange={e=>update({nightEnabled:e.target.checked})}/><span>Switch to Night automatically</span></label>:'Your Day recording runs around the clock.'}</p></div>}
    {editing&&<nav className="ws-steps" aria-label="Webinar setup steps">{steps.map((step,n)=><button key={step.id} aria-current={tab===step.id?'step':undefined} onClick={()=>setTab(step.id)}><span>{n+1}</span><step.icon size={16}/>{step.label}</button>)}</nav>}
    {error&&<div role="alert" className="ws-alert">{error}<button className="wb-text" onClick={()=>void load()}>Reload</button></div>}{notice&&<div role="status" className="ws-notice"><Check size={16}/>{notice}</div>}
    {loading&&!settings?<p role="status">Loading your studio…</p>:<section id={`ws-${tab}`} aria-label={titles[tab]}>
     {tab==='intelligence'&&settings&&<WebinarIntelligence enabled={settings.optimizer.enabled} busy={busy} onToggle={toggleIntelligence}/>}
     {tab==='dashboard'&&<WebinarDashboard webinars={webinars} onCreate={create} onEdit={select} onOptimizer={()=>setTab('intelligence')}/>}
     {tab==='offers'&&draft&&<>{!embeddedCheckoutReady&&<p className="ws-alert">Connect the matching Stripe publishable key to enable card payments inside the room. Until then, visitors continue to your secure Stripe checkout and return to name their bot.</p>}<WebinarOffersEditor webinar={draft} onChange={update}/></>}
     {tab==='timers'&&draft&&<WebinarTimersEditor webinar={draft} onChange={update}/>}
     {tab==='review'&&draft&&<WebinarReview webinar={storedDraft!} busy={busy||upload!==null} isNew={isNew} onPublish={()=>void save('published')}/>}
     {tab==='session'&&(draft?<div className="ws-editor-grid"><div className="ws-editor-main">
      <section className="ws-card ws-video-card"><div className="ws-card-heading"><div><h2>Your video</h2><p>The presentation visitors will watch.</p></div><span className="ws-status">{draft.status}</span></div>
       {draft.videoUrl?<video key={draft.videoUrl} src={draft.videoUrl} poster={draft.posterUrl||undefined} controls preload="metadata" onLoadedMetadata={e=>{const d=Math.round(e.currentTarget.duration);if(Number.isFinite(d)&&d>=10&&d<=14400&&Math.abs(d-draft.durationSeconds)>2)setDuration(d);}}/>:<button className="ws-video-empty" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)void uploadFile(file);}} onClick={()=>fileInput.current?.click()}><span><Upload size={30}/></span><strong>Drop your next session here</strong><small>Choose an MP4, WebM or MOV · up to 2 GB</small></button>}
       <input ref={fileInput} hidden type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadFile(f);e.target.value='';}}/>
       {upload!==null?<div className="ws-upload-progress"><progress max={100} value={upload}/><span>Uploading {upload}%</span><button className="wb-text" onClick={()=>abortUpload.current?.abort()}>Cancel</button></div>:<div className="ws-upload-actions"><button className="ws-secondary" onClick={()=>fileInput.current?.click()}><Upload size={15}/>{draft.videoUrl?'Replace video':'Upload video'}</button><span>Or paste a direct video URL below</span></div>}
       <label className="wb-label">Video URL<input value={draft.videoUrl} onChange={e=>update({videoUrl:e.target.value})} placeholder="https://…/your-webinar.mp4"/></label><label className="wb-label">Cover image URL <small>optional</small><input value={draft.posterUrl} onChange={e=>update({posterUrl:e.target.value})} placeholder="https://…/cover.jpg"/></label>
      </section>
      <section className="ws-card"><div className="ws-card-heading"><div><h2>Session details</h2><p>Make this session feel like yours.</p></div></div><label className="wb-label">Title<input value={draft.title} maxLength={150} onChange={e=>update({title:e.target.value})}/></label><label className="wb-label">Short description<textarea rows={2} value={draft.description} maxLength={600} onChange={e=>update({description:e.target.value})}/></label><label className="wb-label">Availability<select value={draft.status} onChange={e=>update({status:e.target.value as Webinar['status']})}><option value="draft">Draft · only you</option><option value="published">Published</option></select></label><label className="wb-check"><input type="checkbox" checked={draft.intelligenceEnabled} onChange={e=>update({intelligenceEnabled:e.target.checked})}/><span>Include in automatic webinar testing</span></label><p className="ws-hint">One link for this webinar. Day plays at all hours until you add Night. Existing viewers keep their recording and saved place.</p></section>
     </div><aside className="ws-inspector"><section className="ws-card"><div className="ws-card-heading"><div><h2>Build the flow</h2><p>Set the moments that move people forward.</p></div><Clock size={20}/></div><div className="ws-timeline">{([{key:'nameAt',label:'Ask their name',detail:'Name only · at the bottom of chat',n:'01'},{key:'contactAt',label:'Capture email & phone',detail:'Both together · at least 30 seconds after name',n:'02'}] as const).map(item=><div className="ws-timeline-row" key={item.key}><span>{item.n}</span><div><b>{item.label}</b><small>{item.detail}</small><WebinarTimeInput label={item.label+' at'} value={draft[item.key]} max={draft.durationSeconds} onChange={value=>update({[item.key]:value})}/></div></div>)}</div><WebinarTimeInput label="Video length" value={draft.durationSeconds} onChange={setDuration}/><p className="ws-hint">Detected from your video. Set hours, minutes and seconds. Skipped prompts get one reminder after 5 minutes of watching.</p><WebinarAudienceEditor webinar={draft} onChange={update}/></section>
     </aside></div>:<div className="ws-first-session"><span className="ws-large-icon"><Video size={34}/></span><h2>Your first session starts here.</h2><p>Upload your video, set the pitch moment, and make it yours.</p><button className="wb-primary" onClick={create}><Plus size={17}/>Create a session</button></div>)}
     {tab==='chat'&&(draft?<div className="ws-chat-editor"><section className="ws-card"><div className="ws-card-heading"><div><h2>Timed conversation</h2><p>Upload a chat script or add messages. Use {'{{name}}'} to address the viewer.</p></div><button className="ws-secondary" onClick={()=>chatInput.current?.click()}><Upload size={16}/>Import CSV / JSON</button></div><input ref={chatInput} hidden type="file" accept=".json,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/><p className="ws-hint">CSV: time, name, message, kind—or your spreadsheet columns username, message, minutes, seconds. Kind is host, ai or replay. Imported spreadsheet scripts are labeled AI notes; use replay only for genuine past comments.</p><div className="ws-preset-row"><label className="wb-label">Start from your example pacing<select value="" onChange={e=>{if(e.target.value)applyPreset(e.target.value as keyof typeof chatPresets);}}><option value="">Choose a timing preset…</option>{Object.keys(chatPresets).map(k=><option key={k} value={k}>{k}</option>)}</select></label><p className="ws-hint">Uses the rhythm from your examples as assistant prompts. You can edit every message and second.</p></div><div className="ws-cue-list">{draft.chat.map((c,index)=><div className="ws-cue" key={c.id}><WebinarTimeInput label="Appears at" value={c.at} max={draft.durationSeconds} onChange={at=>update({chat:draft.chat.map((row,n)=>n===index?{...row,at}:row)})}/><label className="wb-label">Name<input value={c.name} maxLength={60} onChange={e=>update({chat:draft.chat.map((row,n)=>n===index?{...row,name:e.target.value}:row)})}/></label><label className="wb-label">Type<select value={c.kind} onChange={e=>update({chat:draft.chat.map((row,n)=>n===index?{...row,kind:e.target.value as 'host'|'replay'|'ai'}:row)})}><option value="host">Host note</option><option value="ai">AI session note</option><option value="replay">Replay comment</option></select></label><button className="wb-icon" aria-label={`Remove message ${index+1}`} onClick={()=>update({chat:draft.chat.filter((_,n)=>n!==index)})}><Trash2 size={17}/></button><label className="wb-label ws-cue-text">Message<textarea rows={2} value={c.text} maxLength={1500} onChange={e=>update({chat:draft.chat.map((row,n)=>n===index?{...row,text:e.target.value,variations:undefined}:row)})}/></label>{c.kind!=='replay'&&c.variations?.length? <label className="wb-label ws-cue-text">Session alternatives <small>one per line · unchanged timing</small><textarea rows={3} value={c.variations.join('\n')} onChange={e=>update({chat:draft.chat.map((row,n)=>n===index?{...row,variations:e.target.value.split('\n').filter(Boolean).slice(0,5)}:row)})}/></label>:null}</div>)}</div><button className="ws-secondary" onClick={()=>update({chat:[...draft.chat,{id:crypto.randomUUID(),at:Math.min(draft.durationSeconds,(draft.chat.at(-1)?.at??0)+30),name:'iCash X',text:'',kind:'host'}]})}><Plus size={16}/>Add message</button></section>
      <section className="ws-card"><div className="ws-card-heading"><div><h2><Sparkles size={19}/> Different chat, every session</h2><p>AI writes alternatives in your style. You review them once; the room mixes them for each session.</p></div></div><label className="wb-label">Your chat style<textarea rows={4} maxLength={2500} value={draft.chatStyle} onChange={e=>update({chatStyle:e.target.value})}/></label><label className="wb-check"><input type="checkbox" checked={draft.variationEnabled} onChange={e=>update({variationEnabled:e.target.checked})}/><span>Vary approved messages for each new session</span></label><button className="wb-primary" disabled={busy||!aiReady||!draft.chat.length||draft.chat.length>40} onClick={()=>void generateVariations()}><Sparkles size={16}/>{busy?'Generating…':'Generate session alternatives'}</button><p className="ws-hint">Generate up to 40 cues at a time. Times, genuine replay comments and your offer remain fixed. Refreshing or returning to an unfinished session keeps the same chat. Editing a base message clears its old alternatives.</p></section>
      <section className="ws-card"><div className="ws-card-heading"><div><h2><Sparkles size={19}/> Let AI help you write</h2><p>Paste your transcript. Review the generated host notes before saving.</p></div></div><label className="wb-label">Transcript or session outline<textarea rows={7} value={transcript} maxLength={24000} onChange={e=>setTranscript(e.target.value)} placeholder="00:00 Welcome…"/></label><button className="wb-primary" disabled={busy||transcript.length<20||!aiReady} onClick={()=>void generateChat()}><Sparkles size={16}/>{busy?'Drafting…':'Draft chat from transcript'}</button>{!aiReady&&<p className="ws-hint">AI needs the configured OpenAI key and model. Manual chat remains available.</p>}</section>
      <section className="ws-card"><h2>Give the assistant your knowledge</h2><p>Use your approved facts, FAQs and answers. The assistant uses this to respond privately to visitors.</p><label className="wb-label">Session knowledge<textarea rows={10} value={draft.faq} maxLength={24000} onChange={e=>update({faq:e.target.value})}/></label><label className="wb-check"><input type="checkbox" checked={draft.aiEnabled} onChange={e=>update({aiEnabled:e.target.checked})}/><span>Allow AI replies to viewer questions</span></label></section>
     </div>:<p>Create a session first.</p>)}
     {tab==='followups'&&settings&&<WebinarFollowupSettings settings={settings} readiness={followupReadiness} stats={followupStats} busy={busy} onChange={changeSettings} onSave={()=>void saveFollowups()}/>}
     {tab==='growth'&&settings&&<WebinarGrowthSettings settings={settings} onChange={changeSettings} onSave={()=>void saveFollowups()} metaReady={metaReady} metaHealth={metaHealth} busy={busy}/>}
     {tab==='analytics'&&<WebinarResults webinars={webinars}/>}
     {editing&&draft&&<div className="ws-step-actions"><button className="ws-secondary" onClick={()=>setTab(stepIndex>0?steps[stepIndex-1].id:'dashboard')}><ArrowLeft size={16}/>{stepIndex>0?'Back':'My webinars'}</button>{stepIndex<steps.length-1&&<button className="wb-primary" onClick={()=>setTab(steps[stepIndex+1].id)}>Continue to {steps[stepIndex+1].label.toLowerCase()}<ArrowRight size={16}/></button>}</div>}
    </section>}
   </main>
  </div>}
 </div>;
}
