'use client';
import {Save} from 'lucide-react';
import {type WebinarSettings,type Webinar} from '@/lib/webinar-policy';
type Props={webinars:Webinar[];settings:WebinarSettings;onChange:(value:WebinarSettings)=>void;onSave:()=>void;metaReady:boolean;metaHealth:{sent:number;pending:number;failed:number};busy:boolean};
export function WebinarGrowthSettings({webinars,settings,onChange,onSave,metaReady,metaHealth,busy}:Props){
 const vipOptions=webinars.filter(w=>w.parentWebinarId).map(w=><option key={w.id} value={w.id}>{w.title}{w.status!=='published'?' · Draft':''}</option>);
 return <div className="ws-growth"><section className="ws-card"><h2>Your webinar links</h2><p>Use the main webinar’s permanent /live/ link in your ads. Each main webinar has a separate VIP link for paid buyers. Add Day and Night recordings inside either session; each link stays the same.</p><p className="ws-hint">An ad only advances a known viewer when it repeats a webinar they finished with at least 90% watched. Saved playback and the checkout window come first. The next session must be published and unwatched; otherwise the original link stays in place. Tag ad links with ad_id or paid campaign UTM parameters.</p></section>
 <section className="ws-card"><h2>After the upgrade offer → VIP session</h2><p>Choose the session for homepage or express checkout buyers who decline the VIP upgrade. Webinar buyers keep that webinar’s own VIP session. Confirmed VIP upgrades go straight to bot setup.</p>
 <label className="wb-label">How to choose the VIP<select value={settings.homepageVipMode} onChange={e=>onChange({...settings,homepageVipMode:e.target.value as WebinarSettings['homepageVipMode']})}><option value="selected">Use my selected sessions</option><option value="best-converting">Use the best-converting webinar’s VIP</option></select></label>
 <div className="ws-fields"><label className="wb-label">Day VIP session<select value={settings.homepageVipId??''} onChange={e=>onChange({...settings,homepageVipId:e.target.value||null})}><option value="">First published VIP session</option>{vipOptions}</select></label><label className="wb-label">Night VIP session<select value={settings.homepageVipNightId??''} onChange={e=>onChange({...settings,homepageVipNightId:e.target.value||null})}><option value="">Use the same VIP as Day</option>{vipOptions}</select></label></div>
 {settings.homepageVipMode==='best-converting'&&<p className="ws-hint">Automatic uses the main webinar’s verified purchase conversion rate over the last 30 days, separately for Day and Night. A recording needs at least 20 viewers and 1 buyer. Only published VIP sessions qualify. Your selections above are the fallback when data is limited or reporting is unavailable.</p>}
 <p className="ws-hint">Sunrise and sunset at the viewer’s approximate location choose Day or Night. Without an enabled Night recording, the selected VIP plays its Day video. Upload and publish the VIP to activate it; a draft sends buyers who decline to bot setup. The destination stays attached to the checkout, including retries.</p><button className="wb-primary" disabled={busy} onClick={onSave}><Save size={16}/>Save VIP destinations</button></section>
 <details className="ws-card ws-routing-details"><summary>Day & night matching</summary><p>Automatic: match sunrise and sunset where each viewer is watching. These local hours are only a fallback when their location is unavailable.</p><div className="ws-fields"><label className="wb-label">Fallback Night starts<select value={settings.routing.nightStartsAt} onChange={e=>onChange({...settings,routing:{...settings.routing,nightStartsAt:Number(e.target.value)}})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{h%12||12}:00 {h<12?'AM':'PM'}</option>)}</select></label><label className="wb-label">Fallback Day starts<select value={settings.routing.nightEndsAt} onChange={e=>onChange({...settings,routing:{...settings.routing,nightEndsAt:Number(e.target.value)}})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{h%12||12}:00 {h<12?'AM':'PM'}</option>)}</select></label></div><label className="wb-label">Return directly to the offer for <small>hours after reaching the offer or finishing</small><input type="number" min={0} max={72} step={0.5} value={settings.routing.checkoutWindowHours} onChange={e=>onChange({...settings,routing:{...settings.routing,checkoutWindowHours:Number(e.target.value)}})}/></label><p className="ws-hint">Default: 8 hours. After that, direct returns replay the same webinar. A tagged ad repeating a confirmed completed webinar can open the next eligible unwatched webinar, ranked by paid conversion rate when enough data exists. VIP sessions open only after purchase. Earlier exits resume that day. Finishing starts a full checkout window. Refreshing never extends it. Day and Night follow local sunrise and sunset, including seasonal changes. Saved playback keeps its original recording. Day runs all day until that webinar has a saved, enabled Night recording.</p><button className="wb-primary" disabled={busy} onClick={onSave}><Save size={16}/>Save routing settings</button></details>
 <details className="ws-card ws-routing-details"><summary>Meta Pixel & purchase connection</summary><p>Connect your dataset once to use browser and server measurement.</p><label className="wb-label">Meta Pixel / dataset ID<input inputMode="numeric" value={settings.meta.pixelId} onChange={e=>onChange({...settings,meta:{...settings.meta,pixelId:e.target.value.trim()}})} placeholder="Your Meta dataset ID"/></label><label className="wb-check"><input type="checkbox" checked={settings.meta.enabled} onChange={e=>onChange({...settings,meta:{...settings.meta,enabled:e.target.checked}})}/><span>Enable consent-based browser and server measurement</span></label>{!metaReady&&<p className="ws-alert">The server connection needs your Meta access token and Graph API version before measurement can start.</p>}<p className="ws-hint">Purchase reports the amount actually paid. Browser and server events are deduplicated. Previews and test payments are excluded.</p><div className="ws-meta-health"><span><b>{metaHealth.sent}</b> sent</span><span><b>{metaHealth.pending}</b> pending</span><span><b>{metaHealth.failed}</b> failed</span></div><button className="wb-primary" disabled={busy} onClick={onSave}><Save size={16}/>Save connection</button></details></div>;
}
