'use client';
import {ArrowUpRight,ArrowRight,Video,Plus,Sparkles,Play,Settings2,CheckCircle2} from 'lucide-react';
import {formatWatchTime,webinarOffers,webinarSchema,webinarEndOffer,type Webinar} from '@/lib/webinar-policy';
import type {WebinarPerformance} from '@/lib/webinar-optimizer';
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(cents/100);
export const closeRate=(row?:WebinarPerformance)=>row?.viewers?`${((row.buyers??0)/row.viewers*100).toFixed(1)}%`:'—';
export function WebinarDashboard({webinars,performance,starts,onCreate,onEdit,onOptimizer}:{webinars:Webinar[];performance:WebinarPerformance[];starts:number;onCreate:()=>void;onEdit:(webinar:Webinar)=>void;onOptimizer:()=>void}){
 return <div className="ws-dashboard"><div className="ws-dashboard-metrics"><article><span>Published webinars</span><strong>{webinars.filter(w=>w.status==='published').length}</strong><small>Ready for your audience</small></article><article><span>Webinar starts</span><strong>{starts.toLocaleString()}</strong><small>All time · previews excluded</small></article><article><span>Verified paid value</span><strong>{money(performance.reduce((sum,p)=>sum+p.value_cents,0))}</strong><small>30-day webinar cohort · iCash X</small></article></div><div className="ws-autopilot"><span className="ws-autopilot-icon"><Sparkles size={21}/></span><div><b>Your webinars optimize themselves</b><p>New versions get a fair test. Verified purchases guide more traffic to stronger sessions.</p></div><button className="ws-secondary" onClick={onOptimizer}>View performance <ArrowRight size={15}/></button></div>
 <div className="ws-section-intro"><div><h2>My webinars <span className="ws-count-pill">{webinars.length}</span></h2><p>Create once. Send everyone to your webinar link.</p></div><button className="wb-primary" onClick={onCreate}><Plus size={17}/>New webinar</button></div>
 {webinars.length?<div className="ws-webinar-grid">{webinars.map(w=>{const stats=performance.find(p=>p.webinar_id===w.id&&p.revision===w.revision);return <article className="ws-webinar-card" key={w.id}><button className="ws-webinar-cover" onClick={()=>onEdit(w)} aria-label={`Edit ${w.title}`} style={w.posterUrl?{backgroundImage:`url(${JSON.stringify(w.posterUrl)})`}:undefined}><span className="ws-webinar-cover-icon"><Play size={28}/></span><span className={`ws-publish-badge ${w.status}`}>{w.status==='published'?'Published':'Draft'}</span><span className="ws-cover-duration">{formatWatchTime(w.durationSeconds)}</span></button><div className="ws-webinar-card-content"><span className="ws-webinar-type">{w.audience==='all'?'Any time':w.audience==='returning'?'Returning viewers':`${w.audience} session`} · Automated</span><h3>{w.title}</h3><div className="ws-card-numbers"><div><strong>{stats?.viewers??0}</strong><span>Viewers</span></div><div><strong>{closeRate(stats)}</strong><span>Close rate</span></div><div><strong>{money(stats?.value_cents??0)}</strong><span>Paid value</span></div></div><div className="ws-card-actions"><button className="ws-secondary" onClick={()=>onEdit(w)}><Settings2 size={15}/>Edit webinar</button><a className="wb-text" href={`/webinar?preview=${w.id}`} target="_blank" rel="noopener noreferrer">Preview <ArrowUpRight size={15}/></a></div></div></article>;})}</div>:<div className="ws-first-session"><span className="ws-large-icon"><Video size={34}/></span><h2>Let’s create your first webinar.</h2><p>Upload a video, add your offers and chat, then publish. We’ll handle who sees it.</p><div className="ws-empty-steps"><span>1 · Video</span><span>2 · Offers</span><span>3 · Chat</span><span>4 · Publish</span></div><button className="wb-primary" onClick={onCreate}><Plus size={17}/>Create my webinar</button></div>}<p className="ws-hint">Card results use the last 30 days and the current saved version. Close rate = unique viewers with a verified purchase ÷ unique viewers who started watching. Repeat purchases never add another buyer.</p></div>;
}
export function WebinarResults({webinars,performance,onRefresh}:{webinars:Webinar[];performance:WebinarPerformance[];onRefresh:()=>void}){
 return <section className="ws-card"><div className="ws-card-heading"><div><h2>What turns viewers into buyers?</h2><p>Verified iCash X payments · last 30 days · current saved versions</p></div><button className="ws-secondary" onClick={onRefresh}>Refresh</button></div><div className="ws-table-wrap"><table><thead><tr><th>Webinar</th><th>Viewers</th><th>Buyers</th><th>Close rate</th><th>Purchases</th><th>Paid value</th></tr></thead><tbody>{webinars.map(w=>{const p=performance.find(p=>p.webinar_id===w.id&&p.revision===w.revision);return <tr key={w.id}><td><b>{w.title}</b></td><td>{p?.viewers??0}</td><td>{p?.buyers??0}</td><td><strong>{closeRate(p)}</strong></td><td>{p?.purchases??0}</td><td>{money(p?.value_cents??0)}</td></tr>;})}</tbody></table></div>{!webinars.length&&<p className="ws-hint">Your results will appear once a webinar starts receiving viewers.</p>}<p className="ws-hint">Buyers are counted once per version. Purchases can include several payments from one buyer. Refunds, disputed payments, test transactions and owner previews are excluded. Other checkout providers need a verified payment connection before their sales can count.</p></section>;
}
export function WebinarReview({webinar,isNew,busy,onPublish}:{webinar:Webinar;isNew:boolean;busy:boolean;onPublish:()=>void}){
 const checked=webinarSchema.safeParse({...webinar,status:'published'}),offers=webinarOffers(webinar),available=webinarEndOffer(webinar),ready=checked.success&&!!available;
 return <div className="ws-review"><section className="ws-card"><span className="wb-eyebrow">READY WHEN YOU ARE</span><h2>One final look, then you’re live.</h2><p>New visitors will see this version. Existing viewers keep their saved session.</p><div className="ws-review-items">{[{label:'Video',value:webinar.videoUrl?`${formatWatchTime(webinar.durationSeconds)} · video added`:'Upload your presentation',ok:!!webinar.videoUrl},{label:'Offers',value:`${offers.length} timed ${offers.length===1?'offer':'offers'}`,ok:!!available},{label:'Conversation',value:`${webinar.chat.length} timed messages · AI ${webinar.aiEnabled?'on':'off'}`,ok:true},{label:'Audience',value:webinar.audience==='all'?'Any time':webinar.audience,ok:true},{label:'Optimizer',value:'Automatic · verified iCash X payments',ok:true}].map(item=><div key={item.label}><CheckCircle2 size={19} className={item.ok?'ws-check-ok':'ws-check-pending'}/><div><b>{item.label}</b><span>{item.value}</span></div></div>)}</div>{!checked.success&&<p className="ws-alert">{checked.error.issues[0].message}</p>}{!available&&<p className="ws-alert">Add an available offer before publishing.</p>}<div className="ws-review-actions">{!isNew&&<a className="ws-secondary" href={`/webinar?preview=${webinar.id}`} target="_blank" rel="noopener noreferrer"><Play size={16}/>Preview saved webinar</a>}<button className="wb-primary" disabled={busy||!ready} onClick={onPublish}>{busy?'Publishing…':webinar.status==='published'?'Publish changes':'Publish webinar'}<ArrowRight size={16}/></button></div></section></div>;
}
