'use client';
import {ArrowRight,Play,CheckCircle2} from 'lucide-react';
import {formatWatchTime,webinarOffers,webinarSchema,webinarEndOffer,type Webinar} from '@/lib/webinar-policy';
import type {WebinarPerformance} from '@/lib/webinar-optimizer';
import {WebinarDailyDashboard} from '@/components/webinar-daily-dashboard';
export const closeRate=(row?:WebinarPerformance)=>row?.viewers?`${((row.buyers??0)/row.viewers*100).toFixed(1)}%`:'—';
export function WebinarDashboard({webinars,onCreate,onEdit,onOptimizer}:{webinars:Webinar[];onCreate:()=>void;onEdit:(webinar:Webinar)=>void;onOptimizer:()=>void}){return <WebinarDailyDashboard webinars={webinars} onCreate={onCreate} onEdit={onEdit} onOptimizer={onOptimizer}/>;}
export function WebinarResults({webinars}:{webinars:Webinar[]}){return <WebinarDailyDashboard webinars={webinars} expanded/>;}
export function WebinarReview({webinar,isNew,busy,onPublish}:{webinar:Webinar;isNew:boolean;busy:boolean;onPublish:()=>void}){
 const checked=webinarSchema.safeParse({...webinar,status:'published'}),offers=webinarOffers(webinar),available=webinarEndOffer(webinar),ready=checked.success&&!!available;
 return <div className="ws-review"><section className="ws-card"><span className="wb-eyebrow">READY WHEN YOU ARE</span><h2>One final look, then you’re live.</h2><p>New visitors will see this version. Existing viewers keep their saved session.</p><div className="ws-review-items">{[{label:'Video',value:webinar.videoUrl?`${formatWatchTime(webinar.durationSeconds)} · video added`:'Upload your presentation',ok:!!webinar.videoUrl},...(webinar.nightVersion?[{label:'Night video',value:webinar.nightVersion.videoUrl?`${formatWatchTime(webinar.nightVersion.durationSeconds)} · video added`:'Add your night recording',ok:!!webinar.nightVersion.videoUrl}]:[]),{label:'Offers',value:`${offers.length} timed ${offers.length===1?'offer':'offers'}`,ok:!!available},{label:'Conversation',value:`${webinar.chat.length} timed messages · AI ${webinar.aiEnabled?'on':'off'}`,ok:true},{label:'Recordings',value:webinar.nightVersion?(webinar.nightEnabled?'Day + Night · automatic switching':'Day · night paused'):'Day · runs around the clock',ok:true}].map(item=><div key={item.label}><CheckCircle2 size={19} className={item.ok?'ws-check-ok':'ws-check-pending'}/><div><b>{item.label}</b><span>{item.value}</span></div></div>)}</div>{!checked.success&&<p className="ws-alert">{checked.error.issues[0].message}</p>}{!available&&<p className="ws-alert">Add an available offer before publishing.</p>}<div className="ws-review-actions">{!isNew&&<a className="ws-secondary" href={`/webinar?preview=${webinar.id}`} target="_blank" rel="noopener noreferrer"><Play size={16}/>Preview saved webinar</a>}<button className="wb-primary" disabled={busy||!ready} onClick={onPublish}>{busy?'Publishing…':webinar.status==='published'?'Publish changes':'Publish webinar'}<ArrowRight size={16}/></button></div></section></div>;
}
