'use client';
import {Plus,Trash2,ShoppingBag,ExternalLink} from 'lucide-react';
import {webinarOffers,type Webinar,type WebinarOffer} from '@/lib/webinar-policy';
import {WebinarTimeInput} from '@/components/webinar-time-input';
import {WebinarActivityEditor} from '@/components/webinar-activity-editor';

export function WebinarOffersEditor({webinar,onChange}:{webinar:Webinar;onChange:(patch:Partial<Webinar>)=>void}){
 const offers=webinarOffers(webinar);
 function save(next:WebinarOffer[]){onChange({offers:next,pitchAt:Math.min(...next.map(o=>o.at)),endOfferId:next.some(o=>o.id===webinar.endOfferId)?webinar.endOfferId:null});}
 function edit(id:string,patch:Partial<WebinarOffer>){save(offers.map(o=>o.id===id?{...o,...patch}:o));}
 return <div className="ws-offers-editor"><div className="ws-section-intro"><div><h2>Make the right offer at the right moment</h2><p>Add up to 12 offers. Each has its own timing, message and destination.</p></div><button className="ws-secondary" disabled={offers.length>=12} onClick={()=>save([...offers,{id:crypto.randomUUID(),title:`Offer ${offers.length+1}`,description:'',ctaLabel:'See this offer',at:Math.min(webinar.durationSeconds,Math.max(...offers.map(o=>o.at))+60),expiresAt:null,action:'link',url:''}])}><Plus size={16}/>Add offer</button></div>
 {offers.map((offer,index)=><section className="ws-card ws-offer-editor" key={offer.id}><div className="ws-card-heading"><div className="ws-offer-title"><span className="ws-step-number">{String(index+1).padStart(2,'0')}</span><div><h2>{offer.title}</h2><p>{offer.action==='checkout'?'iCash X checkout inside the room':'Your product or checkout link'}</p></div></div>{offers.length>1&&<button className="wb-icon" aria-label={`Remove offer ${index+1}`} onClick={()=>save(offers.filter(o=>o.id!==offer.id))}><Trash2 size={17}/></button>}</div><div className="ws-fields"><label className="wb-label">Offer headline<input value={offer.title} maxLength={150} onChange={e=>edit(offer.id,{title:e.target.value})}/></label><label className="wb-label">Button text<input value={offer.ctaLabel} maxLength={60} onChange={e=>edit(offer.id,{ctaLabel:e.target.value})}/></label></div><label className="wb-label">Short description <small>optional</small><textarea rows={2} maxLength={600} value={offer.description} onChange={e=>edit(offer.id,{description:e.target.value})}/></label><div className="ws-fields"><WebinarTimeInput label={`Offer ${index+1} appears at`} value={offer.at} max={webinar.durationSeconds} onChange={at=>edit(offer.id,{at})}/><label className="wb-label">Where it goes<select value={offer.action} onChange={e=>edit(offer.id,{action:e.target.value as WebinarOffer['action']})}><option value="checkout">iCash X checkout · inside the room</option><option value="link">A product or checkout link</option></select><small className="ws-hint">{offer.action==='checkout'?<ShoppingBag size={14}/>:<ExternalLink size={14}/>} The video keeps playing while the offer appears.</small></label></div>{offer.action==='link'&&<label className="wb-label">Destination URL<input value={offer.url} maxLength={2000} placeholder="https://your-checkout.com/offer" onChange={e=>edit(offer.id,{url:e.target.value})}/></label>}<details className="ws-advanced"><summary>Offer deadline</summary><label className="wb-label">Actual closing date <small>optional · your local time</small><input type="datetime-local" value={offer.expiresAt?new Date(Date.parse(offer.expiresAt)-new Date(offer.expiresAt).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>edit(offer.id,{expiresAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><p className="ws-hint">Leave blank for an evergreen offer. A deadline never resets for a returning viewer.</p></details></section>)}
 <WebinarActivityEditor webinar={webinar} onChange={onChange}/>
 <section className="ws-card"><h2>After the video</h2><label className="wb-check"><input type="checkbox" checked={webinar.redirectAtEnd} onChange={e=>onChange({redirectAtEnd:e.target.checked})}/><span>Open the next step after an 8-second countdown. Viewers can choose to stay.</span></label><label className="wb-label">Ending offer<select value={webinar.endOfferId??''} onChange={e=>onChange({endOfferId:e.target.value||null,offers})}><option value="">Latest available offer</option>{offers.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><p className="ws-hint">During the return window, visitors go back to the offer they last opened. Expired offers are skipped.</p></section></div>;
}
