'use client';
import {useState} from 'react';
import {Copy,Shuffle,Save,Sun,Moon,ArrowUpRight} from 'lucide-react';
import {type WebinarSettings,type Webinar} from '@/lib/webinar-policy';
import {webinarSite} from '@/lib/webinar-site';
import {allocation,eligibleVariants,type WebinarPerformance} from '@/lib/webinar-optimizer';
type Props={settings:WebinarSettings;onChange:(value:WebinarSettings)=>void;onSave:()=>void;webinars:Webinar[];performance:WebinarPerformance[];metaReady:boolean;metaHealth:{sent:number;pending:number;failed:number};busy:boolean};
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
export function WebinarGrowthSettings({settings,onChange,onSave,webinars,performance,metaReady,metaHealth,busy}:Props){
 const [copied,setCopied]=useState(false),[period,setPeriod]=useState<'day'|'night'>('day');
 const hour=period==='night'?settings.routing.nightStartsAt:settings.routing.nightEndsAt;
 const pool=eligibleVariants(webinars,[],'UTC',new Date(`2026-01-01T${String(hour).padStart(2,'0')}:00:00Z`),settings.routing);
 const shares=allocation(pool,performance,settings.optimizer);
 return <div className="ws-growth"><section className="ws-card ws-smart-link"><span className="wb-eyebrow">ONE LINK. EVERY SESSION.</span><h2>Your webinar funnel</h2><p>Send every ad, email and bio link here. The room chooses an eligible session and saves each viewer’s place.</p><div className="ws-link-field"><code>{webinarSite.viewerPath}</code><button className="ws-secondary" onClick={()=>void navigator.clipboard.writeText(location.origin+'/webinar').then(()=>setCopied(true)).catch(()=>setCopied(false))}><Copy size={15}/>{copied?'Copied':'Copy link'}</button><a className="ws-secondary" href="/webinar" target="_blank" rel="noopener noreferrer"><ArrowUpRight size={15}/>Open</a></div><p className="ws-hint">UTM attribution follows the visitor. Use the same URL across Meta ads; the session is chosen after they arrive.</p></section>
 <div className="ws-editor-grid"><section className="ws-card"><div className="ws-card-heading"><div><h2><Shuffle size={18}/> Webinar optimizer</h2><p>Allocate visitors toward verified paid value.</p></div><span className="ws-status">{settings.optimizer.enabled?'active':'manual rotation'}</span></div><label className="wb-check"><input type="checkbox" checked={settings.optimizer.enabled} onChange={e=>onChange({...settings,optimizer:{...settings.optimizer,enabled:e.target.checked}})}/><span>Optimize traffic between eligible webinars</span></label><div className="ws-fields"><label className="wb-label">Minimum visitors per version<input type="number" min={20} max={5000} value={settings.optimizer.minVisitors} onChange={e=>onChange({...settings,optimizer:{...settings.optimizer,minVisitors:Number(e.target.value)}})}/></label><label className="wb-label">Keep testing, %<input type="number" min={10} max={50} value={settings.optimizer.explorationPercent} onChange={e=>onChange({...settings,optimizer:{...settings.optimizer,explorationPercent:Number(e.target.value)}})}/></label></div><p className="ws-hint">Starts with equal traffic. After each eligible version reaches the minimum, it favors purchase value per visitor, with a testing share for every version. Uses 30 days of activity and waits 24 hours before scoring a visitor. This allocates website traffic; your ad budget stays in Meta.</p></section>
 <section className="ws-card"><h2><Moon size={18}/> Day &amp; night</h2><p>Match the room to the viewer’s local time.</p><div className="ws-fields"><label className="wb-label">Night starts<select value={settings.routing.nightStartsAt} onChange={e=>onChange({...settings,routing:{...settings.routing,nightStartsAt:Number(e.target.value)}})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label className="wb-label">Day starts<select value={settings.routing.nightEndsAt} onChange={e=>onChange({...settings,routing:{...settings.routing,nightEndsAt:Number(e.target.value)}})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label></div><p className="ws-hint">Uses the IP timezone supplied by the hosting platform, then the browser timezone. Assign each video to Day or Night in Session settings. Before the offer, same-day visits resume. After watching, the checkout window below takes priority; later visits advance to an unseen session.</p></section></div>
 <section className="ws-card"><h2>After they watch</h2><p>Give interested viewers a direct path back to the offer.</p><label className="wb-label">Send returning viewers to checkout for <small>hours after reaching the offer or finishing</small><input type="number" min={0} max={72} step={0.5} value={settings.routing.checkoutWindowHours} onChange={e=>onChange({...settings,routing:{...settings.routing,checkoutWindowHours:Number(e.target.value)}})}/></label><p className="ws-hint">During this window, an unpaid return opens checkout directly. After it expires, the next visit chooses another eligible unseen webinar, even on the same day. Refreshing never restarts the window. Viewers who leave before the offer still resume their place that day. Set 0 to advance immediately on return.</p></section>
 <section className="ws-card"><div className="ws-card-heading"><div><h2>Traffic &amp; value</h2><p>Current saved webinar versions · last 30 days</p></div><div className="ws-period"><button className="ws-secondary" aria-pressed={period==='day'} onClick={()=>setPeriod('day')}><Sun size={15}/>Day</button><button className="ws-secondary" aria-pressed={period==='night'} onClick={()=>setPeriod('night')}><Moon size={15}/>Night</button></div></div><div className="ws-table-wrap"><table><thead><tr><th>Webinar</th><th>Visitors</th><th>Purchases</th><th>Paid value</th><th>Value / visitor</th><th>Next traffic share</th></tr></thead><tbody>{pool.map(w=>{const s=performance.find(p=>p.webinar_id===w.id&&p.revision===w.revision),share=shares.find(a=>a.webinar_id===w.id)!;return <tr key={w.id}><td>{w.title}<small className="ws-table-sub">Revision {w.revision} · {share.phase}</small></td><td>{s?.visitors??0}</td><td>{s?.purchases??0}</td><td>{money((s?.value_cents??0)/100)}</td><td>{money(share.valuePerVisitor)}</td><td>{settings.optimizer.enabled?`${Math.round(share.share*100)}%`:'Rotation'}</td></tr>;})}</tbody></table></div>{!pool.length&&<p>Publish an eligible {period} or any-time session to begin.</p>}<p className="ws-hint">Share shown for new visitors. Later-day unpaid returns progress through the next ranked unseen sessions. Value per visitor uses visits at least 24 hours old. Each verified live payment is attributed once to the last started session within 7 days; refunds and disputes are excluded. This is paid value, not profit or ad ROAS.</p></section>
 <section className="ws-card"><div className="ws-card-heading"><div><h2>Meta Pixel + Conversions API</h2><p>Send the purchase amount that was actually paid.</p></div><span className="ws-status">{settings.meta.enabled&&metaReady?'enabled':'setup needed'}</span></div><label className="wb-label">Meta Pixel / dataset ID<input inputMode="numeric" value={settings.meta.pixelId} onChange={e=>onChange({...settings,meta:{...settings.meta,pixelId:e.target.value.trim()}})} placeholder="Your Meta dataset ID"/></label><label className="wb-check"><input type="checkbox" checked={settings.meta.enabled} onChange={e=>onChange({...settings,meta:{...settings.meta,enabled:e.target.checked}})}/><span>Enable consent-based browser and server measurement</span></label><p className="ws-hint">ViewContent → Lead → InitiateCheckout → Purchase. Opening the offer is tracked separately. Purchase is confirmed by billing, and browser/server events share one ID. Previews and test payments are excluded.</p>{!metaReady&&<p className="ws-alert">The server connection still needs a Meta access token and Graph API version in the deployment settings. Credentials never go in this screen.</p>}<div className="ws-meta-health"><span><b>{metaHealth.sent}</b> server events sent</span><span><b>{metaHealth.pending}</b> pending</span><span><b>{metaHealth.failed}</b> failed</span></div></section>
 <button className="wb-primary" disabled={busy} onClick={onSave}><Save size={16}/>{busy?'Saving…':'Save smart link settings'}</button></div>;
}
