'use client';
import {Check} from 'lucide-react';
import {webinarPitchAt,type Webinar} from '@/lib/webinar-policy';
import {WebinarTimeInput} from '@/components/webinar-time-input';

export function WebinarActivityEditor({webinar,onChange}:{webinar:Webinar;onChange:(patch:Partial<Webinar>)=>void}){
 const settings=webinar.purchaseNotifications;
 function edit(patch:Partial<typeof settings>){onChange({purchaseNotifications:{...settings,...patch}});}
 return <section className="ws-card"><div className="ws-card-heading"><div><h2>Purchase &amp; funding pop-ups</h2><p>Let viewers see recent, confirmed activity when your offers appear.</p></div></div><label className="wb-check"><input type="checkbox" checked={settings.enabled} onChange={e=>edit({enabled:e.target.checked})}/><span>Show verified purchases and bot funding</span></label>{settings.enabled&&<><div className="ws-fields"><label className="wb-label">Start showing updates<select value={settings.startAt===null?'offer':'custom'} onChange={e=>edit({startAt:e.target.value==='offer'?null:webinarPitchAt(webinar)})}><option value="offer">When the first offer appears</option><option value="custom">At a later video timestamp</option></select></label><label className="wb-label">Minimum time between pop-ups<select value={settings.intervalSeconds} onChange={e=>edit({intervalSeconds:Number(e.target.value)})}>{[15,30,45,60,90,120].map(seconds=><option key={seconds} value={seconds}>{seconds} seconds</option>)}</select></label></div>{settings.startAt!==null&&<WebinarTimeInput label="Pop-ups can start at" value={settings.startAt} max={webinar.durationSeconds} onChange={startAt=>edit({startAt})}/>}<label className="wb-check"><input type="checkbox" checked={settings.includeRegion} onChange={e=>edit({includeRegion:e.target.checked})}/><span>Include approximate state or country when available</span></label><div className="ws-activity-example"><span className="wb-activity-check"><Check size={18}/></span><div><small>EXAMPLE ONLY · NOT A PURCHASE</small><strong>A viewer{settings.includeRegion?' in Texas':''} started a $10/day bot budget</strong></div></div><p className="ws-hint">Uses confirmed live payments from the last 15 minutes, with the actual amount and billing type. Each update appears once per tab and session for 6 seconds. Locations are approximate; names and contact details stay private. Pop-ups wait for an available offer and pause during checkout. No recent payments means no pop-ups.</p></>}</section>;
}
