'use client';
import {useState} from 'react';
import {Copy,Shuffle,Save,Sun,Moon,ArrowUpRight,CheckCircle2} from 'lucide-react';
import {type WebinarSettings,type Webinar} from '@/lib/webinar-policy';
import {webinarSite} from '@/lib/webinar-site';
import {allocation,eligibleVariants,type WebinarPerformance} from '@/lib/webinar-optimizer';
import {closeRate} from '@/components/webinar-dashboard';
type Props={settings:WebinarSettings;onChange:(value:WebinarSettings)=>void;onSave:()=>void;webinars:Webinar[];performance:WebinarPerformance[];metaReady:boolean;metaHealth:{sent:number;pending:number;failed:number};busy:boolean};
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
export function WebinarGrowthSettings({settings,onChange,onSave,webinars,performance,metaReady,metaHealth,busy}:Props){
 const [copied,setCopied]=useState(false),[period,setPeriod]=useState<'day'|'night'>('day');
 const hour=period==='night'?settings.routing.nightStartsAt:settings.routing.nightEndsAt;
 const pool=eligibleVariants(webinars,[],'UTC',new Date(`2026-01-01T${String(hour).padStart(2,'0')}:00:00Z`),settings.routing);
 const shares=allocation(pool,performance,{...settings.optimizer,enabled:true});
 const optimizing=shares.some(s=>s.phase==='optimizing');
 return <div className="ws-growth"><section className="ws-card ws-smart-link"><span className="wb-eyebrow">ONE LINK FOR EVERYTHING</span><h2>Your audience always starts here</h2><p>Use this link in every ad, email and bio. The right session is picked automatically.</p><div className="ws-link-field"><code>{webinarSite.viewerPath}</code><button className="ws-secondary" onClick={()=>void navigator.clipboard.writeText(location.origin+webinarSite.viewerPath).then(()=>setCopied(true)).catch(()=>setCopied(false))}><Copy size={15}/>{copied?'Copied':'Copy link'}</button><a className="ws-secondary" href={webinarSite.viewerPath} target="_blank" rel="noopener noreferrer"><ArrowUpRight size={15}/>Open</a></div></section>
 <section className="ws-card"><div className="ws-card-heading"><div><h2><Shuffle size={19}/> Always optimizing</h2><p>iCash X purchase data guides your webinar traffic.</p></div><span className="ws-auto-badge"><CheckCircle2 size={15}/>Automatic</span></div><div className="ws-optimizer-steps"><div><span>01</span><b>Test your webinars</b><p>New versions start with a fair share of eligible visitors.</p></div><div><span>02</span><b>Measure real purchases</b><p>Close rate and paid value come from verified payments.</p></div><div><span>03</span><b>Send traffic to winners</b><p>Stronger sessions earn more traffic while other versions keep testing.</p></div></div><p className="ws-optimizer-state"><span className="ws-status-dot"/>{pool.length?optimizing?'Optimizing traffic using purchase value':'Learning · collecting enough visits and purchases':'Ready · publish your first webinar to begin'}</p></section>
 <section className="ws-card"><div className="ws-card-heading"><div><h2>Your webinars, side by side</h2><p>Current versions · last 30 days · verified iCash X payments</p></div><div className="ws-period"><button className="ws-secondary" aria-pressed={period==='day'} onClick={()=>setPeriod('day')}><Sun size={15}/>Day</button><button className="ws-secondary" aria-pressed={period==='night'} onClick={()=>setPeriod('night')}><Moon size={15}/>Night</button></div></div><div className="ws-table-wrap"><table><thead><tr><th>Webinar</th><th>Viewers</th><th>Buyers</th><th>Close rate</th><th>Paid value</th><th>Traffic share</th></tr></thead><tbody>{pool.map(w=>{const row=performance.find(p=>p.webinar_id===w.id&&p.revision===w.revision),share=shares.find(a=>a.webinar_id===w.id)!;return <tr key={w.id}><td><b>{w.title}</b><small className="ws-table-sub">{share.phase==='learning'?'Learning':'Optimizing'}</small></td><td>{row?.viewers??0}</td><td>{row?.buyers??0}</td><td><strong>{closeRate(row)}</strong></td><td>{money((row?.value_cents??0)/100)}</td><td><span className="ws-traffic-share">{Math.round(share.share*100)}%</span></td></tr>;})}</tbody></table></div>{!pool.length&&<p className="ws-hint">Publish your first webinar to start. One daytime recording also covers night until a night version is published.</p>}<p className="ws-hint">Close rate counts each buyer once and uses viewers who started playback. Traffic favors paid value per visitor after {settings.optimizer.minVisitors} mature visits per version, with {settings.optimizer.explorationPercent}% kept for testing. Visits mature after 24 hours. This adjusts your webinar mix; your ad budget stays in Meta.</p></section>
 <details className="ws-card ws-routing-details"><summary>Day, night & returning visitors</summary><div className="ws-fields"><label className="wb-label">Night starts<select value={settings.routing.nightStartsAt} onChange={e=>onChange({...settings,routing:{...settings.routing,nightStartsAt:Number(e.target.value)}})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label className="wb-label">Day starts<select value={settings.routing.nightEndsAt} onChange={e=>onChange({...settings,routing:{...settings.routing,nightEndsAt:Number(e.target.value)}})}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label></div><label className="wb-label">Return directly to the offer for <small>hours after reaching the offer or finishing</small><input type="number" min={0} max={72} step={0.5} value={settings.routing.checkoutWindowHours} onChange={e=>onChange({...settings,routing:{...settings.routing,checkoutWindowHours:Number(e.target.value)}})}/></label><p className="ws-hint">Default: 3 hours. After that, an unpaid return gets the next eligible unseen webinar. Earlier exits resume that day. Refreshing never extends the window. Time of day follows the viewer’s local timezone. A main/day recording runs at night until a dedicated night version is published.</p><button className="wb-primary" disabled={busy} onClick={onSave}><Save size={16}/>Save routing settings</button></details>
 <details className="ws-card ws-routing-details"><summary>Meta Pixel & purchase connection</summary><p>Connect your dataset once to use browser and server measurement.</p><label className="wb-label">Meta Pixel / dataset ID<input inputMode="numeric" value={settings.meta.pixelId} onChange={e=>onChange({...settings,meta:{...settings.meta,pixelId:e.target.value.trim()}})} placeholder="Your Meta dataset ID"/></label><label className="wb-check"><input type="checkbox" checked={settings.meta.enabled} onChange={e=>onChange({...settings,meta:{...settings.meta,enabled:e.target.checked}})}/><span>Enable consent-based browser and server measurement</span></label>{!metaReady&&<p className="ws-alert">The server connection needs your Meta access token and Graph API version before measurement can start.</p>}<p className="ws-hint">Purchase reports the amount actually paid. Browser and server events are deduplicated. Previews and test payments are excluded.</p><div className="ws-meta-health"><span><b>{metaHealth.sent}</b> sent</span><span><b>{metaHealth.pending}</b> pending</span><span><b>{metaHealth.failed}</b> failed</span></div><button className="wb-primary" disabled={busy} onClick={onSave}><Save size={16}/>Save connection</button></details></div>;
}
