'use client';
import {useRef,useState} from 'react';
const endpoint='/api/owner-inbound-acceptance/audio-once';
const failures:Record<string,string>={twilio_network_failure:'The Twilio receipt request failed before a response arrived (network or timeout).',twilio_http_other:'Twilio returned an unsuccessful HTTP response.',twilio_token_missing:'The runtime Twilio authentication token is absent or blank. No Twilio request was sent.',twilio_token_invalid:'The runtime Twilio authentication token has an invalid format. No Twilio request was sent.',twilio_response_invalid:'Twilio returned a response that could not be verified.',twilio_http_401:'Twilio rejected the server connection with HTTP 401. The saved token/account combination needs review.',twilio_http_403:'Twilio denied this receipt read with HTTP 403.',twilio_http_404:'Twilio returned HTTP 404 for the prior call under the configured account.',twilio_http_429:'Twilio rate-limited the read with HTTP 429. Leave the call on hold.',twilio_account_missing:'The runtime Twilio account setting is absent or blank.',twilio_account_invalid:'The runtime Twilio account setting has an invalid format.',twilio_read_unavailable:'The server could not authenticate or read the known prior Twilio call. Leave the call on hold.',twilio_receipt_mismatch:'The prior Twilio receipt does not match the configured account and owner route.',private_agent_read_unavailable:'The private test agent could not be read from the provider.',branch_read_unavailable:'The private test branch could not be read from the provider.',phone_read_unavailable:'The incoming phone assignment could not be read from the provider.',main_read_unavailable:'The incoming Main configuration could not be read from the provider.',sign_in_required:'Sign in as the configured owner.',twilio_account_configuration_unavailable:'The server’s Twilio account configuration is unavailable. Leave the call on hold.',database_configuration_unavailable:'The server database configuration is unavailable.',database_access_unavailable:'The server could not read the one-use database gate.',provider_unavailable:'A required provider read failed. Leave the call on hold.',provider_receipt_invalid:'A provider response could not be verified.',provider_credentials_unavailable:'A required provider connection is unavailable.',provider_configuration_invalid:'A provider target configuration is invalid.',provider_review_changed:'Provider settings changed after review. Check readiness again.',test_already_consumed:'The one-use test has already been consumed. Check status.',arm_outcome_unknown:'The arm result is uncertain. Do not arm again. Check status.',readiness_unavailable:'Readiness is unavailable. Leave the call on hold.'};
type Status={status:string;canArm:boolean;canCancel?:boolean;canReconcile?:boolean;checks?:Record<string,boolean>;incomingDiagnostics?:Record<string,number|null>;configHash?:string;versionId?:string;expiresAt?:string;challenge?:string;result?:{status?:string;forwarding?:string;durationSeconds?:number|null;challenge?:string}};
export default function OwnerAudioOnce(){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[code,setCode]=useState<string|null>(null),[message,setMessage]=useState(''),[attempted,setAttempted]=useState(false);
 const active=useRef(false),armAttempted=useRef(false);
 async function run(action?:'arm'|'cancel'|'reconcile'){
  if(active.current||action==='arm'&&(!consent||!status?.canArm||armAttempted.current))return;
  if(action==='arm'){armAttempted.current=true;setAttempted(true);}active.current=true;setBusy(true);setMessage('');
  try{
   const body=action==='arm'?{action,confirmation:'Arm one 60-second owner audio test; provider fees may apply',configHash:status!.configHash,versionId:status!.versionId}:{action};
   const r=await fetch(endpoint,{method:action?'POST':'GET',cache:'no-store',credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(35000),...(action?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
   if(!r.ok){const error=await r.json().catch(()=>null);const reason=typeof error?.reason==='string'?error.reason:'readiness_unavailable';const config=error?.configurationDiagnostics;const details=config&&typeof config.present==='boolean'&&Number.isInteger(config.rawLength)&&Number.isInteger(config.trimmedLength)?` Setting ${config.present?'present':'absent'}; length ${config.rawLength}, trimmed length ${config.trimmedLength}.`:'';setMessage((Object.hasOwn(failures,reason)?failures[reason]:failures.readiness_unavailable)+details+(Number.isInteger(error?.providerHttpStatus)&&error.providerHttpStatus>=100&&error.providerHttpStatus<=599?` HTTP status: ${error.providerHttpStatus}.`:''));setStatus(null);return;}const data:Status=await r.json();if(!data||typeof data.status!=='string'||typeof data.canArm!=='boolean')throw Error();
   const {challenge,...safe}=data;setStatus(safe);
   if(action==='arm'&&data.status==='armed'&&typeof challenge==='string'&&/^\d{8}$/.test(challenge))setCode(challenge);
   else if(!['armed','inspecting','claimed','provider_processing'].includes(data.status))setCode(null);
   setConsent(false);setMessage(action==='arm'?'Armed once. Call the displayed number now and say your code. The code cannot be recovered after leaving this page.':data.status==='passed'?'Audio and dashboard code verified. Forwarding status is shown separately.':'Status checked. No call was placed.');
  }catch{setMessage(action==='arm'?'The arm result is uncertain. Do not arm again. Check status; this test stays one-use.':'Status is unavailable. Leave the call on hold.');}
  finally{active.current=false;setBusy(false);}
 }
 return <section aria-label="One-use owner audio test" style={{maxWidth:650,margin:'2rem auto',padding:'1.5rem',lineHeight:1.6,border:'1px solid currentColor',borderRadius:12}}>
  <h2>One-use owner audio test</h2>
  <p>Call +1 424-394-8384 from your configured owner phone ending 5280 after arming. The AI conversation is capped at 60 seconds. Queue waiting may add up to 30 seconds. Provider fees may apply; forwarding pricing is unverified. Customer credits are not reserved or charged.</p>
  <p>This private test has no seller actions, outbound call, business tools or customer data. Audio recording is disabled; the provider may retain a transcript and usage metadata. Caller ID alone does not verify identity. Say the private dashboard code one digit at a time.</p>
  <button disabled={busy} onClick={()=>void run()}>Check one-use readiness</button>
  <p role="status">Status: {status?.status.replaceAll('_',' ')??'not checked'}</p>
  {status?.checks&&<ul>{Object.entries(status.checks).filter(([,ok])=>!ok).map(([name])=><li key={name}>Needs review: {name}</li>)}</ul>}
  {status?.incomingDiagnostics&&<details><summary>Read-only incoming Main diagnostics</summary><ul>{Object.entries(status.incomingDiagnostics).map(([key,value])=><li key={key}>{key}: {value??'unknown'}</li>)}</ul></details>}
  {status?.canArm&&!attempted&&<><label><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/> I approve this one owner-initiated test with the duration and provider-fee disclosures above</label><p><button disabled={busy||!consent} onClick={()=>void run('arm')}>Arm one test for five minutes</button></p></>}
  {code&&<p>Private test code: <strong>{code}</strong></p>}
  {status?.expiresAt&&<p>Call window ends {new Date(status.expiresAt).toLocaleString()}</p>}
  {status?.canCancel&&<button disabled={busy} onClick={()=>void run('cancel')}>Cancel unused test</button>}
  {status?.canReconcile&&<button disabled={busy} onClick={()=>void run('reconcile')}>Check completed audio result</button>}
  {status?.result&&<p>Audio result: {status.result.status}. Dashboard code: {status.result.challenge}. Forwarding evidence: {status.result.forwarding}. {typeof status.result.durationSeconds==='number'?`Conversation: ${status.result.durationSeconds} seconds.`:''}</p>}
  <p role="alert">{message}</p><p>Refresh, retry, expiry, cancellation or an uncertain result cannot create another allowance. A passed audio test does not certify forwarding or release business calling.</p>
 </section>;
}
