export type ReviewStatusItem={key:string;title:string;status:'blocked'|'review_required'|'recorded'|'not_applicable';detail:string;action:'account_details'|'funding'|'operator_review'|'review_contract'|'none'};
export type PermissionReview={permission_until:string;dnc_checked_at:string;dnc_clear:boolean;revoked_at:string|null;suppressed:boolean};
export function authorityReviewStatus(i:{identity:boolean;availableCents:number;paused:boolean;permissions:PermissionReview[];offer:{max_offer_cents:number;expires_at:string}|null;purchaseSigned:boolean;marketing:{expires_at:string;purchaseMatches:boolean;priceMatches:boolean}|null;now:number}):ReviewStatusItem[]{
 const validDate=(v:string)=>Number.isFinite(Date.parse(v));
 const currentPermission=i.permissions.some(p=>!p.revoked_at&&!p.suppressed&&p.dnc_clear&&validDate(p.permission_until)&&Date.parse(p.permission_until)>i.now&&validDate(p.dnc_checked_at)&&Date.parse(p.dnc_checked_at)<=i.now&&Date.parse(p.dnc_checked_at)>=i.now-30*86400000);
 const offerCurrent=!!i.offer&&Number.isSafeInteger(i.offer.max_offer_cents)&&i.offer.max_offer_cents>0&&validDate(i.offer.expires_at)&&Date.parse(i.offer.expires_at)>i.now;
 const marketingCurrent=!!i.marketing&&i.purchaseSigned&&i.marketing.purchaseMatches&&i.marketing.priceMatches&&validDate(i.marketing.expires_at)&&Date.parse(i.marketing.expires_at)>i.now;
 const rows:ReviewStatusItem[]=[
 {key:'identity',title:'Contract identity',status:i.identity?'recorded':'blocked',detail:i.identity?'Your contract identity is saved.':'Add your legal name or company before the bot can represent you.',action:i.identity?'none':'account_details'},
 {key:'budget',title:'Work controls and credits',status:i.paused||i.availableCents<=0?'blocked':'recorded',detail:i.paused?'Your bot is paused. Existing work is saved; no new automatic work should start.':i.availableCents<=0?'No available credits remain for new paid work. Reserved work may still finish.':'Available credits are recorded. Each task still checks its price and spending limits.',action:i.availableCents<=0?'funding':'none'},
 {key:'contact_permission',title:'Seller contact review',status:currentPermission?'recorded':'review_required',detail:currentPermission?'A current seller-contact permission record exists. Each contact still must pass timing, suppression and dispatch checks.':i.permissions.some(p=>p.suppressed||p.revoked_at)?'A contact has opted out or permission was revoked. Do not contact that recipient again. Other contacts require their own reviewed permission.':'Seller outreach is waiting for reviewed contact permission and a current do-not-call check. Purchased contact details alone do not establish permission.',action:currentPermission?'none':'operator_review'},
 {key:'offer_authority',title:'Offer limit approval',status:offerCurrent?'recorded':'review_required',detail:offerCurrent?'A current maximum offer approval is recorded. The bot must also stay within reviewed property numbers.':'No current approved offer limit is recorded. The bot can collect information but cannot quote an authorized offer.',action:offerCurrent?'none':'operator_review'},
 {key:'marketing_authority',title:'Buyer marketing review',status:!i.purchaseSigned?'not_applicable':marketingCurrent?'recorded':'review_required',detail:!i.purchaseSigned?'Buyer marketing comes after a verified signed purchase agreement and a separate marketing review.':marketingCurrent?'Marketing approval matches the signed purchase agreement and price. Buyer contact permissions are checked separately.':'Your signed purchase agreement still needs a current marketing review matching its terms before buyer outreach.',action:!i.purchaseSigned?'review_contract':marketingCurrent?'none':'operator_review'}
 ];
 return rows;
}
