/** The operator's standing disposition price. Seller purchase math is separate. */
export const assignmentFeeCents=1_000_000;
export function buyerAskingPrice(purchasePriceCents:number){
 if(!Number.isSafeInteger(purchasePriceCents)||purchasePriceCents<=0||!Number.isSafeInteger(purchasePriceCents+assignmentFeeCents))throw Error('Signed purchase price required');
 return purchasePriceCents+assignmentFeeCents;
}
export type BuyerPackage={address:string;principal:string;purchasePriceCents:number;assignmentFeeCents:number;askingPriceCents:number;repairsCents:number|null;arvCents:number|null;closingDate:string|null;businessPhone:string|null;fetchedAt:string|null};
const money=(n:number|null)=>n===null?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n/100);
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderBuyerPackage(p:BuyerPackage){
 if(!p.address||p.address.length>300||!Number.isSafeInteger(p.purchasePriceCents)||p.purchasePriceCents<=0||!Number.isSafeInteger(p.assignmentFeeCents)||p.assignmentFeeCents<0||p.askingPriceCents!==p.purchasePriceCents+p.assignmentFeeCents)throw Error('Buyer package unavailable');
 const phone=p.businessPhone&&/^\+1[2-9]\d{9}$/.test(p.businessPhone)?p.businessPhone:null;
 const facts=[['Purchase contract',money(p.purchasePriceCents)],['Assignment fee',money(p.assignmentFeeCents)],['Estimated ARV',money(p.arvCents)],['Estimated repairs',money(p.repairsCents)],['Closing date',p.closingDate||'Confirm with the deal contact']];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${escape(p.address)} | Buyer package</title><style>body{margin:0;background:#f2f6fc;color:#102a42;font:16px/1.5 system-ui,sans-serif}main{max-width:740px;margin:40px auto;padding:28px;background:#fff;border-radius:24px;box-shadow:0 12px 40px #102a4210}header{font-weight:700;color:#087ec3}h1{font-size:clamp(26px,6vw,40px);line-height:1.12;margin:20px 0}.badge{display:inline-block;color:#075f97;background:#eaf6ff;border-radius:20px;padding:5px 12px;font-size:13px}.price{font-size:40px;font-weight:750;margin:12px 0 0}.muted{color:#596b7b;font-size:14px}dl{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:20px 0;border-block:1px solid #e4eaf0}dd{margin:0;text-align:right;font-weight:650}.cta{display:block;text-align:center;background:#028de3;color:white;text-decoration:none;font-weight:650;padding:15px;border-radius:12px;margin-top:24px}section{margin-top:24px}h2{font-size:18px}@media(max-width:600px){main{margin:12px;padding:22px}dl{font-size:14px}}</style></head><body><main><header>iCash X · Buyer opportunity</header><h1>${escape(p.address)}</h1><span class="badge">Under contract · Assignment opportunity</span><p class="price">${escape(money(p.askingPriceCents))}</p><p class="muted">Buyer price, plus buyer-paid closing costs.</p><dl>${facts.map(([k,v])=>`<dt>${escape(k)}</dt><dd>${escape(v)}</dd>`).join('')}</dl><section><h2>The opportunity</h2><p>${escape(p.principal)} is offering their purchase-contract interest for assignment. The asking price includes the assignment fee shown above.</p><p>Buyer pays all transaction closing costs allocated to Buyer in the signed agreements. Existing seller debts and charges the law assigns to Seller remain separate.</p></section><section><h2>Next steps</h2><p>Ask about access, your closing timeline, proof of funds and the buyer deposit. Showings need confirmed permission. The assignment agreement and verified title/escrow instructions control payment.</p><p class="muted">ARV and repairs are research estimates, not an inspection or appraisal.${p.fetchedAt?' Research dated '+escape(p.fetchedAt.slice(0,10))+'.':''} The executed purchase agreement is provided during contract review; this page is a deal summary.</p></section>${phone?`<a class="cta" href="tel:${phone}">Call about this deal</a>`:''}</main></body></html>`;
}
export function buyerPackageText(price:number,url:string){
 if(!Number.isSafeInteger(price)||price<=0||!/^https:\/\/www\.geticashx\.com\/d\/[a-f0-9]{32}$/.test(url))throw Error('Buyer package link required');
 return `Under contract. Buyer price ${money(price)} + closing costs. Deal package: ${url}`;
}
