import {z} from 'zod';
import {validCalendarDate} from './document-dates.ts';
const text=z.string().trim().max(1000).default('');
const money=z.number().int().nonnegative().max(100000000000).nullable().default(null);
const date=z.string().refine(value=>value===''||validCalendarDate(value),'Enter a real calendar date in YYYY-MM-DD format.').default('');
export const dealTermsSchema=z.object({dealNotes:z.string().trim().max(1200).default(''),seller:text,buyer:text,assignee:text,address:text,legalDescription:z.string().trim().max(12000).default(''),state:z.string().trim().max(2).default(''),priceCents:money,assignmentFeeCents:money,earnestCents:money,assignmentDepositCents:money,inspectionDays:z.number().int().min(0).max(90).default(10),effectiveDate:date,closingDate:date,escrowAgent:text,titleEmail:z.union([z.literal(''),z.string().email().max(254)]).default(''),payoutMethod:z.enum(['wire','ach','check','zelle','cash_app']).default('wire'),payoutHandle:z.string().max(120).default(''),priceSource:z.enum(['proposed','seller_reported']).default('proposed')}).strict();
export type DealTerms=z.infer<typeof dealTermsSchema>;
export type DocumentKind='purchase'|'assignment'|'buyer_package'|'title_packet';
const blank=(s:string)=>s||'____________________';
const usd=(n:number|null)=>n===null?'$____________':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
export function documentSections(kind:DocumentKind,t:DealTerms){
 const property=`Property: ${blank(t.address)}. Legal description: ${blank(t.legalDescription)}. State: ${blank(t.state)}.`;
 const close=`${t.closingDate?'Closing on or before '+t.closingDate:'Proposed closing: within 30 calendar days after the effective date, subject to the parties’ agreement'}, through ${blank(t.escrowAgent)}. Any extension requires a written agreement.`;
 const costs='Buyer pays transaction closing charges, including title-company search, escrow/settlement and title-insurance charges, to the extent legally allocable to Buyer and required by the signed agreement. Seller remains responsible for existing mortgages, liens, unpaid obligations and any charges law requires Seller to pay, unless separately agreed in writing. Taxes and other prorations must be stated in the closing statement.';
 if(kind==='purchase')return {title:'Purchase and Sale Agreement',sections:[
 ['Parties and property',`Seller: ${blank(t.seller)}. Buyer: ${blank(t.buyer)}. ${property}`],
 ['Cash purchase price',`Cash purchase price: ${usd(t.priceCents)}. Effective date is the date of the last required signature: ${blank(t.effectiveDate)}. No financing contingency is provided by this draft.`],
 ['Inspection contingency',`Buyer has ${t.inspectionDays} calendar days after the effective date to inspect and give written termination notice to Seller and escrow. Any required option fee, delivery deadline or state-specific termination provision must be supplied before signing. Inspections require agreed access; no destructive testing without written permission.`],
 ['Condition, title and closing',`Property is purchased as-is, subject to the inspection and title contingencies and legally required disclosures. Seller must provide marketable, insurable title subject only to accepted exceptions. Unresolved material title defects allow Buyer to terminate before closing. ${close} Possession transfers at funding unless a separate occupancy agreement is signed.`],
 ['Closing costs',costs],
 ['Assignment and access','Buyer may assign its contractual purchasing interest, subject to applicable law and any required disclosures or consents. Buyer is acting as principal, may earn an assignment fee, and is not representing Seller. Assignment does not release Buyer unless Seller agrees in writing. Buyer may arrange inspections and showings only with Seller/occupant permission. No ownership transfer occurs before closing.'],
 ['Default and entire agreement','A nondefaulting party retains remedies allowed by applicable law and the signed agreement. Required disclosures and signed addenda are part of the agreement. Changes require a signed writing. All record owners and other required parties must sign. Electronic signatures may be used when validly collected.'],
 ['Signatures','Seller(s): __________________ Date: ______  Buyer: __________________ Date: ______'],
 ]};
 if(kind==='assignment')return {title:'Assignment of Purchase Contract',sections:[
 ['Parties and contract',`Assignor: ${blank(t.buyer)}. Assignee: ${blank(t.assignee)}. Underlying Seller: ${blank(t.seller)}. Purchase contract effective ${blank(t.effectiveDate)}. ${property} Attach the complete executed purchase contract and all amendments.`],
 ['Interest assigned','Assignor assigns its contractual purchaser interest only, not ownership of the real estate. Assignment is subject to the underlying contract, its assignability, required consents, mandatory disclosures and applicable law. Assignee acknowledges receiving and reviewing the underlying agreement.'],
 ['Price and fee',`Underlying purchase price: ${usd(t.priceCents)}. Assignment fee: ${usd(t.assignmentFeeCents)}, payable to Assignor through the closing agent at funding. Buyer closing costs are additional. ${close}`],
 ['Deposit',`Assignee deposits ${usd(t.assignmentDepositCents)} with ${blank(t.escrowAgent)} within 1 business day after the last assignment signature. Deposit is credited toward the assignment fee at closing; any excess must be allocated in signed escrow instructions. Deposit becomes non-refundable for Assignee default after execution, except as stated below and to the extent enforceable. It is not immediately earned or automatically payable to Assignor.`],
 ['Exceptions and escrow','Deposit is refundable if Assignor cannot convey the stated contract interest, a required assignment consent is refused, Seller defaults, an unresolved title defect prevents closing, or the underlying contract validly terminates without Assignee default. Mandatory cancellation/refund rights prevail. Escrow release requires the signed terms, proper authorization and resolution of any dispute.'],
 ['Buyer obligations and costs',`${costs} Assignee assumes purchaser obligations under the underlying contract. This assignment does not change Seller’s contract or release Assignor without Seller’s written agreement. No new inspection contingency is created by this assignment; any remaining underlying rights must be expressly transferred.`],
 ['Signatures','Assignor: __________________ Date: ______  Assignee: __________________ Date: ______  Required consent(s): __________________'],
 ]};
 if(kind==='buyer_package')return {title:'Buyer Opportunity Package',sections:[['Property',property],['Numbers',`Proposed underlying price: ${usd(t.priceCents)}. Assignment fee: ${usd(t.assignmentFeeCents)}. Buyer pays closing costs, including legally allocable title-company charges, under the signed agreements. Deposit: ${usd(t.assignmentDepositCents)}. Verify repairs, value, access and your own underwriting.`],['Interest offered','Draft package for a potential assignment of contractual interest. Do not market or distribute until an executed assignable purchase agreement and marketing authority are verified. No property ownership, clear title, profit or completed deal is represented.'],['Access and timing',`${close} Showings require Seller/occupant and Buyer confirmation. Do not visit unannounced. Proof of funds and authority to sign are required before buyer acceptance.`],['Review items','Attach permitted property photos, repair evidence, value/comparable sources with dates, signed purchase agreement, required assignment disclosures, occupancy/access terms, inspection deadline and title contact. Missing items are not assumed verified.']]};
 return {title:'Title Opening Request — Draft',sections:[['Requested recipient',`${blank(t.escrowAgent)} — ${blank(t.titleEmail)}. Verify recipient and licensing independently before sending.`],['Transaction',`${property} Seller: ${blank(t.seller)}. Purchaser/assignor: ${blank(t.buyer)}. Assignee: ${blank(t.assignee)}. Purchase price ${usd(t.priceCents)}; assignment fee ${usd(t.assignmentFeeCents)}. ${close}`],['Requested services','Please confirm acceptance of the assignment structure, parties and signatory authority; open title; obtain lien/tax/payoff information; identify title exceptions, required releases, disclosures and missing signatures; provide deposit instructions through your verified secure channel.'],['Costs and deposits',`${costs} Assignee deposit ${usd(t.assignmentDepositCents)}. Please confirm deposit receipt and release conditions. No deposit has been collected or confirmed by this draft.`],['Proceeds preference',`User requested ${t.payoutMethod.replace('_',' ')}${t.payoutHandle?' ('+t.payoutHandle+')':''}. This is a preference only, subject to the closing agent’s supported methods and identity checks. Obtain bank/wire details through the closing agent’s secure process, not an AI-generated instruction.`],['Attachments and confirmation','Attach executed contracts, amendments and relevant disclosures only after signature verification. Request title file number, assigned closer, verified contact details, tentative closing time, final settlement statement and written funded/recorded confirmation. This request has not been sent.']]};
}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderDealDocument(kind:DocumentKind,input:unknown){
 const t=dealTermsSchema.parse(input);const d=documentSections(kind,t);if(t.dealNotes)d.sections.push(['Agreed special terms / review notes',t.dealNotes]);
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(d.title)}</title><style>@page{size:letter;margin:.5in}body{font:11pt/1.32 Arial,sans-serif;color:#111;max-width:7.5in;margin:24px auto;padding:0 12px}h1{font-size:19pt;margin:0 0 4px}h2{font-size:11pt;margin:10px 0 2px}p{margin:0}small{display:block;font-size:8.5pt;color:#555}section{break-inside:avoid}@media print{body{margin:0;padding:0;font-size:9pt;line-height:1.23}h1{font-size:16pt}h2{font-size:9pt;margin-top:7px}}</style></head><body><h1>${escape(d.title)}</h1><small>UNSIGNED DRAFT • State-specific legal review and required disclosures/addenda needed. Not a government-promulgated form. One-page core intended; required attachments may add pages.</small>${d.sections.map(([h,p])=>`<section><h2>${escape(h)}</h2><p>${escape(p)}</p></section>`).join('')}<small style="margin-top:12px">iCash X draft v1 • No signature, deposit, title acceptance or closing is confirmed by this document.</small></body></html>`;
}
