import {finalSalePolicy} from './final-sale-policy.ts';
export const membershipTermsVersion='membership-2026-10-10.1';
export const workCreditTermsVersion='work-credits-2026-10-10.1';
export const workCreditTerms='This is a one-time purchase of prepaid work credits. I authorize my bot to start automatically and use these credits for eligible AI work after payment. By default, up to 50% of available credits may be used each day when eligible work exists. I can explicitly allow more spending from my existing balance for that day. No daily charge is authorized. Automatic refill is optional and requires separate authorization. New work stops when available credits are insufficient. Existing account, contact, provider, pricing and spending checks still apply. Credits may be used without a lead, contract, closing or income. Unused credits remain on my account.'+' '+finalSalePolicy;
export type MembershipOffer={revision:number;priceCents:number;interval:'month';enabled:boolean};
export function validOffer(value:MembershipOffer){return Number.isSafeInteger(value.revision)&&value.revision>0&&Number.isSafeInteger(value.priceCents)&&value.priceCents>=100&&value.priceCents<=100000&&value.interval==='month'&&typeof value.enabled==='boolean';}
export const priceLabel=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:cents%100?2:0}).format(cents/100);
export function membershipTerms(cents:number){return `I authorize ${priceLabel(cents)} per month for iCash X software access, renewing monthly until I cancel. This subscription includes $0 in work credits. Property research, calls, texts and other paid AI work use separately purchased prepaid credits. Cancelling immediately ends access and stops new bot work and future monthly renewals. Unused credits stay on my account and can be used with an active subscription. Work already sent to a provider may finish and settle. Live work depends on setup and available services. No deal or income is guaranteed. ${finalSalePolicy}`;}
export function membershipAccessible(m:{state:string;paid_through:string|null}|null,now=Date.now()){return !!m&&m.state==='active'&&!!m.paid_through&&Date.parse(m.paid_through)>now;}
