import {createRecordingProviders,boundedBytes,type RecordingEnv} from './required-call-recording-provider.ts';
import {object} from './required-call-recording.ts';
export function createOwnerRecordingProviders(env:RecordingEnv,fetcher:typeof fetch=fetch){
 const common=createRecordingProviders(env,fetcher);
 async function eleven(path:string){const url='https://api.elevenlabs.io'+path;const r=await fetcher(url,{headers:{'xi-api-key':env.ELEVENLABS_API_KEY??''},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(8000)});if(!r.ok||r.redirected||(r.url&&r.url!==url))throw Error('OWNER_PROVIDER_READ_REQUIRED');return object(JSON.parse((await boundedBytes(r,262144)).toString()));}
 async function callerId(from:string){
  if(from!==env.CONTIGUITY_FROM||from!=='+14243948384')throw Error('OWNER_FIXED_CALLER_REQUIRED');
  const account=env.TWILIO_ACCOUNT_SID;
  async function read(kind:string){const url=`https://api.twilio.com/2010-04-01/Accounts/${account}/${kind}.json?PhoneNumber=${encodeURIComponent(from)}&PageSize=100`;const response=await fetcher(url,{headers:{Authorization:'Basic '+Buffer.from(account+':'+env.TWILIO_AUTH_TOKEN).toString('base64')},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(8000)});if(!response.ok||response.redirected||(response.url&&response.url!==url))throw Error('OWNER_CALLER_READ_REQUIRED');return object(JSON.parse((await boundedBytes(response,262144)).toString()));}
  const owned=await read('IncomingPhoneNumbers');if(Array.isArray(owned.incoming_phone_numbers)&&owned.incoming_phone_numbers.some(x=>{const p=object(x);return p.account_sid===account&&p.phone_number===from&&object(p.capabilities).voice===true;}))return {usable:true,source:'owned_voice_number'};
  const verified=await read('OutgoingCallerIds');return {usable:Array.isArray(verified.outgoing_caller_ids)&&verified.outgoing_caller_ids.some(x=>{const p=object(x);return p.account_sid===account&&p.phone_number===from;}),source:'verified_caller_id'};
 }
 return {...common,callerId,voicePrice:async(to:string,from:string)=>{const url='https://pricing.twilio.com/v2/Voice/Numbers/'+encodeURIComponent(to)+'?OriginationNumber='+encodeURIComponent(from);const r=await fetcher(url,{headers:{Authorization:'Basic '+Buffer.from(env.TWILIO_ACCOUNT_SID+':'+env.TWILIO_AUTH_TOKEN).toString('base64')},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(8000)});if(!r.ok||r.redirected||(r.url&&r.url!==url))throw Error('OWNER_CURRENT_PRICE_REQUIRED');return object(JSON.parse((await boundedBytes(r,262144)).toString()));},branch:(agent:string,branch:string)=>eleven(`/v1/convai/agents/${encodeURIComponent(agent)}/branches/${encodeURIComponent(branch)}`),phone:(id:string)=>eleven('/v1/convai/phone-numbers/'+encodeURIComponent(id)),
  dial60:async(from:string,to:string,twiml:string,callback:string)=>{const url=`https://api.twilio.com/2010-04-01/Accounts/${env.TWILIO_ACCOUNT_SID}/Calls.json`;const r=await fetcher(url,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(env.TWILIO_ACCOUNT_SID+':'+env.TWILIO_AUTH_TOKEN).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({From:from,To:to,Twiml:twiml,Record:'false',TimeLimit:'60',Timeout:'20',StatusCallback:callback,StatusCallbackMethod:'POST',StatusCallbackEvent:'completed'}),cache:'no-store',redirect:'error',signal:AbortSignal.timeout(8000)});if(!r.ok||r.redirected||(r.url&&r.url!==url))throw Error('OWNER_DIAL_OUTCOME_UNKNOWN');return object(JSON.parse((await boundedBytes(r,262144)).toString()));}
 };
}
export type OwnerRecordingProviders=ReturnType<typeof createOwnerRecordingProviders>;
