import {object,canonical,sha,sid,uuid,recordingBaseUrl,type RecordingRow,type RecordingReview} from './required-call-recording.ts';
import {receptionWorkflowIsInert} from './general-reception.ts';
export const ownerRecordingBase='https://www.geticashx.com/api/internal/voice/owner-recording-test';
export const ownerRecordingConfirmation='Call my configured phone once, up to 60 seconds, within my remaining 3-call/$3 provider test budget';
export type OwnerRecordingConfig={id:number;account_id:string;owner_user_id:string;phone:string;from_phone:string;phone_number_id:string;review:Record<string,unknown>;quote:Record<string,unknown>;enabled:boolean;expires_at:string;prior_attempts:number;prior_spend_micros:number;[key:string]:unknown};
export type OwnerRecordingRun={id:string;account_id:string;owner_user_id:string;configuration:OwnerRecordingConfig;attempt:number;row_version:number;state:string;created_at:string;nonce_hash:string;stop_token_hash:string;reserved_micros:number;call_sid:string|null;call_started_at:string|null;recording_sid:string|null;conversation_id:string|null;consent_at:string|null;start_claimed_at:string|null;registration_claimed_at:string|null;provider_started_at:string|null;audio_expires_at:string|null;duration_seconds:number|null;recording_price_micros:number|null;end_requested_at:string|null;call_ended_at:string|null;deleted_at:string|null;settled_micros:number|null;settlement:Record<string,unknown>|null;[key:string]:unknown};
const empty=(x:unknown)=>x==null||Array.isArray(x)&&!x.length||typeof x==='object'&&!Object.keys(object(x)).length;
export function ownerRecordingReview(c:OwnerRecordingConfig,agentInput:unknown,branchInput:unknown,phoneInput:unknown,toolInput:unknown,from:string|undefined,accountSid:string|undefined,now=Date.now()){
 const a=object(agentInput),b=object(branchInput),phone=object(phoneInput),tool=object(toolInput),r=c.review,config=object(a.conversation_config),platform=object(a.platform_settings),p=object(object(config.agent).prompt),over=object(object(platform.overrides).conversation_config_override),api=object(object(tool.tool_config).api_schema),body=object(api.request_body_schema),headers=object(api.request_headers),quote=c.quote;
 const quoteFields=['elevenlabsAllowanceMicrosPerMinute','voiceMaxMicrosPerMinute','streamMicrosPerMinute','speechGatherMicros','recordingMicrosPerMinute','storageMicrosPerMinuteMonth','maxAttemptMicros'];
 const numbers=quoteFields.every(k=>Number.isSafeInteger(quote[k])&&Number(quote[k])>=0);
 const bound=numbers?Number(quote.elevenlabsAllowanceMicrosPerMinute)+Number(quote.voiceMaxMicrosPerMinute)+Number(quote.streamMicrosPerMinute)+20000+2500+536:Infinity;
 const snapshot={conversation_config:a.conversation_config,platform_settings:a.platform_settings,workflow:a.workflow??null,procedures:a.procedures??null};
 const checks={ownerBinding:uuid(c.account_id)&&uuid(c.owner_user_id)&&/^\+[1-9]\d{7,14}$/.test(c.phone)&&c.phone.endsWith('5280'),activeReview:c.enabled===true&&Date.parse(c.expires_at)>now&&Date.parse(String(r.reviewedAt))<=now&&Date.parse(String(r.reviewedUntil))>now,
  agent:a.agent_id===r.agentId&&a.branch_id===r.branchId&&a.version_id===r.versionId&&a.main_branch_id!==r.branchId,branch:b.id===r.branchId&&b.agent_id===r.agentId&&b.is_archived===false&&b.current_live_percentage===0,
  hash:sha(JSON.stringify(canonical(snapshot)))===r.configHash,sixtySeconds:object(config.conversation).max_duration_seconds===60,audio:object(config.asr).user_input_audio_format==='ulaw_8000'&&object(config.tts).agent_output_audio_format==='ulaw_8000',
  privacy:object(platform.privacy).record_voice===false&&object(platform.auth).enable_auth===true,capacity:object(platform.call_limits).bursting_enabled===false&&object(platform.queueing_config).enabled===false,
  overrides:object(over.conversation).max_duration_seconds===true&&object(over.agent).first_message===true&&object(object(over.agent).prompt).prompt===true,
  onlyStopTool:Array.isArray(p.tool_ids)&&p.tool_ids.length===1&&p.tool_ids[0]===r.stopToolId&&empty(p.tools)&&(empty(p.built_in_tools)||p.built_in_tools!==null&&typeof p.built_in_tools==='object'&&!Array.isArray(p.built_in_tools)&&Object.values(object(p.built_in_tools)).every(v=>v===null)),noActions:empty(p.mcp_server_ids)&&empty(p.native_mcp_server_ids)&&empty(p.knowledge_base)&&empty(p.custom_llm)&&empty(a.procedures)&&receptionWorkflowIsInert(a.workflow)&&empty(config.language_presets),
  noExtraCopies:object(object(platform.workspace_overrides).webhooks).send_audio!==true,
  stopTool:tool.id===r.stopToolId&&object(tool.tool_config).type==='webhook'&&object(tool.tool_config).name==='icash_stop_recording'&&api.url===recordingBaseUrl+'/stop'&&api.method==='POST'&&JSON.stringify(object(headers.Authorization))===JSON.stringify({variable_name:'secret__icash_recording_stop_token'})&&Object.keys(headers).length===1&&body.type==='object'&&JSON.stringify(body.required)==='["recordingId"]'&&Object.keys(object(body.properties)).length===1&&object(object(body.properties).recordingId).type==='string'&&object(object(body.properties).recordingId).dynamic_variable==='icash_recording_id'&&empty(api.auth_connection)&&empty(tool.response_mocks),
  caller:phone.phone_number_id===c.phone_number_id&&phone.provider==='twilio'&&phone.phone_number===from&&c.from_phone===from&&r.fromPhone===from&&sid(accountSid,'AC')&&r.providerAccountSid===accountSid,
  budget:numbers&&bound<=Number(quote.maxAttemptMicros)&&Number(quote.maxAttemptMicros)<=1000000&&quote.speechGatherMicros===20000&&quote.recordingMicrosPerMinute===2500&&quote.storageMicrosPerMinuteMonth===500&&Date.parse(String(quote.reviewedAt))<=now&&Date.parse(String(quote.validUntil))>now&&typeof quote.evidenceRef==='string'&&quote.evidenceRef.length>=12,
  identity:typeof r.principal==='string'&&r.principal.length>0&&r.principal.length<=160&&typeof r.assistantName==='string'&&r.assistantName.length>0&&r.assistantName.length<=160};
 return {ready:Object.values(checks).every(Boolean),checks,observed:{agentId:a.agent_id,branchId:a.branch_id,versionId:a.version_id,configHash:sha(JSON.stringify(canonical(snapshot))),stopToolId:tool.id,modelId:p.llm,voiceId:object(config.tts).voice_id,stopToolHash:sha(JSON.stringify(canonical(tool))),maxDurationSeconds:object(config.conversation).max_duration_seconds}};
}
export function ownerProviderRow(r:OwnerRecordingRun):RecordingRow{return {id:r.id,account_id:r.account_id,operation_key:'owner-recorded:'+r.id,provider_account_sid:String(r.configuration.review.providerAccountSid),call_sid:r.call_sid,recording_sid:r.recording_sid,conversation_id:r.conversation_id,state:r.state as RecordingRow['state'],nonce_hash:r.nonce_hash,stop_token_hash:r.stop_token_hash,disclosure_version:'owner-recorded-60s-v1',consent_at:r.consent_at,consent_evidence:null,start_claimed_at:r.start_claimed_at,provider_started_at:r.provider_started_at,ended_at:null,duration_seconds:r.duration_seconds,audio_expires_at:r.audio_expires_at,deleted_at:r.deleted_at,provider_recording_price_micros:r.recording_price_micros,price_is_estimate:true,pricing_policy:{},to_phone:r.configuration.phone,from_phone:r.configuration.from_phone,contact_key:'owner-only',agent_id:String(r.configuration.review.agentId),branch_id:String(r.configuration.review.branchId),version_id:String(r.configuration.review.versionId),max_total_seconds:60,rate_id:'owner-no-customer-rate',charge_cap_cents:0,created_at:r.created_at,call_context:{principal:r.configuration.review.principal,assistantName:r.configuration.review.assistantName,firstMessage:'Thanks. This is our short private phone check. Can you hear me clearly?',prompt:'You are the disclosed AI assistant speaking with your own account owner for a brief phone acceptance test. Keep it casual and brief. Check that they can hear you and have a natural short conversation. Do not discuss business contacts, make offers, schedule calls or use business tools. If permission is withdrawn, another person joins, or anything is unclear, call icash_stop_recording immediately and stop talking. Never claim a confirmed hangup until callEnded is true. The call must end within 60 seconds of answer.'}};}
export function asProviderReview(c:OwnerRecordingConfig){return c.review as unknown as RecordingReview;}
