import {createHash,createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
import {boundedBody,receptionTarget,receptionUrl} from './general-reception.ts';
import {ownerInboundTarget} from './owner-inbound-acceptance.ts';
import {readOwnerForwarding,OwnerForwardingError} from './owner-forwarding-readiness.ts';

// One fixed enable operation, using existing credentials. No lease purchase,
// payment, credit, key creation, outbound call, disable operation or replay.
// https://docs.contiguity.com/api-reference/product/leases/call-forwarding-enable
const source=ownerInboundTarget.sourceNumber,destination=receptionTarget.calledNumber;
const forwardingUrl=`https://api.contiguity.com/numbers/lease/${encodeURIComponent(source)}/call_forwarding`;
const fallbackUrl='https://www.geticashx.com/api/reception/fallback';
type Obj=Record<string,unknown>;
export type ReceptionForwardingEnv={CONTIGUITY_API_KEY?:string;CONTIGUITY_FROM?:string;TWILIO_ACCOUNT_SID?:string;TWILIO_AUTH_TOKEN?:string;ELEVENLABS_INBOUND_WEBHOOK_SECRET?:string};
export type ReceptionForwardingDeps={rpc:(name:string,body?:Obj)=>Promise<unknown>;fetcher?:typeof fetch;now?:()=>number};
type Forwarding=Awaited<ReturnType<typeof readOwnerForwarding>>;
export type ReceptionForwardingReview={status:'review'|'blocked'|'pending'|'active'|'outcome_unknown';message:string;checks:Record<string,boolean>;forwarding?:{enabled:boolean;destinationMatches:boolean;providerStatus:'active'|'queued';estimatedCompletion:number|null};reviewToken?:string;expiresAt?:string;checkedAt:string;forwardingCostVerified:false};
const obj=(v:unknown):Obj=>v!==null&&typeof v==='object'&&!Array.isArray(v)?v as Obj:{};
const secret=(v:unknown):v is string=>typeof v==='string'&&v.length>=20&&v.length<=4096&&/^[\x21-\x7e]+$/.test(v);
const stable=(v:unknown):string=>Array.isArray(v)?'['+v.map(stable).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(obj(v)[k])).join(',')+'}':JSON.stringify(v)??'null';
const digest=(v:unknown)=>createHash('sha256').update(stable(v)).digest('hex');
function fail(code='readiness_unavailable'):never{throw Error(code);}
function result(deps:ReceptionForwardingDeps,status:ReceptionForwardingReview['status'],message:string,extra:Partial<ReceptionForwardingReview>={}):ReceptionForwardingReview{return {status,message,checks:{},checkedAt:new Date(deps.now?.()??Date.now()).toISOString(),forwardingCostVerified:false,...extra};}
function environment(env:ReceptionForwardingEnv){if(typeof window!=='undefined'||env.CONTIGUITY_FROM!==source||(typeof env.CONTIGUITY_API_KEY!=='string'||!env.CONTIGUITY_API_KEY.length||env.CONTIGUITY_API_KEY.length>4096||! /^[\x21-\x7e]+$/.test(env.CONTIGUITY_API_KEY))||!secret(env.ELEVENLABS_INBOUND_WEBHOOK_SECRET)||!secret(env.TWILIO_AUTH_TOKEN)||!/^AC[a-fA-F0-9]{32}$/.test(env.TWILIO_ACCOUNT_SID??''))fail('configuration_unavailable');}
function commercial(value:unknown,depth=0):boolean{if(depth>6)return true;if(Array.isArray(value))return value.length>100||value.some(v=>commercial(v,depth+1));if(value!==null&&typeof value==='object')return Object.entries(value).some(([key,v])=>/fee|charge|price|cost|amount|currency|subscription|quote|payment|purchase|terms|billing|credits|checkout|consent/i.test(key)||commercial(v,depth+1));return false;}
async function json(response:Response,url:string){if(response.redirected||(response.url&&response.url!==url))fail();if(response.status===402)fail('commercial_confirmation_required');if(!response.ok){await response.body?.cancel().catch(()=>undefined);fail(response.status===401||response.status===403?'provider_access_denied':'provider_unavailable');}if(!/^application\/json(?:;|$)/i.test(response.headers.get('content-type')??''))fail('provider_receipt_invalid');const value=JSON.parse(await boundedBody(response,65536));if(commercial(value))fail('commercial_confirmation_required');return obj(value);}
function transport(env:ReceptionForwardingEnv,deps:ReceptionForwardingDeps){
 const fetcher=deps.fetcher??fetch;let commercialRead=false;
 // Reuse the existing strict GET adapter while rejecting any newly surfaced
 // commercial prerequisites instead of following or paying them.
 const readFetcher:typeof fetch=async(input,init)=>{const url=String(input);if(url!==forwardingUrl||init?.method!=='GET')fail();const response=await fetcher(input,init);if(!response.ok){if(response.status===402){commercialRead=true;fail('commercial_confirmation_required');}return response;}let value:Obj;try{value=await json(response,url);}catch(e){if(e instanceof Error&&e.message==='commercial_confirmation_required')commercialRead=true;throw e;}return Response.json(value);};
 return {read:async()=>{try{return await readOwnerForwarding(env,readFetcher);}catch(e){if(commercialRead)fail('commercial_confirmation_required');throw e;}},enable:async()=>{
  const url=forwardingUrl+'/enable',r=await fetcher(url,{method:'POST',headers:{Authorization:'Bearer '+env.CONTIGUITY_API_KEY,Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({to:destination}),cache:'no-store',redirect:'error',credentials:'omit',signal:AbortSignal.timeout(8000)}),value=await json(r,url),data=obj(value.data),f=obj(data.call_forwarding);
  if(value.object!=='response'||Object.keys(value).some(k=>!['id','timestamp','api_version','object','data'].includes(k))||Object.keys(data).sort().join(',')!=='call_forwarding,number'||data.number!==source||Object.keys(f).sort().join(',')!=='enabled,estimated_completion,status,to'||f.enabled!==true||f.to!==destination||!['active','queued'].includes(String(f.status))||(f.status==='active'?f.estimated_completion!==null:!Number.isSafeInteger(f.estimated_completion)||Number(f.estimated_completion)<0))fail('provider_receipt_invalid');
  return {enabled:true,to:destination,status:f.status as 'active'|'queued'};
 }};
}
async function snapshot(env:ReceptionForwardingEnv,deps:ReceptionForwardingDeps){
 environment(env);const [configInput,stateInput]=await Promise.all([deps.rpc('icash_get_general_reception_config'),deps.rpc('icash_get_reception_forwarding')]),config=obj(configInput),state=obj(stateInput);
 if(config.account_id!==receptionTarget.accountId||config.owner_user_id!==receptionTarget.ownerUserId||config.called_number!==destination||config.enabled!==true||state.schema_version!==1||state.attempt!==null&&(!state.attempt||typeof state.attempt!=='object'||Array.isArray(state.attempt)))fail('configuration_unavailable');
 const forwarding=await transport(env,deps).read();
 const url=`https://api.twilio.com/2010-04-01/Accounts/${env.TWILIO_ACCOUNT_SID}/IncomingPhoneNumbers.json?PhoneNumber=${encodeURIComponent(destination)}&PageSize=2`;
 const response=await(deps.fetcher??fetch)(url,{method:'GET',headers:{Authorization:'Basic '+Buffer.from(env.TWILIO_ACCOUNT_SID+':'+env.TWILIO_AUTH_TOKEN).toString('base64'),Accept:'application/json'},cache:'no-store',redirect:'error',credentials:'omit',signal:AbortSignal.timeout(8000)});
 if(!response.ok||response.redirected||(response.url&&response.url!==url))fail(response.status===401||response.status===403?'provider_access_denied':'provider_unavailable');if(!/^application\/json(?:;|$)/i.test(response.headers.get('content-type')??''))fail('provider_receipt_invalid');const phoneData=obj(JSON.parse(await boundedBody(response,65536)));if(!Array.isArray(phoneData.incoming_phone_numbers)||phoneData.incoming_phone_numbers.length!==1||phoneData.next_page_uri!==null)fail('provider_receipt_invalid');const phone=obj(phoneData.incoming_phone_numbers[0]);
 const routeVerified=phone.account_sid===env.TWILIO_ACCOUNT_SID&&phone.phone_number===destination&&typeof phone.sid==='string'&&/^PN[a-fA-F0-9]{32}$/.test(phone.sid)&&obj(phone.capabilities).voice===true&&phone.voice_url===receptionUrl&&phone.voice_method==='POST'&&phone.voice_fallback_url===fallbackUrl&&phone.voice_fallback_method==='POST'&&!phone.voice_application_sid&&!phone.trunk_sid;
 const normalizedPhone={sid:phone.sid,account_sid:phone.account_sid,phone_number:phone.phone_number,voice_url:phone.voice_url,voice_method:phone.voice_method,voice_fallback_url:phone.voice_fallback_url,voice_fallback_method:phone.voice_fallback_method,voice_application_sid:phone.voice_application_sid??null,trunk_sid:phone.trunk_sid??null,voice:obj(phone.capabilities).voice};
 const normalizedForwarding={enabled:forwarding.enabled,to:forwarding.destination,status:forwarding.providerStatus,estimated_completion:forwarding.estimatedCompletion};
 return {config,state,forwarding,routeVerified,fingerprint:digest({config,state,phone:normalizedPhone,forwarding:normalizedForwarding})};
}
function ready(s:Awaited<ReturnType<typeof snapshot>>){return s.routeVerified&&s.state.attempt===null&&s.forwarding.enabled===false&&s.forwarding.destination===null&&s.forwarding.providerStatus==='active';}
function visible(f:Forwarding){return {enabled:f.enabled,destinationMatches:f.destination===destination,providerStatus:f.providerStatus,estimatedCompletion:f.estimatedCompletion};}
function sign(raw:string,key:string){return createHmac('sha256',key).update('reception-forwarding-enable-v1\0'+raw).digest('base64url');}
function issue(fingerprint:string,key:string,now:number){const data={v:1,action:'enable_forwarding',fingerprint,nonce:randomBytes(16).toString('hex'),expires:now+120000},raw=Buffer.from(JSON.stringify(data)).toString('base64url');return {reviewToken:raw+'.'+sign(raw,key),expiresAt:new Date(data.expires).toISOString()};}
function verify(raw:unknown,key:string,now:number){if(typeof raw!=='string'||raw.length>2048||!/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{43}$/.test(raw))fail('invalid_review');const [body,signature]=raw.split('.'),expected=sign(body,key);if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))fail('invalid_review');const t=obj(JSON.parse(Buffer.from(body,'base64url').toString()));if(Object.keys(t).sort().join(',')!=='action,expires,fingerprint,nonce,v'||t.v!==1||t.action!=='enable_forwarding'||typeof t.fingerprint!=='string'||!/^[a-f0-9]{64}$/.test(t.fingerprint)||typeof t.nonce!=='string'||!/^[a-f0-9]{32}$/.test(t.nonce)||!Number.isSafeInteger(t.expires)||Number(t.expires)<=now||Number(t.expires)>now+120000)fail('invalid_review');return t as {fingerprint:string;nonce:string;expires:number};}
function message(error:unknown){const code=error instanceof OwnerForwardingError?error.code:error instanceof Error?error.message:'';return code==='commercial_confirmation_required'?'The provider returned a fee, payment or terms requirement. Separate approval is needed.':code==='provider_access_denied'||code==='provider_auth_failed'?'Provider access was denied. No alternate credential or retry was used.':'Forwarding readiness could not be verified.';}
export async function reviewReceptionForwarding(env:ReceptionForwardingEnv,deps:ReceptionForwardingDeps):Promise<ReceptionForwardingReview>{try{const s=await snapshot(env,deps),checks={receptionEnabled:true,twilioRouteVerified:s.routeVerified,noPriorAttempt:s.state.attempt===null,forwardingDisabled:s.forwarding.enabled===false,providerChangeSettled:s.forwarding.providerStatus==='active'},extra={checks,forwarding:visible(s.forwarding)};
 if(s.forwarding.routeConfigured&&s.routeVerified)return result(deps,'active','The fixed forwarding destination is active in provider read-back. A real forwarded call has not been verified here.',extra);
 if(s.forwarding.providerStatus==='queued')return result(deps,'pending','The provider change is queued. Forwarding is not yet verified active; refresh read-only status.',extra);
 if(!ready(s))return result(deps,'blocked','The fixed change is not ready or a prior attempt is held. Do not repeat the enable request.',extra);
 return result(deps,'review','Enable forwarding from the fixed leased number to the verified reception entry point. Future forwarding usage costs remain unverified.',{...extra,...issue(s.fingerprint,env.ELEVENLABS_INBOUND_WEBHOOK_SECRET!,deps.now?.()??Date.now())});
 }catch(e){return result(deps,'blocked',message(e));}}
export async function applyReceptionForwarding(env:ReceptionForwardingEnv,deps:ReceptionForwardingDeps,reviewToken:unknown):Promise<ReceptionForwardingReview>{let dispatched=false;try{environment(env);const t=verify(reviewToken,env.ELEVENLABS_INBOUND_WEBHOOK_SECRET!,deps.now?.()??Date.now()),s=await snapshot(env,deps);if(!ready(s)||s.fingerprint!==t.fingerprint||(deps.now?.()??Date.now())>=t.expires)fail('invalid_review');if(await deps.rpc('icash_claim_reception_forwarding',{p_nonce:t.nonce,p_fingerprint:t.fingerprint,p_original_setting:{enabled:false,to:null}})!==true)fail('claim_denied');dispatched=true;
 const api=transport(env,deps),receipt=await api.enable(),after=await snapshot(env,deps),actual=after.forwarding;if(!after.routeVerified||stable(after.config)!==stable(s.config)||!actual.enabled||actual.destination!==destination)fail('provider_receipt_invalid');const pending=receipt.status==='queued'||actual.providerStatus==='queued';
 if(await deps.rpc('icash_complete_reception_forwarding',{p_nonce:t.nonce,p_fingerprint:t.fingerprint,p_result:{enabled:true,to:destination,status:receipt.status}})!==true)fail('completion_unavailable');
 return result(deps,pending?'pending':'active',pending?'The provider accepted the change, but it is queued. Refresh read-only status; do not repeat the request.':'The fixed forwarding destination is active in provider read-back. A real forwarded call has not been verified here.',{checks:{twilioRouteVerified:true,noPriorAttempt:false},forwarding:visible(actual)});
 }catch(e){return result(deps,dispatched?'outcome_unknown':'blocked',dispatched?message(e)+' The durable attempt remains held. Use read-only refresh; do not repeat the request.':message(e));}}
