import {accountMembership} from '@/lib/membership';
import {membershipAccessible} from '@/lib/membership-policy';
import {db} from '@/lib/stripe-test';
import {fundingMode} from '@/lib/funding-policy';
import {launchReadiness} from '@/lib/launch-readiness';
import type {SupportEvidence} from './support-policy';
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const validCents=(value:number)=>Number.isSafeInteger(value)&&value>=0;
const readinessLabels:Record<string,string>={dataProvider:'Property data access needs attention',voiceProvider:'Calling service access needs attention',emailAccess:'Email access needs attention',billing:'Billing configuration needs attention',cashReserve:'Operating reserve check needs attention',discovery:'Property search configuration needs attention',voice:'Calling configuration needs attention',productionContracts:'Production contract configuration needs review',unresolvedDispatches:'A provider action has an uncertain outcome',readiness_unavailable:'Readiness could not be checked'};
/** Fixed, tenant-bound reads only. Never return raw logs, provider payloads, credentials or another account. */
export async function collectSupportDiagnostics(accountId:string):Promise<SupportEvidence[]>{
 const observedAt=new Date().toISOString();
 const check=async(key:string,source:string,fn:()=>Promise<Omit<SupportEvidence,'key'|'source'|'observedAt'>>):Promise<SupportEvidence>=>{
  try{return {key,source,observedAt,...await fn()};}catch{return {key,source,observedAt,status:'unknown',detail:`The ${key} check is temporarily unavailable. Nothing was changed.`};}
 };
 return Promise.all([
  check('work','icash_accounts',async()=>{const [a]=await db<{bot_paused:boolean}[]>(`icash_accounts?id=eq.${accountId}&select=bot_paused`);if(!a||typeof a.bot_paused!=='boolean')throw Error();return {code:a.bot_paused?'paused':'not_paused',status:a.bot_paused?'attention':'ok',detail:a.bot_paused?'Your bot is paused. New automated work is stopped; previously authorized work may still finish. The pause flag alone does not tell us why it was paused.':'Your bot is not paused. Other safety and readiness checks still apply.'};}),
  check('credits','icash_wallets',async()=>{const [w]=await db<{balance_cents:number;reserved_cents:number}[]>(`icash_wallets?account_id=eq.${accountId}&select=balance_cents,reserved_cents`);if(!w)throw Error();if(!validCents(w.balance_cents)||!validCents(w.reserved_cents)||w.reserved_cents>w.balance_cents)throw Error();const available=w.balance_cents-w.reserved_cents;return {code:available>0?'credit_available':'no_available_credit',status:available>0?'ok':'attention',detail:`The live-work wallet has ${money(available)} available and ${money(w.reserved_cents)} held for work already reserved. Test checkout credit is separate. This is credit, not a bank balance or refund amount.`};}),
  check('billing','icash_daily_plans',async()=>{const mode=fundingMode();if(!mode)throw Error('MODE_UNAVAILABLE');const plans=await db<{state:string}[]>(`icash_daily_plans?account_id=eq.${accountId}&mode=eq.${mode}&state=neq.stopped&select=state&limit=21`);if(plans.length>20||plans.some(p=>!['active','stop_requested','payment_failed','pending'].includes(p.state)))throw Error();const stopping=plans.some(p=>p.state==='stop_requested'),failed=plans.some(p=>p.state==='payment_failed');const active=plans.some(p=>p.state==='active');return {code:stopping?'renewal_stop_unconfirmed':failed?'renewal_payment_failed':active?'renewal_active':plans.length?'checkout_pending':'no_renewals',status:stopping||failed||plans.length&&!active?'attention':'ok',detail:stopping?'A stop request is saved, but daily billing cancellation is not yet confirmed. The team should review it.':failed?'A daily plan has a payment issue and needs review.':active?`A ${mode} daily renewal plan is recorded as active in this environment. Review cancellation below to stop future renewals.`:plans.length?'A daily checkout is pending. A pending checkout is not proof of payment.':`No ongoing ${mode} daily renewal plan was found in this environment. This does not refund earlier charges.`};}),
  check('subscription','icash_memberships',async()=>{const m=await accountMembership(accountId);if(!m)return {code:'no_software_subscription',status:'ok',detail:'No software subscription is linked to this account in this billing environment.'};const active=membershipAccessible(m);return {code:m.cancel_at_period_end||m.state==='cancelled'?'software_renewals_stopped':active?'renewal_active':'renewal_payment_failed',status:active||m.state==='cancelled'?'ok':'attention',detail:`Software access is ${money(m.price_cents)}/month; work credits are separate. ${m.cancel_at_period_end||m.state==='cancelled'?'Future software renewals are cancelled.':active?'The software subscription is active. Review cancellation to stop future renewals.':'The software subscription needs attention. Open software subscription settings.'} ${m.paid_through?'Paid access is recorded through '+new Date(m.paid_through).toLocaleDateString('en-US',{timeZone:'UTC'})+'.':''}`};}),
  check('payments','icash_funding_orders',async()=>{
   const mode=fundingMode();if(!mode)throw Error('MODE_UNAVAILABLE');
   const rows=await db<{state:string;price_cents:number;credit_cents:number;credited_at:string|null;paid_at:string|null}[]>(`icash_funding_orders?account_id=eq.${accountId}&mode=eq.${mode}&select=state,price_cents,credit_cents,credited_at,paid_at&order=created_at.desc&limit=20`);
   if(rows.some(p=>!['pending','paid','expired'].includes(p.state)))throw Error();
   const paid=rows.filter(p=>p.state==='paid'),uncredited=paid.filter(p=>!p.credited_at),latest=paid[0];
   if(paid.some(p=>!validCents(p.price_cents)||!validCents(p.credit_cents)))throw Error();
   const recorded=latest?`The latest recorded ${mode} payment in the 20 most recent funding records has a ${money(latest.price_cents)} base price and ${money(latest.credit_cents)} credit allocation. This is not a bank statement or a full charge/refund history. `:'';
   if(uncredited.length)return {code:'payment_uncredited',status:'attention',detail:recorded+`${uncredited.length} recorded paid ${mode} payment(s) in this recent window have not been marked as credited. No payment was retried.`};
   if(rows.some(p=>p.state==='pending'))return {code:'checkout_pending',status:'attention',detail:recorded+`A ${mode} checkout is pending. Pending is not confirmation of payment, failure, or cancellation.`};
   if(latest)return {code:'payment_recorded',status:'ok',detail:recorded+(mode==='test'?'Test payments do not fund the live-work wallet.':'The recent paid records are marked as credited. Available credit can be lower because of work costs or reservations.')};
   return {code:'no_payment_records',status:'ok',detail:`No paid ${mode} funding record was found in the 20 most recent records for this signed-in account. A payment made under another sign-in or not yet linked may not appear here.`};
  }),
  check('screening','icash_screening_jobs',async()=>{const rows=await db<{state:string}[]>(`icash_screening_jobs?account_id=eq.${accountId}&state=eq.failed&select=state&limit=20`);return {code:rows.length?'screening_review':'screening_clear',status:rows.length?'attention':'ok',detail:rows.length?`${rows.length}${rows.length===20?'+':''} property screening results need review. No work was restarted.`:'No failed property screening results were found in this check.'};}),
  check('voice','icash_live_conversations',async()=>{const rows=await db<{state:string}[]>(`icash_live_conversations?account_id=eq.${accountId}&state=eq.review&select=state&limit=20`);return {code:rows.length?'voice_review':'voice_clear',status:rows.length?'attention':'ok',detail:rows.length?`${rows.length}${rows.length===20?'+':''} call results need review. Chat will not redial or repeat provider actions.`:'No call results marked for review were found.'};}),
  check('readiness','icash_launch_checks',async()=>{const r=await launchReadiness(accountId);return {code:r.ready?'readiness_ready':'readiness_blocked',status:r.ready?'ok':r.blockers.includes('readiness_unavailable')?'unknown':'attention',detail:r.ready?'The launch-readiness check passed. This does not guarantee individual outreach or a completed deal.':`Readiness needs attention: ${r.blockers.map(b=>readinessLabels[b]??'An operational safety check needs review').join('; ')}.`};}),
 ]);
}
/** Owner-only deployment health. Fixed endpoint and server configuration, never model-controlled URLs. */
export async function supportDeploymentHealth(fetcher:typeof fetch=fetch){
 const token=process.env.ICASH_SUPPORT_VERCEL_TOKEN,project=process.env.VERCEL_PROJECT_ID;
 if(!token||!project)return {status:'unavailable',detail:'Vercel read-only diagnostics are not configured.'};
 const query=new URLSearchParams({projectId:project,target:'production',limit:'1'});if(process.env.VERCEL_TEAM_ID)query.set('teamId',process.env.VERCEL_TEAM_ID);
 try{
  const r=await fetcher(`https://api.vercel.com/v6/deployments?${query}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error();
  const data=await r.json();const d=data.deployments?.[0];if(!d)throw Error();
  const state=['READY','ERROR','BUILDING','QUEUED','CANCELED','INITIALIZING'].includes(d.state)?d.state:'UNKNOWN';
  return {status:state,detail:`Latest production deployment: ${state}. This is deployment health, not proof that every request succeeded.`,deploymentId:typeof d.uid==='string'?d.uid:null,errorCode:typeof d.errorCode==='string'&&/^[A-Z0-9_]{1,100}$/.test(d.errorCode)?d.errorCode:null};
 }catch{return {status:'unavailable',detail:'Vercel health could not be verified. No deployment changes were attempted.'};}
}
