'use client';
import {useEffect,useRef,useState} from 'react';
import type {OwnerReplyInspection} from '../../lib/owner-call-reply-inspector';
const ownerRecordingConfirmation='Call my configured phone once, up to 60 seconds, within my remaining 3-call/$3 provider test budget';
type Run={id:string;attempt:number;state:string;callSid?:string|null;recordingSid?:string|null;conversationId?:string|null;durationSeconds:number|null;reservedMicros?:number;callEnded:boolean;audioExpiresAt:string|null;deletedAt:string|null;error?:string;settlement?:{totalMicros:number;items:{provider:string;label:string;micros:number;basis:string}[]}|null};
type Status={ready:boolean;reason?:string;checks?:Record<string,boolean>;observed?:Record<string,string|number>;phoneEnding?:string;priorAttempts?:number;priorSpendMicros?:number;remainingAttempts?:number;remainingBudgetMicros?:number;runs?:Run[]};
export default function OwnerRecordingCheck(){const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false);const controller=useRef<AbortController|null>(null),mounted=useRef(true),inFlight=useRef(false);
 const refresh=async()=>{if(!mounted.current)return;controller.current?.abort();const c=new AbortController();controller.current=c;try{const response=await fetch('/api/owner-recording-test',{cache:'no-store',signal:c.signal});if(!response.ok)throw Error('Private owner check is unavailable. Sign in to the configured owner account.');const s=await response.json();if(!c.signal.aborted)setStatus(s);}catch(e){if(!c.signal.aborted)setMessage(e instanceof Error?e.message:'Check unavailable');}};
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;controller.current?.abort();};},[]);
 const start=async()=>{if(inFlight.current||!confirmed||!status?.ready)return;inFlight.current=true;setBusy(true);try{const r=await fetch('/api/owner-recording-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation:ownerRecordingConfirmation})});const x=await r.json();if(mounted.current){setMessage(String(x.status));setConfirmed(false);await refresh();}}catch{if(mounted.current){setMessage('The outcome is unknown. Refresh status before any new attempt.');setStatus(s=>s?{...s,ready:false}:s);}}finally{inFlight.current=false;if(mounted.current)setBusy(false);}};
 return <main className="mx-auto max-w-2xl space-y-5 p-6"><h1 className="text-2xl font-semibold">Private recorded phone check</h1><p>Owner phone ending {status?.phoneEnding??'5280'}. Up to 60 seconds per call, at most 3 calls and $3 total Twilio/ElevenLabs test costs. No customer-wallet charge.</p>{status?.remainingAttempts!==undefined&&<p>{status.remainingAttempts} attempts remaining. ${((status.remainingBudgetMicros??0)/1000000).toFixed(2)} uncommitted provider budget. Unknown calls keep their allowance reserved.</p>}<p>The call asks permission before recording. No or silence ends it. Withdrawal ends the whole call. Audio is private for 30 days; transcript retention is separate.</p><button onClick={()=>void refresh()} disabled={busy} className="rounded border px-4 py-2">Refresh checks</button><p role="status">{message||status?.reason||(!status?'Checking…':status.ready?'Preflight passed.':'Setup or allowance is held.')}</p>{status?.observed&&<details><summary>Observed provider configuration (read-only)</summary><p>These values are evidence for review. Reading them does not approve or enable a call.</p><dl>{Object.entries(status.observed).map(([k,v])=><div key={k}><dt>{k}</dt><dd className="break-all">{String(v)}</dd></div>)}</dl></details>}{status?.checks&&<ul>{Object.entries(status.checks).filter(([,v])=>!v).map(([k])=><li key={k}>Needs review: {k}</li>)}</ul>}<label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Call my configured phone once within this remaining test allowance.</label><button onClick={()=>void start()} disabled={!status?.ready||!confirmed||busy} className="rounded bg-black px-4 py-2 text-white disabled:opacity-40">{busy?'Starting once…':'Start one phone check'}</button>{status?.runs?.map(r=><section key={r.id} className="space-y-2 rounded border p-4"><h2>Attempt {r.attempt}: {r.state}</h2><dl className="break-all"><dt>Carrier receipt</dt><dd>{r.callSid??'Pending'}</dd><dt>Recording receipt</dt><dd>{r.recordingSid??'No recording receipt'}</dd><dt>AI receipt</dt><dd>{r.conversationId??'No verified AI receipt'}</dd></dl><p>{r.callEnded?'Call ended.':'Call termination not yet confirmed.'} Recorded duration: {r.durationSeconds??'pending'} seconds.</p>{r.error&&<p>Needs review: {r.error}</p>}<OwnerReplyInspector runId={r.id} ended={r.callEnded&&!!r.callSid}/>{r.state==='available'&&!r.deletedAt&&r.audioExpiresAt&&Date.parse(r.audioExpiresAt)>Date.now()&&<audio controls preload="none" src={'/api/owner-recording-test/audio?id='+r.id}/>}<p>{r.settlement?'Accounted test cost $'+(r.settlement.totalMicros/1000000).toFixed(4):'Cost evidence pending; '+(Number.isSafeInteger(r.reservedMicros)?'$'+(r.reservedMicros!/1000000).toFixed(2):'the full allowance')+' remains reserved. A later check uses a separate reservation.'}</p>{r.settlement?.items.map((x,i)=><p key={i}>{x.provider} {x.label}: ${(x.micros/1000000).toFixed(4)} ({x.basis})</p>)}</section>)}</main>;
}

const replyReasons:Record<string,string>={
 final_speech_result_found:'One final speech result found.',multiple_final_speech_results:'Multiple final speech results found. Review each event below; none was selected as definitive.',
 no_matching_consent_event:'No matching consent callback was found in the returned events. This does not establish consent or refusal.',
 no_final_speech_result:'No final speech result was found. This does not establish consent or refusal.',
 events_available_after_15_minutes:'Twilio makes these events available 15 minutes after the call ends.',call_not_ended:'The carrier has not confirmed that this call ended.',
 call_end_time_unverified:'The carrier end time could not be verified.',owner_run_unavailable:'This owner test run is unavailable.',
 carrier_binding_unverified:'The carrier receipt did not match this owner test.',event_binding_unverified:'A callback could not be verified against this owner test.',
 pagination_unverified:'The next event page could not be safely verified.',page_limit_reached:'The bounded event-page limit was reached.',provider_page_invalid:'The event page format could not be verified.',
 provider_read_unavailable:'The provider read was unavailable. Any results below are incomplete.',provider_read_not_authorized:'Twilio denied this read. No further provider requests were made.',
 owner_sign_in_required:'Sign in to the configured owner account.',not_released:'Reply inspection is unavailable.',owner_reply_unavailable:'Reply inspection is temporarily unavailable.'
};
export function OwnerReplyInspector({runId,ended}:{runId:string;ended:boolean}){
 const [busy,setBusy]=useState(false),[result,setResult]=useState<OwnerReplyInspection|null>(null),[error,setError]=useState('');
 const controller=useRef<AbortController|null>(null),active=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 const inspect=async()=>{
  if(active.current||!ended)return;active.current=true;setBusy(true);setError('');setResult(null);
  const c=new AbortController();controller.current=c;
  try{
   const response=await fetch('/api/owner-recording-test/reply?id='+encodeURIComponent(runId),{cache:'no-store',signal:AbortSignal.any([c.signal,AbortSignal.timeout(30000)])});
   const data=await response.json();
   if(!mounted.current||c.signal.aborted)return;
   if(!Array.isArray(data.events)){setError(replyReasons[data.reason]??'Reply inspection is unavailable.');return;}
   setResult(data);
  }catch{if(mounted.current&&!c.signal.aborted)setError('Reply inspection could not finish.');}
  finally{active.current=false;if(mounted.current&&!c.signal.aborted)setBusy(false);}
 };
 return <div className="space-y-2 border-t pt-3"><button type="button" onClick={()=>void inspect()} disabled={busy||!ended} className="rounded border px-3 py-2 disabled:opacity-40">{busy?'Reading captured reply…':'Inspect captured reply (read-only)'}</button><p className="text-sm">Read Twilio’s speech-recognition result from this test’s permission prompt. No new call is started.</p>{error&&<p role="status">{error}</p>}{result&&<div aria-live="polite" className="space-y-2"><p>{result.status==='incomplete'?'Incomplete inspection. ':''}{replyReasons[result.reason]??'Reply inspection is unavailable.'}</p><p>{result.pagesRead} event pages read. {result.matchedEvents} matching callbacks; {result.finalEvents} final speech results.</p>{result.events.map((event,index)=><div key={index} className="space-y-1 rounded border p-3"><p>Callback {index+1}{event.partial?' · partial speech field present':''}</p><p className="whitespace-pre-wrap break-words">Captured reply: {event.speechStatus==='present'?event.speech:event.speechStatus==='empty'?'(empty)':event.speechStatus==='invalid'?'(invalid field)':event.speechStatus==='partial'?'(withheld partial result)':'(not provided)'}</p><p>Confidence: {event.confidenceStatus==='valid'?event.confidence:event.confidenceStatus==='empty'?'empty':event.confidenceStatus==='invalid'?'invalid':'not provided'}</p><p>Event time: {event.eventTime??'not provided'} · HTTP response: {event.httpResponse??'not provided'}</p>{event.redacted&&<p>Sensitive-looking text was redacted.</p>}{event.truncated&&<p>The reply was shortened or withheld because of length.</p>}</div>)}</div>}</div>;
}
