'use client';
import {useEffect,useRef,useState} from 'react';
const ownerRecordingConfirmation='Call my configured phone once, up to 60 seconds, within my remaining 3-call/$3 provider test budget';
type Run={id:string;attempt:number;state:string;callSid?:string|null;recordingSid?:string|null;conversationId?:string|null;durationSeconds:number|null;reservedMicros?:number;callEnded:boolean;audioExpiresAt:string|null;deletedAt:string|null;error?:string;settlement?:{totalMicros:number;items:{provider:string;label:string;micros:number;basis:string}[]}|null};
type Status={ready:boolean;reason?:string;checks?:Record<string,boolean>;observed?:Record<string,string|number>;phoneEnding?:string;priorAttempts?:number;priorSpendMicros?:number;remainingAttempts?:number;remainingBudgetMicros?:number;runs?:Run[]};
export default function OwnerRecordingCheck(){const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false);const controller=useRef<AbortController|null>(null),mounted=useRef(true),inFlight=useRef(false);
 const refresh=async()=>{if(!mounted.current)return;controller.current?.abort();const c=new AbortController();controller.current=c;try{const response=await fetch('/api/owner-recording-test',{cache:'no-store',signal:c.signal});if(!response.ok)throw Error('Private owner check is unavailable. Sign in to the configured owner account.');const s=await response.json();if(!c.signal.aborted)setStatus(s);}catch(e){if(!c.signal.aborted)setMessage(e instanceof Error?e.message:'Check unavailable');}};
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;controller.current?.abort();};},[]);
 const start=async()=>{if(inFlight.current||!confirmed||!status?.ready)return;inFlight.current=true;setBusy(true);try{const r=await fetch('/api/owner-recording-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation:ownerRecordingConfirmation})});const x=await r.json();if(mounted.current){setMessage(String(x.status));setConfirmed(false);await refresh();}}catch{if(mounted.current){setMessage('The outcome is unknown. Refresh status before any new attempt.');setStatus(s=>s?{...s,ready:false}:s);}}finally{inFlight.current=false;if(mounted.current)setBusy(false);}};
 return <main className="mx-auto max-w-2xl space-y-5 p-6"><h1 className="text-2xl font-semibold">Private recorded phone check</h1><p>Owner phone ending {status?.phoneEnding??'5280'}. Up to 60 seconds per call, at most 3 calls and $3 total Twilio/ElevenLabs test costs. No customer-wallet charge.</p>{status?.remainingAttempts!==undefined&&<p>{status.remainingAttempts} attempts remaining. ${((status.remainingBudgetMicros??0)/1000000).toFixed(2)} uncommitted provider budget. Unknown calls keep their allowance reserved.</p>}<p>The call asks permission before recording. No or silence ends it. Withdrawal ends the whole call. Audio is private for 30 days; transcript retention is separate.</p><button onClick={()=>void refresh()} disabled={busy} className="rounded border px-4 py-2">Refresh checks</button><p role="status">{message||status?.reason||(!status?'Checking…':status.ready?'Preflight passed.':'Setup or allowance is held.')}</p>{status?.observed&&<details><summary>Observed provider configuration (read-only)</summary><p>These values are evidence for review. Reading them does not approve or enable a call.</p><dl>{Object.entries(status.observed).map(([k,v])=><div key={k}><dt>{k}</dt><dd className="break-all">{String(v)}</dd></div>)}</dl></details>}{status?.checks&&<ul>{Object.entries(status.checks).filter(([,v])=>!v).map(([k])=><li key={k}>Needs review: {k}</li>)}</ul>}<label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Call my configured phone once within this remaining test allowance.</label><button onClick={()=>void start()} disabled={!status?.ready||!confirmed||busy} className="rounded bg-black px-4 py-2 text-white disabled:opacity-40">{busy?'Starting once…':'Start one phone check'}</button>{status?.runs?.map(r=><section key={r.id} className="space-y-2 rounded border p-4"><h2>Attempt {r.attempt}: {r.state}</h2><dl className="break-all"><dt>Carrier receipt</dt><dd>{r.callSid??'Pending'}</dd><dt>Recording receipt</dt><dd>{r.recordingSid??'No recording receipt'}</dd><dt>AI receipt</dt><dd>{r.conversationId??'No verified AI receipt'}</dd></dl><p>{r.callEnded?'Call ended.':'Call termination not yet confirmed.'} Recorded duration: {r.durationSeconds??'pending'} seconds.</p>{r.error&&<p>Needs review: {r.error}</p>}{r.state==='available'&&!r.deletedAt&&r.audioExpiresAt&&Date.parse(r.audioExpiresAt)>Date.now()&&<audio controls preload="none" src={'/api/owner-recording-test/audio?id='+r.id}/>}<p>{r.settlement?'Accounted test cost $'+(r.settlement.totalMicros/1000000).toFixed(4):'Cost evidence pending; '+(Number.isSafeInteger(r.reservedMicros)?'$'+(r.reservedMicros!/1000000).toFixed(2):'the full allowance')+' remains reserved. A later check uses a separate reservation.'}</p>{r.settlement?.items.map((x,i)=><p key={i}>{x.provider} {x.label}: ${(x.micros/1000000).toFixed(4)} ({x.basis})</p>)}</section>)}</main>;
}
