'use client';
import {useEffect,useRef,useState} from 'react';
import type {RecordedOutboundReadiness} from '@/lib/recorded-outbound-readiness';
function valid(v:unknown):v is RecordedOutboundReadiness{const r=v as RecordedOutboundReadiness;return !!r&&r.mode==='read_only'&&['checked','partial','unavailable'].includes(r.status)&&typeof r.checkedAt==='string'&&Number.isFinite(Date.parse(r.checkedAt))&&/^agent_[A-Za-z0-9]+$/.test(r.agentId)&&/^agtbrch_[A-Za-z0-9]+$/.test(r.branchId)&&/^agtvrsn_[A-Za-z0-9]+$/.test(r.expectedVersionId)&&(r.observedVersionId===null||/^agtvrsn_[A-Za-z0-9]+$/.test(r.observedVersionId))&&(r.observedConfigHash===null||/^[a-f0-9]{64}$/.test(r.observedConfigHash))&&typeof r.providerChecksPass==='boolean'&&r.checks&&typeof r.checks==='object'&&!Array.isArray(r.checks)&&Object.keys(r.checks).length<=32&&Object.entries(r.checks).every(([k,v])=>/^[A-Za-z]{1,80}$/.test(k)&&typeof v==='boolean');}
export default function ProductionRecordingReadiness(){
 const [result,setResult]=useState<RecordedOutboundReadiness|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>pending.current?.abort(),[]);
 async function read(){if(pending.current)return;const c=new AbortController();pending.current=c;setBusy(true);setError('');setResult(null);try{const response=await fetch('/api/owner-recording-test/production-readiness',{method:'GET',cache:'no-store',credentials:'same-origin',signal:c.signal});const value=await response.json();if(!response.ok||!valid(value))throw Error('UNAVAILABLE');if(!c.signal.aborted)setResult(value);}catch{if(!c.signal.aborted)setError('Production configuration read is unavailable. Sign in as the configured owner.');}finally{if(pending.current===c)pending.current=null;if(!c.signal.aborted)setBusy(false);}}
 return <section className="space-y-3 rounded border p-4" aria-busy={busy}><h2 className="font-semibold">Production recording configuration</h2><p>Read the prepared 10-minute outbound branch and its three tools. This only displays configuration evidence. It does not start a test, change settings, save a review or activate customer calls.</p><button type="button" disabled={busy} onClick={()=>void read()} className="rounded border px-3 py-2">{busy?'Reading provider…':'Inspect production branch (read-only)'}</button>{error&&<p role="alert">{error}</p>}{result&&<><p role="status">Checked {result.checkedAt}. Provider checks: {result.providerChecksPass?'Pass':'Needs review'}.</p><dl className="break-all"><dt>Branch</dt><dd>{result.branchId}</dd><dt>Observed version</dt><dd>{result.observedVersionId??'Unavailable'}</dd><dt>Selected model</dt><dd>{result.observedModelId??'Unavailable'}</dd><dt>Maximum output tokens per turn</dt><dd>{result.maxOutputTokens===-1?'Provider unlimited':result.maxOutputTokens??'Unavailable'}</dd><dt>Canonical configuration fingerprint</dt><dd>{result.observedConfigHash??'Unavailable'}</dd></dl><details><summary>Validation checks</summary><ul>{Object.entries(result.checks).map(([k,v])=><li key={k}>{k.replace(/([a-z])([A-Z])/g,'$1 $2')}: {v?'Yes':'No'}</li>)}</ul></details><p>Provider readback alone does not verify call behavior, supplier budgets or release approval.</p></>}</section>;
}
