'use client';
import {useRef,useState} from 'react';
import type {ReceptionSetupReview,SetupAction} from '@/lib/reception-setup';
const labels:Record<SetupAction,string>={prepare_branch:'Prepare isolated reception branch',configure_branch:'Apply fixed reception configuration',route:'Route the existing number to reception',restore:'Restore original phone routing'};
const details:Record<SetupAction,string>={prepare_branch:'Create one dedicated branch with the disclosed AI greeting, the reviewed profile’s maximum duration, 120 response tokens, no tools or customer data. Existing shared settings must already disable recording and limit concurrency to one. Main, the owner test and phone routing stay unchanged.',configure_branch:'Apply the fixed safe configuration to the dedicated reception branch only. This requires reception to be disabled.',route:'Change only this number’s Voice URL and fallback to the guarded reception and reject-only fallback. The original voice routing is saved before the request. Calls may consume approved customer credits.',restore:'Restore the exact original Voice URL, fallback and methods from the saved server snapshot. Other phone settings remain unchanged.'};
const sharedLabels:Record<string,string>={sharedAuthenticationEnabled:'Agent authentication must already be enabled',sharedRecordingDisabled:'Agent voice recording must already be off',sharedConcurrencyOne:'Agent concurrency must already be one',sharedBurstingDisabled:'Agent bursting must already be off',sharedQueueDisabled:'Agent queueing must already be off'};
const names:Record<string,string>={profile_configuration_invalid:'The configured duration, charge cap or rate does not match an approved profile. Setup is blocked; profiles cannot be changed here.',shared_agent_safety_settings_require_separate_review:'The existing agent-wide authentication, recording, concurrency or queue settings do not meet reception safety limits. These controls cannot change shared settings or other branches.',existing_postcall_hmac_secret_missing:'No existing post-call HMAC secret is configured.',existing_reception_postcall_webhook_missing:'No existing authenticated reception webhook was found.',separate_funding_and_enablement_required:'Call funding and reception enablement still require separate approval.',prior_write_requires_read_only_reconciliation:'A previous write is unresolved. Refresh for current evidence; do not repeat it.',postcall_webhook_readback_unavailable:'Existing webhook settings could not be read.',twilio_readback_unavailable:'The existing Twilio phone settings could not be verified.',database_unavailable:'The reviewed reception database setup is not installed or readable.'};
export default function ReceptionSetup(){
 const [review,setReview]=useState<ReceptionSetupReview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<SetupAction|null>(null),[receipt,setReceipt]=useState('');const running=useRef(false);
 async function run(action?:SetupAction){if(running.current)return;const item=review?.actions.find(a=>a.action===action);if(action&&!item)return;running.current=true;setBusy(true);setError('');setConfirm(null);
  try{const r=await fetch('/api/owner-reception/setup',{method:action?'POST':'GET',cache:'no-store',credentials:'same-origin',headers:action?{'Content-Type':'application/json'}:undefined,body:action?JSON.stringify({action,confirm:true,reviewToken:item!.reviewToken}):undefined});const data=await r.json();setReview(data);if(!r.ok)setError(data.message??'Setup could not be checked.');}catch{setReview(null);setError(action?'The request outcome is unknown. Refresh read-only status; do not repeat the change.':'Readiness could not be checked.');}finally{running.current=false;setBusy(false);}}
 async function reconcile(){if(running.current)return;running.current=true;setBusy(true);setReceipt('');try{const r=await fetch('/api/owner-reception/reconcile',{method:'POST',cache:'no-store',credentials:'same-origin'});const data=await r.json();setReceipt(typeof data.message==='string'?data.message:data.status==='no_call'?'No admitted reception call yet.':data.status==='completed'?'The completed call receipt was verified.':data.status==='failed'?'The failed call receipt was verified.':'The receipt is still held or unavailable; completion has not been verified.');}catch{setReceipt('Provider receipt check could not be completed.');}finally{running.current=false;setBusy(false);}}
 return <section aria-busy={busy}><button disabled={busy} onClick={()=>run()}>{busy?'Checking…':'Refresh read-only readiness'}</button>{error&&<p role="alert">{error}</p>}{review&&<><p role="status">{review.message}</p><ul>{review.blockers?.map(b=><li key={b}>{names[b]??b.replaceAll('_',' ')}</li>)}</ul><ul>{Object.entries(sharedLabels).filter(([key])=>review.checks?.[key]===false).map(([key,label])=><li key={key}>{label}</li>)}</ul>{review.checks?.providerReadbackMode&&<p>Call completion uses authenticated provider read-back with the existing server credentials. No new webhook secret is required.</p>}{review.profile&&<p><strong>{review.profile.name==='owner_quick_test'?'Owner-only quick test':'Normal reception'}</strong>: up to {review.profile.maxDurationSeconds} seconds; customer charge cap ${(review.profile.customerChargeCapCents/100).toFixed(2)} per call.{review.profile.name==='owner_quick_test'?' This requires separate explicit approval and only admits the configured owner caller.':' Normal reception is the default profile.'} These setup actions do not approve charges or change profiles.</p>}{review.branch&&<p>Dedicated branch: {review.branch.id}<br/>Reviewed version: {review.branch.version}<br/>Configuration fingerprint: {review.branch.configHash}</p>}{review.actions?.map(item=><div key={item.action} style={{border:'1px solid #bbb',borderRadius:8,padding:16,marginTop:16}}><h2 style={{fontSize:18}}>{labels[item.action]}</h2><p>{details[item.action]}</p>{confirm===item.action?<><p>Confirm this specific change before the review expires.</p><button disabled={busy} onClick={()=>run(item.action)}>Confirm change</button>{' '}<button disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button></>:<button disabled={busy||Date.parse(item.expiresAt)<=Date.now()} onClick={()=>setConfirm(item.action)}>Review change</button>}</div>)}</>}<hr/><h2 style={{fontSize:18}}>Latest reception call</h2><p>Check the latest admitted call against ElevenLabs and Twilio. This does not start a call.</p><button disabled={busy} onClick={reconcile}>Check latest provider receipt</button>{receipt&&<p role="status">{receipt}</p>}</section>;
}
