'use client';
import {useEffect,useState} from 'react';
import {AccountAccess} from '@/components/account-access';
import {priceLabel,type MembershipOffer} from '@/lib/membership-policy';
export default function OwnerPricing(){
 const [offer,setOffer]=useState<MembershipOffer|null>(null),[price,setPrice]=useState(''),[enabled,setEnabled]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[denied,setDenied]=useState(false);
 async function load(){try{const r=await fetch('/api/billing/offer',{cache:'no-store'});const d=await r.json();if(r.status===403){setDenied(true);return;}if(!r.ok)throw Error(d.error);setDenied(false);setOffer(d.offer);setPrice(String(d.offer.priceCents/100));setEnabled(d.offer.enabled);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load pricing.');}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy||!offer)return;const cents=Math.round(Number(price)*100);if(!Number.isFinite(cents)||cents<100||cents>100000){setError('Enter a monthly price between $1 and $1,000.');return;}setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/billing/offer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({priceCents:cents,revision:offer.revision,enabled})});const d=await r.json();if(!r.ok)throw Error(d.error);setOffer(d.offer);setMessage(`Saved. New software checkouts are ${priceLabel(d.offer.priceCents)}/month. Existing subscription prices are unchanged.`);}catch(e){setError(e instanceof Error?e.message:'Could not save pricing.');}finally{setBusy(false);}}
 return <main className="owner-pricing-page"><a href="/">← Workspace</a><span className="membership-caption">OWNER SETTINGS</span><h1>Your software offer</h1><p>Set the price customers see after your webinar. Work credits are separate.</p>{denied?<><p>Sign in with the platform owner account to edit pricing.</p><AccountAccess onSignedIn={()=>void load()}/></>:offer?<form onSubmit={save}><label>Software price per month ($)<input type="number" min="1" max="1000" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} disabled={busy} required/></label><label className="owner-checkout-toggle"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)} disabled={busy}/>Allow new software purchases</label><div className="owner-price-review"><strong>{priceLabel(Math.round(Number(price||0)*100))}/month</strong><span>$0 in work credits included. Customers add credits inside the workspace.</span></div><button className="setup-primary" disabled={busy}>{busy?'Saving…':'Save software price'}</button><p>Applies to new checkouts only. Existing subscription amounts stay the same.</p><a href="/join" target="_blank" rel="noopener noreferrer">Preview webinar checkout ↗</a></form>:<p role="status">Loading pricing…</p>}{error&&<p role="alert">{error} <button onClick={()=>void load()}>Reload</button></p>}{message&&<p role="status">{message}</p>}</main>;
}
