'use client';
import {useEffect,useRef,useState} from 'react';
const ownerVoiceConfirmation='Call my configured phone once for a 60-second AI test';
type Status={status:string;canCall:boolean;destination?:string;expiresAt?:string;durationSeconds?:number|null;checks?:Record<string,boolean>;observedConfigHash?:string|null;observedVersionId?:string|null;error?:string};
export default function OwnerVoiceAcceptance(){
 const [status,setStatus]=useState<Status|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[attempted,setAttempted]=useState(false);
 const submitting=useRef(false);
 async function refresh(){setBusy(true);try{const r=await fetch('/api/owner-voice-acceptance',{cache:'no-store'}),data=await r.json();if(!r.ok)throw Error(data.error);setStatus(data);setMessage('');}catch{setStatus(null);setMessage('Sign in to the configured owner account, or ask for the check to be configured.');}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 async function call(){if(submitting.current||attempted||!confirmed||!status?.canCall)return;submitting.current=true;setAttempted(true);setBusy(true);
  try{const r=await fetch('/api/owner-voice-acceptance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation:ownerVoiceConfirmation})}),data=await r.json();if(!r.ok)throw Error(data.error);setStatus(data);setMessage(data.status==='provider_accepted'?'The provider accepted the one call request. Answer your phone.':'The call is held for review. No automatic retry will occur.');}
  catch{setStatus(null);setMessage('The outcome needs review. Do not try another call; use Check status.');}finally{setBusy(false);submitting.current=false;}}
 return <main style={{maxWidth:620,margin:'3rem auto',padding:'1.5rem',lineHeight:1.6}}><h1>Private owner call check</h1><p>One AI call to the configured owner phone {status?.destination??''}. Maximum 60 seconds after connection, with up to 20 seconds ringing. Audio recording is disabled. The provider may retain a transcript and usage metadata.</p><p>This checks the phone connection and AI voice only. It cannot make offers, send messages, schedule real callbacks, sign documents or start seller outreach. No customer credits are debited. Provider usage may still be charged to the owner’s provider account.</p><p role="status">Status: {status?.status.replaceAll('_',' ')??'unavailable'}{typeof status?.durationSeconds==='number'?` · ${status.durationSeconds} seconds`:''}</p>{status?.checks&&Object.values(status.checks).some(v=>!v)&&<div><h2>Provider checks needing attention</h2><ul>{Object.entries(status.checks).filter(([,ok])=>!ok).map(([name])=><li key={name}>{name.replace(/([a-z])([A-Z])/g,'$1 $2')}</li>)}</ul></div>}{status?.observedConfigHash&&status?.observedVersionId&&<details><summary>Read-only provider review reference</summary><p>Observed version: {status.observedVersionId}</p><p style={{overflowWrap:'anywhere'}}>Observed configuration hash: {status.observedConfigHash}</p><p>These observations do not release or place a call.</p></details>}{status?.expiresAt&&<p>Expires: {new Date(status.expiresAt).toLocaleString('en-US',{hour12:true})}</p>}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy||attempted}/> I own this phone and want this one AI test call now</label><div style={{display:'flex',gap:12,marginTop:16}}><button onClick={()=>void call()} disabled={busy||attempted||!confirmed||!status?.canCall}>Call my phone once</button><button onClick={()=>void refresh()} disabled={busy}>Check status</button></div><p role="alert">{message}</p><p>Any uncertain request stays consumed and requires review. Checking status never places another call.</p><a href="/">Back to workspace</a></main>;
}
